### ISSUE TITLE
Update Transactions in Web Services

### ISSUE THREAD

**Issue by benkipnis** [k2view-academy/K2View-Academy#100]
I am trying to issue an UPDATE statement from within a web-service but it is not effecting the data.  I'm not seeing any errors, but it also appears that data is not being updated when i query the LUDB.

How should i be doing this?

Sample Code: 
ludb("INCIDENT", incident_id);
ludb().beginTransaction();
ludb().execute("UPDATE root SET incident_name=? AND incident_description=? WHERE incident_id=?", incident_name, incident_description, incident_id);
ludb().commit();

**Comment by danicar12** [comment]
Check after running command release; you may be accessing not the latest LUI.

Best regards,

Daniel Carrera Alonso
Technical Account Manager
K2VIEW
daniel.carrera.alonso@k2view.com
m. +31 (0) 629395413
whatsapp. +48 694443243

**Comment by lionbro1** [comment]
Hi,

Maybe another sync run afterwards on the same instance that override the value you updated?

As the code as you shared above should work.

Regards,
Lion

**Comment by benkipnis** [comment]
This appears to be related to this happening on the root node.  Once i
moved this to a secondary node (using a dummy root node) it began to work
successfully.

I had verified that truncate and sync were turned off.

**Comment by lionbro1** [comment]
I tried updating both root table and inner table and it worked fine. code example:

ludb("CRM", ID);
ludb().beginTransaction();
ludb().execute("UPDATE CUSTOMER SET CUSTOMER_ID=30");
ludb().execute("UPDATE CASES SET CASE_ID=40");
ludb().commit();
