### ISSUE TITLE
How to list all files under Resources?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#1006]
Is there a way to list all files located under Resources located under SharedObjects or LUs either from java code or from Broadway?

![image](https://github.com/k2view-academy/K2View-Academy/assets/66338066/e8f9802a-61e4-4f70-9be6-c0b70b8e618f)

**Comment by lionbro1** [comment]
Hi,

Can you explain the exact use case? 
As it is not a good practice to implement a code that will be dependent on Resources names.

**Comment by rsekarp** [comment]
My Scenario :
i have to execute a list of Create CQLs.
For operational / maintenance purpose - would like to have them in separate .cql files.     
And keeping them outside of Fabric flow in resources folder - will help my DB developers to check & modify the query - impacting only those .cql files in gitlab. 

My Fabric flow - is expected to read all the .cql files under resources and execute them one by one. 
Let me know if more details needed in this regard. 
any other solution / suggestion is welcome.  Thank you.

**Comment by lionbro1** [comment]
Hi,

It can be acheived  by using SysEnv and ls actors.

1. SysEnv to get the right project path
2. ls to list the files under this path

Example below

<img width="1053" alt="Screenshot 2024-03-14 at 14 49 27" src="https://github.com/k2view-academy/K2View-Academy/assets/21338328/554953b4-666c-41bd-bea9-32b8f0ebe52d">

**Comment by rsekarp** [comment]
We are on 6.5.9 and i dont see SysEnv Actor. So how can i get that path without using teh actor. @lionbro1

**Comment by lionbro1** [comment]
you can use LuFunction in that case or hard coded path
