### ISSUE TITLE
Can I retrieve job 'name' and 'uid' from a broadway flow that is triggered as a BROADWAY_JOB? 

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#1007]
How can I get a broadway job's name and uid inside the flow? Name and UID are not passed as args in the startjob command. 
Fabric version 6.5.9

My main goal is to get the tries count (from k2_jobs table) so that I configure how many times I can retry a job.

**Comment by lionbro1** [comment]
Hi,

It is not recommended to update k2_jobs table directly.

You will better set the retries when using the startjob command, you can find more details on this Q&A

https://github.com/k2view-academy/K2View-Academy/issues/575
