### ISSUE TITLE
Is it possible to use encrypted SMTP for sending e-mails to user from TDM flows

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#1008]
Hello, one of our customer is going to use SMTP interface to send e-mail to the end user as a result of TDM flow execution. Due to security policies they require this interface to be encrypted, but I can not find any option to configure TLS for it... Is that possible? If yes - could you please guide me on how to set it up?

_____________
Best regards,
         Andrey

**Comment by lionbro1** [comment]
Hi,

Fabric is using TLS by default for an SMTP interface.
