### ISSUE TITLE
Fabric 5.5 | Webservice logging

### ISSUE THREAD

**Issue by neenjapt** [k2view-academy/K2View-Academy#101]
Hi,

During some local testing for a project, we noticed WS requests are logged automatically by Fabric at both start and end of execution and a couple topics raised our attention.

Is there a way to control the amount of information logged automatically by Fabric?
If it is indeed possible, can you please explain how to achieve it or refer to a document where this is documented?

Thanks,
Bruno

**Comment by lionbro1** [comment]
Hi,

You can change the log level in logback.xml, for more details please refer to https://github.com/k2view-academy/K2View-Academy/blob/ad6408d31e837cdc4f37ef5c83c8300b2fa58770/articles/21_Fabric_troubleshooting/02_Fabric_troubleshooting_log_files.md

**Comment by neenjapt** [comment]
Hi,

Thanks for the prompt reply.
However, I have to push the same question again since the link you provided only mentions how to change log levels in a generic way and never mentions anything specific for enabling a finer logging for Webservices.

Using the **Logback.xml** file, can we create specific Logback appenders for Webservices (or even for a specific one in case we just need to troubleshoot a particular one) ?

Thanks,
Bruno

**Comment by taliei** [comment]
The Trace Fabric command enables writing internal operations performed by Fabric into trace files. The Trace mechanism can be used on both global and session levels.​ The Trance file is generated under /k2view/home/traces/ or <Projects path\Projects\<project name>\FabricHome\traces. To view the file content, use http://localhost:3213/static/trace/trace.html.
You can trace Webservices by populating the ​operations parameter of the create trace command by webservice.
For more information about the Trace command, please run help trace on the Fabric console. 

Thanks,
Tali
