### ISSUE TITLE
LU Schema - storage and cache properties

### ISSUE THREAD

**Issue by ShaniRotemIl** [k2view-academy/K2View-Academy#1010]
1. Regarding "Cache Location" property, I see the below in the KB:
 
_**If the default path in the config.ini is updated to another path, the cache is always located according to the config.ini regardless of the LU Schema property setting in the Fabric Studio.**_
 
https://support.k2view.com/Academy/articles/32_LU_storage/02_storage_management.html

Does it mean that if I'm changing the default path in the config.ini but for one of the  LUTs i'm setting this property to "storage", it will not store it in the storage?
 
2. Regarding "Storage" property, I see the below in the KB:
 
_**When the Cache Location is set to Storage, store the cache under the storage folder in Fabric ${FABRIC_STORAGE}/storage/fdb_cache/ if this location exists. If this location does not exist, store the cache in ${FABRIC_HOME}/storage/fdb_cache/.**_
 
So there is no relation to the STORAGE_DIR settings, as configured in config.ini [fabric]?
_Root dir for storage data
STORAGE_DIR=${FABRIC_HOME}/storage_

 Thanks

**Comment by natalylic** [comment]
1. **MDB_DEFAULT_CACHE_PATH** holds the location of the Fabric MDB cache files on the server. The default path is set in the config.ini and can be changed if required. Once the default is updated, this location is taken and applicable for all LUs.
If the MDB_DEFAULT_CACHE_PATH is not set (meaning, remains the default) and the Cache Location property = Storage (on a specific LU), the LU Storage is located at **${FABRIC_STORAGE}/storage/fdb_cache/** if this location exists. If this location does not exist, store the cache in **${FABRIC_HOME}/storage/fdb_cache/**.
If Cache Location property = Default, the LU Storage is located at **/dev/shm/fdb_cache/** if it exists. If it doesn't exist, then at **${FABRIC_HOME}/storage/fdb_cache/**.
2. **STORAGE_DIR** is an internal directory, to store Fabric JARs. This is not related to LU Storage.
