### ISSUE TITLE
Recommended way to edit config files in WebStudio env

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#1012]
Hello, what is the recommended way to editing config files (like config.ini) while working with WebStudio?

_____________
Best regards,
         Andrey

**Comment by eyalk2** [comment]
1. Studio - if it is for a specific per space - then it shall be done at **space**, by editing the config.ini - 
    - Click to menu File > Open.
    - Using the arrow, go one level up and then navigate to the config folder.
    - double click the file to open it for editing. 
    - make changes and save
    - If the change requires fabric restart then either 
        - Pause and resume the space. 
        - open Linux terminal via the command pallet, and then run - "nohup k2fabric restart >> /proc/1/fd/1 &" 
    > Note: any file located under workspace, like the config, is not affected when space is paused or resumed. it is considered as persistent.
2. Studio - if it shall be sone for all spaces on the project space profile, then at the **k2cloud orchestrator** 
    - go to projects page. 
    - click to open the advanced settings popup
    - edit the config.ini text area and save the project.
    - Next space that will be created will use this config
3. non studio - we are working now on make it accessible at UI (k2cloud orchestrator and/or at space Admin UI)

**Comment by avvakandr** [comment]
Thank you Eyal, that worked!

I was trying to edit it using vi or vim other day, but it looks like these are not available ...

____________
Best regards,
         Andrey
