### ISSUE TITLE
Recommended configuration for DBs when Postgres is used as System DB and TDM DB

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#1015]
Hello, what is the recommended DB setup for TDM implementations if customer chose to use Postgres as system DB and as TDM DB? 

- Do we recommend using different DBs for system vs TDM ?
- or it can be the same DB (and we create different schemas for fabric system DB and TDM under the same DB)?
- or we do not care and we can go with whatever is easier for DBAs to manage ?

______________
Best regards,
         Andrey

**Comment by taliei** [comment]
Hi.

Both options - including Fabric system DB in the TDM DB or separating the DBs -  are valid and can work.

Separating the system DB and the TDM DB into 2 DBs may enable better control since it enables a separate configuration of each DB for better performance. 


Tali
