### ISSUE TITLE
Tables not visible on Data Explorer Web Admin Gui but showing up in console

### ISSUE THREAD

**Issue by debargha95** [k2view-academy/K2View-Academy#1016]
Hi,

There is an LU with 248 tables. In the Data explorer on the web admin gui some of the tables are not showing up. But when a describe schema <LU>; is performed the table is visible. The table can also be selected after performing a get. Is there a limit on how many tables are visible in the Data Explorer on the web admin gui?

Regards,
Debargha

**Comment by lionbro1** [comment]
Hi,

There is no limitation, if it happens again, please open a bug in freshdesk.
