### ISSUE TITLE
Query on KAFKA_POLL_RECORDS

### ISSUE THREAD

**Issue by sharanyavj** [k2view-academy/K2View-Academy#102]
In iifConfig.ini, we see the below

## the batch size should provide processing time within Kafka timeout limits divided by 3.
#KAFKA_POLL_RECORDS=100

Is it KAFKA_POLL_RECORDS default value  100 or we can change it according to KAFKA timeout limits. I am seeing the 

#KAFKA_SESSION_TIMEOUT_MS=30000
 
So even if divided by 3 its either 10000 (session timeout in Ms) or  10 (session timeout in secs).Could you please clarify on this.

**Comment by Krutyolkin** [comment]
KAFKA_POLL_RECORDS - the more is better for reducing the load on Kafka, but the consumer will wait for the timeout (currently there is an open bug related to this parameter) if enough records were not fetched.

KAFKA_SESSION_TIMEOUT_MS - time Kafka waits till declaring the consumer disconnected, without explicit request. This causes partition reassignment and could be time-consuming.

Recommended value:
The processing time of KAFKA_POLL_RECORDS in any (bad, but not terrible) case should be smaller than KAFKA_SESSION_TIMEOUT_MS. Kafka recommends setting KAFKA_SESSION_TIMEOUT_MS to 3 times larger than the reasonable processing time.
Note that setting KAFKA_SESSION_TIMEOUT_MS to large values means that if a consumer dies unexpectedly, its partitions will not be redistributed among active consumers for that time.
Also, if a consumer uses partitioned (not topic assignment) or there are only one partition and no high availability the redistribution considerations are less valid. In this case, the other consumers will not be willing to catch the released partition, but if, for example, the job will restart and try to consume the same partition it will have to wait till timeout passes.
Fabric uses the following strategies:

1. IidFinder - topic consumer
2. Common area - single partition consumer
3. Kafka parsers with partition parameter - single partition.
