### ISSUE TITLE
How is InnerFlowDynamic  actor different than InnerFlow?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#1022]
If I set flowName parameter of an InnerFlow actor as Link and add an input parameter to it, will it be any different than InnerFlowDynamic actor?

**Comment by natalylic** [comment]
The **InnerFlowDynamic** actor can receive its input parameters (flow name and its input parameters) **at run-time** to flowName and params inputs respectively. While **InnerFlow** actor should be setup during the flow creation. Even if you change the flowName parameter of the **InnerFlow** actor to a link, this actor has no input port for getting the input parameters.
![image](https://github.com/k2view-academy/K2View-Academy/assets/62207927/103a3bb9-db38-453c-83e8-dc5d238c633c)
