### ISSUE TITLE
How to identify which columns from LU tables are being utilized in code?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#1026]
Raising on behalf of customer - "Is there any capability/runtime metric available that can show how many fields/columns in various LU objects are being actively accessed/utilized during Cycle executions?

We are loading huge amounts of data for multiple tables into LU and we need to see if we can eliminate some of the columns that are not being utilized without having to go through whole code and logic manually."

**Comment by lionbro1** [comment]
Hi,

This is part of Data Lineage feature that is planned to be developed as a part of 2024 product roadmap.

The ability to track what we bring into Fabric and how we expose it to the external systems (by Web-Services) etc.
