### ISSUE TITLE
Catalog Discovery Process- Crawler supported sources

### ISSUE THREAD

**Issue by AlexMaziya** [k2view-academy/K2View-Academy#1027]
What are the current supported sources (Interface Type) the Crawler can run on?

**Comment by natalylic** [comment]
Any JDBC connection type is supported.

The list of Catalog interface types certified by QA is: 
- PostgreSQL, Oracle, SqlServer, MySQL, DB2, Cassandra,  SQLite, Salesforce, Teradata

**Comment by natalylic** [comment]
In addition, in V8.0 we will support parsing of complex fields in the above interfaces. Complex field is a field that includes a string in JSON or XML format.
