### ISSUE TITLE
NFS

### ISSUE THREAD

**Issue by ShaniRotemIl** [k2view-academy/K2View-Academy#1028]
Hi, 

Where can i define the NFS details for MDB_DEFAULT_SCHEMA_CACHE_STORAGE_TYPE=NFS

Thanks

**Comment by natalylic** [comment]
It can be defined by adding the parameter `MDB_DEFAULT_STORAGE_PATH `to the config.ini.

**Comment by ShaniRotemIl** [comment]
Under what section do we need to add it?

**Comment by natalylic** [comment]
[fabricdb] section

**Comment by ShaniRotemIl** [comment]
Seems like even if this entry is not in config.ini Fabric doesn't throw exception. What path will Fabric use in this case?

**Comment by natalylic** [comment]
The default location is: ```${FABRIC_HOME}/storage```
