### ISSUE TITLE
Broadway HTTP ACTOR

### ISSUE THREAD

**Issue by yevgenibelaigorod** [k2view-academy/K2View-Academy#103]
Hi 
While using HTTP actor  in case of 400 HTTP response code the reason for issue  is suppose to be sent inside the body as error code or message 
But i dont see it as part of what actor exposes. ( The errors array is empty)  when stream is passing json parser
Is there way to access to body of response - because currently the only thing that have access is  the exception via the Error Handler and the stream is empty 
Server returned HTTP response code: 400 for URL: https://test-internal-apigw-alpha.pelephone.co.il:9222/services/data/v49.0/sobjects/Account/Legacy_Unique_Customer_Id__c/12279_PEL?_HttpMethod=PATCH

The same thing is was able to see in different types of errors i can see error message in postman but i couldnt access it in actor

Thanks
Yevgeni

**Comment by yuvalp-k2view** [comment]
Yevgeni, thanks for the feedback.

This is coming in 6.2.2

1) By default, the exception will contain the response status code and the entire error message.

2) You will have the option to disable the exception and get the status code and content. This will enable you to create conditions that react to the status code (for instance 200, 500, else) and access the error "page" data. Network errors will still throw exceptions.
