### ISSUE TITLE
Graceful db updates on issue of STOPJOB BROADWAY_JOB.

### ISSUE THREAD

**Issue by ajay44u** [k2view-academy/K2View-Academy#1037]
I have a Manager job which starts jobs of type BROADWAY_JOB (Inside flows - they actually subscribed to a pubsub consumer).
The Manager job does stops the jobs it started as per logic.

I am trying to figure out a way to update some db tables(from the broadway consumer jobs) after an invocation of stop job command from a Manager job.

Can you please let me know how do I achieve this functionality?

**Comment by natalylic** [comment]
Hello! Please clarify your question since it's not quite clear to me. 
Do you need to update DB tables from the same job that you are trying to stop?

**Comment by ajay44u** [comment]
Yes.

Its related to delta parsers that subscribed to the IIDFINDER delta topics.
We are trying to replace the parser code with broadway flows.

**Current Implementation with Parsers:**
For a LU, Customer - fnGetJobManager -> scheduled timely.

1. Reads the metadata from Customer delta topic (like Partitions N) and starts the (N =~ Partitions)Parsers "deltaIid".
2. Once the parsers are started they process the Kafka polled records.
3. fnGetJobManager, when running on its schedule can decide to stopparser if needed.
4. When the stopparser command is triggered from fnGetJobManager, deltaIid will close the kafka consumer and updates the user statictics tables in cassandra.

**Current Implementation of the Parser code:**
```
@type(RootFunction)
@out(name = "out", type = String.class, desc = "")
public static void k2_MsgParser2(String in) throws Exception {
    Map<String, String> parserArgs = parserParams();
    String parserUID = "deltaIid_" + parserArgs.get("partition");
    final String createTableGetJobsFailedIIDS = "CREATE TABLE if not exists %s.get_jobs_failed_iids (    iid text,    failed_time timestamp,    failure_reason text,    full_error_msg text,    PRIMARY KEY (iid, failed_time))";
    db(getGlobal("DB_CASS_NAME",getLuType().luName)).execute(String.format(createTableGetJobsFailedIIDS, getLuType().getKeyspaceName()));
    Stats stats = new Stats(parserUID);
    stats.insertStats("Started");
    processMessages(msg -> {
        if (msg != null) {
            handleMsg(msg.getKey(), (Long) msg.getValue(), stats, false);
        }
        if (isAborted()) throw new InterruptedException();
        return true;
    });
    stats.insertStats("Stopped");
    yield(null);
}
```

As we are replacing the Parsers logic to Broadway flow.

1. From the Manager when needed to stop, we are using STOPJOB BROADWAY_JOB command to stop the jobs.
2. And with this we are missing on the statistics insert to db. `stats.insertStats("Stopped");`

**Comment by natalylic** [comment]
In your flow, you can use the **StopJob** actor to stop the job (note that the timeout should be defined using its **waitForSeconds** input parameter). Then use the **JMXWrite** actor to write any custom JMX value into the current process JMX statistics module.

**Comment by ajay44u** [comment]
Thanks Nataly for the information. 
However, as we are trying here to write in a user defined stats table in cassandra, not the JMX stats. Not sure if it can solve our need.

1. The STOPJOB command is expected via either fabric command input or as part of a scheduled job execution.
2. We are trying here is to understand if there is a way that allows a broadway_job to execute some user logic (in this case, cassandra inserts) after initiating a stopjob command on it, before the process aborts.

**Comment by natalylic** [comment]
There is no specific actor to do it. You can either write your own actor that will perform this logic, or invoke a DbCommand / DbLoad actor to write to Cassandra interface after the invocation of a StopJob actor.

**Comment by ShaniRotemIl** [comment]
Hi Nataly,
Can you explain how to build our own actor that will perform this logic?
Thank you

**Comment by natalylic** [comment]
A new custom actor can be created using the [Actor Editor](https://support.k2view.com/Academy/articles/19_Broadway/28_actor_editor.html) and this actor can either inherit from an existing core actor or be created from scratch based on your own Java class. Check the section ["How Do I Create a New Actor from Scratch?"](https://support.k2view.com/Academy/articles/19_Broadway/28_actor_editor.html#how-do-i-create-a-new-actor-from-scratch) for more details.

**Comment by ShaniRotemIl** [comment]
We know how to create a new Actor. We are asking how can we catch the abort

**Comment by natalylic** [comment]
You can use the same user code functions as you used in your parser code.
