### ISSUE TITLE
JMX metrics 

### ISSUE THREAD

**Issue by ShaniRotemIl** [k2view-academy/K2View-Academy#1039]
Hi,

Can you please explain the below metrics?

1. **mdbReadLockDuration** Time spent in read locking the mdb 
2. **mdbWriteLockDuration** Time spent in write locking the mdb 
3. **threadPoolWaiting** ThreadPool thread wait duration
What pool is it?
5. **threadPoolExecution** ThreadPool execution duration
What pool is it? what does it mean 'Execution'? in use?

Thanks

**Comment by yuvalp-k2view** [comment]
the write/read lock duration, as defined, it the time the system waited between asking for the lock until it was fulfilled.

threadpool is a general use object so the key in the stats is essential for context. This is mostly used when trying to understand issues (as opposed to monitoring proactively).
