### ISSUE TITLE
Which HTTP interface "Authentication type" matches Salesforce "OAuth 2.0 JWT"?

### ISSUE THREAD

**Issue by dotants** [k2view-academy/K2View-Academy#1043]
Hi

Which HTTP interface "authentication type" options match Salesforce "OAuth 2.0 JWT"?

Salesforce documentation for it:
https://help.salesforce.com/s/articleView?id=sf.remoteaccess_oauth_jwt_flow.htm&type=5

![image](https://github.com/k2view-academy/K2View-Academy/assets/74860302/986d4e83-f0bb-4cc8-891c-3c871c7225e4)

**Comment by eyalk2** [comment]
Hi
Looks like it is not supported
