### ISSUE TITLE
Cassandra RETRY_POLICY parameter in config.ini

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#1046]
1. What does RETRY_POLICY under [default_session] in config,ini do? For which operation is it used?
2. What is the default behavior?
3. What steps are required to change it? I see only 2 options DEFAULT and CUSTOM. Where do we specify the custom retry number?
4. Can we add details about this and other such missing parameters to our support page articles?

Thank you!

**Comment by natalylic** [comment]
The RETRY_POLICY param is used for Fabric connection to Cassandra. 
The default behavior is defined by the Cassandra Java driver. This policy retries queries in only two cases: 

- On a read timeout, if enough replicas replied but data was not retrieved. 
- On a write timeout, if we timeout while writing the distributed log used by batch statements.

When updating the RETRY_POLICY  to CUSTOM, set the below params in config.ini to the required and restart Fabric:
```
## CUSTOM Retry options
#READ_ATTEMPTS=2
#WRITE_ATTEMPTS=2
#UNAVAILABLE_ATTEMPTS=2
#REQUEST_ERROR=2
```
