### ISSUE TITLE
TDM - what is right way to filter out / ignore BE entities if no data extracted for every table in all child LUs in BE

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#1047]
Hello, in one of customer scenarios for TDM we have BE hierarchy with 3 LUs: one parent and 2 child.

In parent LU we have 5 parameters, for child LUs - none.

They first ran 'Extract' task to bring parameters into TDM so later end-users can go and select parameters combination to bring data from source system.

They consider 'valid' entity only if it has data in all tables of both child LUs. In case at least one of tables in one of child LUs brings 0 records from source - they do not want this BE to be extracted or available via params selection for end users.

Since we have all parameters defined at parent LU level, even if we 'fail' get / sync for child LU based 0 records count for table - we still have parameters stored in TDM DB and they can lead to invalid BE extraction later.

What is the right way to filter those? 
- Is there a way to 'discard' parent LU parameters in case sync for one of child is not successful?
- If not possible - shall we create some 'artificial' parameter based on query that checks if there is at least one record in each table and return true if 'count' = 'number of tables' in LU and false if 'count' < 'number of tables'? (and add one such parameter with value = true in our task with AND condition)?
-  any other way ?

_____________
Best regards,
         Andrey

**Comment by taliei** [comment]
Hi.

We cannot  'discard' parameters, but you can add a parameter of 'complete_child_data' to the child LU and set it to true only if all the child data exists for the entity.  The task creator can select entities where the complete_child_data is true.

Tali
