### ISSUE TITLE
Broadway- update null on population fields

### ISSUE THREAD

**Issue by AlexMaziya** [k2view-academy/K2View-Academy#1049]
I have a requirement to set null value in a field population in case value does not exist in a lookup table:

However, when the lookup returns NULL, the orig value (from SourceDBActor) is being passed from the params instead of the NULL which I Need to set.
IgnoreNulls does not seem to affect in a Insert population.

Can I force NULL into the table without removing the params link?
Note: removing the params link and connect each field individually works, but can be tedious WA in a very large tables.

Below throws: org.postgresql.util.PSQLException Cause: The column index is out of range: 1, number of columns: 0

<img width="956" alt="image" src="https://github.com/k2view-academy/K2View-Academy/assets/58711321/95c99cec-814e-425b-b836-4f320321ff6d">

**Comment by natalylic** [comment]
You need to check the DbFetch output. If it's null, **pass an empty string**. Otherwise - pass the fetched value.
![image](https://github.com/k2view-academy/K2View-Academy/assets/62207927/e5259d26-6db6-4e3f-af24-ce0e1bc670d8)

**Comment by AlexMaziya** [comment]
Empty string is not equivalent to null in some DBs and applications.
There are cases where null is required. 
Is the only way to achieve that is with removing params link and connecting each field individually?

**Comment by natalylic** [comment]
Data object in Broadway does not distinguish between null and no value.
So you should either draw individual links, Or, make an update statement after insert.
