### ISSUE TITLE
"Cant write to trace" warnings in logs while Trace is running.

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#1050]
What do these log messages mean? It is printed when we are running a trace to analyze a batch process. Is it skipping writing trace records to the trace file? Why would that happen?

WARN  2024-04-22 14:55:35,141 [LID10e2000000005614] [bpu:974b1f55-ddfa-41d7-b08c-da7cb68efaa0_2b4cd8b2-4213-4db4-8b8a-0b1f1e6d7c50_LU1.1234_tid:425150] c.k.c.s.t.m.TraceSession - Can't write to TraceEvent queue for session flow_trace1
WARN  2024-04-22 14:55:35,141 [LID10e2000000005614] [bpu:974b1f55-ddfa-41d7-b08c-da7cb68efaa0_2b4cd8b2-4213-4db4-8b8a-0b1f1e6d7c50_LU1.2343_tid:425131] c.k.c.s.t.m.TraceSession - Can't write to TraceEvent queue for session flow_trace1
WARN  2024-04-22 14:55:35,141 [LID10e2000000005614] [bpu:974b1f55-ddfa-41d7-b08c-da7cb68efaa0_2b4cd8b2-4213-4db4-8b8a-0b1f1e6d7c50_LU1.3434_tid:425131] c.k.c.s.t.m.TraceSession - Can't write to TraceEvent queue for session flow_trace1
WARN  2024-04-22 14:55:35,141 [LID10e2000000005614] [bpu:974b1f55-ddfa-41d7-b08c-da7cb68efaa0_2b4cd8b2-4213-4db4-8b8a-0b1f1e6d7c50_LU1.1234_tid:425149] c.k.c.s.t.m.TraceSession - Can't write to TraceEvent queue for session flow_trace1

**Comment by yuvalp-k2view** [comment]
Trace can work in ASYNC/SYNC mode. In ASYNC mode, we want to have no effect on system performance. If the queue is full, the message is bypassed. This means we are creating messages faster than the disk can consume them (The queue can hold 1000 messages).

Use syncWrite in your trace command to assure all messages are written, even at the expense of blocking the traced operation.
