### ISSUE TITLE
Fabric Console on Cloud Native Deployment

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#1051]
Fabric+Studio 7.2.2 image through a Space from k2cloud

How to open one or more terminal sessions to Fabric console when Fabric is deployed on K8S?
> Note: I know that it can be accessed through the Fabric Portal, but that's not what I want.

I logged into the Fabric pod with:
- `kubectl exec -n <namespace> -it <dev-fabric-deployment-pod> -- /usr/bin/bash`

I tried to run `fabric`, but it is not in the path.

I `cd ~/workspace/fabric/bin` and run it from there as `./fabric`, but it complains with
- `java.net.ProtocolException: Peer says: User has no roles`

I assume that this error is because no user credentials were passed and, as such, it is trying `admin`.  

Anyway, I tried `./fabric -u admin -p admin` and got the same error.

Considering that login was done through `k2cloud` login, how to define user and password for login?
I assume that user should be the email I used to login into `k2cloud`, but would the password be a SAML token? If so, how to capture it?

Please advise.
Thanks.

**Comment by eyalk2** [comment]
Access via kubectl shall not be done, unless for maintenance.

**Comment by feamcor** [comment]
> Access via kubectl shall not be done, unless for maintenance.

It is reasonable assumption on production environments, although not always practical for support considering that some projects disable Web Admin and others doesn't allow Studio.

But for development and testing, is it only the terminal in Studio or the terminal in Admin the option?
Both cases don't allow multiple terminal sessions.

So, in a scenario of maintenance, how to handle the error I initially described?

BTW, I tried to create `admin` user through Web Admin and also through Fabric console and it doesn't let due to some exception when integrating with Cassandra.
> ERROR: You have to be logged in and not anonymous to perform this request

![image](https://github.com/k2view-academy/K2View-Academy/assets/639119/08a7330b-5c49-4587-9d8d-e3e9da1e2c0b)
Is this expected?

Please advise.
Thanks.

**Comment by eyalk2** [comment]
you can open multiple fabric terminal sessions (you did not explain what is needed for), by opening several browser tabs.
please do not use the kubectl for functionality. This is not the right  way users shall use.
In addition, most users do not have such access at all:

  *
not at SaaS
  *
not at self host at cloud
  *
on prem as K8s in a box is usually installed on VM, not on personal machines.

________________________________
