### ISSUE TITLE
Is it possible to check for incoming email in Fabric?

### ISSUE THREAD

**Issue by dotants** [k2view-academy/K2View-Academy#1053]
Hi

Assuming we have an SMTP interface and can send mail using "Email" actor.
Is it possible to have a job to "listen" for receiving email on that interface?

**Comment by feamcor** [comment]
My 2 cents...
As far as I know, SMTP is used only for sending emails.
For receiving email, a POP3 or IMAP interface would be required.
I'm not sure if those are available in Fabric.
Anyway, same can be achieved through automation APIs using, for instance, webhooks.

**Comment by yuvalp-k2view** [comment]
SMTP is a protocol for sending email. There is currently no builtin actor to retrieve emails mailbox.
Indeed webhooks (web service) are an easier way to be notified on events. 
We can explore inbox integration as a future Broadway actor.
