### ISSUE TITLE
Behavior of Reference Tables

### ISSUE THREAD

**Issue by debargha95** [k2view-academy/K2View-Academy#1056]
Hi,

We are doing Reference Syncs using ref_Sync tables='all';
One of the ref table failed because of some issue in the source and the fabric node was restarted. The ref_Status for that table is showing as READY.
![image](https://github.com/k2view-academy/K2View-Academy/assets/165196534/9ce40281-2fee-478b-b9e5-48197491802e)
However in the k2_jobs table it is showing up as FAILED.
![image](https://github.com/k2view-academy/K2View-Academy/assets/165196534/d9a77edc-3a56-43a2-a75d-6f86be007c09)
When a Batch tries to run on an LU that uses this Reference table it does not proceed forward and it fails while checking the status of this ref table.

Is this the correct behavior of the ref table, showing as READY after the restart even though the last sync failed ?
How can we make sure that the table sync was successful?

Thank you.

**Comment by lionbro1** [comment]
Hi,

This is a bug, we plan to resolve it on next Fabric release (8.1), better to track it on freshdesk.

**Comment by debargha95** [comment]
Hi Lion,

Thank you for your response. Is the batch process checking the k2jobs table before starting and not the ref_Status?
Which tables should we check to confirm that the ref table loads have been completed successfully?

Regard,
Debargha
