### ISSUE TITLE
Option to create customized reports in TDM and make them available via UI

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#1057]
Hello, one of our customer is asking for a feature to generate customized reports from TDM task execution and make it available for download via TDM UI portal... is it something we can support today or maybe in planned releases? 

They are looking for CSV file with 5-10 columns from their LU tables (they are generating it currently from BW post-exec flow and sending over e-mail, but want to expose via UI instead).

_____________
Best regards,
         Andrey

**Comment by taliei** [comment]
Hi.

Currently, this feature of downloading a customized report from the TDM portal is not available.  We will add this feature to our backlog.

Thanks,
Tali
