### ISSUE TITLE
Custom hint in TDM param page

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#1058]
Hello, is it possible to add a hint to a parameter in Requested Entities page when we chose 'Parameters' option? 

<img width="736" alt="image" src="https://github.com/k2view-academy/K2View-Academy/assets/92332494/bc4f301a-2b47-4438-ae3b-7fe27aaf1ffb">

Something similar to what we can do in Custom Logic Flow -

<img width="643" alt="image" src="https://github.com/k2view-academy/K2View-Academy/assets/92332494/503282f7-9559-446a-8549-e8fa7dffa54f">

_____________
Best regards,
          Andrey

**Comment by taliei** [comment]
Hi.

We plan to add improvements in the parameters solution in our roadmap for 2024 (Q4). We will add an option to display a description of parameters as a part of this roadmap item.

Tali
