### ISSUE TITLE
Fabric 5.5 | Webservice logging

### ISSUE THREAD

**Issue by neenjapt** [k2view-academy/K2View-Academy#106]
Hi,

_This is a followup on issue https://github.com/k2view-academy/K2View-Academy/issues/101 since I am unable to reopen it._

Thanks for the prompt reply.
However, I have to push the same question again since the link you provided only mentions how to change log levels in a generic way and never mentions anything specific for enabling a finer logging for Webservices.

Using the **Logback.xml** file, can we create specific Logback appenders for Webservices (or even for a specific one in case we just need to troubleshoot a particular one) ?

Thanks,
Bruno

**Comment by lionbro1** [comment]
Tali answered on original issue #101, closing this one

**Comment by feamcor** [comment]
For your information...

The example below can be added to `logback.xml` to enable a separated log file (`k2fabric_ws.log`) for web services.

In the general log file (i.e. `k2fabric.log`) you will find the OOB starting and end web service log messages but, on the new log file, you will find whatever custom log message that you add to a web service (under `com.k2view.cdbms.usercode.lu.k2_ws` package).

``` xml
<!-- ++++++++++++++++++++++++++++++++++++++++++++++++++ -->
<!--             Custom Web Service Logging             -->
<!-- ++++++++++++++++++++++++++++++++++++++++++++++++++ -->

  <appender name="WS_FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
    <!-- In Windows, remove the following "file" property in order to avoid log files renaming errors. -->
    <file>${FABRIC_HOME}/logs/k2fabric_ws.log</file>
    <rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
       <fileNamePattern>${FABRIC_HOME}/logs/k2fabric_ws.log.%d{yyyy-MM-dd}.%i</fileNamePattern>
       <maxFileSize>100MB</maxFileSize>
       <maxHistory>10</maxHistory>
       <totalSizeCap>3GB</totalSizeCap>
    </rollingPolicy>
    <encoder>
      <pattern>%-5level [%thread] %date{ISO8601} %logger{10} - [LID%X{logid}] %msg%n</pattern>
    </encoder>
  </appender>

  <appender name="WS_ASYNC500" class="ch.qos.logback.classic.AsyncAppender">
    <queueSize>500</queueSize>
    <discardingThreshold>0</discardingThreshold>
    <appender-ref ref="WS_FILE" />
  </appender>

  <logger name="com.k2view.cdbms.ws" level="INFO" additivity="false">
    <appender-ref ref="WS_ASYNC500" />
    <appender-ref ref="ASYNC500" />
  </logger>

  <logger name="com.k2view.cdbms.usercode.lu.k2_ws" level="INFO" additivity="false">
    <appender-ref ref="WS_ASYNC500" />
  </logger>

  <logger name="com.k2view.cdbms.usercode.lu.k2_ws.CSM" level="DEBUG" />
  <logger name="com.k2view.cdbms.usercode.lu.k2_ws.CCB" level="DEBUG" />
  <logger name="com.k2view.cdbms.usercode.lu.k2_ws.KIAS" level="DEBUG" />

<!-- ++++++++++++++++++++++++++++++++++++++++++++++++++ -->
```

For more granular control, add a logger per category class that you require (see 3 loggers at the bottom of the example above) and declare the custom logger on each corresponding category class.

``` java
public class Logic extends WebServiceUserCode {
	protected static Logger log = (Logger) LoggerFactory.getLogger(Logic.class.getName());
...
}
```
