### ISSUE TITLE
Disable Catalog classifiers w/o deleting them

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#1060]
Hello - is it possible to disable default catalog classifiers w/o deleting them (and w/o unselecting PII checkbox under PII config page)?

_____________
Best regards,
         Andrey

**Comment by natalylic** [comment]
Yes, it can be done by setting the score of the relevant classification to zero.
Note that it you disable the classification, the classification will not be assigned and as a result - the PII will not be assigned as well.
![image](https://github.com/k2view-academy/K2View-Academy/assets/62207927/9907a268-6f23-4c9d-ae91-8cb28d9c8838)
