### ISSUE TITLE
Cloud JDBC Interface - Schema filter

### ISSUE THREAD

**Issue by Talbarkan** [k2view-academy/K2View-Academy#1062]
Hi,

How do I setup schema filter in jdbc (Oracle) cloud interface?

**Comment by eyalk2** [comment]
What is the purpose of the filter? I remind you that the filter at .Net is just optimization for the Studio, and not related to Fabric actions.

**Comment by Talbarkan** [comment]
I need the same optimization...
I have DBs with many schemas that i don’t need and it takes a very long time to load/run queries etc.


Regards,

 ***@***.***

Tal Barkan
(+972) 050-2146510

**Comment by eyalk2** [comment]
Showing only specific schema at Studio does not affect on queries, which is done by Fabric.
Works differently than in .Net, and for this there is no point to filter schemas

**Comment by Talbarkan** [comment]
So you are saying that i need to include the schema name in every query there might be the same table name in multiple schemas...



Regards,

 ***@***.***

Tal Barkan
(+972) 050-2146510

**Comment by eyalk2** [comment]
yes.
like you need to do anyway. meaning for runtime


________________________________
