### ISSUE TITLE
How are partitions for common table related topics defined?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#1063]
When I deploy references, the corresponding topics will be created with how many partitions? Is it a fixed value? Is it dependent on the num.partitions property in server.properties?

Also, does the common area consumer check for how many partitions are in the topic? Does it matter to this consumer?

**Comment by lionbro1** [comment]
Common tables are not using partitions, it is using partition_id as zero, it can't be changed in the configuration.
