### ISSUE TITLE
How to pass null value to LUFunction actor input ?

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#1066]
Hello, I'd like to call a java function from my BW flow using LuFunction actor. Function that I'm calling has few input parameters and I need to set few of them into null value. When I'm trying to do so using NullValue actor in front - I still see that my LuFunction is getting empty String object (for inputs defined as String type) instead of null:

This is how it is in the flow - for reference only for executionNote input:
<img width="241" alt="image" src="https://github.com/k2view-academy/K2View-Academy/assets/92332494/41fc5546-63b9-44ff-8055-9a78a8820e36">

and this is what I see from debugger:
<img width="197" alt="image" src="https://github.com/k2view-academy/K2View-Academy/assets/92332494/40851934-6f14-4d61-ba5f-33baebb4c70e">

For reference - these are all my input params defined in java function and as I see null is coming only for Object datatype and always initialized into "" or 0 or 'false' for Primitive datatype (like Integer, Boolean, String, Long). 

<img width="164" alt="image" src="https://github.com/k2view-academy/K2View-Academy/assets/92332494/34cc7944-f510-4594-ade2-2921a7ae135b">

Is there any way to make inputs as null for all datatypes?  

______________
Best regards,
          Andrey

**Comment by natalylic** [comment]
In Broadway **null** has an implicit conversion to every supported **primitive** type (String, Long, etc).
The **NullValue** actor assigns the Object with the **null** value specifically. 
You should do one of the following:
1. Define the required input param as **Object**. Then, if there is no link to this input, it will be "translated" as null. Or you can as well connect the **NullValue** actor to this input.
2. Or, Use a **MapCreate** actor:
![image](https://github.com/k2view-academy/K2View-Academy/assets/62207927/d99b19ad-af83-4440-8696-7d9665e3183d)

**Comment by avvakandr** [comment]
Hi Nataly,
 If I change input param to be an Object - via LuParam - inptut param - set schema

{
    "type": "object"
}

then I still get empty string in my java function as an input (or you meant to say I have to change it in Java function from String to Object)?

If I use NullValue -> MapCreate -> LuParam as you proposed in option 2 above - then I get my input as "{}" (it loos like it is getting converted to the type I have under java function for this param):

<img width="357" alt="image" src="https://github.com/k2view-academy/K2View-Academy/assets/92332494/93919b8a-5ca4-4a6f-ba3f-1d9cfcccf222">

and result in debugger:

<img width="395" alt="image" src="https://github.com/k2view-academy/K2View-Academy/assets/92332494/db03295c-7321-4550-94e4-1ed5330b02b6">

Is there something wrong in how I use MapCreate ? I have just one input as input1 defined as link:
<img width="155" alt="image" src="https://github.com/k2view-academy/K2View-Academy/assets/92332494/4ad3d2fd-22be-4e4a-8769-99d38716cbec">

____________
Best regards,
         Andrey

**Comment by natalylic** [comment]
I meant that you need to define the Java function input as Object.
