### ISSUE TITLE
Implement Web Service in Fabric that takes HTML Form as Request

### ISSUE THREAD

**Issue by patriciailie42** [k2view-academy/K2View-Academy#1068]
Fabric 7.2.2 .+ NET Studio

Hi,
Please advise how to implement a web service in Fabric that allows HTML Form requests (`application/x-www-form-urlencoded`).
Currently, when implemeting the web service I keep getting error `406` (Not Acceptable) with the following exception: 

```
ERROR 2024-05-21 07:56:19,683 [LID710d000000000021] [http-nio-3213-exec-6] c.k.f.a.ApiServlet - Failed while executing /api/customer/35
com.k2view.fabric.api.ApiServletException: unsupported media type application/json
...
```

Thanks.

**Comment by eyalk2** [comment]
Only JSON and XML are supported
