### ISSUE TITLE
Call in BroadWay a HTTP Request with Inputs 

### ISSUE THREAD

**Issue by barakgk2view** [k2view-academy/K2View-Academy#107]
We are trying to invoke from a Braodway Flow a WebService which performs a POST (Insert record to Common).  
We had passed to the parameter of "stream" in the HTTP actor the JSON 
{
  "MEDICATION_NAME": "MARIANA4",
  "MEDICATION_ID": "204"
}
Where the common table (MEDICATION_REFERENCE)includes those two fields 
And getting the below error
com.k2view.fabric.commonArea.producer.MessageDataHandleException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (NOT NULL constraint failed: MEDICATION_REFERENCE.MEDICATION_ID)
 
![image](https://user-images.githubusercontent.com/26691183/95011431-52fac200-0639-11eb-80df-05d2ea8f9304.png)

**Comment by natalylic** [comment]
The **Http** Actor is able to receive the data using **[stream]** input argument.
Add "Content-Type": "application/json" to the **header** input argument, to specify that the input is in JSON format.
Make sure the input is enclosed into [ ] brackets like this:
In the below example, the input is:
[
  {
    "ADDRESS_ID": "200"
  }
]
The Http header is:
{
  "accept": "application/json",
  "Content-Type": "application/json",
  "Authorization": "Bearer token1"
}
![image](https://user-images.githubusercontent.com/62207927/95014268-74b27400-064e-11eb-82d6-6141e74e1bbc.png)
