### ISSUE TITLE
Fabric LUI schema change behavior

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#1070]
How does Fabric know there is a change in schema of an LU? Is it based on some hash? by comparing table by table, column by column?

How will a Fabric GET command behave in following scenarios? Assume it is in SYNC OFF mode.
1. LU was deployed but there was NO* change in schema
2. LU was deployed following a change in schema (eg: new column was added)
3. LU was deployed with a schema change but before we refresh the LUIs, the schema change was reverted, and LU was deployed again 

My fabric version is v6.5.9_HF19 but will any of this behavior change with newer versions?

**Comment by natalylic** [comment]
Please see the following article which describers the sync behavior: [here](https://support.k2view.com/Academy/articles/14_sync_LU_instance/10_sync_behavior_summary.html).

Schema change are considered any change such as add or delete a column, rename table, add or delete table, change column type. Assuming these changes have been deployed. 
This behavior has been in the system for many versions and is not changing in the newer versions.

**Comment by smokyMount** [comment]
Hi Nataly,

The article talks about sync behavior. How does Fabric know there is a change in schema of an LU? Is it based on some hash? by comparing table by table, column by column?
Also, will it apply schema changes to an LUI if LU was deployed with a schema change but **_before_** we resync that LUI, the schema change was reverted, and LU was deployed again?
