### ISSUE TITLE
Running command on SFTP interface

### ISSUE THREAD

**Issue by dotants** [k2view-academy/K2View-Academy#1072]
Hi

We have an SFTP interface, on which we need additional operations, mainly "mv", in addition to file-read / file-write.
However, the interface does not allow SSH connection, i.e. we cannot define an SSH interface with the same credentials.

How can we execute one of the commands supported by SFTP on the SFTP interface? What is the Java code for it?

**Comment by natalylic** [comment]
There are several built-in actors that support the commands: **cp, ls, md, mv, rm**.
![image](https://github.com/k2view-academy/K2View-Academy/assets/62207927/ef5a6826-9f99-4560-94b5-1fe5dbe473f1)

**Comment by dotants** [comment]
Please note: the "mv" actor does not work with "SFTP" interface and always fails with "no such file" exception (Fabric 7.2).
Replacing it with "cp" and "rm" solves the issue.

**Comment by natalylic** [comment]
Please open a ticket for it, with the exception stack and all details, and it will be checked and fixed.
