### ISSUE TITLE
[TDM] LuParams - special characters in column_name field of LuParams MTable

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#1075]
Hello - can we use special characters in LuParams MTable (under column_name)? Client is looking to use parameters that starts with * r $ to indicate special use for it to their end users. 

For example, they want to create task templates and instruct users that if parameter starts with '*' - like *BANK_CODE - testers should not modify value for it and keep it unchanged while using this template to create their own task (or execute existing task).

I tested this in my local env and it seems working, but I'd like to confirm there is no hidden issues with it...

___________
Best regards,
           Andrey

**Comment by taliei** [comment]
Hi.

You can add a special character to the parameter's name. Example:
![image](https://github.com/k2view-academy/K2View-Academy/assets/43947470/a5c2066a-751b-4589-a60a-337a40f06e27)

Notes:
The LU name is always concatenated with the parameter's name.
If you change a parameter name, you must drop the <lu>_params table and clean the LU's records from the tdm_params_distinct_values. Then you need to redeploy the Reference and rerun an extract task with sync mode force (Always Refresh Data from Source option).

Tali
