### ISSUE TITLE
[TDM] LuParams - Using > or < or >= or <= operands for date type params

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#1076]
Hello - one of our customer has defined LuParam as date type and they want to configure load task using ranges based on that param (like 'open' > 2024-02-01 and 'open' < 2024-03-01). 

We can see only = or <> or IN or NOT IN or IS NULL or IS NOT NULL coming up for this type in TDM UI. Is there a way to configure ranges for date type?

____________
Best regards,
         Andrey

**Comment by taliei** [comment]
Hi.

This is a bug in TDM 8.1. We solved it in TDM 9.0. Do you plan to upgrade TDM 8.1 to TDM 9.0? If you need HF on TDM 8.1. please open a freshdesk ticket.

Thanks,
Tali
