### ISSUE TITLE
Is there a way to permanently turn off Auto Refresh in GUI?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#1079]
Or is there an option to increase the interval between each refresh?

![image](https://github.com/k2view-academy/K2View-Academy/assets/66338066/149ba382-073c-469f-806a-7df8f1326f31)

**Comment by lionbro1** [comment]
No, It is currently not configurable. If you need such capability please raise a CR in freshdesk and explain the motivation.
