### ISSUE TITLE
How do i enable SSL/TLS1.2 for web services?

### ISSUE THREAD

**Issue by benkipnis** [k2view-academy/K2View-Academy#108]
How do i enable SSL/TLS1.2 for web services?  

Additionally, can services be configured to make SSL connections using the normal port (3213)?

Fabric 6.2.1

**Comment by lionbro1** [comment]
There is Fabric hardening document that covers all security hardening aspects. WS with SSL is covered on section 4.5.

https://k2view.sharepoint.com/:w:/r/sites/KS/_layouts/15/Doc.aspx?sourcedoc=%7B480201FA-6D79-412A-A153-BC6C9530EC4C%7D&file=Fabric%206.2%20Hardening.doc&action=default&mobileredirect=true
