### ISSUE TITLE
K2VIEW Catalog: Is it possible to manually mark a field as a PK/FK 

### ISSUE THREAD

**Issue by alexmessel** [k2view-academy/K2View-Academy#1080]
Is it possible to manually mark a field as a PK/FK in the catalog for VIEWS on DBs that don't support defining  PK/FK on views?

**Comment by natalylic** [comment]
Yes, as part of Edit Catalog - you can add any custom property to any dataset or field.
In the images below, you can see that a PK was added to the field MusicianId:
![image](https://github.com/k2view-academy/K2View-Academy/assets/62207927/2207417f-f556-4d93-8d1b-10fa22413ee8)
![image](https://github.com/k2view-academy/K2View-Academy/assets/62207927/c7dc4445-4b4b-4635-a44e-e2f3dd0b34de)
