### ISSUE TITLE
Batch Process from larger physical machine

### ISSUE THREAD

**Issue by debargha95** [k2view-academy/K2View-Academy#1087]
Hi team,

In our cluster we have 25 VMs with 16 cpus and 2 physical machines with 112 cpus. We run a lot of batch processes. Is there any benefit in starting the batch process from the larger physical machine compared to the smaller vms?

Regards,
Debargha

**Comment by lionbro1** [comment]
Hi,

No benefit, you can run it on any node, the importance is how to control the balance between the nodes by a configuration of the workers and affinity
