### ISSUE TITLE
Graphit - Trace

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#1088]
Fabric 6.5.9

I'm trying to profile the execution of a graphit using the trace command.
Already tried with `level=debug`, `operations=graphit`, even `category=solutions`, but got no entry related to the graphit start, iterations, end, etc.
What is necessary to make it to work properly?
Be aware that we added other operations/categories also (e.g. webservice, sqlcommands, etc.).
Please advise.
Thanks.

**Comment by Rwedkabha** [comment]
how did you run you graphit file(direct in studio/BW/WS) ?

my tests result :
attached trace file:
[example.fabrictrace.txt](https://github.com/user-attachments/files/15972795/example.fabrictrace.txt)

command that i run :
trace SESSION_SCOPE  test3 'categories=commands;operations=graphit;';

i run it using BW

**Comment by feamcor** [comment]
> how did you run you graphit file(direct in studio/BW/WS) ?
> 
> my tests result : attached trace file: [example.fabrictrace.txt](https://github.com/user-attachments/files/15972795/example.fabrictrace.txt)
> 
> command that i run : trace SESSION_SCOPE test3 'categories=commands;operations=graphit;';
> 
> i run it using BW

Hi @Rwedkabha, hope you are doing well.

Graphit is being triggered from the webservice Java function.

In the file that you shared, I don't see any line that indicates the `graphit` operation.

I see only `connection`, `preparedStatement` and `sqlCommand` that are all database related.

Of course that Graphit includes many queries within, but I want to see its details, similar to what Broadway profiler provides.

Some testing was done and running a set of queries from Graphit is taking 350ms, while running these queries, one-by-one, on Fabric console, when summing up their times, are taking less than 100ms.

Cheers.

**Comment by eyalk2** [comment]
He ran Graphit to get these results. What similar example you have from trace, where you see different results from the trace system. Can you share such trace output?

**Comment by feamcor** [comment]
When trying, I see similar output, but nothing specific to the graphit execution as a whole, like when it started, when it ended, no line with operation graphit.

As I commented before, _Some testing was done and running a set of queries from Graphit is taking 350ms, while running these queries, one-by-one, on Fabric console, when summing up their times, are taking less than 100ms._, I would like to figure out why it takes so long when run by Graphit. I can only assume that it has some bootstrapping and termination process that consumes a lot of time.

**Comment by feamcor** [comment]
No conclusion that trace returns rows related to Graphit execution, apart from the queries executed within.

**Comment by eyalk2** [comment]
sorry for answering in delay - Trace cannot show it.
Please note that what can take time is the GET, which need to sync data. I'm not sure if your calculation of _queries_ take into account this or only the SQL select statements.

(I also thought that you talked about Graphit running as WS, and that open session might take time. But I realized that such session opening shall take only about 1 ms...)

If you still want to investigate it, more deeper, you shall run YourKit to trace it, and send use the results
