### ISSUE TITLE
How to disable the AI in the TDM 9.x? 

### ISSUE THREAD

**Issue by taliei** [k2view-academy/K2View-Academy#1090]
TDM 9.x provides AI integration for AI-based synthetic entity generation. How to disable this capability?

**Comment by taliei** [comment]
Verify that the AI interfaces are disabled (set them to inactive) in the TDM projects in order to disable the AI-based training and generation TDM tasks.
Click [here](https://support.k2view.com/Academy/articles/TDM/tdm_implementation/17_tdm_ai_generation_implementation.html) for more information about the TDM AI implementation.

**Comment by avvakandr** [comment]
Hi Tali, can we delete these interfaces as well as AI-named broadway flows to minimize AI labels appearance ?

**Comment by taliei** [comment]
Hi.

They can delete the AI interfaces if these interfaces are not in use.

Thanks,
Tali
