### ISSUE TITLE
Exec Actor 

### ISSUE THREAD

**Issue by mariana-shinnara** [k2view-academy/K2View-Academy#1091]
Hi,
I want to use the Exec Actor in order to run a bash script.
I provided this command:
**./fabric/scripts/initFinderTables.sh** 
but I'm getting the following error output:
ERROR: transport error 202: bind failed: Address already in use
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [src/jdk.jdwp.agent/share/native/libjdwp/debugInit.c:744]

Am I providing the command wrong? or it's something else.
please advise.

Thanks,
Mariana

**Comment by natalylic** [comment]
It seems that the error is not related to the actor, it is coming from the command:
`ERROR: transport error 202: bind failed: Address already in use`
When you run the command manually, without the actor - does it work?

**Comment by mariana-shinnara** [comment]
Yes I'm able to run the command from the terminal and it works

**Comment by feamcor** [comment]
Please see https://chatgpt.com/share/99c66ed9-619e-46ce-9a57-0448ff39ac18
It might be that it is conflicting with an already open port.
Please check the JVM options used by the tool, at least to ensure that no remote debugging is enabled.
I hope it helps.

**Comment by mariana-shinnara** [comment]
Hi,
I also tried this after consulting with Devops/Nataly. got the same error
<img width="737" alt="Exec" src="https://github.com/k2view-academy/K2View-Academy/assets/70898083/44828da0-5da0-4d25-a3ca-955caad8a1c9">

**Comment by natalylic** [comment]
As discussed in the conf call, please open a freshdesk ticket, attach all the data there and Sergey will continue his investigation.

**Comment by natalylic** [comment]
Regarding your other question about how to run "echo $FABRIC_HOME" command from the Exec actor: 
**Here it is**:
![image](https://github.com/k2view-academy/K2View-Academy/assets/62207927/9d6209d6-8dad-45a5-9e63-0230ed8e89ea)
-------------------------------------------------- **Or like this** -----------------------------------------------------
![image](https://github.com/k2view-academy/K2View-Academy/assets/62207927/5a62413e-d8b9-4eab-9730-4f6288f8d1bf)
