### ISSUE TITLE
Broadway JMXWrite actor

### ISSUE THREAD

**Issue by tarikh03** [k2view-academy/K2View-Academy#1096]
JMXWrite always writes jmx under customStats.
is there a way to use this Actor and write to different title, like iidf_stats_LU in the screenshot example?

<img width="359" alt="image" src="https://github.com/k2view-academy/K2View-Academy/assets/47483757/c1e75a27-3a90-4eef-8341-07d863b59931">

using code for example we simply use:

CustomStats.count("iidf_stats_LU", "whatever1", 1);

**Comment by lionbro1** [comment]
currently not supported
