### ISSUE TITLE
[TDM] Is there an easy way to remove specific post-execution flow from BE and all tasks in TDM?

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#1097]
Hello - one of our client would has a post-execution flow (for example 'mypostexecution') attached to Business Entity 'AAA' and added to several tasks on top of that Business Entity. Now he wants to delete this flow from Business Entity and all tasks where it was added. 

I was hoping that by removing it from BE in TDM UI, it will be removed from all tasks as well, but we still can see this flow in post execution of each task where it was selected before. 

Is there a way to clean it up in some user-friendly way - or they need to go into each task and delete manually (they say they might not know / remember all their tasks where it is used and they have big list of these tasks)?

_____________
Best regards,
         Andrey

**Comment by taliei** [comment]
Hi.

We've added a ticket for TDM 9.1 to automatically remove a post/pre-execution process from the related tasks when this process is removed from the BE.

Meanwhile, you can identify the related tasks using the following query on the TDM DB: 

select t.* from tasks t 
where t.be_id = ? 
and t.task_id in (select te.task_id from tasks_exe_process te where te.process_name = ? );

Then you can open the tasks and remove the post-execution process.

Alternatively, you can run the following query to delete the post-execution process from the tasks:  

 delete from tasks_exe_process te  
 where task_id in (select task_id from tasks t where be_id = ?) 
 and process_name = ?;

Regards,
Tali
