### ISSUE TITLE
[TDM] Is there a way to suppress interface test error while starting task?

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#1098]
Hello - one of our customers is asking if there is a way to suppress interface test error on TDM Start Task operation? 

They have HTTPS interface that is failing on test_connection w/o certificate, but they are using HTTP actor with option noCertificateCheck = true. While they are checking for options to add this into their fabric cert store, they are asking if there is an option to improve user experience by ignoring this interface error somehow so it is not popping up every time they click on start task?

As I see we have an option Ignore Test Connection under Permission Set - but I understand it will not actually suppress this error, but just control whether task should fail immediately or still ask to ignore and continue... 

Is there any way to configure / get rid of this connection error for specific interface?

_____________
Best regards.
          Andrey

**Comment by taliei** [comment]
Hi.

Currently, there is no way to suppress a test connection error message. We've added it to our backlog.

Regards,
Tali
