### ISSUE TITLE
Broadway flow dynamic arguments

### ISSUE THREAD

**Issue by mariana-shinnara** [k2view-academy/K2View-Academy#1100]
Hi,

I have a case where I want to send dynamic number of arguments to the broadway flow. For example:
broadway LU.bwFlows arg1=value1, arg2=value2, arg3=value3 ... 

I don't know the number of inputs or their names, I need to receive them dynamically.
Is there a way to do that in bw?

Thanks,
Mariana

**Comment by natalylic** [comment]
**InnerFlowDynamic** actor allows to send **flowName** and its **params** dynamically at run time.
