### ISSUE TITLE
Is there a function in Fabric that lets you read custom jmx stat ?

### ISSUE THREAD

**Issue by tarikh03** [k2view-academy/K2View-Academy#1101]
there is a reset and count methods in CustomStats to set the jmx, but I couldn't find a method that reads the JMX, like there is in broadway with JMXRead actor in Broadway.

is there such method we can use?

**Comment by lionbro1** [comment]
Hi,

As you mentioned above the JMXRead actor provide this info, why you need it as a user function?

**Comment by tarikh03** [comment]
because the JMXWrite doesnt provide the option to choose our own jmx title.
so we have to use java to do it. in relation to -> https://github.com/k2view-academy/K2View-Academy/issues/1096

**Comment by lionbro1** [comment]
We have the following method to support it, let us know if it helps so we can expose it as user code on next releases.

Stats supports:
public long value(StatsType type, String key) {
return StatsNode.get(this).findLeaf(key).value(type);
}

**Comment by tarikh03** [comment]
when trying to initialize Stats in order to call value, just like JMXRead does, it is failing for below exception:

ERROR 2024-07-11 09:39:48,257 [LID3b07000000000020] [http-nio-3213-exec-4] c.k.f.s.m.FabricCommandMB - 
java.sql.SQLException: com.k2view.broadway.exception.StageException: Flow: bwReadLag Level: 2 Stage: Stage 2 Actor: ReadLag1 CONSUMER_GROUP is not a valid Stats [init, fabricCommands, fabricCommandsErrors, solutionDeploy, tableSweep, maintenanceErrors, maintenanceIncrementalVacuum, maintenancePassiveCheckPoint, maintenanceTruncateCheckPoint, webserviceCurrentRequests, webserviceCalls, webserviceErrors, simpleLUIQueries, jdbcActiveSessions, jdbcIdleSessions, jdbcMaxSessions, workerThreads, logicalUnitType, loaderQueue, loaderTotal, loaderFailed, loaderSuccess, loaderInFlight, cassandraC


![image](https://github.com/k2view-academy/K2View-Academy/assets/47483757/97c4dccf-516d-4f89-9557-9d39a0f803fb)

when I try to read customerStats, it works, because it is part of the Stats Enum.
