### ISSUE TITLE
Logs after changing config.ini

### ISSUE THREAD

**Issue by mariana-shinnara** [k2view-academy/K2View-Academy#1102]
Hi,
I'm changing config.ini parameters and I want to know if fabric restart is needed after the change or not.
Can I rely on the k2fabric.log? I tried observing the log message after I changed few parameters but each time I see a different message.

what is the best way to know if fabric restart is needed after changing config parameter?

Thanks,
Mariana

**Comment by lionbro1** [comment]
Hi,

yes, you should rely on the log message, it notifies you if a restart is needed or not.

**Comment by mariana-shinnara** [comment]
what is the message to look for?

**Comment by lionbro1** [comment]
If a restart is needed you will get the message

Configurator will not update "parameter name" from "parameter old value" to "parameter new value" at runtime
