### ISSUE TITLE
Where can we find documentation of com.k2view.cdbms.shared.Db?

### ISSUE THREAD

**Issue by dotants** [k2view-academy/K2View-Academy#1103]
Hi

Where can we find documentation of com.k2view.cdbms.shared.Db?
[there is no documentation of it in the Fabric Admin --> Documentation page]

**Comment by lionbro1** [comment]
Hi,

You can find it under the documentation application

"your host"/app/doc/user-api/com/k2view/cdbms/shared/Db.html
