### ISSUE TITLE
Restart of fabric is failing on QUORUM error when cassandra consistency Level is Local_ONE

### ISSUE THREAD

**Issue by Samba-4382** [k2view-academy/K2View-Academy#1105]
we have cassandra cluster with two DC'S, And we have one DC down.
select from fabric using cqlsh is working and api calls is working fine.
But when we tried to restart fabric it is failing with QUORUM error even when the consistency level is LOCAL_QUORUM under cassandra section.
we changed the setting to LOCAL_ONE, But still failing on QUORUM error.
Tried to start one node in other DC which is down, But fabric is still failing on QUORUM error.
Is there a way to fix it or did anyone faced this issue

![Fabric error](https://github.com/user-attachments/assets/2c102fdf-87d3-45d3-b87b-6cca96af7bb2)

**Comment by lionbro1** [comment]
Hi,

We are not familiar with such an issue, please open a freshdesk ticket with all the details (full log) for tracking.

Meanwhile closing the Q&A.
