### ISSUE TITLE
Is Fabric v7.2.x compatible with Cassandra v3.11.x?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#1106]
The release notes say certification from 7.1.x onwards was done on Cassandra v4 only.

**Comment by lionbro1** [comment]
As stated on the release notes https://support.k2view.com/Academy/Release_Notes_And_Upgrade/V7.2/Fabric_Release_Notes_V7.2.2_HF9.pdf.html Fabric 7.2.2 was certified with Cassandra 4.1.3, but it works with Cassandra 3.11.X as well
