### ISSUE TITLE
Using secretmanager outside of interface config

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#1107]
Hello, one of our clients is using secretmanager integration (HashiCorp) for interface credentials access (like user / password / tokens). This integration works fine for all their interfaces config. 

In one of their API calls they need to pass this token in a payload as well - is there a way to configure / access this secretmanager parameter from BW flow or via global ?

We tried to set it for global the same way it is resolved for interface - but this doesn't seem to work and giving us the same value as we set ${secretmanager:approle/tdm_test.afsAuthSecret} and not the actual value from HashiCorp.

_______________
Best regards,
          Andrey

**Comment by eyalk2** [comment]
What do you mean in " they need to pass this token in a payload"?
From later setntence it is looks like you mean that the value is dynamic, right?

**Comment by avvakandr** [comment]
Hi Eyal - this value is not dynamic, but it is stored in HashiCorp. They need to get it from HashiCorp and send it inside payload. 

They are using same values today in interface config and it is working ok for interface - via ${secretmanager:approle/tdm_test.afsAuthSecret}. 

Question how to read this inside BW flow where they construct payload for API.

_____________
Best regards,
          Andrey

**Comment by eyalk2** [comment]
Got it. 
But is not the interface itself enough to provide their need? is not it one of supported API methods we have in interfaces?

**Comment by avvakandr** [comment]
Let me double check if they need something special for that - maybe you are right and they just need to switch to different interface auth methods...

___________
Best regards,
         Andrey
