### ISSUE TITLE
Graphit to return the right format in json

### ISSUE THREAD

**Issue by mnfirefly** [k2view-academy/K2View-Academy#1110]
Hi,
I have the following setting in Graphit:

![image](https://github.com/user-attachments/assets/7d75825b-e7e7-4903-b2d1-29a67a3be885)

The result is:

`"subscriberID" : [ {
"subscriberID" : "1234"},
{"subscriberID" : "5678"}
]
`

But I need this result:

`"subscriberID" : [ 
"1234",
"5678"
]`

What are exactly the settings to make it return a result like this?

Thank you :)

**Comment by lionbro1** [comment]
Hi,

The solution is to introduce an array that will aggregate the values and print the array outside of the loop.

For example:
<img width="1310" alt="Screenshot 2024-07-25 at 13 46 57" src="https://github.com/user-attachments/assets/acbfe24b-3e74-4b1f-8a2a-dff9b1ae71f9">

**Comment by mnfirefly** [comment]
Thank you, @lionbro1 for this solution.
I hope it will work for me :)

**Comment by alexmessel** [comment]
There is an alternative way to get a JSON array

![image](https://github.com/user-attachments/assets/e18c4633-7535-4674-8051-de0e2f7b7dcd)
