### ISSUE TITLE
[WEB STUDIO] What is the purpose of Environments.k2fabEnv_encrypted.xml file in Web Studio

### ISSUE THREAD

**Issue by alexmessel** [k2view-academy/K2View-Academy#1112]
In the web studio there is a Environments.k2fabEnv_encrypted.xml file which has the same format  and information as Environments.k2fabEnv.xml.

What is the purpose of this file?

**Comment by eyalk2** [comment]
This is probably some leftover in your project at Git. remove it. not needed

**Comment by alexmessel** [comment]
I created a project from scratch, and then that file appeared.

**Comment by eyalk2** [comment]
please share the environment details (link)
In general, this is an option to preserve 2 versions of the environment xml, but as mentioned - this is not in use at web studio.
