### ISSUE TITLE
Where are the interface details from environment file stored in v7.2.2?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#1113]
In v6.5, I could check an interface's maxConnectionsNumber, jdbc url etc from global_settings table in Cassandra. That seems to have changed in v7.2.2. Where can I find those details now? I want to verify that the environment file deployed few days back was correct one by verifying details about interfaces.

This is the query that worked on 6.5.9 and before.
`SELECT * from k2system.global_settings where name='ENVIRONMENTS_DATA';`

**Comment by lionbro1** [comment]
Hi,

In order to support all the different storage types, from Fabric 7.x and on, this information is saved in defined storage (parameter: DEFAULT_GLOBAL_STORAGE_TYPE in config.ini) as blob

**Comment by smokyMount** [comment]
Thanks. How can I view it as plain text? I tried using blobasText in select query but that did not work.
As mentioned before, we want to look at it for verification purpose.

**Comment by lionbro1** [comment]
You can't, but this is done on purpose in order to make sure there is no access to the interfaces full details (passwords, etc..)
