### ISSUE TITLE
Broadway Job Retry

### ISSUE THREAD

**Issue by mariana-shinnara** [k2view-academy/K2View-Academy#1114]
Hi,

What is the way to start broadway job without retry mechanisim?

**Comment by natalylic** [comment]
The ability to control the number of retries when executing a job can be done via the user code as follows:
```
import com.k2view.cdbms.jobs.JobExecutor;

JobExecutor.failJob(new Exception(), JobExecutor.FailAnd.noRetry);

```
See more details how to define the # of retries or no retries [here](https://github.com/k2view-academy/K2View-Academy/issues/893).
