### ISSUE TITLE
Can Fabric Report Data be fetched from External DB?

### ISSUE THREAD

**Issue by gtoumiek2** [k2view-academy/K2View-Academy#1115]
i'm working currently on a project that stores the results of a process in an external postgres database which connects to it using the interfaces in fabric project

then using another broadway flow, i query that data from the external postgres database, and generate an excel file

im trying to replace that excel with a fabric report

**Comment by natalylic** [comment]
The Fabric's Reports application enables building the reports which receive the data using a REST API.
You can create a Graphit or WS that retrieves the data required for your report and then bind it to the report layout. 
All the information about how to build a report can be found in the Support site - [here](https://support.k2view.com/Academy/articles/38_reports/01_reports_overview.html).
