### ISSUE TITLE
Data profiling CSV files for PII 

### ISSUE THREAD

**Issue by AlexMaziya** [k2view-academy/K2View-Academy#1118]
Is there a way to run discovery job directly on sets of CSV files for PII identification?

**Comment by natalylic** [comment]
Yes, you can do it as follows:
1. Install the CSV JDBC connector in Web Studio.
2. Create an interface with type = CSV
3. Run the discovery job on this interface

This is an example CSV interface definition:
![image](https://github.com/user-attachments/assets/527e0de1-48a5-4618-b3b2-39ccb17ca43e)

Then you run the discovery and it identifies the classifications & PII - just like for any JDBC interface:
![image](https://github.com/user-attachments/assets/5b5ee21f-4318-4a6e-9e3c-706e4afdc388)
