### ISSUE TITLE
Javascript actor - Bridge to Java data types - Nashorn

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#1120]
Fabric 7.2.2

A few questions about the Javascript actor:

1. I see that Nashorn is being used. What version of ES is it being bootstrapped? ES6?
2. I see that the code completion in the Javascript actor provides tips related to the browser/webview interpreter (a lot of references to DOM, SVG, etc.) instead of the Fabric embedded interpreter. Why is that? It doesn't seem correct in the context of a Broadway flow.
3. I'm not able to use Java data types (e.g. initialize an ArrayList, etc.) within the Javascript actor, restricting some actions that could be easily handled through the Java bridge instead of building flows with boilerplate actors. Is there some configuration to enable that?

Please advise.
Thanks.

**Comment by yuvalp-k2view** [comment]
Formally ES6 but Nashorn support is very limited. Currently there isn't an option with a similar performance to Nashorn.
We do try to improve this a bit by running babel on the output to make it more compliant. If you check the actual flow file, you can see that there are sometimes js versions (if needed).

We will check if we can change the code completion settings to be configured for javascript w/o browser api support.

We currently don't expose the Java api directly. Working with basic types [] {} number string date etc will work for most cases since after the execution, we convert the result to more native java objects.

**Comment by feamcor** [comment]
Hi @yuvalp-k2view,
Javascript arrays are translated to Java maps where keys are the array indices.
This behavior doesn't allow Javascript code that enhances an input object (map) to be written.
When translating the map to JSON, it breaks the expected schema (as object/map is not an array).

This example (only for illustration):

```javascript
if(conditionIsTrue)
{
  inputObject["newKey"] = [
    { "key1":"value1", "key2":1 },
    { "key1":"value2", "key2":2 }
  ];
}
inputObject;
```

Would translate to the following JSON:

```json
{
  "key1":"value",
  "key2":"value",
  "newKey": {
    "0": { "key1":"value1", "key2":1 },
    "1": { "key1":"value2", "key2":2 }
  }
}
```

Instead of the following JSON:

```json
{
  "key1":"value",
  "key2":"value",
  "newKey": [
    { "key1":"value1", "key2":1 },
    { "key1":"value2", "key2":2 }
  ]
}
```

The reason for such behavior is clear, but allowing the bridging with Java data types, would allow the following code (only for illustration):

```javascript
if(conditionIsTrue)
{
  const newArray = ArrayList() // or java.util.ArrayList()
  const item1 = { "key1":"value1", "key2":1 };
  const item2 = { "key1":"value2", "key2":2 };
  newArray.add(item1);
  newArray.add(item2);
  inputObject.newKey = newArray;
}
inputObject;
```

**Comment by feamcor** [comment]
In the screenshot below, I present three ways of performing similar change (again, only for illustration), depending on much of the new data is static and can be represented through `Const` actors.

![image](https://github.com/user-attachments/assets/3900aad3-d3bd-42dd-a49d-772aa16b71dc)

**Comment by yuvalp-k2view** [comment]
As I wrote, when the types are returned from the Javascript actor we make sure to turn them into Java native objects. For instance:
<img width="473" alt="Screenshot 2024-08-14 at 19 25 31" src="https://github.com/user-attachments/assets/8ffa513b-38a1-4f1b-9aac-eb2bdc900adc">
