### ISSUE TITLE
Parameter for the number of total object instances allocated to the pub sub pool

### ISSUE THREAD

**Issue by debargha95** [k2view-academy/K2View-Academy#1122]
Hi,

In Fabric 7.2.2 we have the PUB_POOL_MAX_TOTAL in the config.ini that we can use to control the number of total object instances allocated to the pool for the Publish actor.  What is the equivalent to that in Fabric 6.5.9 and what is it set to?

Regards,
Debargha

**Comment by omernissan** [comment]
In Fabric 6.5.9, we use the same parameter, PUB_POOL_MAX_TOTAL. The default value is set to 1000.

**Comment by debargha95** [comment]
PUB_POOL_MAX_TOTAL is not there in the config.ini. Is it a hidden parameter that we can add to the config.ini and update the default value of 1000?
We are using 6.5.9 HF 18 and HF 19.

**Comment by natalylic** [comment]
Yes, this parameter is hidden in 6.5.9.
