### ISSUE TITLE
How to pass binding variables to batch command based on an SQL query?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#1123]
Is it possible to have select query in the batch command with binding variables when it's triggered from Broadway or Java?
For example, in this sample command from a broadway flow, cycle_no is to be passed dynamically:
`Batch CustomerLu using ("select customer_id from customer where cycle_no=${cycle_no}") fabric_command="sync_instance CustomerLu=?";`

When I try to run a similar batch command from a broadway flow, it throws following error:

```
java.sql.SQLException: com.k2view.broadway.exception.StageException: 
Flow: flowTestBindingBatchCommand Level: 2 Stage: Stage 2 Actor: DbCommand2 column index out of range [1-0]
Batch CustomerLu using ("select customer_id from customer where cycle_no= ? ") fabric_command="sync_instance CustomerLu=?"; class java.sql.SQLException Cause: column index out of range [1-0]
```

**Comment by smokyMount** [comment]
i can prepare the query before running it in batch command but then it wont be a prepared stmt

**Comment by natalylic** [comment]
The way to do it is by running the BATCH command from the Broadway flow as follows:
1. Receive an input parameter using as External input, e.g.: `10`
2. Define the rest of the SELECT statement as Const, e.g.: `select customer_id from CUSTOMER where customer_id <= `
3. Concatenate them using the Concat (without any delimiter).
4. Execute BATCH using DbCommand actor, with the following SQL: `BATCH Customer FROM CRM_DB USING ( ${sql_state} ) FABRIC_COMMAND="sync_instance Customer.?" with async=true;` while the sql_state param will receive the concatenated string.
<img width="522" alt="image" src="https://github.com/user-attachments/assets/00829286-1f8c-4e6d-9dea-7a1bcbaf7b3e">

**Comment by smokyMount** [comment]
Yes, I know this option, but this is not a prepared statement to the database to fetch the iid list.

**Comment by natalylic** [comment]
This is currently the only available option in the product.
