### ISSUE TITLE
Where do we define paths for k2fabric.err and k2fabric.out files?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#1125]

**Comment by mhanna** [comment]
Hi
The mentiond paths are defined in the start scripts and set to 
ERR="$FABRIC_HOME/logs/k2fabric.$TS.err"
OUT="$FABRIC_HOME/logs/k2fabric.$TS.out"

While the TS is the current timestamp

For more details
https://support.k2view.com/Academy/articles/21_Fabric_troubleshooting/02_Fabric_troubleshooting_log_files.html
