### ISSUE TITLE
GraphIt - JSON object with no entry name

### ISSUE THREAD

**Issue by benkipnis** [k2view-academy/K2View-Academy#113]
I am trying to create a single-level JSON via GraphIt using a LUDB query.  I want to query the data and produce a single-level JSON with the fields in it.  Something like:

{
"field1" : "value1",
"field2" : "value2"
}

When i build the GraphIt, it requires me to put an entry tag on the SQL query which in turns adds that tag as the field name, creating something more like:
{
"entry_field" : {
  "field1" : "value1",
  "field2" : "value2"
  }
}
If i leave the entry tag empty/null, the SQL does not run/display results.

GraphIt Screenshot:
![image](https://user-images.githubusercontent.com/31930711/95511930-1d7e0d80-0986-11eb-8957-7f13b0ecf6da.png)

**Comment by lionbro1** [comment]
This is the default functionality -, to omit the root name for JSON (only needed in XML where a root map must have a name).
In this case, you put the "real" root node as a child of another node (GET)..
If you put the GET as a prior sibling of the root, it will work as you intend.

![image](https://user-images.githubusercontent.com/21338328/95682904-a5ffe680-0bf0-11eb-9e72-55498ccaf9c4.png)

![image](https://user-images.githubusercontent.com/21338328/95682914-b9ab4d00-0bf0-11eb-986b-99ea769a5743.png)
