### ISSUE TITLE
How to invoke fabric built-in webservice from broadway or java code

### ISSUE THREAD

**Issue by amirgk2view** [k2view-academy/K2View-Academy#1131]
Hi, 
I have an interface which I can see its details (schemas and  tables) in the query builder. 
I would like to use fabric built in webservice API to get the details (schemas and  tables)  of this interface. 

Is there such an API ? how can I invoke it ? 

Best Regards,
Amir

**Comment by lionbro1** [comment]
Hi,

Currently we don't have a built-in product API to bring this info, you can get it by pure implementation.

We consider adding such APIs on future releases.
