### ISSUE TITLE
Scheduled job starting as result of multiple immidiate jobs

### ISSUE THREAD

**Issue by dotants** [k2view-academy/K2View-Academy#1136]
Hi

On Fabric 7.2, we have a scheduled job that runs daily at 2:00 AM.
During execution of a migration run, we start multiple "immediate" jobs.
It seems that the scheduled job status changes to  "waiting" when the immediate jobs start, and when some of the immediate jobs end the scheduled job is starting instead of waiting for it's scheduled hour.

Is this a known issue? Is there a solution for it?

**Comment by lionbro1** [comment]
The execution of the immediate jobs finished before 2:00 AM? if so, it should schedule the next run to 2:00 AM.

Also please check what was the job status before the immediate execution started.

If that's not happening, please open a ticket with all details in the freshdesk.

**Comment by dotants** [comment]
It seems that it happens when the number of jobs exceeds the K2JOBS_POOL_SIZE.
But why does the scheduled job start to process when a place for it is available?

**Comment by lionbro1** [comment]
it shouldn't, please open freshdesk ticket to track it
