### ISSUE TITLE
What does COMMONAREA_TABLE_REPLICATE job mean?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#1138]
When triggering ref_sync tables=all in fabric_6.5.9 HF19, I see a bunch of COMMONAREA_TABLE_REPLICATE jobs along with COMMONAREA_TABLE_SYNC jobs. We have 146 common tables. I see 146 COMMONAREA_TABLE_SYNC jobs and only 37 COMMONAREA_TABLE_REPLICATE jobs.

1. What does that job type mean? 
2. How is it different then COMMONAREA_TABLE_SYNC?

![image](https://github.com/user-attachments/assets/1b7f4c73-37fd-4911-96e1-2b3a4455c4ec)

**Comment by lionbro1** [comment]
Hi,

Common replicate job is created when a node goes off sync and requests other fabric node to generate a snapshot of its current table.

Technically, the issue related to this situation can arise when node is not responsive and stacks without updating a snapshot within expected time. 

We would recommend upgrading to a version with this issue resolved.
