### ISSUE TITLE
Async code in event function

### ISSUE THREAD

**Issue by ShaniRotemIl** [k2view-academy/K2View-Academy#1139]
Hi,

Following question on:
https://github.com/k2view-academy/K2View-Academy/issues/573

I created a BW flow ("a.flow"), that is using innerFlowAsync to call another flow ("b.flow"). All the second flow does ("b.flow"), is sleeping for 5 seconds (using Sleep actor)

I created 2 events functions, both executing a.flow (fabric().execute("broadway Customer.a");

I see in the logs that the second event function is waiting on the first one to complete, and only then starting.

![image](https://github.com/user-attachments/assets/14d6fdc6-b078-419d-b6ad-05514853b25d)

According to Q&A 573, the GET should wait until all processes completes, not each process waits on the one before it. Can you please explain?

**Comment by lionbro1** [comment]
Hi,

When defining several event functions they will run in sequence order, if you want to run some activities in parallel, please do it under the same event function.

**Comment by ShaniRotemIl** [comment]
I opened a ticket:
https://k2view.freshdesk.com/a/tickets/39207
