### ISSUE TITLE
Broadway Actor "ls", GCS and a Validation error

### ISSUE THREAD

**Issue by gtoumiek2** [k2view-academy/K2View-Academy#1142]
Hi,
We have a validation error triggered in Broadway on an Actor called "ls", we're using it to list files on a GCS bucket
Customer is getting this message "[ validation ] Missing mandatory input on Actor: Is1 ( path )"

but if we specify anything else than empty string the actor will stop working
how can we remove this validation error?
 

 
![image](https://github.com/user-attachments/assets/65e75df8-651e-4aa1-9b89-39ed5bdeed63)

**Comment by natalylic** [comment]
This is only a warning because this parameter is defined as mandatory. However you can still execute an actor and get the results.
![image](https://github.com/user-attachments/assets/211ca502-b904-437f-a5f2-8cb6251bcd19)

**Comment by gtoumiek2** [comment]
is there a way to get rid of this validation warning ?

**Comment by natalylic** [comment]
This error can be dismissed by clicking on it as described [here](https://support.k2view.com/Academy/articles/19_Broadway/18_broadway_flow_window.html#flow-validation-footer).
However, currently the dismiss option doesn't work. It will be fixed in the next version.
