### ISSUE TITLE
GCS Interface listener, new file event retention period

### ISSUE THREAD

**Issue by gtoumiek2** [k2view-academy/K2View-Academy#1144]
Hi, 
Considering the below scenario:
1. fabric server was down, or the interface listener job was down
2. new files arrived in the bucket
3. running the fabric server or starting the interface listener (30 mins later)
4. the events arrived and the InnerFlow was triggered

is there any retention period for these events?

**Comment by natalylic** [comment]
There is no retention period.

**Comment by gtoumiek2** [comment]
does this mean that fabric queries the bucket for all files that it hasn't processed before?

**Comment by natalylic** [comment]
Yes. After the server restart, fabric "remembers" which files were processed.

**Comment by gtoumiek2** [comment]
Thanks for the explanation
