### ISSUE TITLE
Cassandra copy command

### ISSUE THREAD

**Issue by mariana-shinnara** [k2view-academy/K2View-Academy#1149]
Hi, 
I want to execute cassandra copy command in order to copy data from a file to cassandra table, I tried using dbCommand actor but apparently the copy command is not supported.

I there another way to achieve this in broadway?

Thanks,
Mariana

**Comment by natalylic** [comment]
You can use the Broadway actors to read the file and load the data to Cassandra.
Note that it is recommended to use the **Cassandra Loader** interface for writing a lot of data to Cassandra - as explained [here](https://support.k2view.com/Academy/articles/28_cassandra_loader/01_cassandra_loader_overview.html)

**Comment by ShaniRotemIl** [comment]
Nataly,

The question is how can we execute Cassandra copy command on the cloud? we need this option...

**Comment by lionbro1** [comment]
In managed Cassandra you can't have access to cp command, you need to create a broadway flow that will export the table to csv file and visa versa.
