### ISSUE TITLE
Function description

### ISSUE THREAD

**Issue by ShaniRotemIl** [k2view-academy/K2View-Academy#1150]
Hi,

What is the use of the all the descriptions when declaring a function (cloud studio)?
 a.  Function level
 b. Output description
 c. Input description

**@desc("")**
@out(name = "result", type = String.class, **desc = ""**)
public static String functionName(**@desc("")** String param1) throws Exception {
}

I couldn't find anywhere that it is presented

**Comment by natalylic** [comment]
This annotation was introduced for backward compatibility with .NET.
If @desc is specified, it is shown as a Web service description for Open API spec.
