### ISSUE TITLE
Java Logic files

### ISSUE THREAD

**Issue by ShaniRotemIl** [k2view-academy/K2View-Academy#1151]
Hi,

1. What happens when we have two functions with the same name, declared in two different "categories"?
When we are selecting decision/event/trigger/enrichment function in the Studio, i don't see any reference to the package name.

2. How can i use a function from one Category Logic file, in other category?
For example, function in category (package) "Category1", need to use a function that is declared in package "Category2".
Do i have to implicitly write in Category1.Logic:
_import static com.k2view.cdbms.usercode.lu.Customer.Category1.Logic.*;_
?

Thanks

**Comment by natalylic** [comment]
#1 Undefined behavior, the server will run one of these functions. Currently there is no error or warning.

#2 Do the import and use the function, OR write full package name before the function name
