### ISSUE TITLE
ENABLE_PARTITIONED_MDB

### ISSUE THREAD

**Issue by ShaniRotemIl** [k2view-academy/K2View-Academy#1153]
Hi,

When using ENABLE_PARTITIONED_MDB option:
1. Don't we also need to configure ASYNC_LOAD_MAX_MEMORY_IN_MB?
2. How exactly this config works? i understand it adds the chunk to the partition but:
 - What happens after installing the system, deploying an LU and then changing it to true? do we need to delete the table and deploy again?
 - What happens if after some time we change is back to false? do we need to delete the entity table and deploy again, so it won't be part of the partition?

Thanks

**Comment by mironabr** [comment]
Parameter ENABLE_PARTITIONED_MDB  should never be changed on live fabric

**Comment by ShaniRotemIl** [comment]
What about my first question?

**Comment by natalylic** [comment]
When starting a project, you can set ENABLE_PARTITIONED_MDB=true and configure ASYNC_LOAD_MAX_THREADS to the required number of parallel threads. The ASYNC_LOAD_MAX_MEMORY_IN_MB is set to a default value, though it can also be updated. 
Note: there is no upgrade path for existing projects. You must clean all data in Fabric and bring Fabric back. It is recommended to turn this feature on only when dealing with very large LUIs that are split into multiple chunks.

**Comment by ShaniRotemIl** [comment]
1. Maybe we should add it to the KB as ASYNC_LOAD_MAX_MEMORY_IN_MB is not mentioned in this feature context.
2. I discussed with Yuval regarding "It is recommended to turn this feature on only when dealing with very large LUIs ". According to him, it is always recommended, not only for VERY large LUIs
Thanks!

**Comment by natalylic** [comment]
Setting `ENABLE_PARTITIONED_MDB=true` enables the LUI partitioning, while the other two parameters - `ASYNC_LOAD_MAX_THREADS `and `ASYNC_LOAD_MAX_MEMORY_IN_MB `- should be set for the parallel load. 
I updated the articles explanation, so it will be more clear.
