### ISSUE TITLE
Retrieve Log Tag ID from Broadway

### ISSUE THREAD

**Issue by gtoumiek2** [k2view-academy/K2View-Academy#1154]
Hi Product Team, 
Question is, there a way to retrieve the "Log Tag ID" from a Broadway flow ?
customer wants to use it in custom logging

![image](https://github.com/user-attachments/assets/bac5b1df-6fc7-4d03-a548-6737e21e29d1)

![image](https://github.com/user-attachments/assets/3e962595-e919-46b8-84a9-1e6645ac5d3f)

**Comment by mhanna** [comment]
Hi,

You can use the following user function LogIdUtil.getLogId() within the LuFunction actor.

**Comment by gtoumiek2** [comment]
thanks for the response, getting can't find symbol
using Fabric .NET 8.0 

what is the import i should be using ?

**Comment by mhanna** [comment]
com.k2view.fabric.logbinder.LogIdUtil

**Comment by gtoumiek2** [comment]
Thanks it worked,
* import needed log-binder-8.0.0_300.jar to be added to classpath
