### ISSUE TITLE
DbLoad Actor batch size

### ISSUE THREAD

**Issue by gtoumiek2** [k2view-academy/K2View-Academy#1156]
Hi Product Team, 
I was going through [this article](https://support.k2view.com/Academy/articles/19_Broadway/actors/05_db_actors.html)
searching for a way to increase the DbLoad Actor's batch size from the 1K default value

can you suggest if this is possible ?

**Comment by natalylic** [comment]
The batch size is controlled by the hidden parameter IO_JDBC_BATCH_SIZE in the section [io] of the config.ini.
You can override it, if it's required.
