### ISSUE TITLE
SET command

### ISSUE THREAD

**Issue by ShaniRotemIl** [k2view-academy/K2View-Academy#1157]
Hi, when running SET command, i see the below 2 parameters:

EXECUTION_ID                       |2bd13b38-fb4a-44ac-b057-502c8d31d7df                                                                                                                            LOG_ID                                   |2a23000000000012     

Can you please explain what are those parameters?

**Comment by natalylic** [comment]
EXECUTION_ID is an ID of the current execution. Fabric sessions are in a pool. Every time we take a session from the pool, we give it a new EXECUTION_ID. This ID is going all the way with that session, so we can identify the flow, in logs and in audit.
LOG_ID is a unique identifier for a session which we can see in the log.

**Comment by ShaniRotemIl** [comment]
Thank you. 
I cannot find the LOG_ID in the logs

![image](https://github.com/user-attachments/assets/981df25b-f84b-4e1c-ba92-ca4228d9bd72)

Watching the logs of this GET, i don't see it is used:

![image](https://github.com/user-attachments/assets/ccc373a1-d4c1-4dca-8ab1-e5f48438e0ec)

**Comment by mhanna** [comment]
LID is the logid

**Comment by ShaniRotemIl** [comment]
But it's not the same

**Comment by ShaniRotemIl** [comment]
Nataly, i see in the logs other value than i see in the session. Can you please explain?
Thank you
