### ISSUE TITLE
Task status is not changing to the Completed and It has been pending from last 3 hours or so.

### ISSUE THREAD

**Issue by KadirKankroliya** [k2view-academy/K2View-Academy#1158]
I have added extract task and it is not getting completed. Status has been a Pending from a lot of while now. Attaching the Screenshot.
![Uploading Task Is Pending.PNG…]()

**Comment by lionbro1** [comment]
Hi,

It seems the TDM execute job is down, please go to the studio, deploy the TDM LU and try again.

**Comment by KadirKankroliya** [comment]
Just need to click Deploy all Updated logical units under fabric. Right?

**Comment by lionbro1** [comment]
you can do that, but there is no need to deploy all the LUs, just right click on TDM LU and choose deploy.

**Comment by KadirKankroliya** [comment]
Wow. It worked. Thanks a lot.
