### ISSUE TITLE
After Completing Extract task, data is not displayed under Customer table.

### ISSUE THREAD

**Issue by KadirKankroliya** [k2view-academy/K2View-Academy#1159]
After Completing Extract task, data is not displayed under Customer table. Please see attached issue.
![image](https://github.com/user-attachments/assets/89518d81-0616-488d-85a3-6043c9cf3547)

**Comment by lionbro1** [comment]
Hi,

If you are in a middle of training assignment, please raise a question to training team, using training@k2view.com email.

Regards,
Lion

**Comment by KadirKankroliya** [comment]
Sure. Thanks.
