### ISSUE TITLE
LUI version information

### ISSUE THREAD

**Issue by giladsalem** [k2view-academy/K2View-Academy#116]
hi,

how do i retrieve the current version of a certain LU instance ? ( without querying Cassandra ENTITY table )

thanks,
Gilad

**Comment by giladsalem** [comment]
within the GET session, run the following query : 
select version('LU_TYPE');

for example, LU=KIAS.
select version('KIAS');

**Comment by patrickmcgrory** [comment]
Hi

Can you change this to my k2view address? patrick.mcgrory@k2view.com
