### ISSUE TITLE
Globals

### ISSUE THREAD

**Issue by ShaniRotemIl** [k2view-academy/K2View-Academy#1160]
Hi,

1. Can you explain what is saved under each record in the global_settings? what is the difference between "Effective global" and "globals"?
![image](https://github.com/user-attachments/assets/5924801a-6222-4820-8f6b-2e04bcf515d0)

4. Is DEFAULT_GLOBAL_STORAGE_TYPE settings related in any way to Globals? if so, can you please explain what is this settings and how is it used?
Thanks

**Comment by natalylic** [comment]
The **k2system.global_settings** table is an internal Fabric table that saves various settings related to Fabric restart, etc. For example, this table is used to identify the overridden value of Globals or Environments when restarting Fabric.
The **DEFAULT_GLOBAL_STORAGE_TYPE** is not related to Globals. It is a parameter that defines the Fabric storage type where Fabric will save internal blobs. Currently Fabric use it to save LU ZIP, LU JAR and environment XML.

**Comment by ShaniRotemIl** [comment]
Thanks. Can you explain what is the difference between "Effective global" and "globals" records?

**Comment by natalylic** [comment]
This is an internal Fabric table and it is not supposed to be used by the implementation layer.

**Comment by ShaniRotemIl** [comment]
Hi Nataly,

In lower versions we used to check the XML in some cases. In know it is not possible now, but i need this answer for lower versions.
Thanks
