### ISSUE TITLE
What is Sync Mode "New" in Web studio's data viewer?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#1161]
Web studio version: 8.0.0_40
Fabric Version: 8.0.0_322-HF4  

![image](https://github.com/user-attachments/assets/191b0aef-7308-4c99-9869-000da370183f)

**Comment by lionbro1** [comment]
Hi,

In new sync mode, we are first doing "delete instance" and then regular sync (on).

**Comment by smokyMount** [comment]
Thanks, Lion. Is it possible to do this from the server as well?

**Comment by lionbro1** [comment]
No, this is a mode added only to Studio for easier debugging capabilities.

In server side you can run delete instance command and afterwards set sync on mode.
