### ISSUE TITLE
Creation of Postgres database when using Postgres as system db

### ISSUE THREAD

**Issue by debargha95** [k2view-academy/K2View-Academy#1162]
Hi,

I used the following links to configure Postgres as the system database:

[LU Storage Documentation](https://support.k2view.com/Academy/articles/32_LU_storage/04_business_entity_on_pg.html)
[Cassandra Keyspaces for Fabric] https://support.k2view.com/Academy/articles/02_fabric_architecture/06_cassandra_keyspaces_for_fabric.html)

I added the Postgres connection details under [system_db] in the config.ini file and set FABRICDB_ENGINE=postgresql. 
After restarting Fabric, should it automatically create the database specified in the config.ini, or do I need to include the database creation in the deploy.flow for the Logical Unit (LU)?

Thank you.

**Comment by debargha95** [comment]
Update, on the fabric cloud environment it was able to create the database on it's own but on the .net it was not able to.

**Comment by lionbro1** [comment]
Hi,

It is not clear what you are trying to set up, PG as system DB or Business Entity on PG (called internally Fabric DB one)?

As the FABRICDB_ENGINE parameter is under [fabric] section and not [system_db] as mentioned below.

To set up PG as system DB follow this article https://support.k2view.com/Academy/articles/02_fabric_architecture/06_cassandra_keyspaces_for_fabric.html

To set up PG as Fabric DB one to store also the LU data, follow this article
https://support.k2view.com/Academy/articles/32_LU_storage/04_business_entity_on_pg.html
