### ISSUE TITLE
execute session_trace on a TDM task

### ISSUE THREAD

**Issue by AlexMaziya** [k2view-academy/K2View-Academy#1164]
I'd like to troubleshoot TDM task for performance.
How to execute session trace from the terminal? what are all the required globals that need to be set?

example:

trace session_scope test_2 'categories=database,commands,solutions,broadway;level=debug;maxColLen=2048;';
SET TDM_SOURCE_ENVIRONMENT_NAME='SRC';
SET GLOBAL=???
SET GLOBAL=???
SET GLOBAL=???
SET GLOBAL=???
broadway CustomerLU.TDMOrchestrator iid="SRC_123", luName=CustomerLU, syncMode="OFF", reserveInd=true;
trace off;

**Comment by AlexMaziya** [comment]
below setup worked for me. you can also control type of the task (Extract/Load/Reserve etc)

```
set TDM_TASK_EXE_ID=9999;
set TDM_SOURCE_ENVIRONMENT_NAME='SRC';
set TDM_TAR_ENV_NAME='TAR';
set TARGET_ENVIRONMENT_ID=2; --ENV ID AS EXIST IN TDM DB ENVIRONMENTS TABLE
set TDM_INSERT_TO_TARGET = true;
set TDM_DELETE_BEFORE_LOAD='false';
set SCOPE_INITIATED="";
trace session_scope test_1 'categories=database,commands,solutions,broadway;level=debug;maxColLen=2048;';
broadway Customer.TDMOrchestrator iid="SRC_1001", luName="Customer", syncMode="ON", reserveInd=true;

trace off;
```

**Comment by taliei** [comment]
Hi Alex.

I see that you set a specific IID in the session. If you would like to check the performance for particular IIDs, you can open the Highst Execution Time tab in the Batch Monitor window, click the ... on the required entities, and select the Data Explorer:

![image](https://github.com/user-attachments/assets/f58f6ba0-a5f6-43dd-abdd-9292e2251b6e)



The Data Explorer window can show you the statistics on each LU population.

Tali

**Comment by AlexMaziya** [comment]
My bottle neck is the Load to target. The task is just Load (sync off).
My goal is to identify which load flow takes the most as I have 50 tables in my LU.

**Comment by k2viewLTD** [comment]
Can someone answer this please ?




Achi Rotem

President

Mobile: (+972) 50-8478470

[signature_1606061372]<https://www.k2view.com/>

________________________________

**Comment by lionbro1** [comment]
In that case, what you suggested above is the right solution, you need to run the Broadway flows that write the data to target in trace mode. You can read further here https://support.k2view.com/Academy/articles/29_tracing/01_tracing_overview.html
