### ISSUE TITLE
BroadwayJob Actor

### ISSUE THREAD

**Issue by ShaniRotemIl** [k2view-academy/K2View-Academy#1165]
Hi,

When executing a startjob command using dbCommand Actor, the session_scope is passed to the job (as seen in k2_jobs). 
However, when using the BroadwayJob Actor instead of dbCommand, the session_scope is not transferred.

Is there a way to force the BroadwayJob to pass the session_scope to the job?

Thanks

**Comment by natalylic** [comment]
Is there any specific parameter of the session scope that you need to be passed?
Please elaborate on it.

**Comment by ShaniRotemIl** [comment]
Session Globals

**Comment by natalylic** [comment]
Currently, this is not supported by the BroadwayJob Actor. We will fix it in the future release.
For now, please use the DbCommand Actor.

**Comment by ShaniRotemIl** [comment]
Thanks Nataly
