### ISSUE TITLE
Example for do-while loop.

### ISSUE THREAD

**Issue by rohithkollegal** [k2view-academy/K2View-Academy#1167]
Hi,
    I am looking for a example for do while loop actor.   If now need an example in broadway flow to accomplish the do-while loop.
Looking for solution for the below code

do
		{
			$sql="SELECT sequenceName.nextval FROM dual";
			$nextvalue=DBSelectValue('InterfaceName',$sql,$params);
			$sql="SELECT count(*) FROM schema.table where column_name=$column_name";
			$count=DBSelectValue('interfaceName',$sql,$nextvalue);
		}while($count=0);

**Comment by natalylic** [comment]
The **While** actor can be used to create a logical loop.
It returns a virtual array that contains the result of the script as long as the result has a truthy value.

Below are two examples of how you can use the **While** actor:

1. The actor always returns ‘true’ (infinite loop): in this case, you need to make a stop condition inside the loop. 
<img width="635" alt="image" src="https://github.com/user-attachments/assets/e87af9ae-12ac-4198-ac46-7bb3a4098d26">

2. The actor performs a validation and either returns ‘true’ (to continue the loop) or ‘false’ (to finish it).
<img width="628" alt="image" src="https://github.com/user-attachments/assets/64e400e6-ebac-48f5-bbd1-636991aa1643">

**Comment by natalylic** [comment]
Attached are the flows - for your reference. 
[While.zip](https://github.com/user-attachments/files/17377474/While.zip)
