### ISSUE TITLE
Job restart automatically after crash

### ISSUE THREAD

**Issue by gtoumiek2** [k2view-academy/K2View-Academy#1168]
there was a case where a customer has several broadway jobs handling masking tasks
the fabric server crashed due to OOM, it is a single node installation

once the fabric was started again the jobs were picked up by the server, and restarted automatically

is there any way / configuration to prevent this from happening?

**Comment by omernissan** [comment]
No, there is no configuration available to prevent the automatic restart of the jobs once the Fabric server is restarted. The jobs will be automatically picked up and restarted by the server. However, you can stop them manually by issuing a stop command after they have restarted.
