### ISSUE TITLE
[TDM] Execute TDM task for few millions entities

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#1169]
Hello, one of our customer would like to execute TDM task for entire DB population (~4m entities). 

We tried Custom Logic Flow - but it seems to always limit by 100k max irrespectively from requested value (they are using TDM 9.0). 

What is our recommendation for this ? 

_____________
Best regards,
         Andrey

**Comment by taliei** [comment]
Hi.

The default Broadway limitation on the number of processed records is 100K records when moving records into a concrete collection from a virtual iterator. If you need a higher number of records, do the following:

Open the config.ini file and edit the [broadway] section – 
Add the MAX_CONCRETE_ARRAY_SIZE attribute and set its value with a value higher than 100,000; for example:

MAX_CONCRETE_ARRAY_SIZE=50000000

Then restart Fabric.

Please let me know if it helps.

Regards,
Tali

**Comment by avvakandr** [comment]
Hello Tali,
    This didn't help - we have as following:

![image](https://github.com/user-attachments/assets/f0aa3414-1da0-4de3-aad3-8adc29a4d8e4)

and we still limited by 100000 rows in our table level task.

_____________
Best regards,
         Andrey

**Comment by taliei** [comment]
Hi.

Please restart Fabric after editing the config.ini.

Tali

**Comment by taliei** [comment]
For the DbCommand actor, the resultSet is streamed and is not limited to 100K records.  Set the **innerFlowClose** input parameter of the **customLogicDirectFlowUtil** to **false** in order to support the streaming of the resultSet by the inner flow and avoid the Broadway limitation of the maximum number of records (set to 100K by default).
