### ISSUE TITLE
MTable data updated during runtime persists after restart

### ISSUE THREAD

**Issue by gtoumiek2** [k2view-academy/K2View-Academy#1170]
Hi Product Team, 
Working with a customer, we need the MTable to be updated frequently
currently doing so using MTableLoad actor, is there a way to persist these changes across the cluster even after restart? (without the need to redeploy)

**Comment by natalylic** [comment]
MTable is less recommended to be used, when data is updated frequently. 
The suggested approach is to load your data into some DB and create a Common table with a population.

**Comment by gtoumiek2** [comment]
Hi Nataly, Thanks for the response 
MTable is used during the InnerFlowMasking, previously we used cassandra but suffered from poor performance
SQLite/Common suffers the same fate when having 300K dataset used for masking while preserving uniqueness

do we have a memory based solution to keep up with the performance requirements?

**Comment by natalylic** [comment]
Can you please provide more details about your use case, so that we can propose you the best solution.

**Comment by gtoumiek2** [comment]
The MTable is used inside a MaskingInnerFlow's inner flow its used to generate masked Names, Aliases and Email Addresses according to the customer's business rules 

previous attempts were done using an oracle db table and cassandra table, but the performance was poor 
MTable was the fastest
currently the MTable holds a 300K unique names set that is used for the masking
the customer wants to update this MTable without deploying

or in other words wants to keep the performance gain by using the MTable with the ability to update it

**Comment by natalylic** [comment]
MTables are supposed to be used for small static lists of reference data. In your case, there is a very big dataset (300K), it's dynamic and you cannot do the deploy. Thus, MTables are not an appropriate solution for that.
We do recommend to load your data into a SQLite/Common table and improve the performance of this retrieval.
For example:
* If your table has a sequential `ROWID` or a primary key that is numeric and contiguous, you can use it to select a random row.
* Or, consider adding a randomized column to your table and indexing it.
