### ISSUE TITLE
[Catalog] Is there an option to revert to a previous version(s) in Catalog?

### ISSUE THREAD

**Issue by alexmessel** [k2view-academy/K2View-Academy#1171]
Is there an option to revert to a previous version(s) in Catalog?

**Comment by natalylic** [comment]
If you mean - to create a catalog artifact based on a previous version, the answer is yes.
You can select the required version from the Versions drop-down list and run the "Build Artifact".
The created artifact - catalog_field_info.csv file - includes a version number (in the last columns title).
