### ISSUE TITLE
[Catalog] Is it possible NOT to use the latest catalog version to create an artifacts?

### ISSUE THREAD

**Issue by alexmessel** [k2view-academy/K2View-Academy#1172]
Is it possible NOT to use the latest catalog version to create an artifact?

For example, if the latest version is 4, can we generate artifacts from version 2?

**Comment by natalylic** [comment]
Yes, just select the required version and run the build artifact as described [here](https://support.k2view.com/Academy/articles/39_fabric_catalog/09_build_artifacts.html#build-artifacts).
