### ISSUE TITLE
TDM Deployment to a Multi-Node Cluster - Required Components

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#1174]
I always had the assumption that for a multi-node cluster deployment, no matter if on premises, on VMs, on Containers, or recently on K8S Pods, **Kafka** is a required component at least due to the following tasks:

1. **Project/Environment Deployment** - deployment assets are transferred between nodes using dedicated topics.
2. **Reference Table Sync** - transactions applied to common tables are published through dedicated topics for synchronization across the nodes, as common is stored as local SQLite files on each node.
3. **Outbound CDC Sync** - transactions applied to LUIs are published through dedicated topics for the CDC producer and consumers, including the OOB Search consumer that integrates with Elasticsearch/Opensearch.

Consider that task 2 and 3 are not used in a project...

- Would task 1 still require Kafka? Please answer per Fabric version: 6.5, 7, 8.
- Did Project/Environment deployment mechanism changed on version 7 or 8?
- Did the introduction of Postgres and SQLite as possible System Database, removed the need for Kafka?
  - If so, would that also be valid while using Cassandra?
- Does TDM overrides any usual Fabric process that would not require Kafka on multi-node/pod cluster?
- If yes, Kafka is not required anymore for task 1, where are these details described in the Knowledge Base?

Please advise.
Thanks.

**Comment by lionbro1** [comment]
1. TDM solution that doesn't use common tables or Kafka/PUBSUB  interfacei n implementation  doesn't need Kafka component as a part of the solution.
2. No
3. The use of Postgres or Sqlite as system DB removes the mandatory need for Cassandra, the customer can choose what works for him the best.
4. No

**Comment by feamcor** [comment]
@lionbro1 thanks for the reply, but it doesn't address my question.
Although this hypothetical project doesn't have common, and doesn't have outbound CDC, still it is running on a multi-node cluster, so **how** is Fabric performing project deployment if Kafka (the topics created based on each node's node.id) is not available? Please elaborate. Thanks.

**Comment by lionbro1** [comment]
Deployment is using TCP/JDBC layer to distribute the deployment to all the cluster.
