### ISSUE TITLE
In which scenarios will fabric refer to k2_lut_info table to pull code from it?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#1175]
Fabric version - 6.5.9/7.2.2
System DB - Cassandra

We know that the deployment of a Logical Unit, References and Web Services creates new records in the k2_lut_info table and updates/overwrites with latest code and sync_version whenever they are redeployed.

In terms of pulling the code from k2_lut_info, which one of the following is correct _when I restart fabric_?

1. Pulls every time fabric is restarted, regardless of sync_version
2. Pulls only if sync_version in k2_lut_info is greater than the sync_version of the code present on the server (located in $FABRIC_HOME/storage/lu directory)
3. Pulls the code as long as the sync_versions are different, without checking which has the latest timestamp.

**Comment by natalylic** [comment]
After fabric restart or when LU info is needed, fabric selects **the latest** entry from **k2_lut_info** of the relevant LU.

**Comment by smokyMount** [comment]
Thank you, Nataly. What does latest entry mean? Since there is only one record per LUT, does it compare the sync_version to see if the version in k2_lut_info is newer than the one present on the fabric nodes?

**Comment by mironabr** [comment]
Yes
