### ISSUE TITLE
Common table - data restore 

### ISSUE THREAD

**Issue by ShaniRotemIl** [k2view-academy/K2View-Academy#1176]
Hi,

https://support.k2view.com/Academy/articles/22_reference(commonDB)_tables/03_fabric_commonDB_runtime.html

The above article states: " It is also important to note that when setting up the job interval to a very long period, the restore process can take longer to run."

Could you please explain why a longer job interval would increase the time needed to restore the data?

Thanks

**Comment by lionbro1** [comment]
Since the restore process also consumes all the messages (data changes) since the last backup.

**Comment by ShaniRotemIl** [comment]
Understood. Thanks :)
