### ISSUE TITLE
Attach Pre and Post Functions to a Fabric Session

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#1177]
Fabric 7 and 8

Is there, in Java, a way to define a function that would be executed...
  1. After a Fabric Session is instantiated and before it starts performing its tasks?
  2. After a Fabric Session is closed and before it is released?

If so, please elaborate.

Is there, in Java, a way to determine the ID of the Fabric Session in context?

If not in Java, can it be retrieved by querying Fabric?

Please advise.
Thanks.

**Comment by feamcor** [comment]
Similar question as above, but related the LUI Sync (get).

So far, my assumption is that once a Fabric Session is instantiated or taken from the pool, many syncs (gets) could be performed between start and end of the session.

If so, is there a separated context for each LUI Sync? How is it called, and does it have an ID?

Please advise.
Thanks.

**Comment by yuvalp-k2view** [comment]
There are no functions triggered by the creation/destruction of a session.
If you are looking at GET, you can add a first step that checks if this session has been "initiated" with your custom code. This state can be saved by a SET variable. I can't think of an equivalent when a session is closed.

There is an EXECUTION_ID variable that is unique for every session (SET EXECUTION_ID to query).

There are no separate contexts for each sync occurring on the same session, they all run on the same session.
