### ISSUE TITLE
MTable population during runtime

### ISSUE THREAD

**Issue by gtoumiek2** [k2view-academy/K2View-Academy#1178]
1. can an MTable be created during runtime using MTableLoad without a csv existing in the project at all?
2. if yes, will the MTable be replicated across the cluster automatically?

**Comment by natalylic** [comment]
1. Yes, an MTable can be created dynamically using MTableLoad actor, by passing your input values to the `data` input param. The data can come from any source, from the select using a DbCommand actor, or from Graphit, WS, etc.
https://support.k2view.com/Academy/articles/19_Broadway/actors/09_MTable_actors.html
3. When the MTable is created at run-time, it is only available at one node. The `SET CLUSTER_DISTRIBUTE_AFFINITY = ALL` command can be used to distribute the subsequent Fabric command to the specified affinity.
https://support.k2view.com/Academy/articles/09_translations/06_mtables_overview.html
