### ISSUE TITLE
Common table update at specific times

### ISSUE THREAD

**Issue by ghost** [k2view-academy/K2View-Academy#118]
Hello,

I have been looking for a way to have a couple of common tables at a specific time, for example 02AM. Pretty much like the use case described here: [Use Case 3](https://github.com/k2view-academy/K2View-Academy/blob/226ae057cced04ab3203a37fb8be32f1d9736db8/articles/22_reference%28commonDB%29_tables/03_fabric_commonDB_runtime.md#use-cases)

But I haven't found a way for it yet. Is it possible to have some information?

Thank you,

**Comment by lionbro1** [comment]
Hi, to accomplish the use case above, you need to define a reference table with sync mode 'None' and create a user job that will be scheduled to run according to crontab schedule that will run the command ref_sync table='table name' while the table name is the table that you want to sync.

**Comment by ghost** [comment]
Thanks. I got it 👍

**Comment by smokyMount** [comment]
Hi Lion,
Can we update the article to say this can be done using User Jobs?
