### ISSUE TITLE
Querying LU Tables for all IIDs in DbOne

### ISSUE THREAD

**Issue by debargha95** [k2view-academy/K2View-Academy#1181]
Hi,

I am currently using DBONE on the K2view cloud. In the POSTGRES database, I can see the LU-related data in the tables labeled __<LU_NAME>.table_name
![image](https://github.com/user-attachments/assets/6a95b199-6c71-4f90-a296-ae4efc35f4aa)

However, I do not see any data under the views for <LU_NAME>.table_name

![image](https://github.com/user-attachments/assets/3ac0984c-5f76-4465-a56c-e37326fec3b2)

I would like to access all the data for a specific table associated with a particular LU. Is selecting from __<LU_NAME>.table_name the correct approach, or should I expect to find the data under the views for <LU_NAME>.table_name?

**Comment by lionbro1** [comment]
Hi,

As mentioned in the following article https://support.k2view.com/Academy/articles/32_LU_storage/04_business_entity_on_pg.html that's correct, __<LU_NAME> is the schema you should look for when reading the data. The <LU_NAME> is created only for Fabric internal use.
