### ISSUE TITLE
Java Dependencies

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#1182]
Fabric >=7.2.2

1. With `java-dependencies.xml`, can I add any dependency available on Maven within Fabric?
2. After `dependency` elements are provided, will Fabric run Maven to retrieve/download the dependencies?
3. If so, *how* and/or *when* will Fabric run Maven, or should it be run manually?
5. Where will the dependencies be downloaded into?
6. Do the changes described in [Dependencies Best Practices](https://support.k2view.com/Academy/articles/COE/Fabric_Implementation_Best_Practices/best_practice_dependencies.html) have to be performed for that work?
7. If so, what are the necessary changes to accomodate the Maven dependencies?
8. Will the Maven dependencies be loaded in way to not conflict with Fabric dependencies (like what was described in the "Dependencies Best Practices" above)? 

Please elaborate in detail as I could not find any documentation for this file.
Thanks.

**Comment by yuvalp-k2view** [comment]
You have to run the java-dependencies.xml file by right clicking it on the file tree and selecting "Download Java Dependencies".
The libraries are downloaded into "lib" and have to be committed to git.
This is still not a change in the fabric build process but a utility to bring the jars and continue with the exiting procedure.

There is no changes that need to happen in config or other. Starting in version 8, the default is an isolated and dynamic class loader for the project code. Libraries from lib are automatically packaged during the build process and shipped to the server during deploy.
