### ISSUE TITLE
Fabric and Project Dependencies

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#1183]
Related to [Dependencies Best Practices](https://support.k2view.com/Academy/articles/COE/Fabric_Implementation_Best_Practices/best_practice_dependencies.html)...

_"As each project has its **class dependencies**, we need to make sure that Fabric doesn’t use those dependencies."_

  1. What are the class dependencies mentioned in this paragraph?
  2. Are they related to the JARs generated by a project build?
  3. Or are they related to 3rd-party classes/libraries that are required as part of project's custom code?

_"Note that once `PACKAGE_NAMES_CLASS_LOADING_FILTER` is uncommented, the **project's JARs** must be placed to the `ExternalJars` folder."_

  4. What are the project's JARs mentioned in this paragraph?
  5. Are they related to the JARs generated by a project build?
  6. Or are they related to 3rd-party classes/libraries that are required as part of project's custom code?

Please advise.
Thanks.

**Comment by lionbro1** [comment]
the answer for both is 3rd party classes/libraries that are required as a part of project's custom code
