### ISSUE TITLE
k2studio web - Restart Fabric

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#1186]
How does the `Restart Fabric...` option (see screenshot below) work?

1. Does it work without stopping and starting the pod?
2. Does it trigger some of the Fabric scripts? If so, which one?
3. Does it work **only** within a k2cloud/k2agent installation?
4. From UX/DX, what to expect from it? I tried in a Space and it provided no visual feedback.

Please advise.
Thanks.

![image](https://github.com/user-attachments/assets/1430ecbf-0d26-4cb7-80ef-82f96e9fe69b)

**Comment by lionbro1** [comment]
Hi,

This option executes the following command:

nohup k2fabric restart >> /proc/1/fd/1 &

It just restart Fabric not the POD, using the existing Fabric restart script.
