### ISSUE TITLE
How to disable the masking by the catalog or masking actors?

### ISSUE THREAD

**Issue by taliei** [k2view-academy/K2View-Academy#1193]
Hi.

How can I disable the masking of PII data without changing the catalog configuration? 

Thanks.

**Comment by taliei** [comment]
Hi.

The masking actors, including the catalog masking actors, have an input parameter named category. The default category value is enable_masking. The masking is applied whether the enable_masking key is set to true or null.

If you need to _**disable the masking on a given process, you must set the enable_masking key to false**_ on the session.

For more information about the masking actors, see https://support.k2view.com/Academy/articles/19_Broadway/actors/07_masking_and_sequence_actors.html

**Comment by avvakandr** [comment]
Hi Tali - a follow-up question... how can we disable cache for masking, but keep catalog masking enabled?

____________
Best regards,
      Andrey

**Comment by taliei** [comment]
Hi.

The caching is done if you mark the PII classification as consistent and/or unique in the catalog.  If you want to avoid caching for a given flow, you can set the catalog masking actor's interface input parameter to NONE.
