### ISSUE TITLE
How to i override a value of a global on the session level

### ISSUE THREAD

**Issue by einavvelan** [k2view-academy/K2View-Academy#12]
How can I override the value of a global parameter on a session level?

**Comment by lionbro1** [comment]
You can use the SET command to override the global on the session level.
Usage: SET KEY=VALUE; or SET KEY VALUE;
In Java code it can be used as  fabric().execute("set KEY="+ i_value);

For more details please refer to : https://github.com/k2view-academy/K2View-Academy/blob/master/articles/08_globals/03_set_globals.md
