### ISSUE TITLE
Collect traces from fabric using OpenTelemetry agent

### ISSUE THREAD

**Issue by ignacio-butler-42** [k2view-academy/K2View-Academy#1200]
Hello,

We're trying to configure the Open Telemetry agent to capture traces events from Fabric so that they can be exported to external dashboards.

The agent we're using is https://opentelemetry.io/docs/zero-code/java/agent/ which will take care of capturing any required event and push it to our preferred location.

We've successfully configured it and the questions next come from the fact the agent is working for various jdbc libraries (including Cassandra) so we get traces for those; but no traces are being published for API calls/web services which is the primary objective of this exercise:

- Which library is fabric using to expose APIs and WS calls to the client? Supported libraries are: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/supported-libraries.md
- If "disabled" by any reason, which would be the configurations to allow such agent to monitor events in the fabric server?
- Would it be possible to get traces from https://support.k2view.com/Academy_6.5/articles/29_tracing/01_tracing_overview.html to be also exposed to opentelemetry? Which is the library this uses?

Thank you in advance,

**Comment by lionbro1** [comment]
Hi,

You should use our JMX capabilities to capture this info.

You can refer to https://support.k2view.com/Academy/articles/34_JMX_statistics/01_JMX_overview.html for more details.

**Comment by ignacio-butler-42** [comment]
Hello,

In the JMX interface there are only metrics exposed; this scenario is different as we want to export **traces** which is different scenario from metrics collection.

Exporting traces to a common place allows operators to track various calls not only to WS but the JDBC calls they make.

Thus the questions above remain open. The open telemetry agent can inject calls to the most common Java frameworks (javax.http servlets, spring-web, etc over most application servers) and there seem to be preventing this from happening in the default configuration.

**Comment by lionbro1** [comment]
in that case consider to use auditing capabilities, you can expose the auditing results to any platform, you can read more here https://support.k2view.com/Academy/articles/27_auditing/01_auditing_overview.html

**Comment by ignacio-butler-42** [comment]
Hi @lionbro1, I guess the correct link is the last one I pasted in my original comment. Auditing is to track users' activities from my understanding; traces are to track system activities.

The problem with that one is that it is not practical to have fabric traces only available at fabric because traces are cross system entries (traces are since the client across all intermediary servers).

What I need to learn is whether fabric might be blocking in any way otel agent to run or else, which configuration would be missing to support it.

Thank you in advance,
