### ISSUE TITLE
Delete Specific Catalog Version

### ISSUE THREAD

**Issue by gtoumiek2** [k2view-academy/K2View-Academy#1201]
Hi Product Team, 
i wanted to ask if there is a way to remove a catalog version, for example
i'm at version 4, i want to go back to version 3 and remove version 4

i'm aware that i can go back to version 3 and "build artifacts" based on it,
the question is that if there is a way to remove version 4 entirely?

**Comment by natalylic** [comment]
There is no option to remove a version. You can delete the whole Catalog and then start it again from scratch:
![image](https://github.com/user-attachments/assets/a18b6b1e-4072-4d3f-a966-71689c9ff432)
