### ISSUE TITLE
subscribe from beginning using bw subscribe actors

### ISSUE THREAD

**Issue by tarikh03** [k2view-academy/K2View-Academy#1202]
Is there anyway I can control the offset I want to start consuming messages from?

 either from beginning, or from specific offset.

Also there is an option in kafka, when opening a consumer, to set group id as empty string, by this no group id is getting
created when consuming and offset won't be tracked.
in bw Subscriber actors, if I sent empty string to group_id as input, in code it will remote it from properties and thus it will 
set the default group_id set in interface, also this option I believe should be available in bw, consuming messages without committing.

**Comment by VikiWeizmann** [comment]
Hi Tarik,
Please find bellow the answers:
 
1. Controlling  the offset:
In our current design, you cannot directly control the offset to start consuming. The offset will either be the last committed offset or determined by the auto.offset.reset configuration (earliest or latest).

2. Empty group ID:
No, empty group IDs are not allowed in our implementation. All consumers must have a valid group ID.

3. Consume messages without committing offsets:
Broadway does not support consuming messages without committing.

**Comment by tarikh03** [comment]
Hi Viki,

Are any of these might be part of future releases?

it is very essential for debug and exploring cases.

**Comment by natalylic** [comment]
Currently this is not planned. Please open a CR ticket on product and we will check when we can deliver this change.
In your ticket, please explain your use case and who is the potential customer which needs this feature.
