### ISSUE TITLE
Object Storage PARTITIONS_COUNT

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#1205]
On versions 7 and 8 of Fabric...
- Is `PARTITIONS_COUNT` still a hidden parameter for S3 on `config.ini`?
- If so, is `PARTITIONS_COUNT` also available as a hidden parameter for ABS?

For S3, `PARTITIONS_COUNT` had a default value of 5.

Checking on a project that is using ABS, I see one container per LU, but no other level of partitioning within the container, with all MDBs being stored at the root level of the container. ABS has no paths/directories, but when object names include a path, it helps ABS to scale, kind of introducing additional partitioning.

How can such optimization be performed in Fabric?

Please advise.
Thanks.

**Comment by natalylic** [comment]
PARTITIONS_COUNT is not hidden in Fabric 7/8. Currently it is not part of the config template, and it is being added to the `config.ini` automatically after the first blob (LUI) is saved. This param can't be changed after first blob (LUI) was saved.
Is it required for you to have this param in the config template?
As far as we know, ABS partitioning is working differently and does not use path/directories structure for scale. It has it own partitioning mechanism based on the blob name.

**Comment by feamcor** [comment]
About `PARTITIONS_COUNT`... the fact that it is not part of the template, makes it hidden. As such, when not aware of such configuration, it ends up being ignored, and the default 5 is not optimal for a serious production workload.

About ABS blob name... yes, I'm aware that there is no such path/directory structure, and that scaling is based on the blob name, but the information I got is that the blob name should follow a path structure. I mean, instead of `<IID>` it should be `/<path>/<to>/<IID>` where the initial part will be used for scaling. Examples mention that, for instance, workloads based on date, that are not the case on Fabric but just to illustrate the rationale, should not name blobs like `/<path>/<YYYY-MM-DD>/<blob>` but something like `/<path>/<partition>/<YYYY-MM-DD>/<blob>`.

I'm no expert on ABS, but want to be sure that the current flat naming convention adopted by Fabric is actually not leveraging the best scaling behavior from ABS.

Please advise.
Thanks.

**Comment by natalylic** [comment]
- The reason for hiding the `PARTITIONS_COUNT `parameter is due to the fact that it is a critical Fabric parameter. Incorrect configuration can cause the Fabric data corruption. What do you suggest to be a default value? Based on which research or AWS article?

- Regarding the ABS blob name, based on our research: it is not needed to use a date as a prefix for partition purpose. The R&D dev continues investigating this issue to get the best scaling results.
