### ISSUE TITLE
Is there a way to shuffle result set from DB query actor?

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#1206]
Hello, one of our TDM customer is looking to shuffle the result from their DB query in Custom Logic Flow before passing it to Filter / limit actor that actually generate the list for TDM task... in default variation, when they limit it by 1 - it always gives them the same entity and they want this to be a little 'randomized' within the result set that DbCommand  actor (select query) returns...

Is there a simplified / user friendly actor or flow that they can use to achieve this? Or they need to build this shuffling logic themselves using our standard actors ? I understand this may not be a complex task for someone who knows BW, but for TDM person it can be a little challenging... 

______________
Best regards,
         Andrey

**Comment by avvakandr** [comment]
we probably can use something like ORDER BY DBMS_RANDOM.RANDOM in case of Oracle...

**Comment by natalylic** [comment]
Getting "randomized" results from the DbCommand actor is the function of the query implementation (and not an actor feature). 
To write a SQL `SELECT` statement that returns one random row each time it is executed, you can make use of the `ORDER BY` clause in combination with a random function, and limit the result to one row. 
The exact syntax can vary slightly depending on the database system you're using. Here are examples for several popular databases:
1. **MySQL:**
   ```sql
   SELECT * FROM your_table
   ORDER BY RAND()
   LIMIT 1;
   ```
   In MySQL, the `RAND()` function is used to generate a random order of the rows.

2. **PostgreSQL:**
   ```sql
   SELECT * FROM your_table
   ORDER BY RANDOM()
   LIMIT 1;
   ```
   PostgreSQL uses the `RANDOM()` function to achieve the same effect as MySQL's `RAND()`.

3. **SQLite:**
   ```sql
   SELECT * FROM your_table
   ORDER BY RANDOM()
   LIMIT 1;
   ```
   In SQLite, `RANDOM()` is also used for random ordering of rows.

4. **SQL Server:**
   ```sql
   SELECT TOP 1 * FROM your_table
   ORDER BY NEWID();
   ```
   SQL Server uses `NEWID()` to generate a unique identifier for each row, effectively randomizing the order.

5. **Oracle:**
   ```sql
   SELECT * FROM (
     SELECT * FROM your_table
     ORDER BY DBMS_RANDOM.VALUE
   )
   WHERE ROWNUM = 1;
   ```
   In Oracle, you use `DBMS_RANDOM.VALUE` to order rows randomly and `ROWNUM` to limit the results.
