### ISSUE TITLE
ADI: What is the process for recycling failed entities in the same execution plan

### ISSUE THREAD

**Issue by AlexMaziya** [k2view-academy/K2View-Academy#121]
In case we had an error for several entities what are the steps to re-execute them during same execution?

**Comment by lionbro1** [comment]
Hi, 

First, If the trigger to your question is the fact we were missing re-try option when connecting to DB (like : Cassandra) it was resolved on the original ticket - a private php was provided and it will be part of ADI 2.13 release. So actually using this feature is a good solution to avoid recycling

Secondly, If re-cycling is still a must, better to have another execution that will take the failed entities from previous run on entity inclusion PG table.

 Third, during the execution you can identify the failed entities and write them in to the entity inclusion PG table again, in this case statistics can be damaged as it will show more entities were process than the one originally planned.
