### ISSUE TITLE
GIT  configuration in Web Studio

### ISSUE THREAD

**Issue by Evaitops** [k2view-academy/K2View-Academy#1210]
I tried to find detail information about configuring connection to git server in WebStudio but I can find it.

How do you configure this integration?

**Comment by eyalk2** [comment]
The configuration is set at Cloud Platform Orchestrator, at the Projects page.
When creating spaces via docker compose and not via Cloud Orchestrator, this is available at the env file.

**Comment by Evaitops** [comment]
Thanks.. and is it possible configure git with ssh instead of https??

**Comment by eyalk2** [comment]
No. Our code expect to have it as URL (as usually used  for pointing to a central GIT source)
