### ISSUE TITLE
Permissions in fabric CLI 

### ISSUE THREAD

**Issue by gtoumiek2** [k2view-academy/K2View-Academy#1212]
Hi Product, 
in fabric permissions, is there a way to grant a permission to a role enabling viewing jobs (aka, `jobstatus;`) ?

P.S. current state we have to grant the `ALL` permission which also enables the user to stop the job 
![image](https://github.com/user-attachments/assets/317c3dc3-b7f4-4789-90fd-64890dda1994)

**Comment by natalylic** [comment]
Currently there are no existing permissions that control job commands. You can open a CR for that.
However, a viable solution for your need is to create a Web Service that will perform the required command (e.g. `jobstatus`) and grant a permission to your role to this Web Service. 
Note that you need to set **Elevated Permission** to **true** in this Web Service.

**Comment by gtoumiek2** [comment]
They use the admin panel to view the jobs and batches
and the admin panel's job windows triggers `jobstatus`
![image](https://github.com/user-attachments/assets/7433206f-2487-431a-95e6-43d7a09df009)

1. is there a way to modify the call in the admin panel to call a custom webservice to implement your suggestion?
2. There is a READ permission which why it doesn't support `jobstatus` as this is a read command?

**Comment by natalylic** [comment]
The READ permission controls the ability to read (or write) data from the Fabric instances. It doesn't control the Fabric commands.

Regarding K2Admin - you can't override or customize it. Instead, you can create your own Web app - as explained in the K2Documentation > Web Framework API Documentation. So if you only need to display the jobs status, create an HTML page with a table invoking your custom Web Service.
