### ISSUE TITLE
Custom Web Service Endpoint

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#1214]
Fabric >=v7

In `config.ini` there is the configuration below:
```ini
...
[fabric]
...
## Setup Servlet Filters
## [{"class":"com.custom.MyFilter","patterns":["/ws","/api/*"],"params":{"p1":"v1","p2":"v2"}}, {"class":"com.custom.AnotherFilter"}}]
## Patterns is optional and will default to the app web services. Params is optional.
## Product filters:
## [{"class":"com.k2view.cdbms.ws.ProxyAPI","params":{"fabric_redirect":"SERVER","fabric_retry":"1","fabric_tokens":"token1,token2","fabric_affinity":"","read_timeout_sec":"60","connect_timeout_sec":"60"}}]
## [{"class":"com.k2view.cdbms.ws.ResultCacheFilter","patterns":["/ws","/api/*"],"params":{"cacheMaxRequests":"10000","cacheDuration":"10000"}}]
## [{"class":"com.k2view.cdbms.ws.ProxyForward","patterns":["/anyurl"],"params":{"target":"http://..."}}] (requires restart)
#WEBSERVER_FILTERS=
...
```
- What is the purpose of `com.k2view.cdbms.ws.ProxyAPI`?
  - On which situation would it require changes in the `config.ini`?
- What is the purpose of `com.k2view.cdbms.ws.ResultCacheFilter`?
  - On which situation would it require changes in the `config.ini`?
- What is the purpose of `com.k2view.cdbms.ws.ProxyForward`?
  - On which situation would it require changes in the `config.ini`?
  - Different from the entries of the other two product filters, this one looks an example.
 
I would like to create a web service endpoint separated from the product one.

- Is implementing a custom filter the way to go?
  - If so, is there any code example available?

- How would the `WEBSERVER_FILTERS` parameter look like? Would it be like the example below?

```ini
WEBSERVER_FILTERS=[{"com.custom.MyFilter","patterns":["/newapi/*"],"params":{"p1":"v1",...}}]
```

- If a custom filter is added, would I be required to repeat the product filters entries, like in the example below?

```ini
WEBSERVER_FILTERS=[{"class":"com.k2view.cdbms.ws.ProxyAPI","params":{"fabric_redirect":"SERVER","fabric_retry":"1","fabric_tokens":"token1,token2","fabric_affinity":"","read_timeout_sec":"60","connect_timeout_sec":"60"}},{"class":"com.k2view.cdbms.ws.ResultCacheFilter","patterns":["/ws","/api/*"],"params":{"cacheMaxRequests":"10000","cacheDuration":"10000"}},{"class":"com.k2view.cdbms.ws.ProxyForward","patterns":["/anyurl"],"params":{"target":"http://..."}},{"com.custom.MyFilter","patterns":["/newapi/*"],"params":{"p1":"v1",...}}]
```

Please advise.
Thanks.

**Comment by eyalk2** [comment]
- This refers to Tomcat filters that you can apply. 
- You can implement your custom filter. Please refer to Tomcat documentation and examples. In general such class shall implements Filter and at least have the doFilter method
- in config you put what you need to add. what are product filters you refer to? These are examples.
