### ISSUE TITLE
HTTP Actor/interface -configure proxy script settings

### ISSUE THREAD

**Issue by AlexMaziya** [k2view-academy/K2View-Academy#1215]
I'm trying to run POST API call using HTTP actor in my BW flow.
I'm not able to resolve the address and getting:
`java.nio.channels.UnresolvedAddressException`

![image](https://github.com/user-attachments/assets/fd31d220-f858-4115-bacc-930182bf24e5)

*postman call connects successfully.

There is a setup proxy script configured on the network:
<img width="626" alt="image" src="https://github.com/user-attachments/assets/6c4d0492-2061-4bb2-b1c3-07452c09bb75">

How can I configure proxy settings (script) in Fabric configuration (.Net and web-studio) or perhaps on the HTTP actor/interface?

**Comment by eyalk2** [comment]
If this is a network proxy, where each request from machine shall go out via such proxy, then you shall set the environment variables http_proxy, https_proxy.


* If I understand your Fabric is located at the machine where Fabric is installed, where Postman is done from you laptop.

**Comment by AlexMaziya** [comment]
Adding to configuration in fabric-server-start.bat resolved the issue:
SET JVM_OPTIONS_DEBUG=-Dhttps.proxyHost="MY_PROXY_HOST" -Dhttps.proxyPort="PROXY_PORT"
where MY_PROXY_HOST:PROXY_PORT is the value returned from the proxy setup script.
