### ISSUE TITLE
[TDM] Is there a simple / configuration way to exclude some columns from TableLevel load task?

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#1217]
Hello, one of our customer using TDM table level task to load tables from prod to lower environment (MySQL and SqlServer) and some tables have auto-generated columns that should be excluded from our load / insert query.

Is there a way to configure these columns or we have to build custom load flow for that?

_____________
Best regards,
         Andrey

**Comment by taliei** [comment]
Hi.

You can define a custom load flow for each table to avoid inserting some fields. For more details see _TableLevelDefinitions MTable - Customized Logic for Tables_ section of https://support.k2view.com/Academy/articles/TDM/tdm_implementation/09_tdm_reference_implementation.html

Regards,
Tali
