### ISSUE TITLE
How to copy files from Fabric server to S3?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#1219]
Hi,

Is there a way to copy or move a file created on fabric to S3?
When trying to create file directly on S3, the append functionality is not working and is getting overwritten every time.

**Comment by natalylic** [comment]
The way to do it is to use a **FileRead** actor to read it from fabric and then **FileWrite** actor to write it to S3:
<img width="241" alt="image" src="https://github.com/user-attachments/assets/4655a684-c2a6-4658-b01e-e04da67a4b9c">

**Comment by feamcor** [comment]
Hi @smokyMount, usually, object storage services like S3, ABS, and GCS, don't allow append operations.

[AWS recently introduced appending](https://aws.amazon.com/about-aws/whats-new/2024/11/amazon-s3-express-one-zone-append-data-object/) only on the S3 Express One tier (which is also a new tier, mostly for AI/ML workloads).

Object storage is not like a file system or block storage (like EBS) that are modified in place.

AWS provides an additional service to mount a S3 bucket like a file system, which would provide a protocol layer for handling objects as files through standard POSIX interface. Of course, there is a cost for that.

If that service would be in place, then Fabric would use it as regular file (I mean no need for using S3-ready actors).
