### ISSUE TITLE
[Catalog] Is there a way to filter-out permanently particular field from being masked?

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#1220]
Hello, we are facing a conflict for Email field in clients' data source. We have it exactly like that appearing in multiple tables in the same DB schema ('Email') and in most cases it is defined as a String and should be treated as PII (and we should mask it). 

So we have Catalog config that classifies such field as EMAIL and as PII.

Issue comes up with one table that has the same field name 'Email' defined as int. After discovery this Email field is classified as EMAIL and falling into the same PII category EMAIL as other fields. Once we pass it through catalog masking we get string e-mail address and we are trying to insert it into 'int' field.

We can manually update catalog_field_info for this table/column to make it not a PII - but next time they re-build artifacts it will be created as PII again.

We can add this entire table in exlude_list of plugins.discovery - but this will exclude all other columns of this table from profiling, plus with TDM Table Level it throws exception when we try to execute task for this table:

`Exception in fnGetTablesOrder(): com.k2view.discovery.crawl.ObjectNotExistsGraphException: Cant build schema model from empty response, id: 'dataPlatform:TRGDatabaseBackend.schema:dbo.dataset:TrackerHFCNOCAttendance.class:TrackerHFCNOCAttendance' class com.k2view.discovery.crawl.ObjectNotExistsGraphException Cause: Cant build schema model from empty response, id: 'dataPlatform:TRGDatabaseBackend.schema:dbo.dataset:TrackerHFCNOCAttendance.class:TrackerHFCNOCAttendance'`

Is there a way to exclude one column only so it will stay exclude from one execution to another w/o a need to update something manually every time we want to run discovery / build artifacts?

____________
Best regards,
         Andrey

**Comment by natalylic** [comment]
Yes, there is a way to override the Catalog masking mechanism. It can be done by adding the `masking `property to this field using the manual Catalog Edit option and setting its value to `OFF`, as shown below.
The property will remain on this field even if you run discovery on the same interface again.
The `masking` property's valid values are explained [here](https://support.k2view.com/Academy/articles/39_fabric_catalog/11_catalog_masking.html#the-masking-property).

https://github.com/user-attachments/assets/12316a17-f313-4f42-bb37-000a6947f3aa

**Comment by natalylic** [comment]
Alternative way to achieve your request is to remove the field's classification, edit it to another value or remove the PII property.
In any case, this is not recommended to modify the `catalog_field_info.csv` file as this is an artifact which represents the Catalog.

**Comment by avvakandr** [comment]
Hello Nataly,
       If I change this Catalog Masking parameter to OFF in my space - how can we propagate this to all other spaces/developers (or to my new space that I will create in a week )? Is it part of some MTable file?... or this change is not persisted anywhere except for Neo4j DB and everyone has to do the same change in their space ?

**Comment by avvakandr** [comment]
To add to the previous comment - I meant in case we need to execute Discovery on a new space and not just re-use catalog_field_info we generated earlier from different space where this parameter was added...

**Comment by natalylic** [comment]
The addition of the **masking** parameter with value **OFF** is performed on the Catalog tree. This change is the Catalog override which creates a new Catalog version. This is not a reference data change.
As such, it cannot be propagated to other spaces as the Catalog itself cannot be propagated to other spaces. Once you perform Build Artifact, this property will be part of the **catalog_field_info** MTable file. 
So in case you need to executed discovery on a new space you should either do this manual override again, or modify the classification regex rules that will not mark this field as "EMAIL".

**Comment by avvakandr** [comment]
Can we somehow use table name in classification rules? our challenge is that they have same EMAIL field name in many other tables where it must be a PII... 

is there an option to enhance our classification rules by adding an optional parameter for table (or 'dataset') - as a regex condition as well? By default for backward compatibility we can keep it empty or * (to cover all tables), but if it is provided - then field-rule classification will be applied only to those tables that match the dataset condition.

**Comment by natalylic** [comment]
The classification rules are just the regular expressions which don't have any conditions. But you can "play" with the classification's score. Currently there are two rules for identifying an EMAIL:
<img width="536" alt="image" src="https://github.com/user-attachments/assets/78336539-e69f-426f-85ac-1d433200e0c9" />
The first one is applied on the **field value**, the second - on the **field name**. Both have a score = 1.
If your "problematic" field includes an integer, it means that it is identified as EMAIL by the second rule (based on its name). It doesn't pass the first rule. You can delete the second rules or reduce its score to be below the threshold (less than 0.4). 
It this way, this field will not be marked as EMAIL. At the same time, all other fields that actually hold emails will be marked as EMAIL by using the same rule.
