### ISSUE TITLE
[TDM] TablLevel task - vaule drop-down for rows filtering

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#1224]
Hello, is there an option to bring drop-down values for table-level task (similar to LU Params subsetting)? 

![image](https://github.com/user-attachments/assets/fbeb697d-2b4e-428f-8dca-508613c19ee4)

______________
Best regards,
         Andrey

**Comment by taliei** [comment]
Hi.

Currently it is not supported. The text box for each parameter contains free text and it is up to the user to set the correct value.
We plan to improve the table's filtering parameters and display valid values in our roadmap for 2025.

Thanks,
Tali
