### ISSUE TITLE
Job Status Column named "Ownership Candidates Num"

### ISSUE THREAD

**Issue by FlorinelTudor** [k2view-academy/K2View-Academy#1225]
Hello K2View,
When I was checking a job status I noticed there is a column named "Ownership Candidates Num" (screenshot below) which I'm unsure of what it displays, since we have 9 fabric nodes in our test environment and I couldn't any description in the K2view Knowledge Base.
![image](https://github.com/user-attachments/assets/20533c5f-c8b0-48f7-9d5e-ec3710efeafa)

**Comment by natalylic** [comment]
`Ownership candidates num` means the number of nodes that can run the job (affinity). 
When a job runs with a specific affinity, `Ownership candidates num` will be equal to 1.

**Comment by FlorinelTudor** [comment]
Hi, I have a follow-up. question, looking at the screenshot below:
<img width="1087" alt="Screenshot 2024-12-18 at 09 09 31" src="https://github.com/user-attachments/assets/6b86f4b0-2bd4-4753-93d1-61a6dcd6114e" />

Why do User jobs have 18 and broadway ones 23?

**Comment by natalylic** [comment]
Per the Dev team investigation, it seems to be a "bug". Please open a freshdesk ticket for it and it will be checked and fixed.

**Comment by Zeherros** [comment]
<img width="604" alt="Screenshot 2024-12-18 at 17 50 08" src="https://github.com/user-attachments/assets/a77e70b5-8b21-4627-be9d-3f01209ada53" />
I can't log in
