### ISSUE TITLE
Credentials in Custom Connection Strings 

### ISSUE THREAD

**Issue by gtoumiek2** [k2view-academy/K2View-Academy#1226]
Hi Product Team, 
When creating a fabric interface and specifying Custom Connection String 

according to documentation, credentials can be passed inline within the connection string
![image](https://github.com/user-attachments/assets/849456ce-2671-43f8-9647-21d9394e11be)

during testing fabric ignores the inline username and password and takes into consideration only the ones that appear in the dedicated "User" and "Password" field.

![image](https://github.com/user-attachments/assets/9b523dd1-dc20-48b2-86fd-40c59d75b3ee)

is this a bug or by design?

**Comment by gtoumiek2** [comment]
just to clarify, if the K2VIEW_USR that appears in the connection string is defined in the "User" field the connection will work
but according to Oracle thin driver docs passing the credentials inline is supported

**Comment by mironabr** [comment]
Currently it does not supported in Fabric. It is less secured and does not recommended

**Comment by gtoumiek2** [comment]
Understood, thanks a lot
