### ISSUE TITLE
[Broadway] Is there a way to filter-out elements in array using filter actor?

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#1228]
Hello, we have a case in our BW flow when we have two arrays - one has all table fields and another one has the field names that we do not want to use for insert. Is there a simple & user-friendly way to do such filtering / diff with Filter actor (or some other actor)? I know we can filter-out one particular value with Filter, but was looking to extend that for multiple values - can not find any example or guidance on that in our KB...

Thank you!

______________
Best regards,
        Andrey

**Comment by natalylic** [comment]
Please see below the example flow that receives a full and exclude list and uses the **Filter** actor to created the new filtered list:
<img width="416" alt="image" src="https://github.com/user-attachments/assets/41ce101b-3bbf-4afd-b8d8-81dcf6c0c884" />
The implementation of the Inner Flow is below:
![image](https://github.com/user-attachments/assets/38116b0b-e87d-4cc9-80fb-1d0b886d8c6f)
Note that the external name of the input and output of the Inner Flow should be **value**.
The example flows are attached.
[Example.zip](https://github.com/user-attachments/files/18238706/Example.zip)
