### ISSUE TITLE
SQLite JSON1 Extension

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#124]
1. Is SQLite JSON1 extension enabled in Fabric?
1. If not, does it require product to enable it, or can it be enabled directly by the project?
1. Is there any experience and/or recommendations about using it?
 
Thanks.

**Comment by lionbro1** [comment]
Hi,

It is enabled.

For Example:

fabric>select json_valid('{"x":35}');
|json_valid('{"x":35}')|
+----------------------+
|1                     |

(1 rows)
