### ISSUE TITLE
External JARs

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#125]
When an external dependency is introduced to the project (e.g. some library jar) is there any way to have it deployed automatically to the server nodes' ExternalJars folder during the deployAndBuild script execution, or has it to be handled manually?

**Comment by lionbro1** [comment]
Hi,

It should be copied manually. the deploy process is not taking care of it.

**Comment by lionbro1** [comment]
Since Fabric 8, it is possible to include the external jars on the deployment process by locating the jars under the project/lib, you can read further here https://support.k2view.com/Academy/articles/COE/Fabric_Implementation_Best_Practices/best_practice_dependencies.html
