### ISSUE TITLE
WS calls using Graphit

### ISSUE THREAD

**Issue by neenjapt** [k2view-academy/K2View-Academy#126]
Hi,

Whenever I call a Graphit object from my WS Java code, I seem to be unable to manipulate the WS output regardless of what is being done or the WS configurations.

The WS has "Is Raw" enabled and I've made some tests returning empty strings and null objects but it is all ignored if a Graphit call is made from the WS code.

My goal is to handle the Graphit output for doing some changes prior to returning the WS output.
For this particular case, I'm trying to convert empty strings into null objects and this conversion is working properly as I can confirm from the logging produced but the WS always returns the raw Graphit response.

I'm no sure if it is related but I've also tried defining the HTTP status after the Graphit call with **_response().setStatus(200)_** but it is also ignored unless I set it before the Graphit call.

Thanks,
Bruno

**Comment by lionbro1** [comment]
Hi,

You can't enhanced on the WS the data retrieved from the graphit, you need to change graphit logic so it will fit to your needs.
