### ISSUE TITLE
Store User and Password for external API Calls

### ISSUE THREAD

**Issue by barakgk2view** [k2view-academy/K2View-Academy#127]
As part of the DPM we are accessing the Vendor websites (SF/SAP/BAMBOO ....) by API and the first part is to get the Token by using a user and password. Is there a secured way to store n the k2view the user and password, and later retrieve them ?

**Comment by lionbro1** [comment]
Hi,

You can use either HTTP or Custom interface to store the password as encrypted.

In order to get the original value, you should use getCustomProperties user code API.
