### ISSUE TITLE
shared function changes are not taken into consideration on Web Services

### ISSUE THREAD

**Issue by einavvelan** [k2view-academy/K2View-Academy#13]
I've edited a shared function, used by the web services. However- when invoking the web services- the old version of the function is executed. How can I get the fixed version of the function by the web service?

**Comment by lionbro1** [comment]
When you edit a shared object (for example- function) you must re-deploy all the objects (web service, LU, etc..) that use this shared object to load the changes in the shared function.

**Comment by lionbro1** [comment]
@lionbro1 check this one

**Comment by lionbro1** [comment]
@lionbro1 take 3

**Comment by lionbro1** [comment]
@lionbro1 take 4
