### ISSUE TITLE
Using in WS the function getCustomProperties

### ISSUE THREAD

**Issue by barakgk2view** [k2view-academy/K2View-Academy#135]
In one of my WS I am using the function of getCustomProperties with an interface to get the information, but it does not recognize the interface details and returning nulls.
When using the  dame function in the context of a LU it returns the information.
1) Is there anything special I need to do ?
2) Is the function only available to run in the context of the LU?

**Comment by natalylic** [comment]
The function getCustomProperties() is available in the context of the LU and of the WSs. 
The call is exactly the same. You can see the code example in the [Custom Interface KB article](https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.2/articles/24_non_DB_interfaces/07_custom_interface.md).
Note that the function must receive an interface name, for example when calling:
~~~ 
Map<String, String> props = getCustomProperties("MyCustom");
~~~
make sure you have defined a Custom interface type named **MyCustom**.
