### ISSUE TITLE
Cassandra crashed with core dump during startup in 3rd party library sigar.dll

### ISSUE THREAD

**Issue by sathishpuram** [k2view-academy/K2View-Academy#145]
Cassandra fails to startup and crashes with core dump while loading sigar.dll 3rd party library. 

Error Message:
-------------
A fatal error has been detected by the Java Runtime Environment:
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000010014ed4, pid=39744, tid=0x0000000000009794

JRE version: Java(TM) SE Runtime Environment (8.0_261-b12) (build 1.8.0_261-b12)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.261-b12 mixed mode windows-amd64 compressed oops)
Problematic frame:
C [sigar-amd64-winnt.dll+0x14ed4]

Reported Issue: Oracle JDK bug on JDK 8u261 or higher release. Cassandra crashes with core dump. [https://issues.apache.org/jira/browse/CASSANDRA-15950]

Solution: Use JDK 8u251.  Known JDK issue. [https://www.oracle.com/java/technologies/javase/javase8u211-later-archive-downloads.html]

**Comment by sathishpuram** [comment]
Reported Issue: Oracle JDK bug on JDK 8u261 or higher release. Cassandra crashes with core dump. [https://issues.apache.org/jira/browse/CASSANDRA-15950]

Solution: Use JDK 8u251.  Known JDK issue. [https://www.oracle.com/java/technologies/javase/javase8u211-later-archive-downloads.html]

**Comment by mpp4manu** [comment]
You can also comment out the following line in the cassandra.env.ps1 file:

$env:JVM_OPTS = "$env:JVM_OPTS -Djava.library.path=""$env:CASSANDRA_HOME\lib\sigar-bin"""

I did this based upon posts related to Cassandra and Windows 10.  It worked for me.
