### ISSUE TITLE
Ability to add new a new Environment without using Fabric Studio.

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#146]
Hi,

Is there a way to create a new Environment and add Production interface details to it directly on the server w/o using Fabric Studio? The people who have access to studio do not have the production credentials. So, they can't add it to the Environments. 

I did refer to [this ](https://github.com/k2view-academy/K2View-Academy/blob/caff264b8ccb3e752fba2cd6d4ce989d227bb7aa/articles/25_environments/04_offline_deployment.md)link where it shows how to deploy environments from a file. Would it work if I did the following:
1. Added a new environment to existing set of environments with server, username, password (_not encrypted_), etc
2. Deployed using `Deploy environments from file ‘{filename}’ ` command.
3. Set the environment using `SET_GLOBAL ENVIRONMENT='<environment name>'` command

Thank you,
Hardik

**Comment by natalylic** [comment]
The above steps are correct. The **Environments.k2fabEnv.XML** file can be prepared / edited manually. It is not a must to use Fabric Studio for this purpose. I've updated the article to indicate this point.
