### ISSUE TITLE
Monitor JMX events for queries to Oracle source interface

### ISSUE THREAD

**Issue by JohnH-K2View** [k2view-academy/K2View-Academy#150]
New Relic monitoring is detecting queries against Cassandra and fabric "get" commands, but does not see the transactions executed within LU population DBQueries or db("%").fetch(...) commands executed in population functions against an Oracle source.  Is it possible to have these queries to source also show in monitoring?

**Comment by lionbro1** [comment]
Hi,

JMX shows statistics, if you want to drill down into queries level on source you need to use trace mechanism

https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.2/articles/29_tracing/01_tracing_overview.md
