### ISSUE TITLE
Information request on fabric config.ini parameters

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#153]
Hello,

I wish to get information on 2 fabric parameters of config.ini file.
JOB_SERVERS_WORKERS_COUNT
MAX_WORKERS_PER_NODE 

In previous version the parameter JOB_SERVERS_WORKERS_COUNT was controlling the concurrent number of entities that could be extracted during migrate.  In fabric 6, I see no effect of JOB_SERVERS_WORKERS_COUNT on migration speed, the parameter MAX_WORKERS_PER_NODE when increased, the migration speed is increased and verified by seeing more entities in migrate_in_process command. 

Please let us know the usage of above parameters.

Regards,
Prathamesh

**Comment by lionbro1** [comment]
Hi,

JOB_SERVERS_WORKERS_COUNT parameter was replaced by MAX_WORKERS_PER_NODE on release 6.0 and on.
We don't use JOB_SERVERS_WORKERS_COUNT anymore, it was stayed their by mistake, on latest 6.x release we removed it to avoid confusions.

MAX_WORKERS_PER_NODE parameter sets the maximum number of threads that are used in all batch (and migrate) process units (executions) together on this node.     
Support setting MAX_WORKERS_PER_NODE=0 per node to avoid running a batch process on a specific node.
