### ISSUE TITLE
Supporting Apache Pulsar

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#157]
Hi,

Does Fabric support Apache Pulsar streaming platform? Are there any examples to show connectivity with Puslar?

Thanks,
Hardik

**Comment by lionbro1** [comment]
Hi,

Fabric doesn't support Pulsar as a direct connector, but you can explore the option of Pulsar adopters to Kafka or if there are Pulsar bridging solutions to JMS, as Fabric knows how to connect to any JMS queue.

**Comment by lionbro1** [comment]
link to Purlsar bridging solution to Kafka

http://pulsar.apache.org/docs/en/adaptors-kafka/

**Comment by smokyMount** [comment]
Thanks, Lion. I will take a look into it.
