### ISSUE TITLE
Information on migrate_summary

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#161]
Hello,

There are 2 fields within migrate_summary command where if possible can you provide more details?
Ent./sec (pace)
Ent./sec (avg.)

Runtime guide only mentions the following, 
Ent./sec (pace)- latest execution of entities per second
Ent./sec (avg.)- average number of executed entities per sec

I think Ent./sec (avg.) works same as previous versions.  What is Ent./sec (pace) and why is it it now included in migrate_summary? 
Thanks

**Comment by lionbro1** [comment]
Hi,

The pace is exactly the same as the regular avg, it just count the avg on the last 100 seconds of the batch process, so users can know if there is a slow down happening currently compare to the overall batch process avg run time.
