### ISSUE TITLE
Max Connection Number

### ISSUE THREAD

**Issue by giorashi-zz** [k2view-academy/K2View-Academy#167]
What is the relation between the Max Connection Number parameter in the Studio interface definition to the parameter MAX_CONNECTIONS_TO_SOURCE in the config.ini

**Comment by natalylic** [comment]
MAX_CONNECTIONS_TO_SOURCE in the config.ini defines the default. Thus if no value is defined in the Studio, the config.ini value will be used. Otherwise, the value is taken from the Studio. Note that this definition is per node.
