### ISSUE TITLE
Iidfinder ignore messages

### ISSUE THREAD

**Issue by tarikh03** [k2view-academy/K2View-Academy#172]
Is there an option to make iidfinder ignore messages for instances that are not in fabric?

For example:

1. Get CUSTOMER.1234 (Cache tables will be filled)
2. Delete CUSTOMER.1234 (data in cache for this instance still there)
3. iidfinder gets message for this instance, which is not in fabric.

Current: delta message will be inserted into delta table.

required: delta to be ignored.

I know there is a black list, where we can change cause of the instance, then deltas will be ignored, but this will also block future gets.

**Comment by Krutyolkin** [comment]
Hi Tarik,
  You can add the instance to the 'blacklist' after (2) above. It will make the iidFinder skip all the messages for the Delta and thus more sync will be running for this instance.
  The exact procedure of adding to the blacklist depends on the version (6.3 and above it's iid_info table). 
  I'd suggest consulting Rivi/Nir on this item as well.

Best regards,
Sergey.

**Comment by tarikh03** [comment]
Thanks for the response,

I mentioned though in the initial issue that adding instance to the black list and changing the cause will block the sync if I try to sync the instance again.

once I delete instance, it will get inserted into black list with deleted as a cause, in that case it will still get detlas.
now if I change the cause to something else that "deleted", iidfinder will stop assigning deltas to this instance, but I will not be able to perform sync because the instance is in the black list with status different than "deleted".

this adding instance to black list and changing cause will not help me.
also Delete instance command does not allow me to sit specific cause for the deletion which will be reflected in the black list.
I will have to limit deletion in WS or special get handling.

so my concern is that if a customer doesn't want to get deltas inserted for instances that are not in fabric, is there in fabric a way to do so?

**Comment by Krutyolkin** [comment]
Hi,

  No, there are only mentioned options.

Lion,
Please consider a feature request.

Best regards,
Sergey.

________________________________
