### ISSUE TITLE
Table not found issue 

### ISSUE THREAD

**Issue by miriabi18** [k2view-academy/K2View-Academy#175]
When i am calling webservice in server mode  ,it is failing due to the below error 

  "error": "Fabric Synchronization - com.k2view.cdbms.exceptions.SyncException: Exception in FEB_ALERTS(): com.k2view.graphIt.tree.GraphitException: CASE1: [SQLITE_ERROR] SQL error or missing database (no such table: CUST_PNDG_ITEMS_CNT)",

When i check in fabric studio the table existing and my graphit is running fine in local mode . Could someone help out here

**Comment by alexmessel** [comment]
Is CUST_PNDG_ITEMS_CITY an LU table? If yes, did you execute get on any of the LU instances before you execute graphit?

**Comment by lionbro1** [comment]
Hi @miriabi18,

The right platform to track such issues is freshdesk.

This platform is meant to serve any generic question you have on how our product works.

Closing the ticket.

Thanks,
Lion
