### ISSUE TITLE
can we control the number of resend in a job if it fail ?

### ISSUE THREAD

**Issue by tamarzohar** [k2view-academy/K2View-Academy#178]
can we control the number of resend in a job if it fail ?
Thanks
Tamar

**Comment by greg-k2view** [comment]
The management of job failures behaviour can be controlled programmatically in your implementation. Fabric's Java API contains the following methods:  
failJobAlwaysRetry(): will always attempt to re-run a failed job
failJobNoRetry(): will not attempt to re-run the job.
retryUntilMax(): - default - will retry to run the job - up to 10 times retrial (max retrials is set to 10)

These methods can be invoked in a try...catch statement in case your Java code has thrown an exception when calling the job

try {
//your code here
} catch(Exception e) {
failJobAlwaysRetry(e);
}
