### ISSUE TITLE
Web Service Query Parameter Includes Dots

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#179]
TMF OpenAPI REST guideline dictates the use of query parameters with full JSON-path, that is, web service input parameters include dots (e.g. customer.contact.phonenumber). Fabric Studio, as expected (not a valid Java variable name), doesn't allow parameters using such naming convention. Is there a routing layer before reaching the web service method, that would allow such transformations? Please advise. Thanks.

**Comment by lionbro1** [comment]
Hi Fabio,

Are you looking for parameter name or value including dots?


As in Fabric you can define parameter called input1 and set it as required, when you will call the Web-Service you can fill input1 with any required value, like:

http://localhost:3213/api/{input1 value can include dots}?token=ABC

Does it answer your question?

**Comment by feamcor** [comment]
I'm asking about the query parameters.
For example:
`http://{host}:{port}/path/to/resource/{resource_id}?parameter1.with.dots={value1}&parameter2.with.dots={value2}`
I need a way to translate `parameter1.with.dots` to an input parameter (e.g. `parameter1`) of the web service.
Thanks.

**Comment by lionbro1** [comment]
Did you consider URL redirect functionality?

https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.4/articles/15_web_services_and_graphit/16_rest_api_additions.md

**Comment by feamcor** [comment]
Thanks, I will read the suggested documentation and do a trial on it.
I see that `rewrite.config` would have to be deployed manually, to all Fabric nodes.
I mean, it would not be part of automated deployment (via Studio) or `buildAndDeployArtifacts.sh` script.
Is that correct?

**Comment by lionbro1** [comment]
you will have to create it on the required folder on all nodes, it is not part of automatic deployment.

**Comment by lionbro1** [comment]
closing ticket

**Comment by lionbro1** [comment]
better solution (from intelliJ - not studio)

@webService(path = "", verb = {MethodType.GET}, version = "1", isRaw = false, isCustomPayload = false, produce = {Produce.XML, Produce.JSON})
public static void newWs(@param(name = "in.to.it", description = "LU name", required = true) String in) throws Exception {
