### ISSUE TITLE
Not clear enough what replaces each deprecated method & not clear that with the new functions there is no resultSetWraaper object

### ISSUE THREAD

**Issue by DavisDaniella** [k2view-academy/K2View-Academy#180]
https://github.com/k2view-academy/K2View-Academy/blob/4b2749ed4704765ead7b0bce3d167d9c074d39e1/articles/05_DB_interfaces/09_fabric_API_for_DB_interfaces.md

Please provide examples on each deprecated method how it was camper to how it should be
There is nothing about  resultSetWraaper object not supported in new functions

**Comment by lionbro1** [comment]
In order to know what replaces each deprecated method you need to use Fabric Java API DOC, knowledge base is not covering it.

http://localhost:3213/app/doc/user-api/index.html

It is it missing for a given method you can open a ticket as needed.
