### ISSUE TITLE
Hadoop Hive Interface authentication with Kerberos

### ISSUE THREAD

**Issue by ghost** [k2view-academy/K2View-Academy#181]
Is it possible to have a Hadoop Hive interface to use Kerberos authentication instead of the default user/password?

Can you you provide information on how to configure it? Thank you.

**Comment by greg-k2view** [comment]
Absolutely, Kerberos authentication is fully supported - please execute the following steps:

**Prerequisites**
Download the following jar files from the internet - hive-jdbc-3.1.0.3.1.0.0-78-standalone.jar

You will also need the jdbc wrapper jar for Kerberos - attached to this answer.
[jdbc-wrapper-1.0-SNAPSHOT.jar.zip](https://github.com/k2view-academy/K2View-Academy/files/6023840/jdbc-wrapper-1.0-SNAPSHOT.jar.zip)

Create a directory on Windows (example -C:/K2View/kerberos_config/) and Linux (example -$K2_HOME/kerberos_config/) to store keytab and certificate files. 
These files will be used by the interface while opening up a connection to Hive every time.


**A: Steps to create a new Database Type in studio:**

1. Right click on Database Types under Shared Objects in the project tree

2. Select ‘New Database Type From Template’>’Hadoop Hive’

3. Update the Class Name field with ‘com.k2view.cdbms.WrapperDriver’

4. Update URL Template (This will be used as the connection string template in the Interface) with below value: jdbc:hive2://[HOST]:[PORT]/[DATABASE];principal=hive/[HIVE_PRINCIPAL]

5. Update the default port (if not 10000)

6. In the right pane of new database type, add following JDBC connection properties:
a. kerbUser-username for which the keytab is to be used
b. keytabPath_win – location(Windowspath) of keytab file for above user to be used by Fabric Studio
c. keytabPath_linux –location(Linuxpath) of keytab file for above user to be used by Fabric server 
d. isSSL -set it to true is SSL is enabled else, set it to false.
e. certPath_win -location(Windowspath) of SSLcertificate file to be used by Fabric Studio. Not required if SSL is not enabled.
f. certPath_linux -location(Linuxpath) of SSL certificate  file  to  be  used  by  Fabric server. Not required if SSL is not enabled.
g. certPwd -password for SSL certificate. Not required if SSL is not enabled.

7. Save the Database Type. Upon saving, a new folder (folder name will be the name that is given to Database Type while saving) will be created under your project’s lib directory on your windows machine.

8. Copy the 2 jar files (from the link provided in section 1.1) to this new folder.


**B: Create Hadoop_Hive Interface**
**Steps to create a new Kerberized Hive interface:**

1. Right click on Interfaces under Shared Objects in the project tree.
2. Select the newly created Database Type from the dropdown list.
3. Click on ‘Convert to Generic DB Interface’ link (highlighted in blue)
4. In the Connection Details section, fill up the Server, Database, User and Password field
5. Set ‘Custom Connection String’ to True
6. Update the connection String by replacing the [HIVE_PRINCIPAL] placeholder with the Kerberos principal.
7. Under the Connection Properties section, update the relevant fields.
8. Test Connection String.
9. Save the interface.

**C: FABRIC SERVER SIDE SETUP**
1. As mentioned in the prerequisites, make sure that the keytab file and SSL certificate are copied to each fabric server in the cluster.
2. Copy the jar files mentioned in the prerequisites to External Jars directory under Fabric’s Home ($K2_HOME) directory in each fabric server in the cluster.
