### ISSUE TITLE
Broadway - Call stored procedure that returns output parameters

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#182]
Hi,

I am trying to call a PL/SQL Stored Procedure using a DbCommand Actor in Broadway. I am able to successfully call them by passing the required inputs to it. However, in certain cases, I need to get the outcome of that Stored Procedure and use it further but I am unable to capture that output from the DbCommand Actor. 
Is there any actor in Broadway that can be used to call PL/SQL stored procedure that returns output?

Thanks,
Hardik

**Comment by natalylic** [comment]
You need to use LuFunction Actor for this purpose.

**Comment by feamcor** [comment]
Fabric 7.0

Please provide an example in Java to call stored procedures where output parameters are provided as input parameters.

Should `db("INTERFACE").execute("...");` be used?

Example
```sql
call procedure1(in1, in2, out1, out2, out3);
```

Please advise.
Thanks.

**Comment by dotants** [comment]
Using Fabric 7.2, calling stored-procedure from DbCommand works, but you need to "hide" the stored-procedure inside a "select" statement. The statement cannot be a prepared statement, so you cannot use ${paramName}, only ${@paramName}

Oracle stored procedure DBCommand example - Db Command can be called directly using ${@paramName}:
    select siebel.profcrm.contact_best_f('${@billingid}') from dual

Informix stored procedure DbComman example - Db Command cannot have any parameters, so switch parameter values and create SQL statement in a "StringFormat" actor, and link the statement with parameter values already replaced to the SQL parameter of the DbCommand:
Sting format:    Select unnamed_col_1 error_code, unnamed_col_2 message From TABLE(sp_agi_elegibility_cartao(${numbase}))

![image](https://github.com/k2view-academy/K2View-Academy/assets/74860302/92e92ef0-fbe7-489a-9192-1cddb8cac672)
