### ISSUE TITLE
Broadway - Create fixed length files

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#184]
Hi,

We are trying to create a flow in Broadway to write to a fixed length file that has a constant length for each field and record. I see a FixedColumnParser actor but my understanding is that it used to parse an "incoming" records and not for generating a fixed length record. Is there an actor in Broadway (We are using Fabric v6.3) that can be used for this? 

Thanks,
Hardik

**Comment by natalylic** [comment]
You can use the FixedColumnParser Actor to define for each input column where it starts (the position) and which length should be considered. Then connect its output with the FileWrite Actor's input.

**Comment by smokyMount** [comment]
Hi Team,

The FixedColumnParser actor does not seem to work with FileWrite actor for generating fixed width output files. 

The requirement is to create fixed-width files. where data is contained in columns that are of a fixed width (meaning that each column contains a certain number of character positions). Data that does not fill the width of the column is padded with filler characters, which are usually spaces or zeroes. No delimiters are used to separate the fields in the file. Each column can have a different width defined, for ex: col1 can be 10 characters long, col2 20, col3 15, etc.

**Comment by natalylic** [comment]
The purpose of a **FixedColumnParser** actor is to read the file with fixed columns. If you're looking to do the opposite - to create a fixed-width file, you should pad each column to the required width, create a line and then write this line into a file.
Use the below sample flow as an example:
![image](https://user-images.githubusercontent.com/62207927/153822960-43a78bfe-7b4d-49d7-bf47-3bbb9099d97a.png)
This is how the output file looks like:
![image](https://user-images.githubusercontent.com/62207927/153823865-e206a280-76f7-44b1-8f4b-2b498fae7050.png)
