### ISSUE TITLE
API Authentication passed to Kerberized Interface

### ISSUE THREAD

**Issue by ghost** [k2view-academy/K2View-Academy#185]
Hello,

Following issue #181 I would like to understand if Fabric supports the ability to have an Active Directory user credentials being used in a webservice request, that then are fowarded to a Db Interface(Hadoop Hive in this case) that is kerberized so that the conection with the source is made using the original user that made the request.

As an example, lets assume **userA** and **wsTestAccess**.

1. **UserA** accesses a web page that sends Active Directory information in the API Request to **wsTestAccess**
2.  Fabric authorizes **userA** and makes the db request using the configured interface but using **userA**  as user for the conection to the source system.

Mainly the goal here is that the conection between fabric and the source system are always made by a nominal user(that requester of the API call) and not by a fabric specific/dedicated user.

Thank you,

**Comment by greg-k2view** [comment]
Hi,

Please refer to this [link](https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.4/articles/24_non_DB_interfaces/07_custom_interface.md) to see how to create a new custom interface.

The user and password fields can be left empty and the jdbc URL string can be customized with the user credentials as received from the A/D
