### ISSUE TITLE
UserCode.serializeLU() function meaning behind "element in the hierarchy" in javadocs

### ISSUE THREAD

**Issue by wesfloyd** [k2view-academy/K2View-Academy#186]
The input parameter explanation for the serializeLU() function states: "startingLudbObjectName - The element in the hierarchy where the serialization should start"

Could you please help explain:

1. What is meant by Hierarchy? Does this refer to the LU table schema?
2. Does "startingLudbObjectName" refer to the name of the table where the serialization should begin?

Thank you

**Comment by eyalk2** [comment]
1. yes it is.
2. true.

For example - in the demo project, the hierarchy within the Customer LU is 
Customer --> contract --> subscriber, where subscriber is refers to 3 sub tables - balance, invoice and offer. Invoice by itself has a connected table named payment.

When you use the following: serializeLU("SUBSCRIBER");
you will get a JSON which contain list of subscribers of that customer, where each of them contains 3 lists - balance, invoice and offer and each invoice contain by itself list of payment elements.

Attached is an example - the result of the serialize
 function for customer's LUI = 1

[customerLUI1_serilaize_resullt_example.txt](https://github.com/k2view-academy/K2View-Academy/files/6055654/customerLUI1_serilaize_resullt_example.txt)
