### ISSUE TITLE
Page not found on K2View-Academy // SonarQube 

### ISSUE THREAD

**Issue by lagnelli** [k2view-academy/K2View-Academy#187]
Page not found trying to download/see SonarQube 04_K2View_Customized_Rules
@ https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.4/articles/COE/SonarQube/04_K2View_Customized_Rules/01_Customized_Rules.md

**Comment by lionbro1** [comment]
the following link should be used to download the package:

https://github.com/k2view-academy/K2View-Academy/tree/Academy_6.4/articles/COE/SonarQube/02_Installation
