### ISSUE TITLE
Fabric and LUI encryption

### ISSUE THREAD

**Issue by JohnH-K2View** [k2view-academy/K2View-Academy#189]
As it states for MicroDBs (LUI) Encryption that Fabric encrypts each LUI using the AES-256 encryption. Question on this encryption process that if this is FIPS 140 validated? If so then does K2View have a certificate for their product using this?

**Comment by lionbro1** [comment]
We use AES-256 which is a worldwide encryption standard method and is used by many organizations. 
K2View has never validated and registered the encryption process with FIPS 140 since we are non U.S. federal government department or agency.
