### ISSUE TITLE
Broadway error - padStart is not a function

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#190]
Hi,

We are getting 'padStart is not a function' when trying to use it in the JavaScript actor. padStart() is a JavaScript function used for padding one string with another string as referred in the link below:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart

Is there a way to import it and other similar functions (like padEnd(), etc) to Fabric so we can use in the Broadway flows?

Here is how the 'script' input for my JavaScript actor looks like:
![image](https://user-images.githubusercontent.com/66338066/109864294-4601ef00-7c28-11eb-9641-f9fe1c8176ea.png)

Thank you,
Hardik

**Comment by lionbro1** [comment]
Hi,

As mentioned on the JavaScript actor, we support ES5 (ECMA). The methods you mentioned was introduced on ES6.

So you have 2 options:

1. Find the proper functions on ES5 that can do the job.
2. Use LuFunction Actor instead and develop the logic in Java.

Regards,
Lion
