### ISSUE TITLE
How to execute commands on a remote server from a Broadway Flow

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#191]
Hi,

Is there an actor to execute system commands on remote servers using Broadway? I tried using the Exec actor but it does not have an input to specify an SFTP interface.

Thanks,
Hardik

**Comment by natalylic** [comment]
**Exec** actor supports the execution of system processes on local fabric. Execution of system processes on a remote server is not supported.
The files handling actors such as **cp**, **ls**, **md**, **mv** and **rm** - receive an interface in their input.

Please note rexec is not a secured approach for remote access, you need to use ssh, etc...

**Comment by lionbro1** [comment]
please be notified that ssh Actor was added on fabric 6.4.2 for that purpose
