### ISSUE TITLE
What does this error mean "error in opening zip file" when starting Fabric

### ISSUE THREAD

**Issue by wesfloyd** [k2view-academy/K2View-Academy#192]
I was attempting to build a custom Event that sends the serialized LU to S3. Despite manually copying the required JAR libraries to "C:\k2view\k2projects\fabric\<project_name>\lib" I received errors when trying to deploy my LU that the JAR files were not being picked up properly. Then I restarted Fabric, hoping the JAR files would be recognized. Unfortunately, the local Fabric debug server will not start and I receive the attached errors:

INFO  2021-03-09 23:45:53,191 [LIDf804000000000001] [main] c.k.c.l.CDBMSLUTypeFactoryWorker - start create LUTYPE Customer from ZIPERROR 2021-03-09 23:45:53,356 [LIDf804000000000001] [main] c.k.f.b.Boot - com.k2view.cdbms.exceptions.CdbmsException: Error loading LU type 'Customer': java.lang.RuntimeException: java.util.zip.ZipException: error in opening zip file
[Error Starting Fabric.txt](https://github.com/k2view-academy/K2View-Academy/files/6112121/Error.Starting.Fabric.txt)

Can you share any context on what this zip file error might mean?

**Comment by wesfloyd** [comment]
[Error Starting Fabric.txt](https://github.com/k2view-academy/K2View-Academy/files/6112138/Error.Starting.Fabric.txt)

**Comment by greg-k2view** [comment]
Wes, - are you sure cassandra was running ? or restarted ?

**Comment by wesfloyd** [comment]
It appears Cassandra is running normally (per the attached screenshot).

I tried exporting my project to a .k2proj file, then re-importing into a clean/new project, and it works .. so I have a workaround for now. Perhaps this is an unusual error?
<img width="1534" alt="Screen Shot 2021-03-10 at 9 53 10 AM" src="https://user-images.githubusercontent.com/260568/110648423-b4920000-8186-11eb-973f-486bcd560c80.png">

**Comment by greg-k2view** [comment]
Looks like a twitch that might have happened for a number of reasons - including maybe windows related issues. Please next time, if it happens, let's try to debug this live.

**Comment by smokyMount** [comment]
This happened to me when I opened a project from one fabric version on another. It was resolved by creating a new project on the new fabric studio and using the export and import features instead of opening a project.
