### ISSUE TITLE
Enabling Maven Artifacts in Fabric for Dependencies

### ISSUE THREAD

**Issue by wesfloyd** [k2view-academy/K2View-Academy#193]
Is there any way to reference Maven artifacts for java dependencies when writing custom Java classes? Or is the preferred approach to manually copy libraries to <project_dir>/lib/ directory?

**Comment by greg-k2view** [comment]
Wes,

 the way to add external jars is described in this article:
https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.4/articles/31_external_resources/01_external_jars.md

For example https://github.com/google/libphonenumber libraries can be copied to the project libs folder.
