### ISSUE TITLE
Compatible with ipv6

### ISSUE THREAD

**Issue by JohnH-K2View** [k2view-academy/K2View-Academy#194]
Is fabric capable of configuring exclusively with ipv6 addresses instead of ipv4? Any considerations or alternate setup required if so?

**Comment by lionbro1** [comment]
Hi,

All the components used by Fabric such as Cassandra, Kafka, Datastax driver 3.8 are ipv6 compliant, we don't see a reason Fabric will not be compliant as well, however it was never tested officially.

We will include these tests on our next GA release (6.5)
