### ISSUE TITLE
Use of JWT

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#195]
Please improve this documentation: [Fabric Web Services Security - JWT Generation](https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.4/articles/26_fabric_security/05_fabric_webservices_security.md#jwt-tokens-generation).

As far as I understood, API consumer should call `authenticate` API providing JSON object with `username` and `password` attributes. Example:
```bash
curl --request POST \
  --url http://localhost:3213/api/authenticate \
  --header 'Content-Type: application/json' \
  --data '{
	"username":"admin",
	"password":"admin"
}'
```
By being valid, Fabric returns JWT as a cookie on the response.
```
Allow: POST
Set-Cookie: jwt=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0b2tlbiIsImlzcyI6ImZiciIsImlhdCI6MTYxNTU1NDAyMSwiZXhwIjoxNjE1NTU0OTIxLCJ1bm0iOiJhZG1pbiJ9.MIYZTjqTdP5zvy0HQdQZfy63gyVMHRzNlpTQQazAlrA; Max-Age=900; Expires=Fri, 12-Mar-2021 13:15:21 GMT; Path=/; HttpOnly
vary: accept-encoding
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Fri, 12 Mar 2021 13:00:21 GMT
```

Then what comes next?

If I try to call another API, for instance, `status`, how should the JWT be provided?

1. As a bearer token header attribute? Example:
```bash
curl --request GET \
  --url 'http://localhost:3222/api/status?statusFormat=STRING' \
  --header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0b2tlbiIsImlzcyI6ImZiciIsImlhdCI6MTYxNTU1MTc5MywiZXhwIjoxNjE1NTUyNjkzLCJ1bm0iOiJhZG1pbiJ9.gGWoPuUHC1plbCadvcAPYcc_JadIlLS2segBo78hh24'
```
2. As a cookie? Example:
```bash
curl --request GET \
  --url 'http://localhost:3222/api/status?statusFormat=STRING' \
  --cookie jwt=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0b2tlbiIsImlzcyI6ImZiciIsImlhdCI6MTYxNTU1Mjc4NSwiZXhwIjoxNjE1NTUzNjg1LCJ1bm0iOiJhZG1pbiJ9.maGNbaJICdKSj6RjjfIPkzyXukjU0J3UQRTHC94Pb6k
```

I tried both but it didn't work.
1. For the bearer token the response looks like:
```
"Failed to authenticate 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0b2tlbiIsImlzcyI6ImZiciIsImlhdCI6MTYxNTU1MzI3NiwiZXhwIjoxNjE1NTU0MTc2LCJ1bm0iOiJhZG1pbiJ9.LbDClNifI8Um2NgpjjK61JSPG7ZrMMpvFbvPxEuvHEI': Apikey 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0b2tlbiIsImlzcyI6ImZiciIsImlhdCI6MTYxNTU1MzI3NiwiZXhwIjoxNjE1NTU0MTc2LCJ1bm0iOiJhZG1pbiJ9.LbDClNifI8Um2NgpjjK61JSPG7ZrMMpvFbvPxEuvHEI' does not exist."
```
2. For the cookie the response looks like:
```
"Failed to authenticate '': jwt 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0b2tlbiIsImlzcyI6ImZiciIsImlhdCI6MTYxNTU1MzUyMiwiZXhwIjoxNjE1NTU0NDIyLCJ1bm0iOiJhZG1pbiJ9.5IJuU9vjj2M3X2s4AfoYSnBUipqFpGs9qnYwEUkq3I0' validation failed"
```

Also, if I open Fabric Swagger, `authenticate` example/schema lists two other attributes apart from `username` and `password`:
- apikey
- logout

How is their usage?

I look forward to your reply.
Thanks.

**Comment by greg-k2view** [comment]
Hi Fabio,

see the link attached: 
I modified the description to reflect: 
1. how to use postman to generate a JWT token for a non-secured key
2. how to use jwt.io to see the JWT key with the secured token/secret API key (than can be generated in the admin panel)
3. how to return to postman and replace the JWT token in the cookie with the new JWT token value constructed from the secured token
4. swagger can NOT be used for that process (its scope is internal and part of fabric)

 https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.4/articles/26_fabric_security/05_fabric_webservices_security.md#tokens-and-the-admin-panel

let me know if something is not clear.
