### ISSUE TITLE
Is it possible to set the Sync Method to "Time Interval" for a specific Field in an LU Table?

### ISSUE THREAD

**Issue by wesfloyd** [k2view-academy/K2View-Academy#198]
Is it possible to set "[Time Interval](https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.4/articles/14_sync_LU_instance/04_sync_methods.md#time-interval)" sync for a specific field (column) within an LU Table, rather than for the entire table?

If not, could this be achieved in any other creative way .. perhaps using a decision function (plus some other functionality) to only sync for a specific column?

Thank you!

**Comment by lionbro1** [comment]
Hi,

Sync mode can be set on LU schema, Table or population level.

If you wish to sync only one field according to a defined time interval, you can set a separate population that will deal only with the relevant field and set the sync method as time interval on the new population accordingly.
