### ISSUE TITLE
How to get Web-Service timing on Fabric 5.5 and on?

### ISSUE THREAD

**Issue by lionbro1** [k2view-academy/K2View-Academy#20]
The Swagger of Fabric 5.5 onward does not display the execution timing of WS. To view the execution timing of a WS you can do either:

1.	Run the WS as a URL in the Chrome , right click and select inspect to view the execution timing.  Please note that you need to add the token and format to the URL.
2.     Call the WS using tools like postman.
3.	Add @legacy annotation to the category file of the WS and view the old style of output of the WS including the execution timing (not the recommended option).

**Comment by lionbro1** [comment]
lion.brotzky@gmail.com please be notified

**Comment by lionbro1** [comment]
@lionbro1  please be notified

**Comment by lionbro1** [comment]
@lionbro1 please check now

**Comment by lionbro1** [comment]
@lionbro1 test3

**Comment by lionbro1** [comment]
jhjgh

**Comment by Sereenm** [comment]
hi Lion,

@Legacy annotation doesn't work on V6.4.1 is there another way to support the old output style ?
