### ISSUE TITLE
Safe fork/split of a stream

### ISSUE THREAD

**Issue by IvanKostyuk** [k2view-academy/K2View-Academy#201]
Is there any implementation of safe fork/split of a stream for Broadway flow?

I have an actor which produces a stream, I want to use its result in two other actors (parallel or sequential). e.g. I want to save results into an LUI and send by email. If the output is connected to two inputs, then results of both will/could be corrupted.

Any thought?

**Comment by lionbro1** [comment]
Hi,

stream can be connected only to one input.

If you want to connect it to two inputs, first load it to memory (for example use BytesToStings actor).
