### ISSUE TITLE
Clarifying Data Catalog username/password for OrientDB Initial Setup

### ISSUE THREAD

**Issue by wfk2view** [k2view-academy/K2View-Academy#202]
Can you please clarify the specific database name, username and password we should use when setting up the Data Catalog Initially? I'm following [these instructions](https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.4/articles/33_data_catalog/02a_data_catalog_interface.md) for a vanilla setup, but running into this error in Fabric when I attempt to "Write Catalog to debug". I've tried username/password combinations like: admin/admin , Username/Password , Username./Password. and none are working

_"OSecurityAccessException: Wrong user/password to [connect] to the remote OrientDB Server instance"_ 

I've also tried creating the k2db database manually in OrientDB, however I receive an "Unauthorized 401" exception when I attempt this.

Thank you

<img width="613" alt="Screen Shot 2021-04-01 at 10 39 03 AM" src="https://user-images.githubusercontent.com/81371570/113310785-98d9cf80-92d6-11eb-8637-ef3d8ed73e40.png">
<img width="1536" alt="Screen Shot 2021-04-01 at 10 38 52 AM" src="https://user-images.githubusercontent.com/81371570/113310788-98d9cf80-92d6-11eb-9b3e-0fcee2dc9486.png">
<img width="1244" alt="Screen Shot 2021-04-01 at 10 38 25 AM" src="https://user-images.githubusercontent.com/81371570/113310792-9a0afc80-92d6-11eb-8ad8-abea2aaef7a9.png">

**Comment by lionbro1** [comment]
Hi,

You should not create the DB manually. It will be handled automatically.

What is the user/pass you set to the orientDB when you installed it? if you used the default the user/password should be 
root/root.

This is why connection is not established. make sure orientDB user/pass is aligned with the interface definition.

**Comment by wfk2view** [comment]
Thank you! I mistakenly forgot (or auto-generated) my root password. After I re-installed GraphDB and used the right password, this issue is fixed.
