### ISSUE TITLE
Graphit timeouts

### ISSUE THREAD

**Issue by alexmessel** [k2view-academy/K2View-Academy#203]
Do we have a way to set a timeout for the graphit execution like the sync timeout we have for the LU?

**Comment by lionbro1** [comment]
Hi

No, there isn’t as a built-in feature. 

It can be done on implementation side by using Java/JS within the graphit.

**Comment by alexmessel** [comment]
Is it possible to provide an example of how to implement this within the graphit?

**Comment by greg-k2view** [comment]
![image](https://user-images.githubusercontent.com/62937469/113510324-fa15d300-9562-11eb-95c9-45b9e3ff19df.png)


Hi Alex - see a suggested implementation on graphit:
1. note the difference in the condition node is set to 15 ms - not enough time for the process to complete, so graphit jumps to node FALSE
2. if set to over 70 ms - then graphit will jump to the node TRUE and return the value of one of the fields fetched in the select command in the SQL node

![image](https://user-images.githubusercontent.com/62937469/113510415-74deee00-9563-11eb-8feb-bf4d903d3d7a.png)

@lionbro1

**Comment by alexmessel** [comment]
Thank you for the example. Unfortunately, it covers a single select within the graphit and doesn't allow me to timeout the whole graphit.

Let's say I have a graphit with 50 nodes. If it takes more than 2 seconds, I want to abandon graphit execution and throw an exception.

**Comment by greg-k2view** [comment]
Alex , I believe the same technique could be used across a bigger number of nodes - maybe by nesting each into a timeout condition.

This being said will be asking around for more info/ideas and communicate it to you.
