### ISSUE TITLE
Turn off Fabric Admin login page background animation

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#204]
The new Fabric Admin login page background animation is cool, but an issue on environments accessed via remote desktop.
Where in `fabric/staticWeb` can I set that animation to not be executed and stick to, for instance, a static background image?
Thanks.

**Comment by lionbro1** [comment]
Hi,

Currently it is not configurable, we will consider in future releases adding the ability to switch it on/off.

**Comment by lionbro1** [comment]
In addition, you can increase the session timeout in config.ini, default is 15 min

WEB_SESSION_EXPIRATION_TIME_OUT=15

So if you will put higher value you will not be required to login each 15 min.
