### ISSUE TITLE
No document being published to Elasticsearch

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#206]
Hi, I created `Search` interface of type `Search Engine`.
I see index `<lut>_<table>` schema in Elasticsearch.
Table that contains `keyword` columns is being populated (insert) exclusively based on trigger function.
That is, table is on LU schema, but has no population associated to it.
I see `START`, `BODY`, `COMMIT` and `PUBLISH` events on `CDC_TOPIC_<clusterid>` topic.
I see no events on `Search_<clusterid>` topic.
I see no document on Elasticsearch `<lut>_<table>` index.
I see no exceptions on `k2fabric.log`.
Any idea what it could be?
Thanks.

**Comment by feamcor** [comment]
I finally see document being generated.
But index name is `<lut>_<clusterid>_<clusterid>_<table>`.
Could you please elaborate on how the index name is defined?
In the environment's `node.id`, `uuid` has same value as `cluster_id`, e.g. `uuid:dev21` and `cluster_id:dev21`.
Thanks.

**Comment by taliei** [comment]
Hi.

I've updated the following articles:

https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.4/articles/18_fabric_cdc/cdc_consumers/search/03_creating_elasticsearch_indexes_on_search_fields.md

https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.4/articles/18_fabric_cdc/02_cdc_process_architecture.md

Thanks.,
Tali
