### ISSUE TITLE
Troubleshooting Graphit Error Message "some node: Encountered"

### ISSUE THREAD

**Issue by wfk2view** [k2view-academy/K2View-Academy#208]
What is the best way to debug the following type of error message from Graphit? E.g. how should I find or reference Line 1, Column 14?

some node: Encountered " ";" "; "" at line 1, column 14.
Was expecting one of:
    <S_INTEGER> ...
    <S_IDENTIFIER> ...
    <S_CHAR_LITERAL> ...
    <S_QUOTED_IDENTIFIER> ...
    "?" ...

<img width="1200" alt="Screen Shot 2021-04-08 at 3 58 09 PM" src="https://user-images.githubusercontent.com/81371570/114088788-63f3ec80-9883-11eb-93f4-e966bce31dbb.png">

Thank you

**Comment by greg-k2view** [comment]
Hey, can you try using " (double quotes) rather than ' (single quotes) in your JS node statement - dateOfContract ?.

Also can you add the full graphit file - I can't see the first nodes you defined .

**Comment by wfk2view** [comment]
Attaching the full Graphit file for reference. I changed the statement to Double quotes, redeployed, retested and got the  same error message (attached).

Is there a way we could change the error, exception handler, so that it references lines in the Graphit visual file?

<img width="1224" alt="Screen Shot 2021-04-09 at 8 29 38 AM" src="https://user-images.githubusercontent.com/81371570/114180236-ed500100-990d-11eb-88bc-37af66388145.png">

[graphitTest.k2export.zip](https://github.com/k2view-academy/K2View-Academy/files/6285704/graphitTest.k2export.zip)

**Comment by greg-k2view** [comment]
Hi the error is referenced in Line 1 , column 14  - if you are asking that the exact line be made visible and pinpoint exactly to the issue, this is not something supported at this stage.

So the way to do it is to count the lines in the graphit file whereby only lines inside the nodes are incremental line numbers - the node's title frame are not counted as lines.

**Comment by greg-k2view** [comment]
> Hi the error is referenced in Line 1 , column 14 - if you are asking that the exact line be made visible and pinpoint exactly to the issue, this is not something supported at this stage.
> 
> So the way to do it is to count the lines in the graphit file whereby only lines inside the nodes are incremental line numbers - the node's title frame are not counted as lines.

**Comment by greg-k2view** [comment]
@AlexM- thanks for your input :-)

- @wfk2view  / actually, wrt the error you are getting please don't forget to add LUI value in your graphit parameters window. see link here to learn how:
- 
https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.4/articles/15_web_services_and_graphit/17_Graphit/06_using_graphit_files_with_parameters.md#graphit-window---how-do-i-configure-graphit-parameters
