### ISSUE TITLE
Keeping K2View data synchronized with source

### ISSUE THREAD

**Issue by rivigrin** [k2view-academy/K2View-Academy#21]
What is the best practice for keeping data in-sync with the source in order to prevent a delay when the web service is invoked?
Basically, the data should be near time and never expire.

We were thinking of running a background query that will detect, based on the last_updated timestamp column, which records have changed, create a list and perform a migration.

Based on your experience and best practices, is this the recommended way to accomplish that requirement?

**Comment by taliei** [comment]
Synchronizing an LU instance (LUI) by Fabric can be initiated in two modes:
1. Proactive Sync (iidFinder) - synchronizing LUI proactively by interacting with a CDC tool that feeds Fabric with data changes from source systems. This solution is based on an initial load process that sets a baseline for the data in Fabric before the feeds are received from the CDC tool.
Fabric iidFinder mechanism gets the CDC feed to source changes, identifies LU Instance ID(s)impacted by the changes, and updates them in Fabric.
Synchronizing database changes proactively into Fabric ensures a much faster response time to CSR requests for data.

2. Lazy (on-demand) Sync, synchronizing an LUI on demand. For example, data sync is initiated for Customer 123 when a CSR in a Call Center triggers a Fabric WS call requesting fresh data for Customer 123. Fabric only updates data in Customer 123 upon request when the data is needed by the user. A Lazy Sync is initiated based on a predefined Sync method on the LU and the Sync mode.

For more information about Sync, see [Sync Overview](https://github.com/k2view-academy/K2View-Academy/blob/master/articles/14_sync_LU_instance/01_sync_LUI_overview.md).

**Comment by taliei** [comment]
See the link to the ticket for this question:
https://k2view.freshdesk.com/a/tickets/16245
