### ISSUE TITLE
How is Data Fabric managing images?

### ISSUE THREAD

**Issue by dcanmen** [k2view-academy/K2View-Academy#229]
1.: In cases where we would keep pictures as blobs in the LUI - does the compression algorithm have extra compression value on the pictures/blob ?

2:  is there a way that Fabric could save pictures in a way that enable saving space ? (such as S3 bucket + reference link to the object kept in the LUI)

**Comment by greg-k2view** [comment]
1. 
Indeed pictures can be kept them in a separate Logical Unit, which really adds in availability and R/T performance. Access to such pictures can then be done by querying both the customer specific LUI and the images-dedicated LU that can be correlated with the entity ID.

2.
yes, we can use whatever storage needed with some minor implementation - such as S3 Bucket or any other storage service. In that case the address pointing to the specific image can be stored as text in one of the entity LU field

3. On a different note, in cases where PII information is hidden in the image file itself by means of tagging and/or printed values on the picture itself (as it is the case in medical imaging formats), various decoding techniques (such as OCR) can be used to extract the PII information and even anonymize/mask it if necessary
