### ISSUE TITLE
How can we control the interface listener from outside the fabric 

### ISSUE THREAD

**Issue by tamarzohar** [k2view-academy/K2View-Academy#231]
Hi , 
The customer want to control the active of an interface listener using Ctrl M mechanism . 
Do we have any command like we used to have stop job that will stop the interface listener ?

**Comment by natalylic** [comment]
Since Interface listener is a job, it can be stopped using the **stopjob** command.
You can also stop it using the **kill** command, by killing its process.
Or by unchecking the Active checkbox via the Studio and re-deploying the LU.
