### ISSUE TITLE
Bind variables on DML statement

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#234]
The following use of bind variables is possible: `GET ?.?`
I have the same table within many LUs.
I can't use bind variable for the LUT like `INSERT INTO ?.TABLE (...) VALUES (?,...)`
Is there any other option?
A summary of where exactly bind variables can be used on Fabric commands would be welcome.
Thanks.

**Comment by natalylic** [comment]
The SQL statement can be created dynamically using prepared statement parameters, for example:
`Select * From CASES where STATUS = ?`
In a prepared statement, only the parameter value can be presented as ?. Setting ? for table or column name is not supported.
If it is required, you can build the SQL as a string concatenating the table name to it, for example:
`fabric().execute("get FK.1;");`
`return fabric().fetch("select * from "+param+";");`
