### ISSUE TITLE
Best approach to load a large dataset

### ISSUE THREAD

**Issue by ghost** [k2view-academy/K2View-Academy#237]
Hi K2View team,

I have a large dataset(close to 27 million records) that need to load into a cassandra table, currently using a broadway flow with dbcommand to get the data, dbload to insert into cassandra. 

Due to the volume of records I notice a decrease of performa of fabric when the query/loading is happening. Can you advice in a best way to load the information? Is there any inbuilt paging system?

Thank you,
Tiago

**Comment by greg-k2view** [comment]
Hello,
This is a known issue for very large file - 
We have improved the mechanism and considerably reduced loading times by enabling a Cassandra Loader interface and by improving the DBLoad actor. 
This has been introduced in 6.4 but will be released in Fabric version 6.5.

**Comment by ghost** [comment]
Hi  @greg-k2view 
Thank you for the help & feedback. 

I believe the issue might also be with the source data query, the dbcommand actor, that executes a query in the data source is probably loading all records into memory.  I was trying to get an in built way to avoid having to do alot of selects with limit,offset directive. 

Can we have some insystem way to batching / paging the loading?
