### ISSUE TITLE
Get Fabric Job status outside of Fabric

### ISSUE THREAD

**Issue by ghost** [k2view-academy/K2View-Academy#238]
Hello,

We have been looking for a way to keep monitoring the status of our fabric jobs in order to trigger systems alarms to our teams when failures occur.

Is there any option via API or command to know the status of the jobs(something like jobstatus)?

Thank you,

**Comment by greg-k2view** [comment]
Hello,

I suggest you use the fabric-command option that can be sent in a webservice. The result of the command will be displayed in the response.
Do do so:
1. -> open Swagger -> Fabric -> fabric-commands
2. Authenticate/Execute/Try it Out
3.  Modify the body of the request query with the fabric command to be executed:

In your example:

```
{
  "commands": [
    {
      "params": [
      ],
      "command": "jobstatus"
    }
  ]
}

```

To read more on fabric commands, consult: https://support.k2view.com/Academy_6.4/articles/15_web_services_and_graphit/13_Supported_Verbs_Post.html
