### ISSUE TITLE
Webservice/API Request information

### ISSUE THREAD

**Issue by ghost** [k2view-academy/K2View-Academy#239]
Hello K2View,

Is it possible to have more details about each webservice/api call , things like the request IP, start date/time, used params, etc..?

I have been trying to use the trace option but have not succeed.

**Comment by greg-k2view** [comment]
Hello :-) - which trace option are you talking about ? The fabric-command one ?

About auditing Fabric such logins, Web Service calls and Fabric command, please read about the 2 different strategies detailed in this series of articles:
https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.4/articles/27_auditing/01_auditing_overview.md

https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.4/articles/27_auditing/02_filtering_strategy.md

https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.4/articles/27_auditing/03_persistence_strategy.md


As a reminder all API calls details are detailed in these articles:

https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.4/articles/15_web_services_and_graphit/12_Supported_Verbs_Get.md

https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.4/articles/15_web_services_and_graphit/11_response_codes.md

https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.4/articles/15_web_services_and_graphit/13_Supported_Verbs_Post.md

https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.4/articles/15_web_services_and_graphit/14_Supported_Verbs_Put.md

https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.4/articles/15_web_services_and_graphit/15_Supported_Verbs_Delete.md

https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.4/articles/15_web_services_and_graphit/16_rest_api_additions.md
