### ISSUE TITLE
How does ADI monitors server memory & CPU in Execution Plan?

### ISSUE THREAD

**Issue by AlexMaziya** [k2view-academy/K2View-Academy#24]
How does ADI monitoring stats shown in the execution/flow monitor? 
Especially the CPU\Memory metrics while the EP is executing?
In addition, there is a server_stats table in the k2app schema in PostgreSQL. How is that table populated?

**Comment by lionbro1** [comment]
Hi,

Example of statistics captures:

Memory Statistics:  
Execution of: 
1.	Total: /usr/bin/vmstat | grep 'System configuration'
2.	Avail: /usr/bin/vmstat | tail -1 | awk '{print $4}'
3.	Used: total – avail;

CPU Statistics:
Execution of:  vmstat 5 1 | tail -1 | awk '{print $16,$17}'

Monitors:
Entity Average Time:
select datediff(entity_inclusion_end_time,last_update_timestamp,'sec') elapsed_in_sec ,entities_processed  from execution_stats_totals where execution_detail_id = $executionDetailID"


Product fill server_stats table according to the results on these sampled commands.
