### ISSUE TITLE
Listener interface

### ISSUE THREAD

**Issue by tarikhad** [k2view-academy/K2View-Academy#242]
For Listener interface, if the directory has more than one file. What is the order of files the listener picks up. Does it look for the file creation time ? to pick the first incoming file first and follow the order ?

**Comment by natalylic** [comment]
The Interface Listener picks up the files - each time a new file arrives to the directory defined in the interface. However if there are several files that arrive simultaneously, there is no commitment on the order of picking up the files. This functionality is similar to the Parsers.
