### ISSUE TITLE
FabricDB Prepared Statement Cache limit reached 500

### ISSUE THREAD

**Issue by ghost** [k2view-academy/K2View-Academy#243]
Hello K2View team,

Recently we increased the load on real time data being consumed by kafka interfaces and when there is more load we started to receive the following warning with this info:

**_c.k.f.f.c.PreparedStatementCache - [LID4eb6000000047e93] FabricDB Prepared Statement Cache limit reached 500_**

We have inserts into multiple cassandra tables and also into a couple of reference(common) tables.

Can you please advice on what can be done to avoid problems?

Thank you,

**Comment by lionbro1** [comment]
Hi,

Cache can be increased on config.ini if needed (MDB_PREPARED_STATEMENT_CACHE_LIMIT). 
However 500 should be enough for the implementation in most of the times. 
We would recommend to have code review with COE team to explore if code improvements are applicable. 
Please open fresh desk ticket for this if you need this kind of service.
