### ISSUE TITLE
Start/Stop CDC Jobs

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#246]
If I had to stop the CDC (search) jobs, how can I tell Fabric to start them again?​
I already restarted Fabric and it didn't work.
If I have to manually do a `startjob`, what is the correct syntax for it?
Mostly regarding the `UID` and the arguments `group_id` and `topic`.
Thanks.

**Comment by taliei** [comment]
Hi.

To restart the CDC jobs do either:

1. Redeploy the LUs with the CDC fields. The deployment restarts the CDC jobs.
2. Manual start of the jobs using the startjob command. Populate the parameters as follows:
> uid - is any unique id that makes you identify it from other jobs.
> group_id -  use the <topicname>_gid convention.
> topic - the CDC type as it declared in the studio.

Thanks,
Tali
