### ISSUE TITLE
Kafka Authentication for Broadway pub/sub Kafka Actor

### ISSUE THREAD

**Issue by mpp4manu** [k2view-academy/K2View-Academy#247]
How do we provide a user ID and password to authenticate to a Kafka instance?  My flow works to a generic instance I have that has no security, but I need to pass authentication information to access my corporate instances.

**Comment by natalylic** [comment]
Kafka interface definition includes SSL properties section. 
Set **Enable SSL = True** and define the SSL properties on the Kafka interface in order to authenticate a Kafka instance.
 
For example:
![KafkaSSL](https://user-images.githubusercontent.com/62207927/117942587-e3a62880-b313-11eb-81c2-ab3ebca6fc88.png)

**Comment by mpp4manu** [comment]
No, that's not right.  Our Kafka instance needs an actual user ID and password.  

Are you saying that the ONLY way that the K2View Kafka client interface can authenticate is by using a client SSL certificate?  If that is true, then it's a HUGE gap, rendering that interface of very limited use.

**Comment by natalylic** [comment]
According to our R&D team - it is possible to connect to Kafka using a user ID and password.
I'll get back to you once will get full details how to do it.

**Comment by natalylic** [comment]
Please advise to which account your question is related? And what is the E2E use case that you're trying to achieve?

**Comment by natalylic** [comment]
To connect with user & password to Kafka, set Security Protocol in the interface definition to **SASL_PLAINTEXT** and give path to the file that contains user & password.

**Comment by mpp4manu** [comment]
AT&T.

I’m just exploring what Broadway can do.

Michael Peoples
Principal Applications Developer
Customer Service and Ops, Operations Engineering & Automation

AT&T Services, Inc.
Westerville, OH
m 614.886.0923 | ***@***.******@***.***>

MOBILIZING YOUR WORLD

**Comment by mpp4manu** [comment]
Which field in the Interface definition would contain the path to the user and password?

Michael Peoples
Principal Applications Developer
Customer Service and Ops, Operations Engineering & Automation

AT&T Services, Inc.
Westerville, OH
m 614.886.0923 | ***@***.******@***.***>

MOBILIZING YOUR WORLD

**Comment by natalylic** [comment]
The definition of the user & password should be performed based on the Apache Kafka setup requirements
