### ISSUE TITLE
Fabric versions supporting TDM7

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#248]
Hello,

In the past, we had a hard dependency on specific fabric version say fabric version 5.3 for TDM version 5.1 , is it still the case with TDM 7?
TDM7 release notes mention fabric 6.4.1 but now 6.4.2 is available, wondering if its ok to go ahead with latest fabric versions TDM projects.
Regards,
Prathamesh

**Comment by taliei** [comment]
Hi.

You can run TDM 7.0.1 either on Fabric 6.4.1 or Fabric 6.4.2.

TDM 7.1 (will be released by the end of May 21) will be based on Fabric 6.5.

Regards,
Tali
