### ISSUE TITLE
Error: "some node: Access to [Customer.1] by user graphit isn't authorized."

### ISSUE THREAD

**Issue by wfk2view** [k2view-academy/K2View-Academy#259]
Testing a Graphit flow in fabric studio 6.5.0 I get the following error message:

"some node: Access to [Customer.1] by user graphit isn't authorized."

Can you help explain why the graphit user isn't authorized, what I can do to fix the authorization issue? E.g. does it need a bearer token?

Also - what does "some node" mean in the error?

Thank you
<img width="1536" alt="Screen Shot 2021-05-17 at 7 51 51 AM" src="https://user-images.githubusercontent.com/81371570/118484020-c17e2300-b6e4-11eb-82a8-3e3132b2c216.png">

**Comment by lionbro1** [comment]
Hi Wes,

You are using fabric 6.5 beta release.

It was fixed on the official release that will be launched tomorrow.

Anyway, links are available here:

https://k2view.sharepoint.com/:w:/r/sites/KS/Releases/K2V%20Product%20Documents/Fabric/V6.5.xx/V6.5.0/fabric%206.5_download_links.docx?d=wc0b9c4116aea4e42935f0286460bc008&csf=1&web=1&e=AsWXIR

**Comment by wfk2view** [comment]
My mistake - thank you for the help
