### ISSUE TITLE
How to delete instance from WS call

### ISSUE THREAD

**Issue by tarikh03** [k2view-academy/K2View-Academy#26]
Hi,

I used below option to delete instance from WS call with no success:

1. db("dbFabric").execute("delete instance <lu_name>.<instance_id>");
2. db("fabric").execute("delete instance <lu_name>.<instance_id>");

is there any other way to delete instance from WS call?

**Comment by lionbro1** [comment]
Hi,

It should work fine, what do you mean by it is not working? what is the exception in the log?

Also if you wish to just delete an instance, from fabric 5.5 and on you can call build-in product WS:

http://<server IP>:3214/api/lu/<LU name>/<iid>/token=<token name>

**Comment by tarikh03** [comment]
It is not deleting the instance as expected.
In logs there is no error.
please fine below code and logs.

fabric version: 5.4.7

Used code:

log.info("wsDeleteIns starting...");

try{
db("dbFabric").execute("delete instance IIDF4_CLE.732");
} catch (Exception e){
	log.info("wsDeleteIns Exception... " + e.getMessage());
}

log.info("wsDeleteIns end...");

Log:

INFO  [https-jsse-nio-9443-exec-4] 2020-06-03 14:49:06,972 c.k.c.w.WebServiceServlet - [LID] [LogbackBinder.info:https-jsse-nio-9443-exec-4::69]  Starting webservice wsInsDelete
INFO  [https-jsse-nio-9443-exec-4] 2020-06-03 14:49:06,973 c.k.c.s.u.UserCode - [LID] [LogbackBinder.info:https-jsse-nio-9443-exec-4::65]  wsDeleteIns starting...
INFO  [https-jsse-nio-9443-exec-4] 2020-06-03 14:49:06,973 c.d.d.c.ClockFactory - [LID] [ClockFactory.newInstance:https-jsse-nio-9443-exec-4::57]  Using native clock to generate timestamps.
INFO  [https-jsse-nio-9443-exec-4] 2020-06-03 14:49:07,200 c.d.d.c.p.DCAwareRoundRobinPolicy - [LID] [DCAwareRoundRobinPolicy.init:https-jsse-nio-9443-exec-4::110]  Using data-center name 'DC1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
INFO  [https-jsse-nio-9443-exec-4] 2020-06-03 14:49:07,206 c.k.c.s.u.UserCode - [LID] [LogbackBinder.info:https-jsse-nio-9443-exec-4::65]  wsDeleteIns end...
INFO  [https-jsse-nio-9443-exec-4] 2020-06-03 14:49:07,230 c.k.c.w.WebServiceServlet - [LID] [LogbackBinder.info:https-jsse-nio-9443-exec-4::69]  End webservice wsInsDelete

**Comment by lionbro1** [comment]
it should work.

Try using 

db("fabric").execute("delete instance <lu_name>.<instance_id>");

and don't put it inside try and catch, if it still doesn't work for you, please open a ticket to R&D.

try the same on high release ), like 6.1.1 that you can test on your laptop.

**Comment by tarikh03** [comment]
I tested same code locally on 6.0.2 and 5.4.7.

on 6.0.2 it is working as expected, on 5.4.7 it is not.

will open a ticket.

**Comment by lionbro1** [comment]
ok, so i close this item
