### ISSUE TITLE
Delete functionality

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#260]
Hi Tali, 

I have a question regarding delete entities functionality of TDM V7. 
Link - https://support.k2view.com/Academy_6.5/articles/TDM/tdm_implementation/08_tdm_implement_delete_of_entities.html

The article explicitly mentions for main target table populations to be created as a Broadway flow population. I read about setting the active target env through this broadway population , is there any other reason for using broadway population for the main TAR table?

Regards,
Prathamesh

**Comment by taliei** [comment]
Hi.

No. The reason for using a Broadway flow on the main TAR table is to set the target environment as active environment before populating the TAR table.


Tali
