### ISSUE TITLE
Can WebServices (APIs) be exposed without Authentication Enabled?

### ISSUE THREAD

**Issue by wfk2view** [k2view-academy/K2View-Academy#262]
I'm doing some testing with web services for demos and trying to expose the web service without Bearer Token authentication. This is for an external [Figma plugin](https://www.figma.com/community/plugin/787488293482536319/Data-Populator) that doesn't support authentication. 

Is there a setting where authentication can be disabled for web services entirely?

Thanks

![image](https://user-images.githubusercontent.com/81371570/119077988-558d0a80-b9c3-11eb-8a7f-207835cf51df.png)

**Comment by greg-k2view** [comment]
Hello,

I am afraid not - there is no possibility to invoke a fabric web service w/o a token (- token that can be either secured or unsecured).

**Comment by lionbro1** [comment]
On Fabric  release 6.5.4 we added the option to define Web-Service and setting No Authentication property to True.
