### ISSUE TITLE
Can we pass inputs to Inner Flow called from the Error Handler actor

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#263]
Hi,

Is there a way to pass inputs to the Inner Flow called from the Error Handler actor? For example, in the image below, how can I pass input to bwHandleInserts flow?

![image](https://user-images.githubusercontent.com/66338066/119523177-2a4b4800-bd42-11eb-98a4-de1f825cba02.png)

**Comment by natalylic** [comment]
The inner flow which is called from the **ErrorHandler** actor receives an **error** object that includes the fields contained in the Broadway error object, such as the error code, flow, stage, actor, actor input parameters and more.
You can then start your inner flow from the **ErrorFields** actor to access the error information easily.

**Comment by smokyMount** [comment]
I tried what you recommended here but the ErrorFields actor is not printing fields from the error object inside the inner flow. Screenshots below. Attaching the export also.

![image](https://user-images.githubusercontent.com/66338066/120023937-1575eb00-bfb4-11eb-8b23-883058ef9f03.png)

![image](https://user-images.githubusercontent.com/66338066/120023892-098a2900-bfb4-11eb-935d-3bc1680db286.png)

[innerFlowErrorHandling.zip](https://github.com/k2view-academy/K2View-Academy/files/6562548/innerFlowErrorHandling.zip)

.

**Comment by natalylic** [comment]
Since the innerErroHanlder flow is an Inner flow, its input argument should be defined as **External** in order to receive the values from the calling flow. 
![errorFields](https://user-images.githubusercontent.com/62207927/120095413-8e00b700-c12e-11eb-9786-967c4899135a.PNG)
