### ISSUE TITLE
Encryption error in environment <env_name>

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#264]
Hi,

When trying to save the Environments file from studio, we sometimes get the error saying "Encryption error in environment <env_name>".
![image](https://user-images.githubusercontent.com/66338066/120010246-890efc80-bfa2-11eb-892b-05c131f9fc46.png)

We were able to resolve it by "Re-keying" for that environment. The question I have is why do we get this error? What's the reason behind this behavior?

Thanks,
Hardik

**Comment by eyalk2** [comment]
Hi,
We assume that on those cases you use "Fabric URL" option at the envionment definitions and you switched from one to antoher, or you just start using "Fabric URL". In such cases re-key is required. Please read more [here](https://support.k2view.com/Academy_6.5/articles/26_fabric_security/04_fabric_interfaces_security.html)
