### ISSUE TITLE
PUT/POST Web Service JSON Request Payload

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#265]
Hi,
What is the recommend way to handle PUT/POST WS requests where payload is a JSON element (i.e. `Content-Type: application/json`)?
Currently, I set my WS with `isCustomPayload=true` and its `request().getInputStream()` is being handled as per code below.
I'm using Gson (`JsonElement`, `JsonParser`, etc.) for parsing the request input stream.
How can I get, automatically, a `List` or `Map` or even `Object` of the request payload without having to handle its input stream?
How can I define an input parameter to the WS that would correspond to the request payload, instead of query parameters?
I don't understand the impact of the `isCustomPayload`, please elaborate on its use case.
Thanks.

```java
static public JsonElement getRequestPayload(String apiName, JSON_TYPE jsonType, HttpServletRequest request) throws Exception {
  JsonElement payload = JsonParser.parseReader(new InputStreamReader(request.getInputStream(), StandardCharsets.UTF_8));
  if (jsonType == JSON_TYPE.ARRAY && !payload.isJsonArray()) {
    throw new ApiException(ApiException.ErrorCode.MRT_API_ERR_10, "Request payload is not a JSON array");
  }
  if (jsonType == JSON_TYPE.OBJECT && !payload.isJsonObject()) {
    throw new ApiException(ApiException.ErrorCode.MRT_API_ERR_10, "Request payload is not a JSON object");
  }
  log.debug(ApiUtilities.LOG_API_PAYLOAD, apiName, JSON_MASKER.mask(payload));
  return payload;
}
```

**Comment by eyalk2** [comment]
To handle POST Json payload you do not need to use custom payload option. This is supported as part of the standard WS. Please see an example [here](https://support.k2view.com/Academy_6.4/articles/15_web_services_and_graphit/06_web_services_code_examples.html#example-of-a-complex-java-input-structure)
