### ISSUE TITLE
MAVEN 

### ISSUE THREAD

**Issue by LumaNasrallah** [k2view-academy/K2View-Academy#266]
is Maven supported ? if yes, can you please explain me how we can use it ?

**Comment by eyalk2** [comment]
Hi
From the example you gave, of extenral JARs dependecies, we can assume that probably cusotmer wishes to take it from Maven. Such method is not available, yet external JARs usage in Fabric project is supported, as explained [here](https://support.k2view.com/Academy_6.5/articles/31_external_resources/01_external_jars.html)
