### ISSUE TITLE
DATETIME_FORMAT and the DATE_FORMAT properties in the config.ini file

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#268]
Hi,

We have Oracle tables in the project where there are some fields with DATE and TIMESTAMP datatypes. The expectation from the date properties in the config.ini file is that when storing such fields to Fabric, DATETIME_FORMAT should convert the timestamp datatype fields and DATE_FORMAT should convert the date datatype fields to the format specified in the cofig.ini file.

But the behavior we observed is that changing DATE_FORMAT property did not make any difference to these datatype columns but changing DATETIME_FORMAT converted both fields to the new format specified. 

What is the difference between the DATETIME_FORMAT and the DATE_FORMAT properties in the config.ini file? How do these fields impact data when storing to Fabric?

**Comment by eyalk2** [comment]
Hi
We are still investigating the issue.
Yet we recommend not using such general configuration, but define it explicitly in flows (using Broadway DateFormat actor) or in fucntions (when needed create a shared utility function). This gives more visibility (e.g. when someone else look at the population) and gives better control.

**Comment by eyalk2** [comment]
Due to a special treatment which required for Oracle, Fabric supports only the DATETIME_FORMAT, which can be used and applied also for date and for time fields. 
The other configurations (date and time), are relevant for other databases.
