### ISSUE TITLE
Multiple GETs and Release statement

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#270]
Hi,

Why do we have a note in the help section of Release statement saying this? 

Important:
When there is a use case of multiple get in a loop on the same fabric session, it is recommended to use the release (without lu name) command after each loop iteration.

![image](https://user-images.githubusercontent.com/66338066/121064577-62fd0f80-c78d-11eb-9d84-e6792bae1b7b.png)

We have a use case where we are doing multiple Gets in a loop for one LU instance while another instance from a different LU type needs to remain in scope. If we did not pass any LU name to release statement, it will release both instances and I'll have to run a GET again on that instance from 2nd LU for each iteration.
Are there any issues that might rise if I pass an LU name in such scenario?

**Comment by taliei** [comment]
Hi.
 It is recommended to use the release command without the LU name only if you need to release the LUIs of all LUs in the session. If you need to release an LUI of a specific LU, you need to set the LU name in the release command.

Regards,
Tali
