### ISSUE TITLE
Fabric jobs - reduce number of tries in case of failures

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#271]
Hi,

The default behavior we see when a user job fails is that a it tries to rerun every minute for max of 10 times. Is it possible to change this number?

**Comment by taliei** [comment]
Hi.

The following parameters are configurable and can be edited in the config.ini file:

## This value will define the delay of fabric heartbeat frequency. Default is 10 sec.
#FABRIC_HEARTBEAT_INTERVAL_MS=10000

## Defined the number of the heartbeat that fabric node can miss before it will be considered as not alive.
#FABRIC_HEARTBEAT_MISS=30

For more details see- 
https://support.k2view.com/Academy_6.5/articles/20_jobs_and_batch_services/09_jobs_configuration.html

Regards,
Tali

**Comment by smokyMount** [comment]
Thanks, Tali. Just to clarify, there is no parameter to change the number of retries when a user job fails?

**Comment by greg-k2view** [comment]
Hello - no there is no parameter - but you can achieve that programmatically by throwing an exception and invoke the failJobAlwaysRetry(e) procedure  - 
consult this article please for more info:
https://github.com/k2view-academy/K2View-Academy/issues/178#issuecomment-778743120
