### ISSUE TITLE
In Fabric CLI is there a way to list generic interfaces?

### ISSUE THREAD

**Issue by JohnH-K2View** [k2view-academy/K2View-Academy#272]
In Fabric CLI (and admin GUI) we can list DB_SOURCES to see all database connections. Is there an equivalent to list Generic interfaces (ex: local file system interfaces)?  The "help list" command only shows valid LIST_TYPE [WS, DB_SOURCES, LU_TYPES, LUT, ENVIRONMENTS, ENVS, INSTANCE_GROUPS, IGS, BROADWAY_FLOWS, BF, ROLES, USERS, TOKENS, ROLE_PERMISSIONS, METHODS]

Is there a way to see other interfaces?

**Comment by taliei** [comment]
Hi.

The next Fabric release - Fabric v6.5.1 - will also support a test connection on non-DB interfaces.  Then the test_connection command will return the list of all interfaces of the active environment and their status.

This will be supported by Fabric 6.5.1.

Regards,
Tali
