### ISSUE TITLE
Oracle interface post connection commands - ALTER SESSION SET CURRENT_SCHEMA

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#273]
Hi there,
I have a `genericdb` interface set to an Oracle database.
Its `User` property is set with `USER_NAME`.
Its post-connection command is set as `ALTER SESSION SET CURRENT_SCHEMA = SCHEMA_NAME`.
It connects accordingly; i.e. `test_connection` returns `passed=true`.

Populations are based on root functions where tables of the queries are not prefixed by their schema.
I mean, query is...
```sql
SELECT COLUMN1, COLUMN2 FROM TABLE1 WHERE COLUMN1=?
```
instead of...
```sql
SELECT COLUMN1, COLUMN2 FROM SCHEMA_NAME.TABLE1 WHERE COLUMN1=?
```
or even...
```sql
SELECT COLUMN1, COLUMN2 FROM USER_NAME.TABLE1 WHERE COLUMN1=?
```

On SQLDeveloper if after connecting I ran the post-connection command above and then one of the population queries, it works accordingly.

On Fabric, by deploying the project, deploying environment, even restarting, whenever I try to perform a `get`, it fails with the following exception...
```
Exception in fn_pop_TABLE1(): java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist
from population [LU:LUT, TABLE:TABLE1, POPULATION:pop_TABLE1]
```

1. How can I check that Fabric is actually running the post-connection statement?
2. If the post-connection statement fails, would I get any error in `k2fabric.log`?
2. Will the post-connection statement run for environments but the debug one?

Please advise.
Thanks.

**Comment by feamcor** [comment]
Fabric version is...
Base Version Tag `fabric-6.4.2_47` at revision `1cfe4800746f1a6c2c07e0ced1ab7ba159043b77`
MDB Version `3.27.2`

**Comment by lionbro1** [comment]
documented as a defect on fabric 6.5.1
