### ISSUE TITLE
Support for Oracle Advanced Network Compression in Fabric 6.4.x

### ISSUE THREAD

**Issue by JZ67** [k2view-academy/K2View-Academy#280]
AT&T CIDS is ready to test 'over the wire' compression between CCR Oracle to Fabric 6.4.2.  They are looking to reduce overall migrate times between CCR (source) to Fabric (target) and mitigate poor performance their network.

They have been assured by their Oracle experts that it can be supported and configured on their CCR side.  I am looking for K2View Product team to evaluate and verify that we can support this in Fabric with our Oracle interfaces, and which configuration changes should be made to support this.

See Oracle whitepaper below.
https://www.oracle.com/technetwork/database/enterprise-edition/advancednetworkcompression-2141325.pdf

Thanks
JZ

**Comment by eyalk2** [comment]
Fabric 6.4.2 JDBC driver supports already Oracle 19c, so it shall support compression.

At the Oracle interface configuration, the connection properties shall be updated - add these 2 properties:
oracle.net.networkCompression=on
oracle.net.networkCompressionThreshold=1024

Alteratively, these 2 properties can be added to the connection string (e.g. jdbc:oracle:thin:@host:port?oracle.net.networkCompression=on&oracle.net.networkCompressionThreshold=1024)
