### ISSUE TITLE
How to load load large number of entities through TDM Broadway

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#281]
Hello,

I was wondering whats the replacement for entity inclusion in latest TDM ?
What would be the best way to do a bulk load through TDM

Regards,
Prathamesh

**Comment by taliei** [comment]
Hi.

Extract tasks or load Data Flux tasks- you can check the "Select All" entities.
Load regular tasks- you can select the Random selection or Parameters options.

For more details about entity selection method of load tasks see-
https://support.k2view.com/Academy_6.5/articles/TDM/tdm_gui/18_load_task_requested_entities_regular_mode.html

Tali.
