### ISSUE TITLE
Load balancer policy

### ISSUE THREAD

**Issue by AlexMaziya** [k2view-academy/K2View-Academy#282]
Do we any guidelines/recommendation/documentation for LB policy to utilize with Fabric and TDM in particular?

[https://support.k2view.com/Academy_6.5/articles/99_fabric_infras/devops/02_fabric_environments.html
](url)

The above mention the LB but does not come with a recommendation. Do we just prefer Round Robin or any other policies preferred?

**Comment by lionbro1** [comment]
Hi,

Our preferable and recommended policy for load balancing is Round Robin.
