### ISSUE TITLE
How to add error handler for individual ref tables since tdmreferenceloader has no such functionality?

### ISSUE THREAD

**Issue by ramya-sruthi-d** [k2view-academy/K2View-Academy#283]
Hi,
I got errors for multiple reference tables when I tried to load them. But I couldn't handle any of them because it is executed using tdmreferenceloader and there is nothing I can modify over there. So, is there a way to handle the error by adding an error handler?

**Comment by prathameshpalaskark2view** [comment]
This Question is regarding a scenario in a current project where multiple error codes will need to be handled. 
The tdmreferenceloader has different error handlers agreed but different tables need different error codes to be handled. Example, table 1 will ignore unique constraint, table 2 will ignore column missing errors. 
![image](https://user-images.githubusercontent.com/46533104/123854912-e6210980-d8e4-11eb-8667-4d167cf07bf1.png)
Within the same error handler if these conditions are provided as input, then both tables will be applied with unique contraint, column missing handler, this is not behaviour expected. Thus, asking if there is a way for better ref error handling based on individual ref tables.

**Comment by taliei** [comment]
Hi.

In case you need to have specific error handlers on specific tables, you can split the Error Handler Of Loading stage, add to the flow conditions that check the reference table name, and set specific error handlers for these tables if needed.

For more information about splitting Broadway stages, see-
https://support.k2view.com/Academy_6.5/articles/19_Broadway/19_broadway_flow_stages.html

Regards,
Tali
