### ISSUE TITLE
Security SAML config more information

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#284]
Hello,

Asking questions with regards to SAML setup for current project.  Read through the fabric security section and referred to below links we have following questions,
https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.5/articles/26_fabric_security/10_user_IAM_SAML_Fabric_flow.md

Q1 ] So when fabric sends the authentication request to IDP, what is the example payload that we send to IDP ? 
Q2] within link refer sentence, Fabric verifies and opens the response using the certification and encryption keys and algorithms, then processes and extracts the content, including the groups/roles with which the user is associated (6)

So what attributes should IDP send to Fabric as part of its authentication payload. 

Q3] Refer link https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.5/articles/26_fabric_security/13_user_IAM_configiration.md#saml-configuration 

In Provide the IDP,  please provide example of below values
SP entity ID --  ?
ACS URL - the endpoint at Fabric to which the SAML response should be sent  ? which endpoint?
SP_ASSERTION_CONSUMER_SERVICE_URL -- Example provided https://<HOSTNAME>:<PORT>/api/authenticate , with hostname as fabric load balancer. What if there is no load balancer? 

Regards,
Prathamesh

**Comment by eyalk2** [comment]
[Q1]
Example (Fabric is at AWS, IDP is Okta)


<samlp:AuthnRequest
                xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="ONELOGIN_d8531448-0932-42ce-886f-6c2edd0540b7" Version="2.0" IssueInstant="2021-07-01T07:17:31Z" Destination=https://k2view-test1.okta.com/app/fabrick2view/exk11pmi86qZ9oDmY5d7/sso/saml ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" AssertionConsumerServiceURL=http://localhost:3213/api/authenticate>
                <saml:Issuer>https://ec2-52-59-139-169.eu-central-1.compute.amazonaws.com</saml:Issuer<https://ec2-52-59-139-169.eu-central-1.compute.amazonaws.com%3c/saml:Issuer>>
                <samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:encrypted" AllowCreate="true" />
                <samlp:RequestedAuthnContext Comparison="exact">
                               <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:Password</saml:AuthnContextClassRef>
                </samlp:RequestedAuthnContext>
</samlp:AuthnRequest>


[Q2]
IDP sends us the user identification (email format) and groups that user is associated to.
The SAML response content is encrypted by the IDP with a public key, where Fabric knows to open it with the private key.


[Q3]
For the example above, at Q1:

SP entity ID = https://ec2-52-59-139-169.eu-central-1.compute.amazonaws.com
(format is - https://<HOSTNAME>)

ACS URL (at config it is named SP_ASSERTION_CONSUMER_SERVICE_URL) - https://ec2-52-59-139-169.eu-central-1.compute.amazonaws.com:3213/api/authenticate
(format is - https://<HOSTNAME>:<PORT>/api/authenticate)

This URL is the Fabric external endpoint. If you are in a cluster then you work with LB, so you shall provide its endpoint. The example above is of a single node Fabric, without LB.

From: prathameshpalaskark2view ***@***.***>
Sent: Wednesday, June 30, 2021 9:55 PM
To: k2view-academy/K2View-Academy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [k2view-academy/K2View-Academy] Security SAML config more information (#284)


Hello,

Asking questions with regards to SAML setup for current project. Read through the fabric security section and referred to below links we have following questions,
https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.5/articles/26_fabric_security/10_user_IAM_SAML_Fabric_flow.md<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fk2view-academy%2FK2View-Academy%2Fblob%2FAcademy_6.5%2Farticles%2F26_fabric_security%2F10_user_IAM_SAML_Fabric_flow.md&data=04%7C01%7Ceyal.orbach%40k2view.com%7Cc674dcbd3a644ba3c77408d93bf88e66%7C994f176e677549549f9e0c719b5e9ca0%7C1%7C0%7C637606760989928572%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kERj2wm6cqj99tiS2L0l8DmmjaR0hpwuG1AP6Va0qsM%3D&reserved=0>

Q1 ] So when fabric sends the authentication request to IDP, what is the example payload that we send to IDP ?
Q2] within link refer sentence, Fabric verifies and opens the response using the certification and encryption keys and algorithms, then processes and extracts the content, including the groups/roles with which the user is associated (6)

So what attributes should IDP send to Fabric as part of its authentication payload.

Q3] Refer link https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.5/articles/26_fabric_security/13_user_IAM_configiration.md#saml-configuration<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fk2view-academy%2FK2View-Academy%2Fblob%2FAcademy_6.5%2Farticles%2F26_fabric_security%2F13_user_IAM_configiration.md%23saml-configuration&data=04%7C01%7Ceyal.orbach%40k2view.com%7Cc674dcbd3a644ba3c77408d93bf88e66%7C994f176e677549549f9e0c719b5e9ca0%7C1%7C0%7C637606760989933564%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vRmJbq81de3OICFCsOcGe830%2FZIJL6AYLwAug%2Fiijs8%3D&reserved=0>

In Provide the IDP, please provide example of below values
SP entity ID -- ?
ACS URL - the endpoint at Fabric to which the SAML response should be sent ? which endpoint?
SP_ASSERTION_CONSUMER_SERVICE_URL -- Example provided https://:/api/authenticate , with hostname as fabric load balancer. What if there is no load balancer?

Regards,
Prathamesh

-
