### ISSUE TITLE
Will the same masking value be generated across different LU's when we keep same masking id and set the useexecutionid to false?

### ISSUE THREAD

**Issue by ramya-sruthi-d** [k2view-academy/K2View-Academy#285]
I want to clarify the above-mentioned issue. I have masking (suppose SSN), which is present in two LU's, so for the same input can I generate the same SSN values irrespective of the LU?

**Comment by tahata1** [comment]
If your 2 LUs are in hierarchy and they are handled in the same execution (same execution_id) then they will get the same values.
If you run the LUs separately then you can set the useexecutionid to false.
BUT in this case if you extract the same instance several times, it will get the same value. 
For example, in execution_id #1 you handled ssn = 111 and it is masked to 333, if you run additional execution #2 with the same ssn (111),  if the useexecutionid is set to false, then again you will get 333 although it is a different run.
For more details regarding Masking, please check:
https://support.k2view.com/Academy_6.4/articles/19_Broadway/actors/07_masking_and_sequence_actors.html
