### ISSUE TITLE
Stopping CDC on local debug

### ISSUE THREAD

**Issue by benkipnis** [k2view-academy/K2View-Academy#287]
How do i disable CDC on local fabric/debug?

I want to maintain the CDC configuration in the tables so it's there for server deployments, but not have the CDC jobs go off on debug.

Thanks!

**Comment by taliei** [comment]
Hi.

You can update the config.ini parameter of the local Fabric debug and set the CDC_PUBLISH_MODE parameter to OFF to avoid publishing CDC messages to this server. Alternatively, you can set this parameter to IF_SETUP (Studio Debug default) to publish the CDC message only if the CDC publisher has been configured in the config.ini file.

For more information see -
https://support.k2view.com/Academy_6.5/articles/18_fabric_cdc/03_cdc_messages.html

Regards,
Tali
