### ISSUE TITLE
Broadway transaction behavior when using InnerFlowAsync

### ISSUE THREAD

**Issue by dotants** [k2view-academy/K2View-Academy#288]
What is the Broadway transaction behavior when using InnerFlowAsyn, where the Inner-flow is in the transaction and performs a DB insert or update on external DB?

**Comment by natalylic** [comment]
Broadway transactions include inner flow. See sub-chapter **Transaction in Inner Flows** in the following article: https://support.k2view.com/Academy_6.5/articles/19_Broadway/23_transactions.html
when **InnerFlowAsyn** actor is used in transaction, it's supposed to behave in the same way as any inner flow.

**Comment by dotants** [comment]
The question was about InnerFlow**Async**, where the inner-flow may still be running when the transaction ends.
