### ISSUE TITLE
ADI - Failover\backup node

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#29]
Hello,

Is it possible to configure an execution plan or the ADI server to run even if a node is unavailable? Or, if a node is unavailable then substitute it with a backup node automatically?

For example, if multiple servers are connected to translator group and one is down, will all the entities be executed on the live nodes?

Thank you,
Hardik

**Comment by lionbro1** [comment]
Hi,

The answer is yes, if you have 3 different servers (Server1, Server2, Server3) and you allocated 10 as max threads for each server and Server3 is going down, the 2 remaining servers will consume each up to 10 threads in parallel max.

So before Server3 was down you could process up to 30 instances in parallel, after server 3 is down you can process up to 20 instances in parallel, the failed server will not try to consume instances.

Of course in such a case you can increase the number of threads for the other 2 Servers if the hardware allows it.

Regards,
Lion

**Comment by AlexMaziya** [comment]
Do all nodes need to be available at the start of the execution and it can handle a node going down during? Or is there a config for minimum nodes required?

I had 2 nodes configured and when starting the execution, nothing happened. As soon as the daemon was started for the 2nd node, the plan immediately kicked off.

**Comment by lionbro1** [comment]
the node that will get down during the execution will not ask for new instances. it can go down in any stage of the execution
