### ISSUE TITLE
There is a confusion on where to link the input for maskingLUDBfunction actor

### ISSUE THREAD

**Issue by ramya-sruthi-d** [k2view-academy/K2View-Academy#290]
Hi,

I was using maskingLUDBFunction actor. The actor has 3 inputs ( value, params, input). I observed that the function works only when there an input linked to the value, but it doesn't really read the given input though. Then I tried connecting to input, in this case, it never goes inside the ludb function. Finally, tried to connect to both value and input only then it is able to read the given input parameter. I am attaching the images for reference, is this the expected behavior
<img width="346" alt="masklu_3" src="https://user-images.githubusercontent.com/30996689/124989745-14999580-e005-11eb-855c-c56fa0f8c9e5.PNG">
<img width="348" alt="masklu_2" src="https://user-images.githubusercontent.com/30996689/124989747-15322c00-e005-11eb-8629-956610128a5a.PNG">
<img width="346" alt="masklu_!" src="https://user-images.githubusercontent.com/30996689/124989748-15322c00-e005-11eb-85fb-fc82bdb1e35c.PNG">
?

**Comment by tahata1** [comment]
In case your LU function has only one input, then linking the input value to 'value' or 'input' should work fine.
If your function has more than one input, then the inputs must be linked to the functions inputs and not to the 'value'.
