### ISSUE TITLE
How to resolve this error when connecting to a MySQL database "folder does not exist or is empty"

### ISSUE THREAD

**Issue by wfk2view** [k2view-academy/K2View-Academy#291]
Can I get your guidance on how to resolve this error? "mysql folder does not exist or is empty". Where should the folder exist? I already have a folder under lib/MySQL.
<img width="1344" alt="Screen Shot 2021-07-11 at 6 13 21 PM" src="https://user-images.githubusercontent.com/81371570/125211416-32206680-e274-11eb-8259-2b6eb907e681.png">
<img width="677" alt="Screen Shot 2021-07-11 at 6 15 24 PM" src="https://user-images.githubusercontent.com/81371570/125211418-32206680-e274-11eb-88c9-7c74ee8a8abe.png">

**Comment by lionbro1** [comment]
Hi,

Do you have the JDBC driver file under this folder?

Please make sure such a file exist, for example, mysql-connector-java-5.1.46.

We don't provide such a driver out of the box as a part of Fabric package as it requires a separate license.

Regards,
Lion

**Comment by wfk2view** [comment]
I was able to solve it by placing the MySQL driver under C:\K2View\Fabric_6.5\Server\fabric\lib\DynamicJars\MySQL . Could we add detail to the error message so that it specifies where to place the driver? Or some other prompt for the user? Otherwise, since MySQL is listed as an out of the box interface, the user would assume the driver would be included as well?


![image](https://user-images.githubusercontent.com/81371570/125279220-b3621280-e2e1-11eb-84b3-6828c9d5a750.png)

**Comment by lionbro1** [comment]
The interfaces appears in the list are the ones we cover on our QA before we release a package, we can't include none free drivers as a part of our OOO package.

**Comment by lionbro1** [comment]
A full explanation on where to place the drivers is fully explain on the knowledge base.


https://support.k2view.com/Academy_6.5/articles/05_DB_interfaces/10_database_types.html

look on JDBC Drivers Management section
