### ISSUE TITLE
Config.ini ENABLE_BROADWAY_DEBUG_SERVLET information

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#293]
Hello,

Requesting information on parameter ENABLE_BROADWAY_DEBUG_SERVLET in config.ini . Will enabling it give more debug details on broadway flows ?

Regards,
Prathamesh

**Comment by lionbro1** [comment]
When enabling this parameter is allows you to debug Broadway Flow as population in Studio when debug environment is set to remote machine.

Nevertheless to mention it should be enabled on the remote machine.
