### ISSUE TITLE
Requesting information regarding how to skip stage or stages in a broadway flow

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#296]
Hello,

Currently we have loopskip actor which can skip the current iteration of a loop and control passes to next iteration. I am curious whether based on certain conditions , if we could skip stages ? 
consider a simple  example, there is a loop in broadway flow reading data from customer tables , in subsequent stages, some conditions are checked and masking other operations are applied on the data , final stage within the iteration is write to a file (stage 10). 

Now if due to an invalid data or any user requirement is  there any way that broadway flow can skip stages , skip from stage 3 to stage 10 within current iteration? 

I have read through https://github.com/k2view-academy/K2View-Academy/blob/1fe6c770955eadb87cc80fd9a39af4433382d231/articles/19_Broadway/21a_complex_iteration_flows.md#:~:text=Split%20into%20Branches-,When,-a%20flow%20is and  for such complex branching examples , but asking on behalf of a client if its possible to skip stages or go to a specific stage within a broadway flow.

Regards,
Prathamesh

**Comment by lionbro1** [comment]
Hi,

Broadway doesn't support skip stage/s functionality, in order to achieve it, you can create an actor that will represent the stages that you want to skip (inner flow) and add a condition before the actor.

Regards,
Lion
