### ISSUE TITLE
Partitioned IIDF - delay sync jobs

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#298]
Hi,

We are using Partitioned IIDF mechanism. Is there a way to not immediately start a delta sync and set time intervals for the sync jobs instead, e.g. 15 mins, 2 hrs etc.? I saw a Global in the project DELTA_JOB_DELAY_TIME with description "Delay iid process time" - Can it be used for this purpose? Is it in milliseconds?  

Also, can this value be set different for different LUs?

**Comment by lionbro1** [comment]
Hi,

There is no way to start the sync workers in a delayed. 

As a workaround you can start with SYNC_WORKERS_COUNT= 0  (in config.ini) and afterward change it to higher value  (will be updated on the fly, no need to restart Fabric or the job).

Currently the value of SYNC_WORKERS_COUNT can't be controlled on LU level.
