### ISSUE TITLE
node.id uuid

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#299]
Hi, what would be the impact if node.id's `uuid` is set with a value that is not a UUIDv4?
I intend to set it with AWS EC2 instance id (e.g. `i-0c197eeff106f58b9`) to make the value discrete.
Would it break anything?
Is Fabric somehow/somewhere expecting that this attribute holds an `uuid`?
I see that on `k2system.nodes`, the node's `uuid` is actually stored on column `guid` that is of `text` instead of `uuid` data type.
Please advise.
Thanks.

**Comment by eyalk2** [comment]
You can use any unique node id. Fabric does not expect any special format.

Note that you can also use logical IDs, when it fits.
see more information here: https://support.k2view.com/Academy_6.5/articles/02_fabric_architecture/05_fabric_main_configuration_files.html#nodeid
