### ISSUE TITLE
Functionality to deploy same EP to different environments with different global variables

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#30]
Hi,

Is it possible to deploy same EP to different environments with different global variables? I believe ADI can integrate with Jenkins for deployments. Can it also leverage UDeploy (or something similar) to manage the Global Variables?

One way is to duplicate an EP for dev and test environments, for example. If any change is made (add a new flow, for example) it needs to be changed in both EPs. But it would be great to just have a single EP so we always know we are testing the same LUs/flows/etc

Thanks,
Hardik

**Comment by lionbro1** [comment]
Hi,

On the EP you have an option to export/import the overrides. 

This can be a valid option, to maintain only one EP, import the relevant override (prod or dev), deploy and run it.

Issue was logged in freshdesk as https://k2view.freshdesk.com/a/tickets/16618


Regards,
Lion
