### ISSUE TITLE
Information on dbload actor upsert functionality

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#301]
Hello,

I would like to request Information on dbload actor upsert functionality. Currently we support oracle, postgres etc. in the dialect. There is an option for generic , I would like to know what does generic mean and how it works internally, and if there is a way we can customize this generic dialect for a particular db say db2.
For example, db2 does not have upsert keyword to do upsert operation it uses merge , https://www.ibm.com/docs/en/db2-for-zos/11?topic=statements-merge , thus in this sort of cases , how to customize the upsert sql statement using generic dialect? 

Regards,
Prathamesh

**Comment by natalylic** [comment]
When running an **UPSERT** command on **DbLoad** actor, you should use one of the supported dialects. 
When using a generic dialect on non supported dialects, you will get an exception. It cannot be extended.
The alternative for non supported dialect is to build your own statement using the **DbCommand** actor.
Dialect support for DB2 is targeted for future releases.
