### ISSUE TITLE
External interfaces/queries tuning - fetch size

### ISSUE THREAD

**Issue by IvanKostyuk** [k2view-academy/K2View-Academy#302]
Need to tune performance of external DB interfaces. What is the default fetch_size for JDBC connections?
How to set default fetch size for a DB interface?
How to set fetch size on DbCommand or DbLoad actors?

**Comment by natalylic** [comment]
Setting of the fetch size on DbCommand or DbLoad actors is not supported.
You can write a custom actor that inherits from DbCommand actor and set the fetch size using the IoSession object by casting it to IoJDBC which has an API to set the fetch size.

**Comment by natalylic** [comment]
The fetch size is not defined per actor. It is defined in the Fabric configuration config.ini file.
Currently there is a bug which prevents Broadway from reading this definition correctly. We are working on fixing it for V6.5.2.
