### ISSUE TITLE
Broadway JavaScript greater or less accuracy

### ISSUE THREAD

**Issue by IvanKostyuk** [k2view-academy/K2View-Academy#304]
Comparing two values of the same type in the actor JavaScript . For comparison using **<** (greater) or **>** (less).
It was noticed, that datatypes are Java datatypes
`java.lang.Object`
`java.lang.String`
`java.sql.Timestamp`
and etc.

Is it allowed to use greater and less for Java datatypes or JavaScript will compare references?
For what Java datatypes greater and less could be used in the actor JavaScript without doubt?

**Comment by yuvalp-k2view** [comment]
Fabric uses the Java JS Nashorn engine.
For anything that is a Number, Nashorm will compare the numeric values correctly.

However, for all other Java objects I could test, Nashorn will compare the String representation of the object (toString()).

This means that for java Date objects, the comparison is not correct and you should instead compare the getTime() result of the Date objects.
