### ISSUE TITLE
Function to be used by several WebServices

### ISSUE THREAD

**Issue by IvanKostyuk** [k2view-academy/K2View-Academy#306]
There are several webservices in different packages/categories which share the same logic. The logic can be extracted into separate function, but this function belongs only to WebService (lu_ws). The added function appears as a webservice even annotations says it is **@type(LudbFunction)** and there is no annotation **@webService**
![image](https://user-images.githubusercontent.com/17881160/127929469-2e8fd6e5-49a6-4686-9a99-5d4a8dd9c1fe.png)

When the function is moved to new Java file under WebServices it does not appear in the tree (only the whole file).

How can a function be created in WebServices to appear in the tree and will not be treated as a WebService (and better in a separate file)?

**Comment by eyalk2** [comment]
A java aimed to be used for web service shall extends "WebServiceUserCode"
any function there shall have the "@webService" annotation.

Does your example follow this?

**Comment by IvanKostyuk** [comment]
Java file/class which implements web services extends WebServiceUserCode and all webservices have the annotation "**@webservice**". The question is about a function, which is used by many web services from different classes.
I'm trying to avoid coupling between different groups of web services (this is why I want to move to different java file) and at the same time have access to the function from Studio (not to entire file, like to functions in other Logical Units (ref and user defined).

**Comment by eyalk2** [comment]
In such case you may put your function at "Shared Object" area, so you can reuse elsewhere
