### ISSUE TITLE
Limiting output of Search queries 

### ISSUE THREAD

**Issue by venkatamedi** [k2view-academy/K2View-Academy#309]
Hi,
Is there any way to limit the output of the search results? 
I have a use case where we need to vend out only the top 50 rows based on the score. Trying to see if there is a better way rather than querying and filtering in java. 

Thanks
Venkata Medisetti

**Comment by mhanna** [comment]
There's a good references in the elasticsearch site
https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html
