### ISSUE TITLE
Asynchronous Transaction inside an LU population

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#311]
Hi, 
Is there a way to do an asynchronous transaction inside an LU population? 
When I try to do so, as shown in example below, I get an error saying _java.sql.SQLException: Exception in fnPopRoot(): java.sql.SQLException: can't change transaction mode inside a transaction! from population_ 

```
String insrtStmt = "INSERT INTO CUSTOMER(CUSTOMER_ID, SSN, FIRST_NAME, LAST_NAME) VALUES (123,0285974464,'ABC','XYZ')";

fabric().execute("set async_trx=true");

fabric().beginTransaction();

fabric().execute("get customer.123");

fabric().execute(insrtStmt);

fabric().commit();
```

**Comment by lionbro1** [comment]
Hi,

LU population is handled under a transaction, as it's part of the sync process, so running async_trx=true within a transaction is not possible, as it trigger a nested transaction that we don't support, it is mentioned on the following article:

https://support.k2view.com/Academy_6.5/articles/23_fabric_transactions/02_fabric_transactions.html

To resolve it there are two options:

1. Open another fabric local session within the population:
            For example :
                   openFabricSession(“fabric2”);
                   db(“fabric2”).execute(“set async_trx=true”);
                   etc...

2. Check if a trigger function can help to solve your case:

https://support.k2view.com/Academy_6.5/articles/07_table_population/11_4_creating_a_trigger_function.html
