### ISSUE TITLE
k2_delta_errors table missing issue on 6.5.0 for new instances

### ISSUE THREAD

**Issue by venkatamedi** [k2view-academy/K2View-Academy#314]
Hi, 
We are working on 6.5.0 (iid finder solution with partition delta) and we noticed that we are getting k2_delta_errors exception that it cannot identify the table and continuously failing. We had to stop the fabric and delete the jobs and restart the fabric to stop the exception. 

We understand that the issue is resolved in 6.4.4 but is there a fix on the 6.5 and above version? If the fix is available on the 6.5 above version please let us know which version to use. 

Thanks.

**Comment by tahata1** [comment]
Hi Venkata

We are not sure if the fix was added to 6.5.x or not, and the developer is on leave.
I'm closing this item, please open a freshdesk ticket and it will be handled through that channel.
