### ISSUE TITLE
Cassandra encryption at rest

### ISSUE THREAD

**Issue by JohnH-K2View** [k2view-academy/K2View-Academy#315]
Do we have any recommendation for using Cassandra transparent data encryption?
Reference: https://docs.datastax.com/en/security/6.7/security/secEncryptTDE.html

**Comment by greg-k2view** [comment]
Hi John, 

Could you provide more details about the need for this ? Is it for Fabric operational DBs or for external sources or targets connected to Fabric  ?

We are not using this, since fabric already has the option to encrypt the blobs kept in Cassandra.
