### ISSUE TITLE
BROADWAY_LU_POOL_SIZE parameter

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#316]
What does the BROADWAY_LU_POOL_SIZE param in config.ini do?

**Comment by tahata1** [comment]
This is the number of compiled instances of a flow in the memory. 
An example: if this parameter is set to 10 and you will run a flow ABC 20 times, at the end of the run, the memory (pool) will have 10 compiled instances of flow ABC for reusing in future.
Using this parameter saves flow compilation time.
