### ISSUE TITLE
TDM 7 - masking primary key columns

### ISSUE THREAD

**Issue by AlexMaziya** [k2view-academy/K2View-Academy#317]
When one of the fields we need to mask (Extract process) is part of the primary key and also included in the TAR tables for purging, how do we handle that?

**Comment by taliei** [comment]
Hi.

I assume that you refer to the delete of the entity from the target by  'purging'.

You can mask the data by the last executed LU table population if the masked field is used as a link field between the LU tables.
See the attached example: the last population of TAR_ACTIVITY table - populationCustomerMaskSSN flow - masks the SSN field of the CUSTOMER LU table:

![CUSTOMER_Masking_Examples](https://user-images.githubusercontent.com/43947470/131690488-cef68123-153f-4761-a5c4-3868fa2a9620.PNG)


Regards,
Tali
