### ISSUE TITLE
How to create custom non-db interfaces?

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#319]
Hi, I have the need of accessing a SOAP service from Fabric. For such, a SSL context has to be defined on Java code in order to ensure certificate validation. For keeping interface details like username, password, truststore, keystore, key etc. I would like to setup a new "HTTPS" interface that mix the params from HTTP but also the SSL-related params found on "KAFKA" interface. I don't intend to use "CUSTOM" interface's data as it is open. Please advise. Thanks.

**Comment by greg-k2view** [comment]
Actually the data field of the custom interface does allow you to add all the details necessary to your connection. Moreover the password field of the custom interface is fully encrypted. 
You can therefore use this interface to connect to the SOAP service intended.

In addition, you can define as many custom interfaces as needed to store the credentials and parameters in the password field (encrypted) and relate to these custom interfaces from your project
