### ISSUE TITLE
grant permission to roles

### ISSUE THREAD

**Issue by tarikh03** [k2view-academy/K2View-Academy#321]
according to grant command instructions, there is an option to use filtering query.

 Filtering query will come right after the <LUT> e.g. GRANT READ ON <LUT> WHERE <COLUMN_NAME>='<VALUE>'

Could you please provide an example? how would <COLUMN_NAME>='<VALUE>' look like?

**Comment by lionbro1** [comment]
Hi Tarik,

WHERE statement is not supported from fabric 5 and on (since we removed the MPP functionality).

We will open internal ticket to fix the help accordingly.
