### ISSUE TITLE
TDM 7 sequences functionality

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#322]
Hello, 

According to what I read from support wiki , there are mainly 2 ways for sequence implementation
1> https://support.k2view.com/Academy_6.5/articles/19_Broadway/actors/08_sequence_implementation_guide.html  -- using the maskingsequence actor
2> https://support.k2view.com/Academy_6.5/articles/TDM/tdm_implementation/11_tdm_implementation_using_generic_flows.html#:~:text=Step%202%20-%20Create-,Sequences,-Sequences%20are%20required   -- using the tdmseqlist actor 

I am trying to understand the motivation behind these two methods to implement sequences .  As I understand it the second method is simply an automation of method 1 unless I am missing something.  Please let me know if there are specific use cases which are solved using tdmseqlist which are not solved by the maskingsequence actor. 

 Also, within the link https://support.k2view.com/Academy_6.5/articles/TDM/tdm_implementation/11_tdm_implementation_using_generic_flows.html#:~:text=Step%202%20-%20Create-,Sequences,-Sequences%20are%20required  , it mentions run the createSeqFlowsOnlyFromTemplates flow only once per TDM implementation,  this is difficult since new flows for tables , new LUs or seq details are changed from time to time in a project. Please clarify. 

Also what are the effects when the flow createSeqFlowsOnlyFromTemplates is run multiple times in a project , has it been observed if there are any problems with running it multiple times.

Regards,
Prathamesh

**Comment by taliei** [comment]
Hi.

The createSeqFlowsOnlyFromTemplates.flow has two Inner Flows that first create a Broadway flow for each sequence in TDMSeqList Actor and then create an Actor from each flow. The generated sequence flows invoke the MaskingSequence Actor to get the new sequence value and populates the source and target IDs in the TDM_SEQ_MAPPING table under the k2masking keyspace.

I've updated https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.5/articles/TDM/tdm_implementation/11_tdm_implementation_using_generic_flows.md to clarify the logic.
The support site will be refreshed with the changes today EOD.

Thanks,
Tali
