### ISSUE TITLE
TDM 7.1 API regularTasksByUser description clarification

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#323]
Hello Tali,

see link -- https://support.k2view.com/Academy_6.5/articles/TDM/tdm_gui/TDM_Basic_Task_Execution_APIs_Flow/02_get_task_list_API.html

Consider that there are 3 environments defined in the GUI DEV, QA , PROD , all 3 are source and target env. ( env type BOTH) 
In the description, of the API ,  
Get all active extract tasks that do not require special permissions if the user has at least one Read TDM Environment role. 
So if a user John is added as READ on DEV , should he be able to see tasks from all 3 envs ? 
Also with regards to " special permissions " what are these special permissions, Please elaborate.

Regards,
Prathamesh

**Comment by taliei** [comment]
Hi.

If the user has a read role at least on one TDM environment, then he can view extract tasks of all TDM environments and execute the task on their environment.
For example- 
If the user has a Read role on DEV only, they can also view extract task created on PROD. However, the user can only execute the extract task on DEV environment.

I've updated the article on GitHub. The support site will be refreshed with the changes today EOD.

**Comment by prathameshpalaskark2view** [comment]
ok Tali . what about the  " special permissions " in the description of the API ?

**Comment by taliei** [comment]
Hi.

I've added an explanation about the special permissions to the item. In addition, I've added a link to the TDM Environment role's permission item for additional information. See the updated item: 

https://support.k2view.com/Academy_6.5/articles/TDM/tdm_gui/TDM_Task_Execution_Flows_APIs/02_get_task_list_API.html

Tali
