### ISSUE TITLE
is MethodType.DELETE supported in 5.4.7

### ISSUE THREAD

**Issue by tarikh03** [k2view-academy/K2View-Academy#324]
MethodType.DELETE is not allowed in 5.4.7

we are getting "HTTP Status 405 - Http method DELETE is not supported by this URL"

we tried both add and set response header but still it doesn't work:

setCustomResponseHeader("Access-Control-Allow-Methods","DELETE");
addCustomResponseHeader("Access-Control-Allow-Methods","DELETE");

execute:

curl -u 'admin:admin' -X DELETE --header 'Accept:application/json' "https://<customer URL>/api/wsDeleteTicketActivity?token=123&ticket_number=123457&format=json"

get:
<!DOCTYPE html><html><head><title>Client Error</title></head><body>HTTP Status 405 - Http method DELETE is not supported by this URL</body></html>

**Comment by lionbro1** [comment]
Hi,

DELETE verb is supported from fabric release 5.5 and on.
