### ISSUE TITLE
Information MaskingwithCollection actor

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#328]
Hello,

The maskingwithCollection actor describes its input as any collection of objects . Thus far, I have experimented with strings, integers as input the actor worked fine. Now, when the input type is object itself , it did not work as expected, meaning masking did not happen as well as no errors. Looking for information if only types such as string, integers are supported or other user defined object types are supported as well.

Regards,
Prathamesh

**Comment by tahata1** [comment]
Hi Prat,

Please send us more details about your scenario, or send us your implemenation
It would be better if you set a call today or tomorrow with me and Pavel Leonov to discuss it

**Comment by lionbro1** [comment]
As this is not a Q&A, ticket should be tracked on freshdesk.
