### ISSUE TITLE
mapbuild flushing

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#329]
Hello,

Is there any way to flush the mapbuild actor

Regards,
Prathamesh

**Comment by natalylic** [comment]
Hello Prathamesh,
Please elaborate on the use case that need to support. 
If you're referring to [Reset Actor State](https://support.k2view.com/Academy_6.5/articles/19_Broadway/32_reset_actor_state.html) functionality, the MapBuild doesn't aggregate the data across multiple executions (loop), thus it doesn't need to be reset.

**Comment by lionbro1** [comment]
Hi Prat,

As no response, we assume Nataly's answer is accepted.

Let us know otherwise, meanwhile closing Q&A.

Regards,
Lion
