### ISSUE TITLE
3rd Party Libraries - compile and run time

### ISSUE THREAD

**Issue by IvanKostyuk** [k2view-academy/K2View-Academy#330]
Currently there is only one location for all 3rd party libraries needed for a project:
`{project_home}/lib`

There is a special rule for interfaces - interface name should match directory holding jars. For a project with a bit more dependencies lib directory turns to unmanageable landfill. Some libraries are required only during run time (when logic is executed) and many in compile time (right before/during deploy). Compile time should not be deployed, but it is very difficult to differentiate which one is for what.

How can this be done? Is there any **BOM** for compile and run time which can be maintained in Fabric?

**Comment by eyalk2** [comment]
As discuseed we plan to have a support of Maven for fabric project implementation, that might help to manage it.
