### ISSUE TITLE
Graphit: all the acceptable sql non-prepared commands.

### ISSUE THREAD

**Issue by AlexMaziya** [k2view-academy/K2View-Academy#331]
Is there a documentation for all possible non-prepared commands we can use in graphit on fabric?
What are all the exceptions for such operation (_delete instance_ for example etc)?

**Comment by greg-k2view** [comment]
Hello,

Actually best is to always use SQL-prepared statements as explained here: https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.5/articles/15_web_services_and_graphit/17_Graphit/03_graphit_node_types.md

Note that non-prepared statements should be used only when you need to parse metadata parameters such as table names or fields names in Graphit, as detailed here:
https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.5/articles/15_web_services_and_graphit/17_Graphit/06_using_graphit_files_with_parameters.md#how-do-i-parse-metadata-parameters-such-as-table-names-or-fields-names-in-graphit-sql-
