### ISSUE TITLE
set env as _dev on deploy 

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#332]
Hello,

Is there a way to set the environment as _dev through the environments deploy of studio or any other mechanism ? This question is for a way through studio, dont need steps to set _dev through fabric server.
![image](https://user-images.githubusercontent.com/46533104/137012296-306a0f31-896e-466e-a633-d539788474e0.png)

Regards,
Prathamesh

**Comment by lionbro1** [comment]
changing environment back to _dev can be done only on server side by using 
set_global environment='';
as mentioned on the following article.
https://support.k2view.com/Academy_6.5/articles/25_environments/05_set_and_list_commands.html
it can't be done on Studio.
