### ISSUE TITLE
Information regarding enable_sequences global

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#336]
Hello,

I recently came across the global enable_sequences being used in the project and was wondering why its used. Can you also let us know what the difference between TDM_REPLACE_SEQUENCES and this enable_sequences global ? 

Regards,
Prathamesh

**Comment by tahata1** [comment]
enable_sequences is used by Broadway's internal MaskingSequence Actor, the actor will mask the input only if this session variable is set to true.
In TDM we set this variable based on the TDM_REPLACE_SEQUECES global.
BTW, the rest of the masking actors have a different session variable - enable_masking, which we also set in the TDM based on the TDM global MASK_FLAG
