### ISSUE TITLE
Parameter handling tdm gui screen question

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#338]
Hello,

In the tdm gui, load task, one option is to use parameters, on the parameters screen, I see the following line, 
For dates use the following format: 'YYYYMMDD'

What is the meaning of above line ? I went through our documentation and found this link ( https://support.k2view.com/Academy_6.5/articles/TDM/tdm_gui/18_load_task_requested_entities_regular_mode.html#:~:text=Date%2C-,populate,-the%20value%20using )  which basically repeats the same sentence to use date in specific format.

Earlier I thought it meant that if column value in an LU was date then it should be stored in the 'YYYYMMDD'  format through the trnluparams query , but on re reading the documentation my understanding seems to be wrong since we see below snapshot on our documentation page displaying date in a different format.

![image](https://user-images.githubusercontent.com/46533104/137998506-ddf07909-7d61-435b-be74-50fd5bed1888.png)

Please let me know your thoughts.

Regards,
Prathamesh

**Comment by tahata1** [comment]
Hi 
The date params should have values same as they have in the original table.
We will check if we can unify the date formats, I'll open a ticket in TDM's Trello
