### ISSUE TITLE
Mark LUT to be not compiled nor deployed

### ISSUE THREAD

**Issue by IvanKostyuk** [k2view-academy/K2View-Academy#339]
When working with libraries (creating or using), there are some LUTs which should not be deployed (in some cases not even attempted to be compiled). What flag or stop-/ignore-file should be set on LUT to prevent from accidental deployment?
Preferably not even to compile it.

Those LUTs are used as templates (similar to Broadway actors and flows).

**Comment by lionbro1** [comment]
Hi,

There is no way to disable LU from deployment or compilation.

Anyway if LU fails on compilation it doesn't prevent you from deploying the other LUs.

When moving to Fabric 7 (web solution), you will be able to disable the compilation/deployment by a pure json setup.

Regards,
Lion
