### ISSUE TITLE
Masking question

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#340]
Hello,
Quick question regarding the masking cache tables. In pretty much all of DB2 customer details like name and address will be in all caps, like "JOHN" while in many of the distributed systems they will be in normal presentation case ("John"), and in some situations like logins they will be almost always in lowercase ("john.smith"). Using the masking cache, would JOHN, John, and john all be masked to the same value, or would they be seen as different and masked to separate values?

Regards,
Prathamesh

**Comment by tahata1** [comment]
Hi
Masking is case sensitive, therefore "JOHN", "john" are masked differently
