### ISSUE TITLE
Will the common tables data remain, if we change the cluster_id in node.id file of an existing project?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#355]
Hi,
We have deployed a project to fabric server. We loaded some data into reference tables and now the team wants to update the cluster_id in node.id file. From what I understand, after updating cluster_id and restarting Fabric cluster, the previous keyspaces with older cluster_id will still remain. New keyspaces with updated cluster_id will be created only after deploying again. 
But does it retain the data stored in common tables or do we need to deploy the references as well and resync them?

**Comment by lionbro1** [comment]
Hi,

The common tables will remain, you just need to re-deploy.

However there are many other areas that can be impacted, such as iidFinder, etc..

So if possible clean the environment before changing the cluster_id.
