### ISSUE TITLE
Batch process was found but can't be resumed - error on batch_retry

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#371]
Hello - customer reported to me the following error when they try to reprocess batch with command

batch_retry '62c5dd28-1d71-412b-b378-d2a66ca70e71';

>>>
Batch process id 62c5dd28-1d71-412b-b378-d2a66ca70e71 was found but can't be resumed
>>>

We can see that this batchId has status "DONE" (according to batch_summary '62c5dd28-1d71-412b-b378-d2a66ca70e71';)

and it has reported 659 failures - so expectation was that batch_retry would reprocess failed instances.

They are running on local laptop env, version 6.5.2

Could you please let me know when we might see this error and if there is any way to work around it?

**Comment by lionbro1** [comment]
Hi,

These kind of issues should be tracked on freshdesk.

The system behavior for batch_retry is to reprocess the failed entities and processing the unhandled entities.

Regards,
Lion
