### ISSUE TITLE
deploy.flow TDM information

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#374]
Hello,

Please add FAQ for what is  the purpose of  deploy.flow in TDM and  if applicable why its not recommended to have soft deploy enabled for it. 

Regards,
Prathamesh

**Comment by taliei** [comment]
Hi.

The TDM deploy flow runs validations on the TDM execution environment and creates the k2masking keypsace if needed.

The soft deploy enables deploying the TDM LU to the debug server without stating the TDM jobs to avoid a situation when both servers- the debug and the execution server- run the TDM jobs on the same TDM DB.

For more information about the deploy.flow and the soft deploy of the TDM LU see https://support.k2view.com/Academy_6.5/articles/TDM/tdm_implementation/04_fabric_tdm_library.html

Regards,
Tali
