### ISSUE TITLE
TDM detailed and summary html reports information

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#375]
Hello,

Asking this on behalf of a client,  what is the purpose behind keeping both html and excel reports available for download in the TDM GUI ? 
As far as I understand all the data present in html is also present in excel report.

Regards,
Prathamesh

**Comment by taliei** [comment]
Hi.

The TDM provides 2 levels of task execution reports:
1. LU level (HTML format for extract tasks)
2. Execution level - summarizes the execution of all related LUs.

Note that the execution level report only contains the list of the root entity IDs and the LU level report contains the list of the LUs entities.

Attached is an example of reports for an extract task that contains Customers, Collection, Billing, and Ordering LUs. See the execution level summary report that also contains general information about the task and the Collection LU report which focuses on the Collection LU execution details.

[Downloads.zip](https://github.com/k2view-academy/K2View-Academy/files/7682907/Downloads.zip)


Regards,
Tali
