### ISSUE TITLE
KAFKA interface with SASL

### ISSUE THREAD

**Issue by alexmessel** [k2view-academy/K2View-Academy#376]
Hi, 

the Fabric 6.4.3 allows to use SASL s security protocol. It requires user/password but interface definition screen doesn't have place for this information. How can we supply user/password for KAFKA with SASL in 6.4.3?

![image](https://user-images.githubusercontent.com/45825146/145470162-87b3e47d-ab52-45af-89bc-cccb9a961959.png)

**Comment by lionbro1** [comment]
Hi,

The user/password on the Kafka interface for SASL was added on release 6.4.4

https://support.k2view.com/Academy_6.5/Release_Notes_And_Upgrade/V6.4/Fabric_Release_Notes_V6.4.4.pdf

https://support.k2view.com/Academy_6.5/articles/24_non_DB_interfaces/03_kafka_interface.html
