### ISSUE TITLE
READ ONLY request to LUs for a user

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#377]
Hi,

I created a new role, dev, with READ permission on Test LU and a new user, dev1, and assigned dev role to dev1. I am still able to add/update LUIs of Test LU when logged in as dev1 user. Is this an expected behavior? If so, how can I restrict a user to only be able to read data from Fabric but not update/modify any LUI?

![image](https://user-images.githubusercontent.com/66338066/145874318-5880eadc-6329-4e35-b7e1-3d6145b469e5.png)

**Comment by smokyMount** [comment]
I tested this on v6.5.3.

**Comment by smokyMount** [comment]
It was tested both on local as well as the remote server and both had same behavior. I was able to add new LUIs or update existing ones for the User with READ permission.

**Comment by greg-k2view** [comment]
Can you please ensure that when you add or update LUIs, it is done from an environment where the user with restrictions is logged on ? (from the admin panel, just logout and login again with the user dev1 and its password
