### ISSUE TITLE
Details on how to implement recursive parsing of a JSON using broadway

### ISSUE THREAD

**Issue by ghassantoumiek2** [k2view-academy/K2View-Academy#379]
please provide details on how to implement recursive parsing of a JSON using broadway

**Comment by natalylic** [comment]
Please find attached the sample implementation for loading the recursive JSON into a DB table.
It includes 2 flows:
•	The first flow JSON_parser_test parsers the JSON file -> company-sample.json.
•	The second flow JSONRecParser invokes itself recursively until the department structure is null. 
![image](https://user-images.githubusercontent.com/62207927/146389592-848fac45-4883-4755-b9cb-7188c4850258.png)
![image](https://user-images.githubusercontent.com/62207927/146390622-bd069f91-b4d6-448c-abe6-81e40aa7d221.png)
