### ISSUE TITLE
Connection Pool Idle Timeout

### ISSUE THREAD

**Issue by JohnH-K2View** [k2view-academy/K2View-Academy#380]
For Fabric interfaces, we set min & max connections.  Is the idle timeout configurable (how long a connection may be inactive before fabric will close it and reduce the pool size)?

When starting a new cluster, we observed the max_connections were initially opened to Oracle (not connections). Is this expected? If so, when is the min_connections archived by the system?

**Comment by greg-k2view** [comment]
Hi, Idle timeout can be configured from Fabric studio, by:
- writing clicking on *Database Types* folder under Shared Object
- Select the New Database Type option (from template or not)
- Expand the *Pool Properties * folder
- Modify the *Min Evictable Idle Time Millis* to the requested value

**Comment by smokyMount** [comment]
What is the default value of idle time out for an Oracle interface when it is not created from Database Types but the default Oracle interface?

**Comment by greg-k2view** [comment]
Default Oracle timeout will be as per JDBC driver spec: it looks like it is set up to 600000 milliseconds.

c.f.: https://docs.oracle.com/cd/E57185_01/ESTUG/apbs02s23.html
oracle.jdbc.ReadTimeout
Configure this property in the server.properties file:
Read timeout while reading from the socket. Timeout is in milliseconds.
If you are using Oracle data sources and are experiencing frequent timeouts, you can increase the value of this option by adding an entry to the server.properties file.
The default value is 600000 milliseconds.
Syntax
oracle.jdbc.ReadTimeout=milliseconds
Example
oracle.jdbc.ReadTimeout=900000
