### ISSUE TITLE
More information for TDM GUI API execution.

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#381]
Hello,

After introduction of fabric 6.5.3 , it requires the fabric role to have QUERY_WS permission in addition to the previous ALL_WS permissions.  Can you add to the page (https://support.k2view.com/Academy_6.5/articles/TDM/tdm_gui/TDM_Basic_Task_Execution_APIs_Flow/README.html) or any relevant section the required role permissions such as ALL_WS, AUTHZ_CLAIMS, QUERY_WS as pre requisite for calling tdm apis ? 
What is the motivation behind introducing QUERY_WS into the product ? I know what it does (https://support.k2view.com/Academy_6.5/articles/17_fabric_credentials/01_fabric_credentials_overview.html ) but not why its been introduced now. 
Regards,
Prathamesh

**Comment by taliei** [comment]
Hi.

Why do you have to add QUERY_WS permission? I've created a new user and assigned it to a newly created Fabric role that has ALL_WS. Then I could connect the TDM GUI.

Thanks,
Tali
