### ISSUE TITLE
API encoding charset question

### ISSUE THREAD

**Issue by rhcp20004** [k2view-academy/K2View-Academy#382]
Hey,

I would like to know in what encoding does the API uses,
Since, posting a request in the swagger returns the values as "null" within the UTF-8 encoding, I would like to know what alternatives could we use.

**Comment by lionbro1** [comment]
Hi,

please read the following article and let us know if it answers your question

https://support.k2view.com/Academy_6.5/articles/15_web_services_and_graphit/16_rest_api_additions.html
