### ISSUE TITLE
Masking Sequencing information during cloning

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#383]
Hello,

Suppose I have the following scenario in TDM 7.1
an LU which contains both masking and maskingwithcollection actors (example ADDR)  , and I run a task which does cloning 10 times. 
All 10 times the maskingwithcollection actor ADDR returns unique/new values even if the usexecutionId  and useenvironment  and useinstanceid is marked as false. 

I was not expecting this behaviour since its not a maskingsequence actor.  How is it working behind the scenes ? If I request for 10 clones , is it creating 10 duplicate entities of the original entity , doing a get on these 10 entities and then loading to the target env ? 

Could you please explain if the maskingwithcollection actor is expected to generate new masked values during cloning operation. 

Regards,
Prathamesh

**Comment by taliei** [comment]
Hi.

TDM 7.2 and below create a new LU instance on each clone. Each clone is kept as a separate instance in Fabric. Therefore the masking actors in the LU population generate a new value on each clone assuming the userInstanceID input parameter is true.

TDM 7.3 changes this behavior and creates only one instance in Fabric to avoid duplication of data in Fabric.  Therefore, when upgrading the TDM to 7.3, you need to add the masking actors to the load flows as well to get different masked values on each clone.

For more information see-
https://support.k2view.com/Academy_6.5/Release_Notes_And_Upgrade/TDM-V7.3/TDM_Upgrade_Procedure_to_V7.3.pdf.html

https://support.k2view.com/Academy_6.5/articles/TDM/tdm_implementation/11_tdm_implementation_using_generic_flows.html

Regards,
Tali
