### ISSUE TITLE
PARSER RESTART status

### ISSUE THREAD

**Issue by alexmessel** [k2view-academy/K2View-Academy#384]
What can cause PARSER to go to RESTART state?
support.k2view.com states that it is RESTART means JOB was actively restarted, but we know for sure no such command was issued.

Is there any other cases when Fabric restarted PARSERS?

**Comment by venkatamedi** [comment]
I noticed when a job is actually running (IN PROCESS) and if we deploy - the job is going to RESTART mode and eventually it is going to  IN PROCESS mode.

**Comment by lionbro1** [comment]
A trigger for a job restart can happen in the following scenarios:

1. node was restarted
2. restart was triggered manually
3. Running a deploy while job is already running
