### ISSUE TITLE
How to get connection pool metrics on New Relic?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#385]
The customer is looking to get metrics that show how many connections are open for an Interface using New Relic. Is there a way to get this information for monitoring?

**Comment by yuvalp-k2view** [comment]
Fabric exposes operation metrics using JMX.
You can find the full list of metrics in the web Statistics app.
Specifically, jdbcActiveSessions and dbcIdleSessions monitor interface connections.
