### ISSUE TITLE
How to handle schema changes in TDM , any best practice for it.

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#386]
Hello,

I wanted to know if we have any best practice when in TDM projects , the schema name changes when the user connects to a different env or db. 
Scenario, I have a LU named CUSTOMER connecting with schema abc in dev env,  later I need to  use prod env and the schema name there is xyz. 
Using synonyms the problem for extracting LU is solved when working with different envs, but in the load and delete flows , in the dbload and dbdelete actors, there is an option for schema input. This schema input is not affected by synonyms and the actors uses the schema thats populated in its input in all environments. 

My current solution was changing the schema link type from Const to link, and then populating it by means of a function or a javascript actor. Please let me know if there is any better recommendation in such a case.

Regards,
Prathamesh

**Comment by taliei** [comment]
Hi Prathamesh.

If you have synonyms on your DBs, then you can use the environments: the load and delete flows run on the target env.
If you do not have synonyms on your DB- you can add an Alter session inner flow to the beginning of the LoadAllTables and DeleteAllTables flows. The Alter session flow can get the schema name from a global (set a different value on each environment  if needed) and activate a DbCommand actor with the following command:
ALTER SESSION SET CURRENT_SCHEMA=<schema name>
The schema name is taken from the global variable.

Regards,
Tali
