### ISSUE TITLE
Fabric accessing /etc/ld.so.conf and /etc/ld.so.conf.d/* files & security

### ISSUE THREAD

**Issue by JohnH-K2View** [k2view-academy/K2View-Academy#389]
A scan from the RASP security tool being implemented by a client found read requests going to one of their watched directories: 
/etc/ld.so.conf
/etc/ld.so.conf.d/bind-export-x86_64.conf
/etc/ld.so.conf.d/dyninst-x86_64.conf
/etc/ld.so.conf.d/kernel-3.10.0-1160.21.1.el7.x86_64.con
/etc/ld.so.conf.d/kernel-3.10.0-1160.24.1.el7.x86_64.conf
/etc/ld.so.conf.d/kernel-3.10.0-1160.31.1.el7.x86_64.con
/etc/ld.so.conf.d/kernel-3.10.0-1160.36.2.el7.x86_64.conf
/etc/ld.so.conf.d/kernel-3.10.0-1160.42.2.el7.x86_64.con
/etc/ld.so.conf.d/mariadb-x86_64

Do we expect Fabric to make such read requests and need to configure RASP to allow this access? Or will blocking the access not effect Fabric operation? The RASP security config default proposed by the security team would block these reads.

Reviewing the files, they seem to not have any relevant information, most are placeholders only with comments, or are referencing libraries we don't think fabric is using.

**Comment by gabiochman** [comment]
Hi @JohnH-K2View 

The id.so ind and load the shared objects (shared libraries) needed by a program, prepare the program to run, and then run it. Linux binaries require dynamic linking (linking at run time) unless the -static option was given to ld(1) during compilation. (see [here](https://man7.org/linux/man-pages/man8/ld.so.8.html ) ).

I don't see why the RASP should block Fabric access to it.
