### ISSUE TITLE
Fabric - Calling SOAP/XML web services - Idiom

### ISSUE THREAD

**Issue by fabiocorreak2view** [k2view-academy/K2View-Academy#39]
Hi, what is the idiomatic way of calling SOAP/XML web services from Fabric?
Should I parse WSDL/XSDs using JAX-WS wsimport and work with the generated artifacts?
Where should the artifacts be stored within the Fabric tree?
Does Studio deploy such dependencies to Fabric server during deployment?
Thanks.

**Comment by lionbro1** [comment]
Fabric does not have a built in SOAP client or a preferred  library. Any standard Java SOAP client solution such as JAX or Axis is acceptable.
Any java code created and maintained in the Java/src folder is compiled and deployed as part of the build and deploy process.
