### ISSUE TITLE
CDC_TRANSACTION_PUBLISHER - Transaction has been dropped - exceeded the TRX_MAX_DURATION_SEC=300

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#399]
We are facing the below WARN flood in logs in fabric deployment that is configured with CDC feature. 

Could you please elaborate what should be set for this parameter TRX_MAX_DURATION_SEC in config and what it means/does?

WARN  2022-01-25 04:57:49,395 [LIDf40a000000000097] [JobPoolExecutorThread_CDC_TRANSACTION_PUBLISHER_11] c.k.f.c.d.CdcKafkaConsumer - Transaction Transaction{trxId='1bccbdf3-c8b7-4fcc-9740-b22680608f5a', luName='CUSTOMER', iid='291271828'} has been dropped - exceeded the TRX_MAX_DURATION_SEC=300
WARN  2022-01-25 04:57:49,399 [LIDf40a000000000097] [JobPoolExecutorThread_CDC_TRANSACTION_PUBLISHER_11] c.k.f.c.d.CdcKafkaConsumer - Transaction Transaction{trxId='4ceeff1b-f46c-4c23-ac5f-225f068e8d8c', luName='CUSTOMER', iid='138516325'} has been dropped - exceeded the TRX_MAX_DURATION_SEC=300
WARN  2022-01-25 04:57:49,401 [LIDf40a000000000097] [JobPoolExecutorThread_CDC_TRANSACTION_PUBLISHER_11] c.k.f.c.d.CdcKafkaConsumer - Transaction Transaction{trxId='fac91fea-562f-4ad8-a42f-b58d5581b2d4', luName='CUSTOMER', iid='138513379'} has been dropped - exceeded the TRX_MAX_DURATION_SEC=300
WARN  2022-01-25 04:57:49,429 [LIDf40a000000000097] [JobPoolExecutorThread_CDC_TRANSACTION_PUBLISHER_11] c.k.f.c.d.CdcKafkaConsumer - Transaction Transaction{trxId='50794c11-ac9e-4a02-bb7f-6b3e9219b280', luName='CUSTOMER', iid='291271827'} has been dropped - exceeded the TRX_MAX_DURATION_SEC=300
WARN  2022-01-25 04:57:49,553 [LIDf40a000000000097] [JobPoolExecutorThread_CDC_TRANSACTION_PUBLISHER_11] c.k.f.c.d.CdcKafkaConsumer - Transaction Transaction{trxId='0abe0a8f-bb21-452e-ad1f-7bac980cf61e', luName='CUSTOMER', iid='138527835'} has been dropped - exceeded the TRX_MAX_DURATION_SEC=300
WARN  2022-01-25 04:57:49,555 [LIDf40a000000000097] [JobPoolExecutorThread_CDC_TRANSACTION_PUBLISHER_11] c.k.f.c.d.CdcKafkaConsumer - Transaction Transaction{trxId='12b78b61-dcb8-4ade-bb44-ced0ff445cf4', luName='CUSTOMER', iid='291285861'} has been dropped - exceeded the TRX_MAX_DURATION_SEC=300

____________
Best regards,
         Andrey

**Comment by mhanna** [comment]
CDC is aware of the time the mdb changes occurs, and therefore avoid long running mdb transactions as a try to eliminate zombie transactions.

If you're ok with the time the transaction takes, then consider increasing TRX_MAX_DURATION_SEC to a bigger number in config.ini
