### ISSUE TITLE
Elastic search installation

### ISSUE THREAD

**Issue by AlexMaziya** [k2view-academy/K2View-Academy#40]
1. During elastic search installation do we need Kibana to be installed or not?
2. Elastic search will be installed as a k2view user? so is that ok or do we need to use a different user?

**Comment by lionbro1** [comment]
1. Kibana is not a must, it is optional if you want to have the ability to use graphic tool to monitor ES.
2. you can install with any user/pass you want, you just need to make sure you setup the search interface in Fabric accordingly. full implementation setup doc can be found under 
https://k2view.sharepoint.com/:w:/r/sites/KS/Releases/K2V%20Product%20Documents/Fabric/V6.1.xx/V6.1.0/Fabric_6.1_CDC_and_Cross_Instance_Search_Updated.docx?d=w6e7056f6f14843cf8607c06f4a995b5a&csf=1&web=1&e=6yoTT1
