### ISSUE TITLE
Renaming an LU

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#405]
After we have deployed and migrated data for an LU, is it possible to rename it? 
I believe if we rename the LU, fabric will consider it as a completely new LU Type. But can we copy the data from the older k2view_<original_lu_name> keyspace to the new k2view_<updated_lu_name> keyspace and access it from Fabric?

**Comment by lionbro1** [comment]
Hi,

We don't recommend this workaround, you can't rename LU,  you need to duplicate the existing one and sync data again. Just changing the keyspace name is not enough there are many other aspects to be considered, for example iidFinder if it's relevant to your project, LUI data encryption and many more.
