### ISSUE TITLE
Is it possible to produce WS YAML file as the WS documentation

### ISSUE THREAD

**Issue by dotants** [k2view-academy/K2View-Academy#413]
Hi

Is it possible to produce WS YAML file or other equivalent of the Swagger, that can server as documentation of WSs expoed on Fabric to users which do not have access to Fabric Swagger URL?

A YAML file can be loaded to an external Swagger editor (e.g. https://editor.swagger.io/) and provide the full WS documentation.

**Comment by lionbro1** [comment]
Hi,

Yes, use the following URL http://IP:3213/api

**Comment by dotants** [comment]
The question was if we can get a YAML or equivalent for users who do **not** have access to  http://IP:3213/api

**Comment by lionbro1** [comment]
You can run http://IP:3213/api by someone who has access and he can provide the outcome to whoever is needed. 

Or if you see no security issue, we added a new feature on 6.5.4 to define no auth on WS, so you can create a custom Web-Service that will call this API and define it with no auth.

**Comment by idopolak** [comment]
the response from the url is the json equivalent to yaml, you can just pass the response to the user.
