### ISSUE TITLE
Documentation for  transaltion trnmigratelist's  column external_table_flow

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#422]
Hello,

Can you please add Documentation for  transaltion trnmigratelist's  column external_table_flow . Specifically explain about how it allows external entity list to be passed and if possible to add the following screenshot, 
![image](https://user-images.githubusercontent.com/46533104/152039206-497b2ea4-2f87-4fbf-9dfe-27bc06f89ae4.png)

Currently, if I look through the release notes , documentation , I dont know the expected  structure of the bw flow that can be used in the trnmigratelist.

Regards,
Prathamesh

**Comment by taliei** [comment]
Hi.

The following article explains how to implement such a Broadway flow: https://support.k2view.com/Academy_6.5/articles/TDM/tdm_implementation/14_tdm_implementation_supporting_non_jdbc_data_source.html

I've added a link to this article in the trMigrateList instructions in https://support.k2view.com/Academy_6.5/articles/TDM/tdm_implementation/04_fabric_tdm_library.html

The link will be refreshed into the support site by today's EOD.

Regards,
Tali
