### ISSUE TITLE
consuming files as a source - ADI

### ISSUE THREAD

**Issue by AlexMaziya** [k2view-academy/K2View-Academy#43]
Can you please share the details, configuration and best practices for source as input file?

**Comment by lionbro1** [comment]
no sure i understand the request. we have parser in ADI, the way to use parser is documented on the user guide. Regarding to best practices, again not sure what are you looking for, you can define the files extension folder and in the EP define how many files will be processed in parallel. let me know if you are looking for a more specific reply.
