### ISSUE TITLE
Broadway actor FileWriter with buffer on Fabric 6.5.4

### ISSUE THREAD

**Issue by dotants** [k2view-academy/K2View-Academy#440]
Hi

when using Fabric 6.5.4 new FileWritter actor with buffer - 
(1) Is there a way to "flush" / "close" the file in order to guarantee the full file is on the disk?
(2) What is the FileWritter buffering behavior when using "SFTP" interface and not a local file - is it still buffered? Does the answer to (1) change?

Thanks
Dotan

**Comment by natalylic** [comment]
The **FileWrite** actor is reading the stream either by 8K or a by different buffer size (if defined). Once the stream ends, the file is flushed and closed automatically. The flow then moves to the next stage.
This behavior is consistent for any interface type - local file system or SFTP.

**Comment by natalylic** [comment]
Correction to the above answer: 
If the file open happens within a transaction, the file is closed when the transaction is complete.
If there is no transaction, the file is closed at the end of the flow.
