### ISSUE TITLE
how to Reset drop on an environment with several Fabric clusters on one Cassandra cluster

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#448]
Hi,

For an environment with several Fabric clusters on one Cassandra cluster, how do we do a reset drop for one of the Fabric projects? I tried running the "./reset.sh drop"  and it dropped keyspaces from other fabric projects as well.

**Comment by lionbro1** [comment]
Hi,

For the fabric cluster that you want to clean, you should run ./reset drop on one node and ./reset drop_local on the others.

You can read further on

https://support.k2view.com/Academy_6.5/articles/02_fabric_architecture/03_fabric_basics_getting_started.html
