### ISSUE TITLE
ADI DB connection handling

### ISSUE THREAD

**Issue by AlexMaziya** [k2view-academy/K2View-Academy#45]
Please share the details around ADI's DB connection handling. Retry count, timeout value, pool connection, etc. 
Do these values change based on the DB type (e.g. Oracle vs Cassandra)? How these values can be customized?

**Comment by lionbro1** [comment]
Hi,

Yes, these values setup is changed according to DB types and the related ODBC driver setup.
In order to override these parameters values you can use the relevant Interface custom server connection capability.
