### ISSUE TITLE
Set TTL for a Logical Unit

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#456]
Is there a way to set Time To Live (TTL) per LU so that the instances for that LU are automatically delete from Cassandra after the defined time has passed?

Eg: We want instances of an LUT to be deleted automatically 7 days after they were synced.

**Comment by lionbro1** [comment]
Hi,

An LUI TTL is defined in the session level, you can add a SET INSTANCE_TTL command as a part of the LU sync process. (in a root function or Broadway population, etc...)

You can read further on the set INSTANCE_TTL command on the following article:

https://support.k2view.com/Academy_6.5/articles/02_fabric_architecture/04_fabric_commands.html
