### ISSUE TITLE
When is the hashmap object cleared from memory when used in an LuFunciton in Broadway flows?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#466]
The hashmap object is returned as output of the LuFunction so we cannot clear it in the function. So, does it get cleared upon completion of the Broadway flow? Is it any different in case on an innerFlow?

**Comment by natalylic** [comment]
The LuFunction output is cleaned by the defined Java Garbage collector and it is not related to Broadway, as Broadway doesn't handle clearing the actors output.

**Comment by JohnH-K2View** [comment]
Can you clarify: if the output is linked to another broadway actor, it would need to ensure persistence until that next actor receives the object. Is GC restrained only until after all linked actors have started, and then the output object is eligible for GC? Or not until those linked actors complete?

**Comment by natalylic** [comment]
The actor output has a reference in the flow until the flow is done, so will be pick by garbage collector after flow execution is done
