### ISSUE TITLE
setCustomResponseHeader not available in 6.1.1.

### ISSUE THREAD

**Issue by tarikh03** [k2view-academy/K2View-Academy#47]
In project customer is using setCustomResponseHeader(String,String) in WS.

setCustomResponseHeader is not available anymore in 6.1.1.

is response().setHeader(String,String) equivalent in 6.1.1? if not what could be used instead?

**Comment by lionbro1** [comment]
Hi,

The answer is yes, it was changed on release 5.5 and on, for more details you can refer to the relevant knowledge item

https://github.com/k2view-academy/K2View-Academy/blob/master/articles/15_web_services/16_rest_api_additions.md
