### ISSUE TITLE
Information regarding super user field on fabric UI users page

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#470]
Hello, 

Please see below screenshot, 
![image](https://user-images.githubusercontent.com/46533104/157279733-b5e4a005-175c-47cb-bc44-eddec39a5bf3.png)

I would like to know more details about the usage of this super user field and when to set it as true/false.  We seem to be missing its documentation, I checked the support site as well as the github , but could not find any relevant information when searching for super user. 

Regards,
Prathamesh

**Comment by natalylic** [comment]
When a user is created as a super-user, the role "admin" is assigned to it automatically.
Meaning, this user gets the permissions ALL and ALL_WS.
Note that if the "admin" role is revoked from this user, the users stops being a super-user.
