### ISSUE TITLE
Fabric- Supported CDC Messages

### ISSUE THREAD

**Issue by taliei** [k2view-academy/K2View-Academy#48]
What types of CDC messages are supported by Fabric? When each type of message is published by Fabric?

**Comment by taliei** [comment]
A specific CDC message is generated for each type of change on the CDC columns.

Fabric has the following CDC messages:
> CDC Schema- generated when an LU is deployed to Fabric for the first time.
> CDC Schema Update- generated when an LU is redeployed to Fabric or when an LU is dropped.
> CDC Delete Tables- generated when deleting an LUI or when executing the CDC_REPUBLISH_INSTANCE on LUI.
> CDC Table Change Info- generated when updating a MicroDB or when executing the CDC_REPUBLISH_INSTANCE on LUI.
More details and examples can be found under [CDC Messages Knowledge Item](https://github.com/k2view-academy/K2View-Academy/blob/master/articles/18_cdc_and_search/02_cdc_messages.md).

**Comment by JohnH-K2View** [comment]
Does CDC send any message in the case of delete instance? "delete instance LUNAME.id"

**Comment by lionbro1** [comment]
yes it does
