### ISSUE TITLE
Do we support "task chaining" 

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#480]
Hello,

Scenario - Suppose there are 4 tasks related to each other out of say 10 tasks on the TDM GUI. The tasks are based on multiple Business Entities , so its LUs could not be modelled as parent child lu hierarchy.  I was asked if we support "Task chaining" . Task chaining means to automate running the tasks automatically in a specific order example task3, then task2 ..finally task1.   I suggested to them to use task scheduler and it mostly solves their problem. I wanted to know if we have any such functionality where a task execution status of say task id 4 can be checked ,and if execution status is Processed , then trigger next task id 3. 

Thanks,
Prathamesh

**Comment by taliei** [comment]
Hi.

Currently, we do not support "Task chaining". Can you please elaborate more about the business use case of task chaining? A business grouping of data can be implemented with the Business Entity that can have multiple LUs. So, what is the business case of chaining different Business Entities in a specific order?

Thanks,
Tali

**Comment by prathameshpalaskark2view** [comment]
Hi Tali,

I agree that the use case is strange. I was told of a scenario where the different BE are chained together , but these BE dont have data links between them. Meaning, they dont have something like parent - child lu relationship that we use internal to a single BE.     

Example BE1 CRM , BE2 OMS  , so if we have 2 different extract/load/clone tasks associated with these 2 BE , the scenario that I understood them to be executing is  once CRM BE with all of its multiple LUs  is loaded for say Entity 100  , then after its execution, OMS BE task is triggered with Entity 200 and its loaded into all target systems associated with OMS BE.   The entities mapping between 2 BEs is not known in advance , but they were looking at the override parameters of ws starttask to execute it.  I think they were exploring product features not necessarily looking to utilize/implement it, and I thought of raising this Q&A , in case this was discussed in the past. 

Thanks,
Prathamesh
