### ISSUE TITLE
Can HTTP actor support SOAP calls?

### ISSUE THREAD

**Issue by dotants** [k2view-academy/K2View-Academy#483]
Can the Broadway actor HTTP support SOAP WS calls?

The article https://support.k2view.com/Academy/articles/31_external_resources/04_invoke_soap_call_example.html sows that Java function needs to be used.

**Comment by natalylic** [comment]
Yes, it supports SOAP. You must define Content-Type as **application/soap+xml** in the header.
See the example below which defines the Content-Type as well as the Authorization parameters. However if the Http actor is using a predefined HTTP interface, you don't need to pass the Authorization string. 
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/62207927/159519575-25fb01d0-e02a-4375-853a-7a748a110865.png)
