### ISSUE TITLE
Fabric 5.5 - How to incorporate full OpenAPI definition

### ISSUE THREAD

**Issue by ghost** [k2view-academy/K2View-Academy#50]
Hi, I see that Fabric, based on some of the web service attributes defined in Fabric Studio, derives an OpenAPI definition and lists it on its internal Swagger portal. Anyway, not all OpenAPI attributes are available and it seems that only the Example section can be manually provided.

How can I provide a complete version of the API's OpenAPI definition?
Is there any directory where I could put a manually edited file to be considered by Fabric?
If so, would this also be transferred to Fabric Server when web services are built and deployed?

Thank you.

**Comment by taliei** [comment]
K2view API REST full mechanism is fully integrated with the latest Open API (Swagger) platform. 
It supports presenting descriptions on API and input parameters level and gives the ability to provide examples of output structure before calling the API. 
For more information about Fabric's integration with Swagger, please refer to https://github.com/k2view-academy/K2View-Academy/blob/master/articles/15_web_services/09_swagger.md knowledge Item.
To learn more about additional configurations of REST API, see https://github.com/k2view-academy/K2View-Academy/blob/master/articles/15_web_services/16_rest_api_additions.md.

**Comment by fabiocorreak2view** [comment]
Thanks @taliei for the reply.
I checked the suggested academy articles but they don't address my questions.

**Comment by taliei** [comment]
Hi.

Please specify which information is needed for you? Unfortunately, your question above is quite generic- what do you mean by the complete version of the API's OpenAPI definition? Which file would you like to edit and locate under a directory? 

Thanks,
Tali

**Comment by feamcor** [comment]
Sure @taliei, please find it below. If not yet clear, let me know and I will contact you offline.

OpenAPI (ex-Swagger) is a ReST API [specification standard](http://spec.openapis.org/oas/v3.0.3), like XSD/WSDL is for SOAP APIs.

Fabric Server embeds [Swagger UI](https://swagger.io/tools/swagger-ui/), which provides API documentation and allows discovery and testing.

As such, I assume that when web services are built and/or deployed within Fabric, the latter generates one (or more) OpenAPI document(s) that describe all the APIs located within the current Fabric project, including the generic LU ones.

Usually OpenAPI's root document is called `openapi.json` or `openapi.yaml`.

- **Q1**: When is this file generated? Build or deployment?
- **Q2**: Who generates it? Fabric Studio or Fabric Server?
- **Q3**: Where is this file located?

I assume that Fabric generates OpenAPI documents based on the attributes present on Fabric Studio; e.g. web service name, category (tag), version, path, verbs and input parameter names, types, descriptions etc.

Also on Fabric Studio, there are three `Example` attributes (JSON, XML, CSV) that I assume would populate part of the `Components` object in the generated OpenAPI document.

All of that automation is excellent, but still the OpenAPI document is not as complete as it could be (e.g. with `schemas`, `responses`, `parameters`, `headers` objects and other attributes etc.), and depending on project requirements, we need to provide a detailed one.

- **Q4**: If a more detailed version of the OpenAPI document is created outside of Fabric, can it be added to Fabric Studio (e.g. as a resource) that then would replace the one that is automatically generated?
- **Q5**: If so, would be deployed to server also, as part of the deployment process?

I look forward to your comments.
Thank you.

**Comment by idopolak** [comment]
Hi @feamcor 

Thanks for your feedback on the OpenAPI, we would like to help with any requirements to get a more complete OpenAPI document, please share use cases or examples.

###  Questions 1 to 3:
The OpenApi spec is generated at the server side, every time the url http://fabricHost:fabricPort/api is invoke and the response body contains the OpenApi spec in json format.
To generate the json:
1. base json file in the config dir `FabricOpenApi.json `.
2. the `paths` is generated at runtime based on the deployed web services and added to the base file.

### -Questions 4 and 5:
The edit is limited to the file `FabricOpenApi.json ` the rest is generated at runtime from the web services annotations, input and output. so this limit the options.

> but still the OpenAPI document is not as complete as it could be (e.g. with schemas, responses, parameters, headers objects and other attributes etc.), and depending on project requirements, we need to provide a detailed one.
