### ISSUE TITLE
DATE FORMAT ISSUE

### ISSUE THREAD

**Issue by soniek123** [k2view-academy/K2View-Academy#504]
I have one sqlite query in that I am converting string to date, my string value is '31-DEC-99 11.59.59.999999 PM AMERICA/LOS_ANGELES' I need to change to date datatype  with this format  2099-12-31 , I have followed this link https://www.sqlite.org/lang_datefunc.html  but its didn't help me more  . Could you please help here.

**Comment by smokyMount** [comment]
Hi,

You can store these dates in the required format as new columns to the LU table itself and then use these new columns when selecting data from it.
