### ISSUE TITLE
Recovery point in Broadway when the flow is started using batch command

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#507]
Hi,

Does Fabric support recovery points in Broadway when the flow is triggered using batch command? If so, how can we use it such that instance of the flow that is triggered can have its own recovery point?

For example:
`BATCH  OracleLU FROM HIS_DB USING ('select patient_id from OracleLU where patient_id <= 1000') fabric_command="broadway OracleLU.SampleFlow SampleIID=?" with async=true;`

**Comment by natalylic** [comment]
The purpose of Broadway recovery point is to recover from crash (such as shortage) and not from failure due to exception.
To re-run the batch after failure occurred, use BATCH_RETRY command to resume a previous Batch process by reprocessing all failed or unhandled entities.
