### ISSUE TITLE
Fabric connection to cassandra

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#512]
Hello, 

In absence of any policy defined in cassandra interface in studio, what policy does fabric use in communication with cassandra ?  ( example DC-aware, token-aware policy )?

Regards,
Prathamesh

**Comment by greg-k2view** [comment]
Hello,

The following policies and default configurations are defined in the Fabric/Home folder of your project, under config.ini file:

**In particular the following entries are of interest:**

Cassandra retries policy [DEFAULT/CUSTOM]
#RETRY_POLICY=DEFAULT

Cassandra reconnect max delay in ms
RECONNECT_MAX_DELAY_MS=1000

Storage can be:
MEMORY/DISK/MDB/CASSANDRA/S3/AZURE_BLOB_STORE/NONE/
MDB_DEFAULT_SCHEMA_CACHE_STORAGE_TYPE=CASSANDRA

Compression algorithm to use when storing an instance in Cassandra. Possible values are : GZIP, LZ4 and NONE. Default is LZ4.
COMPRESSION=LZ4

Use Cassandra lightweight transactions for masking cache.
CASSANDRA_LIGHTWEIGHT_TRANSACTIONS=true

**Comment by smokyMount** [comment]
Do these apply to external Cassandra DBs as well or only the local one that Fabric uses for storage and application management?

**Comment by prathameshpalaskark2view** [comment]
Hi Hardik,  
Gregory is checking for our internal cassandra DB, I sent him an example  detailed article yesterday regarding driver policy settings used by Fabric application.
