### ISSUE TITLE
Security protocols

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#524]
Hello,

What security protocols does Fabric use ? Please see below for more details, 
What are the protocols that we communicate between components within K2View ?

Fabric – Cassandra
Fabric – Kafka
Cassandra – Cassandra (cross DC)
 
I did read all hardening related documents on our support site,  and it does mention TLS being used for Fabric to cassandra , SASL for kafka , but does not specify which version of TLS or SASL or any alternatives that are being used in this secure communication.

Regards,
Prathamesh

Regards,
Prathamesh

**Comment by eyalk2** [comment]
Securing the communication between components is done by using the TLS (where public certification exchange it part of it).
The TLS version is TLS v1.2
