### ISSUE TITLE
ADI setup with Fabric as a source

### ISSUE THREAD

**Issue by AlexMaziya** [k2view-academy/K2View-Academy#53]
What configuration needs to be done on ADI (and on Fabric side) in order to use Fabric as a source for LUDB table population. 
Globals/WS/tokens/config files etc.

**Comment by taliei** [comment]
Hi.

ADI server-
  > tdmConfig.ini- set [FABRIC_CASSANDRA_DATABASE_PARAMS]- set the host + set the compressMode to ZIP. Set the active parameter to true. See example:

[FABRIC_CASSANDRA_DATABASE_PARAMS]
dbType = "cassandra"
dbHost = "10.21.3.3"
dbPort = "9042"
dbUser = "k2admin"
dbPass = "~adi2q28n39Mc5WmOJyQLXl3ng==:9Sask5FbP4PnH5krnBwVig=="
active = "true"
compressMode = "ZIP"

> If you have a TDM project- you need to set the host in [FABRIC] section of the tdmCondfig.ini as well.

ADI Studio-
> Add fabricCassandra interface
> Add FABRIC_DEBUG_IP Global to the shared Globals to run the data viewer on Fabric. Populate the host of your Fabric server in this Global.
> Edit the [FABRIC_CASSANDRA_DATABASE_PARAMS] section of the tdmConfig.ini under C:\k2view\ADI Studio\PhpExt\k2ServerPro\config: set the host and set the active parameter to true.

Fabric server-
Edit the config.ini- set the INSTANCE_COMPRESION to DEFLATE: 
INSTANCE_COMPRESSION=DEFLATE

For TDM projects- create a token: tdm-WS, assign it to a role, and give permissions for all WS to this role.

Regards,
Tali

**Comment by AlexMaziya** [comment]
For Non TDM projects, do we need the following globals to be set?

TDM_REQUEST_OF_FRESH_DATA
TDM_SET_SYNC_OFF
