### ISSUE TITLE
Question related to apps.json properties

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#530]
Hello,

An example, apps.json that I came across during project is as follows,
{
      "name": "Discovery",
      "appId": "discovery",
      "hidden": false,
      "expand": false
   }

What does the expand tag mean in the above structure ? Are there any other tags that can be exposed for development purposes?

Regards,
Prathamesh

**Comment by lionbro1** [comment]
Hi,

The meaning of expend set to true is to display the application in a full screen mode without the top bar.
