### ISSUE TITLE
How to kill a job that is in STOPPING status after it was stopped?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#531]
Is there a way to kill a Job that is showing up in STOPPING status without doing a Fabric restart?  The kill command did not help nor does the stopjob.

My job has been in STOPPING status for past few days and keeps on printing that it is about to be killed in the logs but it never does.

**Comment by lionbro1** [comment]
Hi,

Job that is not responding to Java thread interrupt will be stuck in stopping status. 
It might happen while executing a logic against source (Kafka, rdbms) for a long period. If this job is part of the product, please open a ticket, if it’s your implementation, try to look for the piece of code that might ignore the interruption.
