### ISSUE TITLE
MD5Hashing Method in broadway

### ISSUE THREAD

**Issue by Sunithapasala1234** [k2view-academy/K2View-Academy#535]
Hi Team,

Please provide me a information on how do i create a MD5hashing function in the broadway flow. 

Regards,
Sunitha

**Comment by lionbro1** [comment]
Hi,

Have you considered using masking actors?
https://support.k2view.com/Academy/articles/26_fabric_security/06_data_masking.html
it even uses stronger algorithem than MD5.
