### ISSUE TITLE
How to delete multiple permissions from fabric admin

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#538]
Hello,

I want to delete multiple permissions for a given role from fabric web admin, see below,
![image](https://user-images.githubusercontent.com/46533104/168850630-a3631f39-49d9-4f8b-a7da-1401fe780107.png)

Now, if I have to delete 20 ws permissions from a given role, I have to click for each webservice, 3 dots on the left and revoke permissions. 
Is there any better way through the UI or theough console to delete multiple permissions at once ?

Regards,
Prathamesh

**Comment by lionbro1** [comment]
Hi,

The revoke command syntax only allows a 1 method, one resource, 1 role per command.
 
The GUI was designed to mimic the command (but allows to revoke multiple resources at once by sending multiple commands behind the scene).
 
As a workaround you can delete the role (and re-granting only what is needed…. it will be quicker but will also require re-assigning the role to any user/apikey.
