### ISSUE TITLE
How can I get IIDFinder properties (source schema) on an LU table population object?

### ISSUE THREAD

**Issue by taliei** [k2view-academy/K2View-Academy#54]
Hi.
 
We use addDeletedFinder rundeleteFinder APIs to delete irrelevant data from the IIDFinder cache tables. To do so, we need to send to the addDeleteFinder method the following parameters: LU name, LUI, source schema name + source table name properties, and key.
However, the source schema name may have a different value in different environments. For example- the schema name can be DEV in the development environment and PROD in the production environment.
How can we get the IID Finder properties like source schema name of the LU table population?

**Comment by taliei** [comment]
You can get the IIDFinder properties from the LU table population using the following steps:

1.  Get the information about the LU table object for the input LU table name:

    `TableObject table = ((TableObject)getLuType().ludbObjects.get(table_name));`

2.  Get the first Table Population object of the LU table:

   `TablePopulationObject populationObj = table.getEnabledTablePopulationObjects().get(0);`

3.  Get the sourceSchema from the IIDFinder properties (iidFinfderProp) of the LU table population:

   `String SchemaName = populationObj.iidFinderProp.sourceSchema;`

   

Note, that you can get all IID Finder properties this way. For example:

`String sourceTableKey = populationObj.iidFinderProp.sourceTableKey;`

**Comment by feamcor** [comment]
On Fabric 5.5.x getLuType is set as deprecated.
As such, project lists a few hundred warnings due to the use of deprecated methods.
What to use instead for all of the methods that according to user-api javadocs are deprecated?
Where to get documentation for the existing classes and objects not listed on user-api javadocs?
Thanks.
