### ISSUE TITLE
Javascript actor when variables used in it are not declared/defined

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#545]
Hi,

We have seen that Broadway doesn't produce any error or warning when a javascript actor is trying to refer to a variable that isn't defined as input or var declared within the javascript actor.  Is there a reason for this?  The customer reported seeing this a few times where the developer did this by mistake which caused unexpected results.

**Comment by natalylic** [comment]
In non-strict mode of JavaScript, an assignment to an undeclared symbol is implicitly treated as creating a global variable. This is how the JavaScript actor works and that is the reason why the error is not thrown.
However, if you have 2 undeclared variables in 2 JavaScript actors with the same name - they will override each other. 
Thus as a best practice - we recommend to use declared symbols in your JavaScript actors.
