### ISSUE TITLE
how to copy common tables data between nodes

### ISSUE THREAD

**Issue by lionbro1** [k2view-academy/K2View-Academy#548]
If common tables data in one of fabric cluster nodes is corrupted what is the procedure to overcome it?

**Comment by lionbro1** [comment]
you need to follow these steps

1. Sync one fabric node and stop it
2. stop relevant nodes
3. go to storage/common on the synced node, and make sure the .wal file doesn't exist or empty.
4. go to the relevant nodes storage\common and delete all files (3 at most)
5. copy common.db from the synced node to relevant nodes
6. on relevant nodes, for Kafka consumer group named as node id - move offset to end.
7. restart nodes.

**Comment by natalylic** [comment]
Starting from Fabric 7.0, the steps have been slightly updated. Follow the below steps:
1. Sync one fabric node and stop it
2. Stop relevant nodes
3. Go to storage/common on the synced node, and make sure the .wal file doesn't exist or empty.
4. Go to the relevant nodes storage\common and delete all files (depending on the number of schemas that you defined in Common DB)
5. Copy all the schemas of Common DB from the synced node to relevant nodes
6. Restart nodes.
