### ISSUE TITLE
Detect fabric Ip address from broadway flow

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#553]
Hello,

We have a use case where once a flow is triggered we would like to know the ip address of the fabric node thats working on this flow. 
Is there any internal fabric api that we can use for this purpose ? The client would like to reuse fabric internal mechanism rather than creating custom actor java code to get the ip address. 

Regards,
Prathamesh

**Comment by natalylic** [comment]
There is **clusterstatus** Fabric command that returns the status for all fabric nodes.
You can call this command from the Broadway flow using the DbCommand actor. The node which is used by a flow will be marked as "local node" in notes.
![image](https://user-images.githubusercontent.com/62207927/171350382-88810f72-7f9b-468d-b886-150947bcfe2c.png)

**Comment by prathameshpalaskark2view** [comment]
For future reference, custom java code to retrieve ip address is more performance efficient since in a cluster env, the fabric clusterstatus command results are sometimes returned after long time when system is under load.

**Comment by smokyMount** [comment]
Thanks for the update.
