### ISSUE TITLE
Does fabric support binding for fabric commands in version 5.3?

### ISSUE THREAD

**Issue by amessel-k2view** [k2view-academy/K2View-Academy#56]
Does fabric support binding for fabric commands?

For example:

fabric().fetch("TEST_CONNECTION DbInterface=?","InterfaceName");
or
fabric().execute("set_global global 'LUNAME.GLOBALNAME=?,' "GLOBALVALUE");

**Comment by rulaKhoury** [comment]
yes its support  binding  ;

**Comment by taliei** [comment]
You can use the execute and fetch method to run Fabric commands in your code.
You can find additional information in [Fabric API for DB Interfaces Knowledge Item](https://github.com/k2view-academy/K2View-Academy/blob/master/articles/05_DB_interfaces/09_fabric_API_for_DB_interfaces.md.
)

**Comment by amessel-k2view** [comment]
The link above is not working with 404 error.

I tried to sue binding for the test connection and it works perfect.

However I was not able to  use binding for " set_global global" command. Could you please advise if this command supports binding and if yes, what is the right syntax?

**Comment by taliei** [comment]
Hi.

I fixed the link.

See example for set_global command-
set_global global 'Customer.TEST2=kuku3';

**Comment by amessel-k2view** [comment]
> set_global global 'Customer.TEST2=kuku3';

This command above is not using binding.

For example:
- test connection: fabric().fetch("TEST_CONNECTION DbInterface=?",dbI)

the same approach doesn't work  with set_global global.
I tried this :
fabric().execute("set_global ?"," global Customer.TEST2=kuku3");
fabric().execute("set_global gobal ?","Customer.TEST2=kuku3");
fabric().execute("set_global gobal 'Customer.TEST2=?'","kuku3");

**Comment by lionbro1** [comment]
issue was identified as a bug, should be maintained in freshdesk
