### ISSUE TITLE
LUT agnostic Broadway flow

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#561]
I implemented a Fabric CDC consumer under SharedObjects/Broadway and while inside Studio I can run/debug it.
The flow is LUT agnostic.
But when running through commands like `broadway LUT.FLOW_NAME` or `startjob BROADWAY_JOB LUT.FLOW_NAME` there is no LUT to inform.
What is the recommended approach for handling this?
Would it be by creating a "dummy" LU to host this flow?
Please advise.
Thanks.

**Comment by feamcor** [comment]
No need to create a dummy LU.
Flow can be triggered using any of the existing LUTs, including k2_ref and k2_ws.

**Comment by lionbro1** [comment]
That's correct
