### ISSUE TITLE
Question related to TDM

### ISSUE THREAD

**Issue by romanRatchitski** [k2view-academy/K2View-Academy#563]
Hello, 

![image](https://user-images.githubusercontent.com/87433386/173223476-8f7be936-4d2e-475e-a3b0-d7f4a7e9edc6.png)

At the stage of creating a new Task.
Is there any way to arrange the LU's of the BE in a diffrent order? 
I tried menually to add/remove the LU's to the "Logical Units" Text filed in the TDM GUI, 
also when creating the BE I tried to change the order,
But it keeps the alphabetic order. 
My goal is to set the "WIZ_UPD"  as the first LU.

Is it possible?
Thanks.

**Comment by taliei** [comment]
Hi.

The screenshot in the Q&A refers to an older TDM version. We've updated the task creation windows in TDM 7.4. One of the changes is that the systems (products) and LU list are only displayed when the user clicks the Advanced Business Entity Options in the task.  When the user clicks this setting, a popup window is opened with the list of systems (products) that are attached to the task's environments + BE. The user can click on each system to view its LUs. For more information see https://support.k2view.com/Academy/articles/TDM/tdm_gui/14a_task_general_tab.html .

Regards,
Tali

**Comment by romanRatchitski** [comment]
Hi Tali, 
Thank you for your fast answer. 

I understand that at the new version it workes diffrent . 
But at this version can I change the order of "WIZ_UPD" LU to be the frist? 
Because when I select the LUs or deselect it keeps the LUs in alphabetic order,
And I need the "WIZ_UPD" to be the first LU. 

Thank you.

**Comment by taliei** [comment]
Hi.

Currently, the query selects the LUs from product_logical_units TDM DB table where be_id equals the task's BE. The query does not have an order by and the PG returns the LUs in the order they are created in the DB (usually it is ordered by the lu_id sequence). **Anyhow the display order of the LUs in the task has no impact on the execution order. The execution order of the LUs depends on the task's BE**. It starts with the root LUs, and then continues with the child LUs.  So, if you need the WIZ_UPD to run first, you must define it as a root LU (the parent LU is empty) in your BE. For more information see https://support.k2view.com/Academy/articles/TDM/tdm_overview/03_business_entity_overview.html .

Tali
