### ISSUE TITLE
How to analyse .snapshot files ?

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#568]
Hello,

According to link [https://support.k2view.com/Academy/articles/21_Fabric_troubl...](https://support.k2view.com/Academy/articles/21_Fabric_troubleshooting/01_Fabric_troubleshooting_overview.html#how-does-k2profiler-work) , I have generated snapshots , which are stored in directory  $k2_HOME/storage/snapshots as .snapshot files,.
I wanted to know is there a way to open these .snapshot files on linux server  or we need to upload the .snapshot files to yourkit server for analysis ?

The article on knowledge site does not mention on any next steps after generating snapshot using k2snaphot command. Also, I could not find anything in yourkit documentation on any relevant linux commands to open these files , hence this question on github.

Regards,
Prathamesh

**Comment by mhanna** [comment]
Hi,

You need a yourkit license a cpu snapshot.
if you use a mempry snapshot, which generates a HPROF format, then you can open it with any hprof compatible tool - like jstat
