### ISSUE TITLE
Fabric 5.5 - SQL statements emitted to source DB during get/migrate

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#57]
While developing a new LU for a constrained data source, customer requested all queries that would be emitted by Fabric to the source DB during, for instance, an initial load migration. Their DBAs would then review the queries, suggest optimizations and recommend an initial load strategy.

Is there any configuration parameter or environment variable that could be used on a dev or test environment to have such SQL statements flushed to the log?

Thank you.

**Comment by taliei** [comment]
Hi.

_k2_objects_info gives you statistics on each executed population.
If you would like to do some activity like writing the queries to the log, you can do the following:
1. Define and deploy environments in the Fabric Studio- PROD, DEVTEST .... 
2. Build special root functions for the DEV environment that write the query to the log.
3. Add a decision function for these root functions- this decision function needs to return true if the environment is DEVTEST.
4. Set the environment before running the initial load.

Read more about decision functions-
[Decision Functions Overview](https://github.com/k2view-academy/K2View-Academy/blob/master/articles/14_sync_LU_instance/05_sync_decision_functions.md)

Tali
