### ISSUE TITLE
async broadway flow during LU sync

### ISSUE THREAD

**Issue by tarikh03** [k2view-academy/K2View-Academy#573]
During LU sync (in trigger function) I called broadway flow, which in turn call innerFlowAsync.

even when I am calling innerFlowAsync, it is blocking the sync to finish and the sync is waiting for the flow that defined in innerFlowAsync actor to be completed.

calling it using broadway command, I don't want to start it as a job so it will not create many jobs and exceed the jobs limitation.
also it will fill k2_jobs insanely.

**Comment by natalylic** [comment]
It is by design that SYNC is waiting for all processes (even async) to be completed in order to release all connections and all used resources.
If you don't want to hold the SYNC, run a job using the BroadwayJob actor.
