### ISSUE TITLE
define number of retries when executing startjob command

### ISSUE THREAD

**Issue by tarikh03** [k2view-academy/K2View-Academy#575]
is it possible to define number of retries for the job we call?

**Comment by natalylic** [comment]
One of the following dedicated exceptions can be thrown from your job/parser:
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/62207927/175020797-c2c38771-7ff2-4851-a048-0658ddbd20d0.png)
**failJobAlwaysRetry(e);** -> will retry indefinite number of times
**failJobNoRetry(e);** -> will not retry
**failJobRetryUntilMax(e);** -> will retry up to 10 times (10 is a "hard-coded" value that can't be changed by configuration)

It should be included in the job/parser as **try & catch**:
```
try {
// your logic
} catch (Exception e) {
failJobRetryUntilMax(e);
}
```
