### ISSUE TITLE
How is quorum_hearbeat column updated in the k2ystem.nodes table in Cassandra?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#577]
How is quorum_hearbeat column updated in the k2ystem.nodes table in Cassandra? Which process sends these updates to Cassandra and what happens if a Fabric node is down?

**Comment by natalylic** [comment]
As part of the Fabric cluster process the **quorum_hearbeat** column is updated based on the time interval which is defined in config.ini: **FABRIC_HEARTBEAT_INTERVAL_MS**.
This is part of the Fabric core functionality. 
Node is considered dead after the time which is calculated by FABRIC_HEARTBEAT_INTERVAL_MS x FABRIC_HEARTBEAT_MISS.
You can check if the node status by the Fabric command **clusterstatus** via the console (or in any other way). 
When node is dead, it is considered not to be a part of the cluster anymore, thus it doesn't participate in any of the cross-cluster activities.
