### ISSUE TITLE
Cassandra Permissions required when installing Fabric

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#578]
Are there any Cassandra role creation steps involved during Fabric installation? What happens if the Cassandra user (as configured in config.ini) does not have permissions to create new roles. 

For example:
In cofig.ini user defined as below
```
## Cassandra cluster user and password
USER=fab_user
```
But this fab_user does not have below permissions.
`GRANT CREATE ON ALL ROLES TO fab_user`

And if Fabric does create new role during first install, can that role be created by DBAs separately?

**Comment by natalylic** [comment]
The Support articles [Fabric 6.xx Installation](https://support.k2view.com/Academy/articles/98_maintenance_and_operational/Installations/Linux/01_Fabric_6.xx_Installation_intro.html) and [Fabric 6.xx and TDM 7.xx Setup Single Node](https://support.k2view.com/Academy/articles/98_maintenance_and_operational/Installations/Linux/02_Fabric_6.xx_Setup_Single_node.html) provide detailed explanation about the Cassandra user creation during the Fabric installation.
The section **Post Setup Run on One Node** of the second article provides the commands for changing the default user's password and updating it in **config.ini**.

**Comment by natalylic** [comment]
By default, Fabric creates the **admin** user as the initial superuser when starting for the first time and defines their user and password as **admin**.
If the user/role names of the **admin** should be different: create config/adminInitialCredentials file with the relevant user/pwd as described in the section [Admin user](https://support.k2view.com/Academy/articles/17_fabric_credentials/01_fabric_credentials_overview.html).

If you want to create another user later and provide it admin permissions, you can create a new user by admin and assign it an admin role. 
See the article [Fabric Credentials](https://support.k2view.com/Academy/articles/17_fabric_credentials/01_fabric_credentials_overview.html) for all the commands or do it via the Web Admin.

**Comment by natalylic** [comment]
As discussed during out meeting on Thu, Fabric does not create any new Cassandra user during the installation so, it is fine if the Cassandra user used by Fabric in config.ini does not have the user/role creation privilege.
