### ISSUE TITLE
Fabric 5.5 - Pool Properties - Min/Max Connections

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#58]
Are the pool properties valid per Fabric node or for the whole Fabric cluster? I mean, if an interface is defined as min 0 and max 60 connections, would it open up to 60 per node or up to 60 distributed among all nodes of the cluster?

**Comment by taliei** [comment]
Hi.
 
The minimum and maximum number of connections per interface are allocated by Fabric per node.

See- [](/articles/05_DB_interfaces/03_DB_interfaces_overview.md)
