### ISSUE TITLE
Fabric CDC, publish whole set of data triggered only by one field.

### ISSUE THREAD

**Issue by tarikh03** [k2view-academy/K2View-Academy#580]
I am not able to find how to publish CDC on LU table, where CDC message to contain the whole fields.

let say I have 3 columns in table.
FIRSTNAME
LASTNAME
ID

I want to publish CDC message only when last name changes.
I defined the below:

![image](https://user-images.githubusercontent.com/47483757/176881393-c727cec3-51a0-437c-ab73-6f29813eb432.png)

I set CDC index on all fields:
FIRSTNAME as dataField
LASTNAME as keyField
ID as a dataField

I was expecting to get CDC message only when LASTNAME is updated, and the message to contain all data.
what is happening is that CDC message get published even when updating FIRSTNAME or ID.

**Comment by taliei** [comment]
Hi.

If you only want to send a CDC message when the LASTNAME changes, you only need to include the LASTNAME as a CDC field.

In this case- Fabric will only send the LASTNAME when if changes.

Tali

**Comment by tarikh03** [comment]
Yes that is correct, but it is not what I am requesting, as mentioned in description, I want to publish CDC when LASTNAME is updated, **but** I want the whole set of data to be sent, not only LASTNAME.

**Comment by taliei** [comment]
Hi.

You need to include the entire set of data in the CDC fields. Later on, the CDC consumer can filter the irrelevant data.

Tali
