### ISSUE TITLE
Fabric 5.5 - Get <LUT>.<IID> Execution Plan

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#59]
When a get is performed, does it execute within the context of one or many threads?
I mean, does Fabric execute each and every population sequentially, according to the table order?
Or does it, for instance, within one order, execute the populations concurrently?

**Comment by taliei** [comment]
Hi.

The support of parallel executions of table populations with the same order was added to Fabric in V6.0-
A new parameter was added to config.ini called MAX_PARALLEL_SYNC_SAME_ORDER. This is the max threads to use when running populations in parallel. The default value of this parameter is 1.  Please note that the parallel execution is for bringing data from the source, it doesn’t cover the writing into the Sqlite file.
For more information, see [Table Population Execution Order Knowledge Item](/articles/07_table_population/13_LU_table_population_execution_order.md).
