### ISSUE TITLE
Population of LU Tables from a different LU 

### ISSUE THREAD

**Issue by barakgk2view** [k2view-academy/K2View-Academy#594]
I am trying to perform a table population in LU1 from LU2, if it is done in a regular BW population where I call FabricGet it will be successful in the first iteration (LU2.1) but fails in second iteration (LU2.2).
If I add a Fabric release at the beginning of the loop at the second iteration  it fails due to can't perform this activity within a transaction.
Please suggest a method to achieve this functionality

**Comment by lionbro1** [comment]
You need to open another Fabric session and refer all the internal gets to the new session.

For Example;

openFabricSession(“fabric2”);
db(“fabric2”).execute(“get LU2.?”,customer_id1);
db(“fabric2”).execute(“get LU2.?”,customer_id2);
