### ISSUE TITLE
SQLite Full Text Search

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#596]
SQLite FTS is used by Fabric when selecting "Full Table Search" in table properties.
What is the FTS version set by Fabric (e.g. FTS3, FTS4, FTS5)?
What is the FTS tokenizer set by Fabric (e.g. Simple)?
Are any of these configurable (e.g. config.ini)?
Thanks.

**Comment by mhanna** [comment]
FTS4
Simple

Not configurable

**Comment by feamcor** [comment]
Thanks.
