### ISSUE TITLE
How to start a consumer job for a specific common table topic from a fabric node without restarting fabric?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#600]
We have a common table, without any population, for which transactions are sent from fabric console. We can see that the offset for this common table topic is increasing and all but one Fabric node is not picking this update. 

1. Is it possible to start a consumer job for that common table topic for that fabric node without restarting fabric?
2. Also, is there a way to check from fabric if a consumer job is running in background for any common table that does not have any populations?

**Comment by lionbro1** [comment]
Hi Hardik,

As discussed with Miri, this item should be consider as defect, please open a freshdesk ticket.
Closing the Q&A.

Regards,
Lion
