### ISSUE TITLE
Cache hit ratio

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#602]
Hello,

We recently received a request to expose cache hit ratio metric. basically its a measure to determine if the get is being executed against Cache or its fetching from DB (Cassandra ). Is there any inbuilt metric for determining cache hit ratio?
I looked at the currently exposed JMX metrics and did not see any relevant option for jmx metric for cache. 
But , looking at the statistics in the Fabric GUI , I see a parameter in statistics called mdbCacheCount. What is this parameter? 
![image](https://user-images.githubusercontent.com/46533104/180476398-1037ee2e-ae54-4289-bdee-812f5b1ed263.png)

Is it possible to expose it as a JMX metric ? 

Regards,
Prathamesh

**Comment by yuvalp-k2view** [comment]
It is mdbFetchNoNewVersion
