### ISSUE TITLE
Supporting Interface to Sybase Database

### ISSUE THREAD

**Issue by barakgk2view** [k2view-academy/K2View-Academy#603]
Which versions of Sybase ASE and IQ do we support ?

**Comment by lionbro1** [comment]
Hi,

Fabric is not restricted to a driver version. 

If the built-in interfaces are not supporting the driver you are looking for,
you can use any JDBC driver that is relevant to your project and define a new DB type from template according to your needs.

https://support.k2view.com/Academy/articles/05_DB_interfaces/10_database_types.html

**Comment by barakgk2view** [comment]
Lion,
As part of the existing Interfaces there are two options in the dropdown list

  1.  Sybase ASE
  2.  Sybase IQ

Which versions of those DBs we support OOB ?

Barak

From: lionbro1 ***@***.***>
Date: Sunday, 24 July 2022 at 8:56
To: k2view-academy/K2View-Academy ***@***.***>
Cc: Barak Gablinger ***@***.***>, Author ***@***.***>
Subject: Re: [k2view-academy/K2View-Academy] Supporting Interface to Sybase Database (Issue #603)

Hi,

Fabric is not restricted to a driver version.

If the built-in interfaces are not supporting the driver you are looking for,
you can use any JDBC driver that is relevant to your project and define a new DB type from template according to your needs.

https://support.k2view.com/Academy/articles/05_DB_interfaces/10_database_types.html<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.k2view.com%2FAcademy%2Farticles%2F05_DB_interfaces%2F10_database_types.html&data=05%7C01%7Cbarakg%40k2view.com%7Ccbd3665b5ab24a7d2cc408da6d393d3e%7C994f176e677549549f9e0c719b5e9ca0%7C1%7C0%7C637942389861278655%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PUYLEBHwA5z3mUsMmWTTqG8ArApJhJ2nnOdapq0eGQg%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fk2view-academy%2FK2View-Academy%2Fissues%2F603%23issuecomment-1193253053&data=05%7C01%7Cbarakg%40k2view.com%7Ccbd3665b5ab24a7d2cc408da6d393d3e%7C994f176e677549549f9e0c719b5e9ca0%7C1%7C0%7C637942389861278655%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ezIjwBw9kHPbHx93xm1LWHqbXOe9w5zwmhYwwsf01qs%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGLUM34UAVWPPYFAVAURGJ3VVTLINANCNFSM54PDA26Q&data=05%7C01%7Cbarakg%40k2view.com%7Ccbd3665b5ab24a7d2cc408da6d393d3e%7C994f176e677549549f9e0c719b5e9ca0%7C1%7C0%7C637942389861278655%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VyXXCbylk9bPMO7A6f38XLc5eSWcFPAV4yi7OOXmqNE%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>
* CAUTION: This email originated from outside of K2view *

**Comment by lionbro1** [comment]
Hi,

We can't tell the exact version, as the same driver can support several versions, but as I mentioned there is not restriction to the version, you can try our built-in interface, if it doesn't work for your version you can use our create DB type from template functionality.
