### ISSUE TITLE
Read only permission for specific Reference tables

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#606]
Is it possible to create a user and grant it READ-ONLY permission for only a few reference tables? Which Fabric version supports it?
The use case is to expose only 4 out of many common tables for the Ops team.

Using the below link, I was able to grant read on the k2_ref resource to the new role but it wouldn't allow me to restrict it only to specific tables.
https://support.k2view.com/Academy/articles/17_fabric_credentials/02_fabric_credentials_commands.html

**Comment by lionbro1** [comment]
Hi Hardik,

This granularity is not support by Fabric using common tables functionality.

You can define the relevant restricted reference tables as LU tables on a separate LU, define dummy root table and put all these tables under the dummy root table.

Regards,
Lion
