### ISSUE TITLE
How can I create a flow with 2 nested GET with SELECT statements per each?

### ISSUE THREAD

**Issue by natalylic** [k2view-academy/K2View-Academy#615]
When a GET & SELECT from LU1 is followed by loop on GET & SELECT from LU2, the exception is thrown:
_[SQLITE_ERROR] SQL error or missing database (database LU2 is locked)_
The exception is thrown when trying to RELEASE an instance of LU2 and it happens due to open results set of the SELECT on LU1.
The exception is thrown only when running with Debug Mode = OFF.
![image](https://user-images.githubusercontent.com/62207927/182376356-9eda3784-f849-43ba-bb2a-d124b4bb5459.png)
This problem can be resolved by modifying the flow as follows:
* Upload the first SELECT results to memory by creating an array (using an ArrayBuilder actor), then iterate over this array rather than the result set. 
![image](https://user-images.githubusercontent.com/62207927/182377029-b3cbc68d-d08d-44b8-886c-5b30794fb10f.png)

Another workaround for this problem in Broadway is running the 2nd GET & SELECTs on another session (by creating an interface for Fabric). This solution however has a limitation: the joins between the selects of different LUs are not possible in case of 2 sessions.

**Comment by smokyMount** [comment]
With the addition of BUFFER_RESULT_SET property, can we use _SET BUFFER_RESULT_SET=true_ instead of using ArrayBuilder actor as mentioned above? 
If yes, that can also allow joining between selects of different LUs as well.

**Comment by natalylic** [comment]
Yes, you can use _SET BUFFER_RESULT_SET=true_ instead of using ArrayBuilder actor, to upload the select statements to memory.
It doesn't allow joining between the selects on different LUs.
