### ISSUE TITLE
Fabric 5.5 | Interface type for handling SOAP Webservices via HTTP

### ISSUE THREAD

**Issue by neenjapt** [k2view-academy/K2View-Academy#62]
Hi,

We are currently implementing a requirement to invoke an SOAP Webservice via HTTP and have a few questions in regards to how can we manage the WS configurations such as host, port, URI/Context Path, etc.

Since we want to use the Environments feature for managing each environments configuration values, we thought of using an Interface to hold this WS data.

Regarding the out-of-the-box features, we noticed Fabric already supports an **HTTP** interface (which lacks the URI field to fulfill our purpose) and even a **Custom** one but neither provides a seamless way to manage the required configuration data without reusing some of the default fields for our requirements.

Our current investigation led us to find out a Fabric XML (**FabricInterfaces.xml**) under Studio **Config** folder which seems to allow us to create a custom Interface Type with all the fields we want - we were, however, unable to understand where does this file reside on a Fabric server installation when we looked into a Fabric 5.5 container.

Hope you can help and guide us on how to achieve our requirement.

Thanks,
Bruno Willman

**Comment by taliei** [comment]
Hi.

Fabric 5.5 only supports an HTTP interface for a parser. You can use the CUSTOM interface and set the required additional parameters in the Data attribute of the interface.

Regards.
Tali
