### ISSUE TITLE
Fabric console security

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#626]
Hello,

I have a question related to fabric console security.  See link -- https://support.k2view.com/Academy/articles/26_fabric_security/13_user_IAM_configiration.html#:~:text=server_authenticator%20section%20definitions.-,server_authenticator,-Configuration

Our client wants to enhance console security so that even in case of stolen passwords, or access should not be gained through brute force passwords.  
Accordingly, referring to the console security , I have the following questions, 
1> What is the difference between ldap and adldap ?
2> Any other steps other than those listed in ldap configuration section ? 

Second point is being asked since the hyperlink to the full instructions is broken. Similarly at the end of the page, the hyperlink to custom authenticator mechanism is broken.

Regards,
Prathamesh

**Comment by eyalk2** [comment]
1> LDAP is the protocol which Microsoft AD implemented. AD LDAP (and AD LDAPS) are then dedicated to Microsoft Azure. with their specific settings
2> There are detailed explanations here: https://support.k2view.com/Academy/articles/26_fabric_security/11_user_IAM_LDAP.html and instructions for Azure AD in 2 other articles contained in this article.

The 2 broken links were fixed. thank you for noticing us
