### ISSUE TITLE
Mdb cache expiration

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#632]
Hello,

I am looking for some information on cache expiration policy for mdb. Is it based on expiration time or some other strategy ?
Config.ini parameter, 
## Cache size limit in bytes per Schema for MicroDB instances that are not currently in use
#MDB_DEFAULT_SCHEMA_CACHE_SIZE=10000000

Regards,
Prathamesh

**Comment by lionbro1** [comment]
Hi,

There is no expiration date, you can control the cache size, once it reach to the defined limit fabric will remove from cache the oldest MDBs in cache to free cache space according to the defined cache size in config.ini
