### ISSUE TITLE
What does 'no active subscribers' message in k2fabric.log file mean that is printed after updating config.ini?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#635]
Hi,

We changed the config.ini file and added a new section at the end of file as shown below:

```
[CUSTOMER_LU_cassandra_entity_storage_loader]
MODE=SINGLE
```

After saving the config.ini file the log file shows below lines. What does it mean when it says there are no active subscribers?

> INFO  2022-08-26 00:22:10,319 [LID30fe000000000002] [FileChangeMonitor] c.k.f.c.i.FileChangeMonitor - config.ini was reloaded
> INFO  2022-08-26 00:26:44,366 [LID30fe000000000002] [FileChangeMonitor] c.k.f.c.i.Configurator - Change in CUSTOMER_LU_cassandra_entity_storage_loader.MODE has no active subscribers
> INFO  2022-08-26 00:26:44,367 [LID30fe000000000002] [FileChangeMonitor] c.k.f.c.i.FileChangeMonitor - config.ini was reloaded

**Comment by smokyMount** [comment]
Does it mean this change is not reflected and we need to do a Fabric restart?

**Comment by natalylic** [comment]
The message means that the current active subscribers don't identify the change. Thus, the restart is needed.
