### ISSUE TITLE
WS response codes

### ISSUE THREAD

**Issue by AlexMaziya** [k2view-academy/K2View-Academy#64]
What type of response codes do we have when invoking fabric WS and what is the way it can be altered?

Is there any difference in the response code between version 5.x and 6.x?

**Comment by lionbro1** [comment]
Hi,

Please refer to the following link for a detailed explanation on Fabric WS response codes and the way to override it if needed:

https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.1/articles/15_web_services_and_graphit/11_response_codes.md

There are no differences on the response codes from Fabric 5.5 and on.
