### ISSUE TITLE
Best way to get complete LU data for multiple IIDs via single WS API call

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#642]
Hello - could you please let us know the best way to extract LU data from fabric for multiple IIDs via single WS API call? 

For example, we can get comma-separated list of IIDs as an input (let's say limited to 10 IIDs), then we do set sync off and for each IID we execute get. 

Do we need to go over each table in LU then and select * from <tbl> ? or we have something out of the box available that we can use to generate response?

Thank you!

___________
Best regards,
          Andrey

**Comment by lionbro1** [comment]
Hi,

There are few options:

1. Create a broadway flow that will open parallel async inner flows that will run get for different LUIs in parallel and merge all this data (You can use DBCommand actor to bring the relevant data).
2. You can also call from broadway flow to the product API http://localhost:3213/api/v1.0/lu/CUSTOMER/1?token=ABC to bring all the mdb data for a given LUI (https://support.k2view.com/Academy/articles/15_web_services_and_graphit/12_Supported_Verbs_Get.html).

The broadway flow that you created can be called by product API called fabric-commands, you can read further on this article https://support.k2view.com/Academy/articles/15_web_services_and_graphit/13_Supported_Verbs_Post.html

**Comment by avvakandr** [comment]
Hi Lion, thank you for quick answer!

Is there any product API that I can use from WS directly to serialize data so I do not need to create BW? I saw there is a 

SerializeLU.serialize((FabricDBConnection fdbc, LUType luType, String startingLudbObjectName)) 

can I leverage this in my WS?

_____________
Best regards,
         Andrey

**Comment by lionbro1** [comment]
Hi Andrey,

The product API that serialize LUI data  is what I mentioned above, but it works only for 1 LUI, you can't provide list of LUIs as input.

Broadway flow is the easiest and best way to achieve what you are looking for.

**Comment by avvakandr** [comment]
Hi Lion, but can I call it in the loop from my WS with 1 LUI at a time instead of having WS to call BW that will call another WS ?

**Comment by lionbro1** [comment]
yes you can, but Broadway gives you easier way to merge the outputs, parallel running, error handling, etc.. with zero coding, just by using the existing actors.

**Comment by avvakandr** [comment]
Hi Lion, ok I understood, thank you!...

Just for my curiosity / education purpose - could you please tell me how I can get this FabricDBConnection fdbc ? I spent a bit of time trying to figure it out, but I could not and this is eating me :)  

_____________
Best regards,
         Andrey
