### ISSUE TITLE
How to cancel a batch that was not triggered from Fabric console

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#652]
We tried cancelling the batch from the Admin GUI using the cancel option and using batch_cancel command as well but it throws this error - "Can't stop batch process '<bid>'. (Synced batch process can be stopped only from the coordinator's console or process is not running)"

This batch was triggered from/"Created by" a USER_JOB. How to cancel such batches?

**Comment by lionbro1** [comment]
You have to find the batch in the batch_list command, get it's id,  than check where it's USER_JOB was running from and cancel it from this node
