### ISSUE TITLE
DbCreateTable actor - How to define a composite partition key?

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#654]
How to create a table like the one below using the DbCreateTable actor?
The actor's `fields` property form doesn't allow to define the composite.
The actor's `append` property appends after the table structure.
Please advise.
Thanks.

```sql
CREATE TABLE LUT.idfinder_stats (
    host text,
    operation_name text,
    iteration int,
    last_update_time timestamp,
    operation_value bigint,
    status text,
    PRIMARY KEY ((host, operation_name), iteration)
)
```

**Comment by feamcor** [comment]
As a workaround, I'm using DbCommand actor.
But it should be considered to extend the Cassandra dialect of the DbCreateTable actor.
BTW, I'm using Fabric 6.5.9.

**Comment by smokyMount** [comment]
Hi, did you try using DbCassandraCreateTable actor?

**Comment by feamcor** [comment]
@smokyMount you are so right. I don't know how I overlooked that actor. Thanks.
