### ISSUE TITLE
Can we update max number of connections for a db interface while a sync batch job is running?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#658]
Hi,

If we update max number of connections for a db interface in the Environment file and deploy the environments while a sync batch job is running, will the max number of connections increase during batch runtime?

**Comment by smokyMount** [comment]
For example, say we have <maxConnectionsNumber>60</maxConnectionsNumber> and we start seeing timeouts due to pool being busy while a migration is going on. If we increase this to 100 and deploy the env file, will it apply immediately or only after migration has completed.

**Comment by lionbro1** [comment]
It should apply immediately, but in order to confirm we will run a QA next week to validate.

Confirmed after QA validation
