### ISSUE TITLE
Size wise, how many instances can Fabric handle at a given time?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#659]
Say the server has enough/very high RAM and heap sizes, how much max can Fabric handle at any given time? If I am running a batch process, can we have a 200 instances, 1 GB each all in memory at same time on a given node?
Can JVM be a bottleneck?
Does Fabric put LUIs off-heap to avoid JVM issues? Or does every instance stay and block the heap?

**Comment by lionbro1** [comment]
Yes, max memory size can be set with very high number.
Fabric does uses off-heap for the mdb
