### ISSUE TITLE
How to use Stats category actors in Broadway?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#664]
Are there examples on how to use StatsWriter and StatsReader actors in Broadway? Especially StatsReader in conjunction with DbCommand, ErrorHandler actors.
Also, how do flow level and global level stats work?

Thank you!

**Comment by natalylic** [comment]
The **DbCommand** and **ErrorHandler** actors have a built-in ability to gather the statistics that can then be read by the **StatsReader** actor. The flow level is the statistics gathered from the current flow, while the global is the session level statistics. 
The **StatsWriter** can be used when the statistics should be gathered from other actors by setting the statistics key and value.

Refer to the sub-chapter **How Do I Gather Statistics in TDM?** in this [article](https://support.k2view.com/Academy/articles/TDM/tdm_implementation/12_tdm_error_handling_and_statistics.html) for using the **StatsReader** in TDM.
