### ISSUE TITLE
How to create and use custom Cassandra loader section from config.ini?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#667]
We have a large file that we load to Cassandra using CassandraLoader interface in a DbLoad actor from a Broadway flow. We want to modify the loader properties to use token aware batch and multiple threads to improve the performance.
How to create a new loader section in the config.ini and use it in the CassandraLoader interface? I tried to create one as shown below but the loader was still picking up properties from the default section.

![image](https://user-images.githubusercontent.com/66338066/197376412-9e233dc0-404b-44cc-858b-2b621bf0bcb1.png)
![image](https://user-images.githubusercontent.com/66338066/197376430-adc6a5f6-3e7d-4850-b4a7-1e12b007db35.png)

**Comment by natalylic** [comment]
The configuration that you did looks OK, except for the following two issues:
- Your CONSISTENCY_LEVEL is invalid, there is no such value - SINGLE. 
- Also, the NUMBER_OF_THREADS is too high and you can get improved performance with much lower number. Try setting it to 2 or 4 and see the impact. 
Other than that, the configuration is correct. If you fix the above and it still doesn't work, pls open the freshdesk ticket.

**Comment by smokyMount** [comment]
Created a ticket - https://k2view.freshdesk.com/support/tickets/31807
