### ISSUE TITLE
transactions missing on common

### ISSUE THREAD

**Issue by sharanyavj** [k2view-academy/K2View-Academy#677]
hi Team,

I have a reference table which gets updated via an enrichment (creating a transaction). Some how my insert transaction is missed,  still investigating on that. But later we received an update for that instance which is been avoided by common as the instance not available on the ref table. What would you suggest us on this scenario? How would I insert the record? Its a full text search table so no Pkeys are available.

**Comment by Krutyolkin** [comment]
It could be an update instead of an insert - note that Cassandra treats both as the same command while MDB does not.
Since fabric version 6.5.9, the message is written into logs when an update has no effect (0 rows updated).
