### ISSUE TITLE
MFA for Login into Fabric

### ISSUE THREAD

**Issue by barakgk2view** [k2view-academy/K2View-Academy#683]
Can Fabric support an MFA login ?

**Comment by eyalk2** [comment]
Similar to what stated [here](https://github.com/k2view-academy/K2View-Academy/issues/682), Fabric does not support it directly. When Integrated with SAML, customer can achieve MFA with its IDP. 
These days there are many and improving modern and secure login and auth verifications methods, MFA & passwordless, passkeys and so on. IDPs know to provide it and support up to date methodologies. 

Note that our Cloud Platform comes with already integrated IDP with all these capabilities.
