### ISSUE TITLE
How to use WHILE actor with DB query results

### ISSUE THREAD

**Issue by dotants** [k2view-academy/K2View-Academy#685]
Hi

In a Broadway flow, I want to create a "while" loop, that will continue until the results of a DB query "select count(*) from..." is zero.

How can this be implemented?

**Comment by natalylic** [comment]
The While actor includes a JavaScript where you can check some logic. For example:
![image](https://user-images.githubusercontent.com/62207927/205096331-53d0b846-e9ab-4f68-8233-edbf08e6fd75.png)

**Comment by dotants** [comment]
That does not answer the question

**Comment by natalylic** [comment]
WHILE actor can be used to create a logical loop - when loop is needed and there is no data set to iterate on it. For example:
![image](https://user-images.githubusercontent.com/62207927/205493116-6eb114ac-3be4-4138-b59f-f272509de2fc.png)

In your case, just write **true** in the script of WHILE (it will create an infinite loop), and perform your logic in the loop. Add the loop stopping condition and the LoopStop actor.
