### ISSUE TITLE
Integration with Datadog

### ISSUE THREAD

**Issue by yevgenibelaigorod** [k2view-academy/K2View-Academy#686]
Hi 
Below question comes from Comcast operational team
Is there any intentions of working to provide an integration for Datadog. Datadog is becoming more and more popular & has wide use at Comcast. Integrations are easy to build & if one exists, those metrics are free - otherwise cost is calculated and get expensive quickly
See  Reference for integrations https://docs.datadoghq.com/integrations/

Thanks
Yevgeni

**Comment by eyalk2** [comment]
Datadog provides agents that can be applied on Fabric and can be configured, as needed.
Customized agent, for example for looking at JMX data, which is extra, shall set per customer needs. 
This is done on one of the projects.
We are currently do not plan to provide such integration as in the link, which in some cases are providing minimal stuff for initial setup, which can be done in the standard agents, with some configurations.
