### ISSUE TITLE
Replacing Cassandra with AWS DB products

### ISSUE THREAD

**Issue by barakgk2view** [k2view-academy/K2View-Academy#687]
For the K2View repository we currently support - Cassandra, Astra,S3 and Azure Blob store.
If needed can we support Aurora or DynamoDB ?

**Comment by lionbro1** [comment]
Yes, users can create their own LU Storage save/load plugins.

**Comment by barakgk2view** [comment]
I could not find the definitions of adding a plugin. I the LU Storage I saw only the following options 
<img width="306" alt="LU_Storage_Options" src="https://user-images.githubusercontent.com/26691183/205867893-7d1eeb99-22c5-4cab-a8e6-28781cc4f9f6.png">
Can you direct me to documentation for the setting ?

**Comment by barakgk2view** [comment]
<img width="306" alt="LU_Storage_options_v2" src="https://user-images.githubusercontent.com/26691183/205868342-3cd184a9-2eaf-4b41-92cf-e04a18ba19fd.png">
