### ISSUE TITLE
How to check mdbFileSize & mdbFilePath

### ISSUE THREAD

**Issue by natalylic** [k2view-academy/K2View-Academy#689]

**Comment by natalylic** [comment]
When it is required to get the length (file size) and the absolute path of the MicroDB in scope, do the following:
1. Run GET command on the required LU to get a MicroDB into the scope:
```    fabric>get CRM7Test.100; ```
2. Run the command to select MicroDB file size on the LU in scope:
```    fabric>select mdbFileSize('CRM7Test'); ```
The command returns the length, in bytes, of the file denoted by this abstract pathname, or 0L if the file does not exist.
3. Run the command to select MicroDB file path on the LU in scope:
```    fabric>select mdbFilePath('CRM7Test'); ```
The command returns the absolute pathname string of this abstract pathname.

**Comment by natalylic** [comment]
Note that the above are Fabric commands that allows to find the LUI size / instance size and the path to the LUI file.

**Comment by feamcor** [comment]
Is this only for Fabric 7 or does it work on 6.5.x (if so, from which version)?
If only for Fabric 7, how can the LUI size can be retrieved on 6.5.2?
Thanks.

**Comment by lionbro1** [comment]
Hi,

This is a very old feature, of course it is available on 6.5 as well
