### ISSUE TITLE
is it possible to have separate kafka pipe for each LU?

### ISSUE THREAD

**Issue by tarikhad** [k2view-academy/K2View-Academy#690]
![image](https://user-images.githubusercontent.com/4185806/207030399-6707dcfb-2289-4365-94f9-637111bb7a5e.png)

For each LU there is a topic being created.
but before that there is a step where fabric gathers all messages for all LUs in one topic (CDC_TOPIC_?????).

is it possible to have different CDC_TOPIC_????? for a specific LU?

the idea is to have independent LU message processing.

lets say we have two LUs.

LU1 and LU2:

LU1: produces many messages but it is not that important to process quickly.
LU2: produces few messages but those message need to be handled ASAP.

LU2 message will hang in the queue waiting for LU1 to be processed first.

**Comment by lionbro1** [comment]
Hi,

1. In Fabric 7.0 there is no CDC_TOPIC anymore, we publish the messages directly to the target topic.
2. If you have different priority for each LU, why not to set different target topic for each LU Table (on different LUs).

**Comment by tarikhad** [comment]
how do I set different target for each LU?

![image](https://user-images.githubusercontent.com/4185806/207037204-39e6724a-4128-43e3-b06f-998beabf6275.png)

by default, there will be one topic handling all messages, then it will publish two a topic per LU.

in the above example:

Audit_DEV_47 is for LU1
D1Recon_DEV_47 for LU2

but messages for both LUs will first go through CDC_TOPIC_DEV_47.

Can I configure to have different CDC_TOPIC_DEV_47 for different LUs?

**Comment by lionbro1** [comment]
closing the ticket, the solution was discussed over a call
