### ISSUE TITLE
Graceful termination/suspension of batch execution

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#693]
When `batch_cancel` or `batch_pause` are executed, will Fabric immediately stop the execution of the batch, interrupting the command for those IIDs currently under execution, or does it wait at least for the current executions to complete? I mean, I would like to know if batch can gracefully stop based on these commands. Thanks.

**Comment by natalylic** [comment]
When running ```batch_cancel``` or ```batch_pause```, Fabric aborts any execution in progress. Thus, there is no graceful stop.
