### ISSUE TITLE
Fabric "insert or replace" for multiple rows at once

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#694]
Hi, in Java, how to emit an insert statement for multiple rows at once?
Something that would replicate `insert into (c1,c2,c3) values (?,?,?),(?,?,?),...;` behavior.
If available, does it provide any performance difference compared against individual inserts per row?
Thanks.

**Comment by eyalk2** [comment]
Hi
insert command is only for a single row.
you can call to batch command from Java for multiple.
