### ISSUE TITLE
Is there an easy way to view profiler output?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#695]
Hi,

For a very large Broadway flow (profiler output >750 lines), is there a way to sort and filter profiler output to easily catch the slow performing objects?

Thank you!

**Comment by natalylic** [comment]
The Profiler supports filter using **Ctrl+F** including the options such as : match case, match whole word, regex, etc.
In addition, the Profiler output can be copied and pasted into a text editor.
![image](https://user-images.githubusercontent.com/62207927/207369412-b4dd6592-2e34-4ed9-8e45-d2b6abb462c2.png)
