### ISSUE TITLE
How frequently should the Fabric servers be restarted in a Production cluster?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#696]
Hi,

Is there a recommendation on how frequently we need to restart Fabric servers to make sure everything works normal? 
We started seeing slow performance in production environment for LU populations reading from different sources (no code change). Restarting Fabric servers fixed this performance issue. We had not restarted these nodes for almost 2 months. 

Thanks!

**Comment by lionbro1** [comment]
Hi,

Fabric nodes do not have to be restated to improve performance. It is important in your case to understand the root cause of the issue you are experiencing. You can contact our professional services if you need assistance to analyze your implementation to see how it can be improved.
