### ISSUE TITLE
Upgrade of Python 2.7.x to a later version

### ISSUE THREAD

**Issue by barakgk2view** [k2view-academy/K2View-Academy#701]
Can Fabric support higher versions of Python? 
The answer is for Linux and/or windows

**Comment by lionbro1** [comment]
The python is required for Cassandra not to Fabric.

Cassandra 3 and 4 works only with Python 2.7.

**Comment by barakgk2view** [comment]
1) Do we have a procedure to replace on windows Cassandra 3 with Cassandra 4 or I just need to download the package Cassandra 4 for windows ?
2) Do we have a procedure to replace on windows Python 2.7 with Python 3 or I just need to download the package Python 3 for windows ?

**Comment by itsiktsarfati** [comment]
currently we have no procedure for windows, but both should work correctly with updating the packages

**Comment by barakgk2view** [comment]
Hi Lion,
I just tried installing Cassandra 4.0 and it seems like it does not have BAT files and it seems like it supports only Linux , am I correct?
Any work around for Windows ?

***@***.***

https://stackoverflow.com/questions/67728947/cassandra-executable-not-recognized-in-windows

From: lionbro1 ***@***.***>
Date: Monday, 19 December 2022 at 13:12
To: k2view-academy/K2View-Academy ***@***.***>
Cc: Barak Gablinger ***@***.***>, Author ***@***.***>
Subject: Re: [k2view-academy/K2View-Academy] Upgrade of Python 2.7.x to a later version (Issue #701)

The python is required for Cassandra not to Fabric.

Cassandra 3 works only with Python 2.7.

Cassandra 4 should work with Python 3.

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fk2view-academy%2FK2View-Academy%2Fissues%2F701%23issuecomment-1357478322&data=05%7C01%7Cbarakg%40k2view.com%7Cc1af900df7b5403541e208dae1b1da73%7C994f176e677549549f9e0c719b5e9ca0%7C1%7C0%7C638070451239585744%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ryvEDzMn3l9jWCyhM%2Forw%2FpRI82VtL7FyK9f1eHK1B0%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGLUM34Z6TCU5QPJKYILYJDWOA7IBANCNFSM6AAAAAATDFO6ZA&data=05%7C01%7Cbarakg%40k2view.com%7Cc1af900df7b5403541e208dae1b1da73%7C994f176e677549549f9e0c719b5e9ca0%7C1%7C0%7C638070451239585744%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=somgIWABTe%2BIyjtRklEOm4x8Eu1C%2FTqst7jdFSM3OtI%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>
* CAUTION: This email originated from outside of K2view *

**Comment by lionbro1** [comment]
It seems Cassandra 4 is not coming with bat scripts for windows.

I asked our DevOps to double check
