### ISSUE TITLE
Oracle JDK vulnerability

### ISSUE THREAD

**Issue by barakgk2view** [k2view-academy/K2View-Academy#702]
I received a question regarding JDK vulnerability and if we can replace of Oracle JDK to Open JDK.
My understanding is that we use the Open JDK and NOT the Oracle JDK.
Am I correct?

**Comment by lionbro1** [comment]
For Java 8 we use Open JDK, for Java 17 (Fabric 7) we use Oracle JDK as it is free again.

**Comment by barakgk2view** [comment]
And if they insist on Open JDK, do we have a process or is it transparent?

**Comment by lionbro1** [comment]
Are you asking on Fabric 7? how come there are already vulnerability issues?

If they are using lower Fabric release so we use Open JDK anyway.
