### ISSUE TITLE
Fabric SEARCH doesn't return all of ELASTIC SEARCH's json attributes 

### ISSUE THREAD

**Issue by Siva-K2view** [k2view-academy/K2View-Academy#707]
I noticed that Fabric SEARCH doesn't return all of ELASTIC SEARCH's json attributes. Certain important "Sort" results are required for further use and are not available. Possible to fix it by returning all the json attributes and let the caller filter out unnecessary attributes or is it too much of a payload and has to add only required json attributes on a case by case?

**Comment by lionbro1** [comment]
Hi,

You can get the full ES response structure by using AS_JSON parameter when calling the search command.

You can read further in this article

https://support.k2view.com/Academy/articles/18_fabric_cdc/cdc_consumers/search/05_search_command.html
