### ISSUE TITLE
Ephemeral LUI

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#719]
Fabric 6.5.2

Is there a way to set Fabric to load an ephemeral LUI without persisting it to Cassandra?

I would like to avoid using `set instance_ttl`.

Is `MEMORY` on `MDB_DEFAULT_SCHEMA_CACHE_STORAGE_TYPE` (see below) the value to be used?

On https://support.k2view.com/Academy_6.5/articles/32_LU_storage/02_storage_management.html there is no description about `MEMORY`, `DISK` and `MDB` values.
Also, how `NONE` would differ, for instance, from `MEMORY`?
Would `DISK` require a shared file system mounted on the Fabric nodes?
Please elaborate and enhance the documentation.

Can I set that per LUT?

In case of `MEMORY`, how long would the in-memory LUI be valid?

```ini
## Storage can be:
## MEMORY/DISK/MDB/CASSANDRA/S3/AZURE_BLOB_STORE/NONE/
#MDB_DEFAULT_SCHEMA_CACHE_STORAGE_TYPE=CASSANDRA
```

Please advise.
Thanks.

**Comment by lionbro1** [comment]
Memory means everything is stored in memory, only works for single node and small datasets.
Disk is also local, it is better to remove it as option in the documentation.
NONE means not to save it in the first place.
NFS is the one to use if you want shared storage.
Recommend to do changes via the schema, meaning per LUT.

we will update the article accordingly.

**Comment by feamcor** [comment]
So is `NONE` the option for ephemeral LUIs?
Does it assume that no LUI will be loaded at all, or does it load in-memory/cache but gone when session is done?
Will it still create a cache file on `MDB_DEFAULT_CACHE_PATH`?
Please advise.
Thanks.

**Comment by lionbro1** [comment]
as for the first question, correct.
It will not save it on memory cache, meaning it will just create mdb file in /dev/shm as a part of LUI sync process
