### ISSUE TITLE
get instance failed for database lock when there is unclosed Db.Rows for different instance.

### ISSUE THREAD

**Issue by tarikh03** [k2view-academy/K2View-Academy#72]
|Base Version                    |Tag fabric-6.1.2_7 at revision = 9304c04ae608c4aa96bed7a1d1858721b93c5ef0|
|MDB Version                     |3.27.2  

WS code:

   fabric().execute("get TEST.'"+inp1+"'");

   Db.Rows res1 = fabric().fetch("select col1 from root");

   fabric().execute("get TEST.'"+inp2+"'");

   Db.Rows res2 = fabric().fetch("select col1 from root");

should above code be valid?

it is failing on line 3, (get TEST.inp2) with the below error:

Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (database TEST is locked)

if we add res.close() before the second get, it works.

**Comment by lionbro1** [comment]
Hi,

This is a valid scenario, it was fixed on release 6.2.

Meanwhile adding a release command before the second get should do the job.

Regards
Lion
