### ISSUE TITLE
IID Value Restriction

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#720]
Hi,

Considering that the IID is the key to load a LUI, what are the restrictions about its lenght and content?
I understand that IIDs with chars other than digits, letters and underscore can be provided between single quotes.
I saw in a customer project, an IID being set with web service query parameters that are really long, with dividers, etc.

Please advise.
Thanks.

**Comment by lionbro1** [comment]
Hi,

There is no hard limitation to the IID lenght and no limitation to the content, just as you mentioned make sure you keep the single quotes.
