### ISSUE TITLE
Broadway debug on remote node thru SSL

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#723]
Fabric 6.5.2

On remote Fabric...
- I changed `ENABLE_BROADWAY_DEBUG_SERVLET=true` on `config.ini`.
- I added `-DstudioNoAuth=true` on `jvm.options`.
- SSL is being used `WEB_SERVICE_SECURE_PORT=9443`.

Fabric Studio can reach to remote Fabric.
Debug server changed to remote Fabric.
Still not able to get Broadway debug info.

Is it a limitation that Broadway Debug Servlet can only work on HTTP:3213?

Please advise.
Thanks.

**Comment by lionbro1** [comment]
It seems it should work, QA team still try to validate, will get back to you with the results

**Comment by lionbro1** [comment]
The final conclusion is that in case of full certification mode is works, once using self sign certification it is not working
