### ISSUE TITLE
Milliseconds on DATETIME_FORMAT

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#724]
Fabric 6.5.2

Project has, since the beginning, datetime format set as below.

```ini
DATETIME_FORMAT=yyyy-MM-dd HH:mm:ss
#DATE_FORMAT=yyyy-MM-dd
#TIME_FORMAT=HH:mm:ss
#DATETIME_WITH_TZ_FORMAT=yyyy-MM-dd HH:mm:ss xxx
#DATETIME_FORMAT_LOCAL_TIMEZONE=false
```

I need to change it to the below, because it is currently ignoring (not storing) milliseconds.

```ini
DATETIME_FORMAT=yyyy-MM-dd HH:mm:ss.SSS
#DATE_FORMAT=yyyy-MM-dd
#TIME_FORMAT=HH:mm:ss
DATETIME_WITH_TZ_FORMAT=yyyy-MM-dd HH:mm:ss.SSS xxx
#DATETIME_FORMAT_LOCAL_TIMEZONE=false
```

Is there any kind of consideration on doing such change?

I mean... existing datetime columns will continue stored without milliseconds until they are reloaded or updated, but new ones would include the milliseconds.

Will Fabric deal with it gracefully (i.e. will it parse milliseconds as optional)?

Please advise.
Thanks.

> p.s. please review the default/template `config.ini` that comes with Fabric and Fabric Studio. I observed that on new versions, the default `DATETIME_FORMAT` includes the milliseconds but the default `DATETIME_WITH_TZ_FORMAT` does not. It makes no sense considering that both are timestamps and the only difference is the TZ indication.

**Comment by eyalk2** [comment]
Existing datetime columns will continue stored without milliseconds until they are reloaded or updated, where after reload they include the milliseconds. 
And yes - Fabric does handle it "gracefully", i.e. consider it optionally: if at source some of the date data is with milliseconds and other not, Fabric will add the milliseconds to the LU table for those with milliseconds and will not include it for those at source comes without it.

[TZ behavior's is same as without]
