### ISSUE TITLE
LU as source for another LU using Broadway populations

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#727]
Fabric 7, no IID Finder

Please assume that `LU2` has Broadway population flows where data source are LUIs from `LU1`.
LUIs of `LU1` were already loaded.

Where should the get for `LU1.IID` should be located?
Should it be done on every population?
Or should it be done once on the population of the root table?

I see that the `FabricGet` actor end up changing the global sync mode.
Should a `Fabric Remote` interface be created and data source is queried through it, instead of the default local interface?

Please advise.
Thanks.

**Comment by natalylic** [comment]
Assuming LU1 has been loaded to Fabric, there is no need to define a Fabric Remove interface.
You should perform ```get LU1.IID``` in the root table population of LU2, in a sync off mode.
