### ISSUE TITLE
How does Broadway "parallel" definition behave across few stages

### ISSUE THREAD

**Issue by dotants** [k2view-academy/K2View-Academy#734]
Hi
If I mark a few consecutive stages in a flow as "parallel", will Fabric start a new thread on each stage, or will the same thread execute the few stages?

![image](https://user-images.githubusercontent.com/74860302/215987613-eabe4762-da95-4d3b-b91f-df0435470ce6.png)

**Comment by natalylic** [comment]
We use thread pool, so there is a chance to get the same thread. However this is not guarantied.
