### ISSUE TITLE
Does Fabric have integrated reporting modules for successful/unsuccessful API responses?

### ISSUE THREAD

**Issue by BogdanSTF** [k2view-academy/K2View-Academy#737]
Hello Team,

Does Fabric have integrated reporting modules for successful/unsuccessful API responses?

Kind regards,
Bogdan

**Comment by lionbro1** [comment]
Hi,

Fabric report JMX counters, under Transactions -> webserviceCalls and webserviceErrors, it can be monitored by DataDog or Grafana or whatever monitoring tool used on your account.

If these statistics doesn't fit to your needs, you can write your custom statistics.

You can read further on this article

https://support.k2view.com/Academy/articles/34_JMX_statistics/01_JMX_overview.html

https://support.k2view.com/Academy/articles/34_JMX_statistics/03_JMX_custom.html
