### ISSUE TITLE
Tokenization - Missing JARs in 7.*

### ISSUE THREAD

**Issue by barakgk2view** [k2view-academy/K2View-Academy#738]
In the Tokenization project there are 2 imports
    import com.k2view.fabric.common.encryption.Base64;
    import com.k2view.fabric.common.encryption.Hasher;
When moving the project to 7.0 it does not pass compilation, were these JARs moved to a different package or removed from Fabric?

**Comment by lionbro1** [comment]
These classes were not changed in Fabric 7.0. However all Fabric classes starting on Fabric 7.0 are encrypted, only the ones we exposed as UserCode were not encrypted, you are not supposed to call these classes from the implementation, use a pure Java code or if it is a must to be part of Fabric package please contact the product team to explain why we should add them as UserCode.
