### ISSUE TITLE
ports used by ADI

### ISSUE THREAD

**Issue by AlexMaziya** [k2view-academy/K2View-Academy#74]
Is there a document which specifies all the ports ADI use and their propose?

Does ADI use the following:
port 80 - standard http
port 21 -standard ftp

**Comment by lionbro1** [comment]
LINUX: 

The following ports needs to be open: 

•	3210 & 3510  – Used for our web services (apache) 
•	5432 & 5532	– Used for PostgreSQL. 
•	3389	– Used by RDP  
•	22 		 – SSH/SFTP 


WINDOWS: 

The following ports needs to be open: 

•	3210	– Used for our web services (apache) 
•	3213	– Fabric 
•	5432	– Used for PostgreSQL. 
•	3389	– Used by RDP
