### ISSUE TITLE
Is there a way to disable sync of a single common table?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#742]
In LU schema we have an option to disable populations for tables that we don't want to sync.
Is there a similar direct option to disable sync of specific common tables? Or do we need to use Decision functions to achieve it?

**Comment by lionbro1** [comment]
You can't disable a population in reference table, like in the LU schema.

In order to control reference table sync you can either control it with a decision function or time interval, or define the sync mode as NONE and sync it manually when needed by using the ref_sync command.
