### ISSUE TITLE
[SQLITE_READONLY]  Attempt to write a readonly database from population

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#748]
Fabric 6.5.2

I created a population flow with order 999 to run after all other populations, like an enrichment function.

This flow does a lot of steps, call inner flows, read from a table in Cassandra and update tables within the LUI by mapping flows (not population flows).

When executing a get for the first time, all works accordingly but I always get the error below.
I mean, all changes within the LUI are performed.

![image](https://user-images.githubusercontent.com/639119/218766720-7c3df366-6773-443a-b618-9e28d09204eb.png)

If I execute get again, I get no error (SKIP) and all the changes are there.
I don't know to what "readonly database" it refers to.

Any clues?
Please advise.
Thanks.

**Comment by lionbro1** [comment]
As discussed, closed, should be track as a freshdesk ticket.
