### ISSUE TITLE
How to change admin password in fabric using fabric command line interface?

### ISSUE THREAD

**Issue by alexmessel** [k2view-academy/K2View-Academy#75]
How to change admin password in fabric using fabric command line interface?

**Comment by lionbro1** [comment]
Hi,

You need to create another user with admin privileges and switch with the existing one.

You can find step by step instructions on the following document 

https://k2view.sharepoint.com/:w:/r/sites/KS/Internal%20Assets/Office%20of%20the%20CTO/Product%20Management/Product%20documents/User%20creation%20and%20changing%20access.docx?d=w53696337f68042bb9fba0152bf294ee0&csf=1&web=1&e=ylACSY

**Comment by lionbro1** [comment]
adding a link to freshdesk ticket with document attached
https://k2view.freshdesk.com/a/tickets/17948
