### ISSUE TITLE
How long does the LUI stay in storage directory when the Cache Location is set to Storage?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#752]
1. If we set the Cache Location to Storage in LU property, how long will the LUI stay in ${FABRIC_HOME}/storage/fdb_cache/? 
2. Will it follow the same MDB_DEFAULT_SCHEMA_CACHE_SIZE property in config.ini?
3. Is it possible to set MDB_DEFAULT_SCHEMA_CACHE_SIZE per LUI?

https://support.k2view.com/Academy_6.4/articles/32_LU_storage/02_storage_management.html

**Comment by lionbro1** [comment]
1. It will stay in cache according to the cache size definition, if it will get to the limit a new LUI will override the oldest one.

2. Attached the full article from knowledge base

Fabric enables you to modify the default location of the cache per Logical Unit using the MDB_DEFAULT_CACHE_PATH variable in the [fabricdb] section of the config.ini and the [LU Schema's Cache Location property](https://support.k2view.com/Academy/articles/03_logical_units/04_LU_properties.html) as follows:

When the Cache Location is set to Default, store the cache per the definition of MDB_DEFAULT_CACHE_PATH in config.ini. The default value in config.ini is /dev/shm/fdb_cache/ but it can be changed to another location.
When the Cache Location is set to Storage, store the cache under the storage folder in Fabric ${FABRIC_STORAGE}/storage/fdb_cache/ if this location exists. If this location does not exist, store the cache in ${FABRIC_HOME}/storage/fdb_cache/.
The definition of the ${FABRIC_STORAGE} path can be updated via the fabric-server-start.sh script using the -DFABRIC_STORAGE variable.
If the default path in the config.ini is updated to another path, the cache is always located according to the config.ini regardless of the LU Schema property setting in the Fabric Studio.
Note that both the config.ini and the Fabric Studio configuration changes become effective only after Fabric is restarted. On the first LU deployment the restart is not required.

3. No
