### ISSUE TITLE
Support Interface to Graph DB - Amazon Neptune

### ISSUE THREAD

**Issue by barakgk2view** [k2view-academy/K2View-Academy#753]
1) Do we support interface to graph DBs and in particular Amazon Neptune
2) Do we have the capability to generate data in TDM to graph DBs and in particular Amazon Neptune

**Comment by taliei** [comment]
The graph DBs are not fully supported by the TDM product. The interface connection can be supported using a JDBC connection. However- building an LU with a hierarchical structure can be an issue. Perhaps we can be a pipeline process and just do masking on the documents, but it's not a trivial task.
