### ISSUE TITLE
Upgrade Oracle jdbc jar to v21+ to support FIPS connection flag: CONNECTION_PROPERTY_THIN_NET_SET_FIPS_MODE

### ISSUE THREAD

**Issue by JohnH-K2View** [k2view-academy/K2View-Academy#758]
Current Oracle jdbc driver included with fabric (fabric v 7.0.1) is v19.3; which does not yet support the FIPS connection property [CONNECTION_PROPERTY_THIN_NET_SET_FIPS_MODE](https://javadoc.io/static/com.oracle.database.jdbc/ojdbc8/21.1.0.0/oracle/jdbc/OracleConnection.html#CONNECTION_PROPERTY_THIN_NET_SET_FIPS_MODE)

What's the roadmap to upgrade to v21+ of the embedded Oracle jdbc drivers?

**Comment by lionbro1** [comment]
Hi,

We don't plan Oracle driver upgrade in the coming release 7.1 that is planned to be released on the coming month.

Will handle it as a backlog request, will try to push it for Fabric 7.2 release that will be released on the coming months.

Meanwhile you can create a new DB type based on template and refer it to Oracle 21 driver.
