### ISSUE TITLE
What version of JVM is recommended for Fabric?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#765]
Fabric version 6.5.9
What version of JVM is recommended for Fabric? 
Do we support jdk11?

**Comment by lionbro1** [comment]
Version 6.5.9 doesn't work with JDK 11.

The mapping of Fabric releases and JDK is the following:

Fabric 6.5.9 -> JDK8
Fabric 7.0.X -> JDK17, on the Studio side you can still work with JDK8 for backward compatability to ensure no compilation errors after the upgrade.
