### ISSUE TITLE
how to change log level in version 6.1.1 on Fabric local ? 

### ISSUE THREAD

**Issue by tamarzohar** [k2view-academy/K2View-Academy#77]

**Comment by lionbro1** [comment]
In version 6.1 you need to follow these steps:

1. Under project folder/FabricHome/config/modules - change log:type=STDOUT to log:type=LOGBACK.
2. Under project folder/FabricHome/config/logback.xml replicate the INFO section to STDOUT.
3. Under project folder/FabricHome/config/logback.xml change the INFO section to DEBUG.

In version 6.2 modules already referring to LOGBACK, you just need to change the relevant section in logback.xml from INFO to DEBUG.
