### ISSUE TITLE
Passing DBCommand Actor result to Java function with LinkType as Value doesnot have the expected TYPE.

### ISSUE THREAD

**Issue by sujanjavvaji** [k2view-academy/K2View-Academy#772]
Passing DBCommand Actor result to Java function with LinkType as Value doesn't have the expected TYPE.  It is expected to give array of objects but it is giving different types like  
 
com.k2view.broadway.util.DescribedIoResult 
OR
com.k2view.broadway.lookahead.LookaheadDescribed@1bf29911

Kindly please address this issue

**Comment by natalylic** [comment]
The **DbCommand** Actor doesn't return an array, it returns a result set.
Thus, you need to define your input as ```Iterable<Map<String,Object>>```
