### ISSUE TITLE
cannot change value of TASK_ABORT_GRACE_MS parameter 

### ISSUE THREAD

**Issue by tarikh03** [k2view-academy/K2View-Academy#773]
there is a parameter TASK_ABORT_GRACE_MS that was added to 6.1, which give grace period to job to close connections before killing the job.

![image](https://user-images.githubusercontent.com/47483757/222428733-abce9cf8-d209-4a3d-bab9-0c8d600f3729.png)

 
in 6.4.9 I don’t see it in config.ini, and it also doesn’t take effect when I add it to the config.ini.

currently the value for this field is 5000.

![image](https://user-images.githubusercontent.com/47483757/222428759-57c27183-f3e6-480b-a234-d3339e1bcf6a.png)

change in config.ini and restart were done.

 
![image](https://user-images.githubusercontent.com/47483757/222428786-8f055a72-55fa-43cb-8e79-cef8a570defe.png)

**Comment by lionbro1** [comment]
You should add it under [fabric] section in config.ini, not under jobs section.
