### ISSUE TITLE
Rollback to previous code after a full deployment

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#775]
Fabric 6.5.2

There is an environment where project was always deployed from Studio instead of a package-based deployment using `buildAndDeploy.sh`.

Version control was not enforced and there is no guarantee that current repo contains all the code that is currently deployed to the environment.

Version control is now being enforced, and we would like to do a full, repo-based, package-based, deployment using `buildAndDeploy.sh`.

Although effort was made to ensure that code is complete and up-to-date on repo, we would like to have a rollback process to revert the deployment, in case it is necessary.

How could this be done?

Would backing up `$K2_HOME/storage/lu` prior to the deployment, help?

Would saving the list of versions (`$K2_HOME/storage/lu/<LUT>/<VERSION>/ludb.jar`) to a file so it can be compared later to determine the new versions that were added, help?

What could be updated in Cassandra (e.g. `k2system.k2_lut_info`, `lut_version` vs `lut_last_version`)?

How to ensure that reverted version would be resynchronized across all nodes of the cluster (e.g. `k2system.k2_lut_info.require_sync`)?

Should the updates in Cassandra be done while all Fabric instances are down?

Please advise.
Thanks.

**Comment by lionbro1** [comment]
Hi,

It is not recommended to use these workarounds, it was never tested and not the official product solution.

Perhaps the best solution is to download the project from the select environment and save it somewhere as a copy

http://host_name:3213/lut?lutName=luname&token=token​ - will allow you to get the deployed project downloaded to your laptop.

**Comment by feamcor** [comment]
And how would I redeploy those JARs?
Using the `deploy` command?

**Comment by lionbro1** [comment]
buildanddeploy script
