### ISSUE TITLE
Changing In K2Studio the Debug environment to a different Cassaandra

### ISSUE THREAD

**Issue by barakgk2view** [k2view-academy/K2View-Academy#779]
How can I change in the K2Studio the debug to point to a cassandra that is different then the one on the windows (e.g. a cassandra  on a Linux docker).

**Comment by feamcor** [comment]
I would like to extend this question to how to point to different Fabric and Cassandra, preferably on Linux, probably on containers, without losing any of the features of the Debug Server on Windows (e.g. Broadway debug).

**Comment by lionbro1** [comment]
Hi,

First step is to mark the Debug Env check box in the user preferences to the environment you want to debug on.

Secondly, to debug Broadway, etc.. on the remote Linux environment, please follow this Q&A
https://github.com/k2view-academy/K2View-Academy/issues/592
