### ISSUE TITLE
Querying Data from Another LUT - Where Do I Define the 'get'

### ISSUE THREAD

**Issue by benkipnis** [k2view-academy/K2View-Academy#78]
I have two logical unit types, with the second sourcing some data from the first and then adding more source data to it.  I have made a Fabric connection and can create the query, but where do i put the 'get' statement so the system knows which instance to query from?

Thank you!

**Comment by taliei** [comment]
Hi.

You can define a root function on the population of the second LUT. The root function needs to execute the get instance for the first LUT and query its data.

Tali
