### ISSUE TITLE
Using of Regular function from Utilities category in the Root function of the same LU

### ISSUE THREAD

**Issue by gingerat** [k2view-academy/K2View-Academy#79]
Hi,
is the Root function supposed to access the Utility function inside the same LU?
I'm receiving the "cannot find the symbol" error while trying to call to the Utility function from the code of Root function.
Import of com.k2view.cdbms.usercode.lu.[LU_NAME].Utilities.* doesn't  help a lot.

In spite of this I'm able to use this function in the population via visual layout - but not inside the Root Function code. And I'm trying to avoid excessive entities and simplify the program.

**Comment by taliei** [comment]
Hi.

When invoking a project function- you need to add the required import. Please open the Java file of the root function using IntelliJ, locate your mouse on the invoked function (marked by red), click ALT+ ENTER, and select the option of adding the required import. 
For example - if you invoke fnTest function, defined under the test category of CRM- the following import is added to the Java file: 
import static com.k2view.cdbms.usercode.lu.CRM.test.Logic.fnTest;

Note that you can edit the import as follows if you need to invoke several functions under the same category:
import static com.k2view.cdbms.usercode.lu.CRM.test.Logic.*;

Tali
