### ISSUE TITLE
Trace records correlations to thread

### ISSUE THREAD

**Issue by yevgenibelaigorod** [k2view-academy/K2View-Academy#793]
Hi 
Wanted to know what is a way to set  trace so  it reflect record  correlation to thread and relevant "sub-tree" in viewer

For example to simulate parallel activities i used BW parallel functionality to invoke inner flow 
In log of fabric its clearly shown different threads 
INFO  2023-03-20 19:24:31,399 [LID601000000000059] [pool-testForMultiThread-0] c.k.b.a.b.Logger - Begin of SampleFlow 1
INFO  2023-03-20 19:24:31,399 [LID601000000000058] [pool-testForMultiThread-1] c.k.b.a.b.Logger - Begin of SampleFlow 2
INFO  2023-03-20 19:24:32,402 [LID601000000000059] [pool-testForMultiThread-0] c.k.b.a.b.Logger - End of SampleFlow 1
INFO  2023-03-20 19:24:32,402 [LID601000000000058] [pool-testForMultiThread-1] c.k.b.a.b.Logger - End of SampleFlow 2

But when i am looking on trace file its all flat under main 0f0b4ec8-1699-42ed-9693-a5fe539b1402 transaction and same it shown in viewer

0f0b4ec8-1699-42ed-9693-a5fe539b1402,1679340271399,7397,4,interim,broadway,info/|/testForMultiThread/|/actor start/|/SampleFlow/|/Stage 3/|/Logger1<|>
0f0b4ec8-1699-42ed-9693-a5fe539b1402,1679340271399,7397,4,interim,broadway,info/|/testForMultiThread/|/actor end/|/SampleFlow/|/Stage 3/|/Logger1/|/0/|/<|>
0f0b4ec8-1699-42ed-9693-a5fe539b1402,1679340271399,7397,4,interim,broadway,info/|/testForMultiThread/|/actor end/|/SampleFlow/|/Stage 3/|/Logger1/|/0/|/<|>
0f0b4ec8-1699-42ed-9693-a5fe539b1402,1679340271399,7397,4,interim,broadway,info/|/testForMultiThread/|/actor start/|/SampleFlow/|/Stage 3/|/Sleep1<|>
0f0b4ec8-1699-42ed-9693-a5fe539b1402,1679340271399,7397,4,interim,broadway,info/|/testForMultiThread/|/actor start/|/SampleFlow/|/Stage 3/|/Sleep1<|>
95b70d49-7f0f-4a50-8cda-d3ec7b3c8e9e,1679340272061,8059,1009,interim,jobsReconcile,debug/|//|/cron list loaded, size = 0<|>
95b70d49-7f0f-4a50-8cda-d3ec7b3c8e9e,1679340272061,8059,1009,interim,jobsReconcile,debug/|//|/list loaded, size = 0<|>
39da4b20-d2ec-4006-bc31-85ceb3f6ef01,1679340272061,8059,0,start,jobsReconcile,debug/|//|/JobsReconcile<|>
0f0b4ec8-1699-42ed-9693-a5fe539b1402,1679340272402,8400,1007,interim,broadway,info/|/testForMultiThread/|/actor end/|/SampleFlow/|/Stage 3/|/Sleep1/|/1003/|/<|>
0f0b4ec8-1699-42ed-9693-a5fe539b1402,1679340272402,8400,1007,interim,broadway,info/|/testForMultiThread/|/actor start/|/SampleFlow/|/Stage 3/|/Logger2<|>
0f0b4ec8-1699-42ed-9693-a5fe539b1402,1679340272402,8400,1007,interim,broadway,info/|/testForMultiThread/|/actor end/|/SampleFlow/|/Stage 3/|/Logger2/|/0/|/<|>
0f0b4ec8-1699-42ed-9693-a5fe539b1402,1679340272402,8400,1007,interim,broadway,info/|/testForMultiThread/|/stage end/|/SampleFlow/|/Stage 3/|/1003/|/<|>
0f0b4ec8-1699-42ed-9693-a5fe539b1402,1679340272402,8400,1007,interim,broadway,info/|/testForMultiThread/|/actor end/|/SampleFlow/|/Stage 3/|/Sleep1/|/1003/|/<|>
0f0b4ec8-1699-42ed-9693-a5fe539b1402,1679340272402,8400,1007,interim,broadway,info/|/testForMultiThread/|/actor start/|/SampleFlow/|/Stage 3/|/Logger2<|>
0f0b4ec8-1699-42ed-9693-a5fe539b1402,1679340272402,8400,1007,interim,broadway,info/|/testForMultiThread/|/actor end/|/SampleFlow/|/Stage 3/|/Logger2/|/0/|/<|>

Thanks
Yevgeni

**Comment by lionbro1** [comment]
Hi,

It seems as a defect, please open an incident ticket in freshdesk with all the details.
