### ISSUE TITLE
Trace file name for viewer

### ISSUE THREAD

**Issue by yevgenibelaigorod** [k2view-academy/K2View-Academy#794]
Hi 

The trace viewer is great tool to review the trace 
One thing which will improve the UX - when loading the file to viewer to add on result screen in header instead just "Trace" - the file that is being viewed or trace name
When  openings multiple traces for comparison it will be very helpful 

Thanks
Yevgeni

**Comment by lionbro1** [comment]
sounds as good idea, however Q&A is not the platform to ask for product enhancements.

Please open a freshdesk ticket and classify it as a CR.
