### ISSUE TITLE
Trace record parent/child corelation

### ISSUE THREAD

**Issue by yevgenibelaigorod** [k2view-academy/K2View-Academy#795]
Hi 

Is there way to corelate parent to child transaction  records  in trace ( different transaction ids)?
Example i put in screenshot is from TDM
Job checkMigrateAndUpdateTDMDB - run multiple queries  and when this is the  only this is ruining on server the full tree is shown ( job executes queries and ending )
But if  i will have additional activities on the node which will write records in between -is there any way to build correlation when processing file  - meaning transaction  ending with  8ef79 ( job ) correlated with child transaction ending with  8cdc0 for example  . 

Thanks
Yevgeni

![image](https://user-images.githubusercontent.com/65720642/226461757-dad43e0b-5fd1-4ef3-9398-eb74c7e9cb43.png)

**Comment by lionbro1** [comment]
Hi,

Currently it is not supported.
