### ISSUE TITLE
Db.Statement Objects

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#798]
Fabric 6.5.9

There is a trigger function that is being used in a data pipeline use case to determine if a row was changed and stamp some control info into a control table within the LUI.

In order to optimize the overhead of the trigger, I was wondering if `Db.Statement` can be initialized and reused in advance (as a static), even though every LUI would be a different database.

If so, should they be initialized using `fabric()` or `ludb()`?
Or should another method be used (e.g. bypassing to JDBC through `UserCode.getConnection("INTERFACE")`)?

Please advise.
Thanks.

**Comment by eyalk2** [comment]
Statement cannot be set as static and be reused. Every statement is connected to a connection. Trying to use it might cause memory leaks or other unexpected affects. In addition, it is not sure that even if could using it, it cloud bring to optimization.
