### ISSUE TITLE
Population DbLoad Batch

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#800]
Fabric 6.5.9

There is a trigger function that is being used in a data pipeline use case to determine if a row was changed and stamp some control info into a control table within the LUI.

Would setting population's `DbLoad` property `batch` to `true` bring any improvement?

Please advise.
Thanks.

**Comment by natalylic** [comment]
Batch mode is not helpful for Fabric interface since its goal is to save time over the network and it will not aggregate all executions into a single trigger.
