### ISSUE TITLE
Batch ALLOW_MULTIPLE

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#801]
Fabric 6.5.9

Documentation about `ALLOW_MULTIPLE` flag is brief and not clear to me.
Please elaborate what exactly it entails and provide an example of when it would be beneficial.
BTW, in some pages of the documentation it refers to `allow_multiply` which is a typo.
Thanks.

**Comment by natalylic** [comment]
Hello and thank you for pointing out the typo! It has been fixed.
When ALLOW_MULTIPLE is set to true, a unique UID is generated for a batch process, allowing running the same command again - before the first command is completed. The reason for that can be for example, when the subset of instances is created based on a random entity selection.
