### ISSUE TITLE
Fabric Linux Ports functionality

### ISSUE THREAD

**Issue by AlexMaziya** [k2view-academy/K2View-Academy#804]
I would like to receive detailed documentation for each Fabric Linux Ports what is their purpose. 

Fabric Linux Ports in HW requirements under:
[https://support.k2view.com/Academy/articles/98_maintenance_and_operational/Hardware/2_All_Environments/03_hardware_req_for_prod.html](url)

For example:
3213 - Fabric WS/Admin port without SSL
9443 - Fabric WS/Admin port with SSL
5124 - Fabric deployment port
etc...

**Comment by eyalk2** [comment]
See the attached diagram. 
Note: These ports - at support site and at the at the attached are the defaults. Can be changed when needed

![Fabric ports](https://user-images.githubusercontent.com/74238756/228145938-7c2bcb04-8450-482b-a2d9-dfdee3678f8a.png)
