### ISSUE TITLE
Is there a way to prevent JobsReconcile from touching specific jobs?

### ISSUE THREAD

**Issue by dotants** [k2view-academy/K2View-Academy#807]
Hi

Is there a way to stop JobsReconcile from trying to move a specific job to another node?

**Comment by feamcor** [comment]
Start the job with affinity to a specific node (maybe its IP address)?
JobsReconcile should respect that.

**Comment by lionbro1** [comment]
Hi,

As mentioned above, use the affinity to control it when starting the job.
