### ISSUE TITLE
Tuning INSTANCE_CHUNK_SIZE

### ISSUE THREAD

**Issue by JohnH-K2View** [k2view-academy/K2View-Academy#81]
For a project with larger LU Instance sizes (some instances over 2GB): Fabric has in config we have a parameter INSTANCE_CHUNK_SIZE which controls how many segments are created for storage to Cassandra.  Default is 10MB.

In testing changes to this parameter, we noticed as the size is increased, it potentially causes failures in Cassandra related to other parameters configured in cassandra.yaml:

Failed to apply mutation locally : {}
java.lang.IllegalArgumentException: Mutation of [X] is too large for the maximum size of [Y].

We've found that when setting the instance chunk size; we need to set commitlog_segment_size_in_mb to be slightly larger than twice the INSTANCE_CHUNK_SIZE.

What are best practices for the maximum thresholds of these related values?  For large instances, we want to minimize the number of rows; but as commitlog_segment_size_in_mb increases what are tradeoffs to Cassandra performance?

**Comment by lionbro1** [comment]
Our best practice is to stay with the default (10 MB), it should give you the best performance. why you tried to change it? What is the new value you used that caused the error above?

**Comment by JohnH-K2View** [comment]
After testing; we saw no performance changes in using large chunk sizes.  We'll keep the default.
