### ISSUE TITLE
Aerospike as Storage for Fabric

### ISSUE THREAD

**Issue by barakgk2view** [k2view-academy/K2View-Academy#813]
Can we use Aerospike as the Fabric storage instead of Cassandra? 
Not replacing the operational DB of Fabric.

**Comment by lionbro1** [comment]
Hi,

Fabric currently doesn't support it, however our product is opened to introduce it as a plug-in by a pure implementation effort.
We estimate it as 2-3 weeks of work, as a side note we suggest to evaluate if Aeropike is the right platform as a blob storage, such as : Azure BLOB store, S3, minio, etc.
