### ISSUE TITLE
Waiting Threads on LU table population

### ISSUE THREAD

**Issue by ajay44u** [k2view-academy/K2View-Academy#815]
Would like to know if the statistics page displays the waiting threads per interface used in the LU populations?
	
For Example if a migrate was initiated with 60 workers, and the source interface "A" from environment with max_connections 10.
	Is there stat that highlights the interface A has a waiting threads of number 50 at a given time.

**Comment by eyalk2** [comment]
No, Fabric does not provide this info of how many are waiting.
