### ISSUE TITLE
Configuration  of __consumer_offsets topic traffic by IIDFinder consumer

### ISSUE THREAD

**Issue by AlexMaziya** [k2view-academy/K2View-Academy#82]
Is there a way to limit the traffic of IIDFinder to __consumer_offsets topic?
Instead of sending acknowledgement after every record to a specific time interval / offset?

**Comment by Krutyolkin** [comment]
Hi,
  The Kafka commit is translated into sending a message to Kafka  __consumer_offsets.
By default, this topic is partitioned and different partitions are managed by different Kafka brokers (servers). So, if in your case one of the Kafka brokers is overloaded by commits it should be associated with some other Kafka topic, for which commits are made.
Could you find that topic name?

In general, we cannot commit at the time interval but can change the commit rate, depending on the topic name.
Some IidFinder topics are managed by iifConfig.ini parameter KAFKA_POLL_RECORDS, and increasing it will reduce the load.
If delta topics are involved, change is required in the Studio interface configuration. 

Best regards,
Sergey.
