### ISSUE TITLE
Timeout GraphIt Execution

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#821]
Fabric 6.5.9

In continuation to issue #203...

Would it be possible to wrap the call to GraphIt on a Future and try to get it under a predefined timeout?

Do you foresee any conflict with Fabric framework?

Example:
```java
    ...
    ExecutorService executor = Executors.newSingleThreadExecutor();
    Future<Object> future = executor.submit(() -> {
       return graphit(...);
    });

    try {
        Object result = future.get(30, TimeUnit.SECONDS);
    } catch (TimeoutException e) {
        // Task timed out
    } catch (InterruptedException | ExecutionException e) {
        e.printStackTrace();
    }

    executor.shutdownNow();
    return result;
```

Please advise.
Thanks.

**Comment by eyalk2** [comment]
This is not possible as Fabric based on ThreadLocal info and when you run it in executer you are out of this context.
This is relevant not only for Graphit.

For running things in parallel you shall use Broadway flow with parallel option (stage's property). For example, has several actors on that stage - Graphit actor, LU function actor, and third actor - another Graphit. set parallel to 3 and they will run in parallel. 

You may also consider using, according to the need and use case, you can use innerFlowAsync actor

**Comment by feamcor** [comment]
Eyal, my enquiry is not about running in parallel, but about establishing a timeout for the graphit execution. For instance, I would like GraphIt to be interrupted after 5 seconds. The code provided is just an example of what could have done. Please advise if the platform has some mechanism to achieve that (but not the approach listed on #203). Thanks.

**Comment by eyalk2** [comment]
For this you can use the following:

        try(var s = FabricTask.current().timeout(30000)){
            graphit("myGraphit.graphit");
        }
