### ISSUE TITLE
fabric webservice timeout

### ISSUE THREAD

**Issue by k2viewRami** [k2view-academy/K2View-Academy#826]
what is the parameter to tune fabric webservice timeout?

**Comment by eyalk2** [comment]
what do you mean "fabric webservice timeout"? if there is a client that call to a Fabric WS then it is its role to set timeout.

**Comment by k2viewRami** [comment]
i mean if from the server, do we have timeout to kill the session if it's extend X time ?

**Comment by eyalk2** [comment]
So the case is: 
1. client that call to Fabric WS, right?
2. WS is doing some internal process inside Fabric which takes long time and you wishes to stop waiting to this?

This can be achieved programmatically (timeout does not come from app itself, like Fabric, app GW sometimes have such - 504 response).
Please refer to https://github.com/k2view-academy/K2View-Academy/issues/821

**Comment by k2viewRami** [comment]
so there is no such paramater ? :)

**Comment by eyalk2** [comment]
no,
as I wrote, in server perspective point of view there is no interest to having that. This is client to manage timeouts.
