### ISSUE TITLE
best practice to sync a single LUI asynchronously

### ISSUE THREAD

**Issue by JohnH-K2View** [k2view-academy/K2View-Academy#827]
Migrate or batch command can be run with async=true, and we can pass a single ID as the value to sync, this will let fabric sync a single LU instance without requiring the current session to wait for it to complete.   We use this for partent / child type relationships (parent LU needs to have one or many other LU types sync, e.g. an account and many users, and we want to sync each related USER LU so it's ready for a future web service.  

However if there are many single instances we want to sync this way, we don't want to create a batch command for each, as then the batch tables fill up with many small jobs.  Is there an alternate way to have fabric start a new session to sync a single LU instance in the background without requiring the parent LU or web service to wait for that sync to complete and without creating the overhead of a batch / migrate job?

**Comment by feamcor** [comment]
On 6.5.9, `batch` command has `ALLOW_MULTIPLE` flag (default is `false`). See #801.
If I understood it correctly, it would allow you to keep __appending__ executions to the same batch (because of same batch UID).
I might be totally wrong but that could be an option.
Anyway, let's wait for product to advise :smile:
Cheers.

**Comment by eyalk2** [comment]
The challenge is with brining all the children of the parent? 
If so - cannot you use SQL or IG to know their list and run as batch (async)

**Comment by JohnH-K2View** [comment]
allow_multiple flag will have fabric re-run the same batch; but since I would have different IIDs I'd need to have it driven off of a table to execute differently each time.

Current approach is to do a batch migrate, the issue is not that there may be too many children, but that we're creating too many batch jobs (often we'll only have one child LU instance per parent; If I have 1M+ parent LUIs that means 1M+ batch jobs; which then makes queries against the batch tables much more expensive.

**Comment by eyalk2** [comment]
We are trying to understand your expectation / wishful from Fabric as product in such case, without specific implementation.
How Fabric knows what you want to do on second hop, i.e. to bring the children?
BTW - cannot you bring during the same migrate both parents and children?

**Comment by JohnH-K2View** [comment]
Parent and child are different LU types, so they can't be the same batch.

This is only a performance request , a migrate on a single instance achieves the functional goal. But at the cost of adding  rows to the batch tables. If number of batches is large (100k+ / day), many queries against that table slow down. Having a lower overhead way to asynchronous get a single instance ID that doesn't require starting a job is the request. This async get could (should?) be on the same node, I just don't want it to delay completion of the original task.

John Hereford
Mobile: 214-763-3557

Autocorrect sometimes makes me type things I didn't Nintendo.
________________________________

**Comment by feamcor** [comment]
You can build a similar approach with Broadway and use Kafka topics for keeping the instance group, which is low overhead and can be distributed among nodes according to the number of partitions.

**Comment by lionbro1** [comment]
you can also use common tables to store the list if it's not huge and query the common table in the batch command

**Comment by eyalk2** [comment]
Closing this Q&A.
we have 2 solutions for implementation.
we also set a meeting to hear John's suggestion for the product

**Comment by JohnH-K2View** [comment]
Follow-up with an eventual solution we found to work better.

Instead of calling a regular get on the parent LUI; we built a broadway flow for "get parent then children".  This runs a fabricGet on the single parent LUI, and then does a count of number of children expected given the data in the parent LU. If there are a small number, the flow iterates over a fabricGet actor for those child LUIs. If the count is above some threshold it instead creates a migrate.  This is more efficient than calling the individual migrates as we can be certain the same node syncs the single child if there's only one or two (which already has parent LUI in context; where a migrate might happen on another node, requiring that node to pull the parent LUI form cassandra).

**Comment by eyalk2** [comment]
Thank for the info.

As we spoke one of the main pains is that jobs and batches tables become huge and reading from them get very slowly.
Lion has a suggestion for this - reduce the TTL of these tables, for example for day or two

**Comment by JohnH-K2View** [comment]
Excellent suggestion, I'll test lowering TTL values as well for the cases where we have many broadway & migrate jobs.

**Comment by smokyMount** [comment]
Maybe also add a process to copy its data before it gets deleted due to TTL? Its sometimes helpful when debugging an issue from a few days back.
