### ISSUE TITLE
How to activate Studio license for windows with no internet access

### ISSUE THREAD

**Issue by NirKehat** [k2view-academy/K2View-Academy#828]

**Comment by lionbro1** [comment]
Hi Nir,


<img width="798" alt="Screenshot 2023-04-27 at 7 48 55" src="https://user-images.githubusercontent.com/21338328/234762723-953295a1-b0f6-4eba-925b-1247336e1f7d.png">

<img width="741" alt="Screenshot 2023-04-27 at 7 49 13" src="https://user-images.githubusercontent.com/21338328/234762868-615adc01-3cbf-4401-81bd-a21678483e6e.png">

<img width="788" alt="Screenshot 2023-04-27 at 7 49 32" src="https://user-images.githubusercontent.com/21338328/234762974-90d079d0-b666-42c0-b98f-1d3572d6c3aa.png">

<img width="830" alt="Screenshot 2023-04-27 at 7 49 42" src="https://user-images.githubusercontent.com/21338328/234763034-c9ea22ec-58eb-48d0-ba73-3e0a323268e1.png">

<img width="724" alt="Screenshot 2023-04-27 at 7 52 51" src="https://user-images.githubusercontent.com/21338328/234763129-e45193e9-9889-4bf9-975f-805771c5e4e7.png">
