### ISSUE TITLE
Broadway Subscriber actor return key

### ISSUE THREAD

**Issue by tarikh03** [k2view-academy/K2View-Academy#829]
Subscribe actor is not returning the key, is there a possibility in Broadway to configure Subscriber to print key or timestamp ?

![image](https://user-images.githubusercontent.com/47483757/234788064-4b9b94f7-d22f-45e4-b938-7018e00af262.png)

also, do we have the option to define kafka Deserializer?

**Comment by natalylic** [comment]
In Fabric 7.0.1, a new actor **SubscribeWithMetadata** was added. 
This actor returns the message including its data (‘value’ field) and metadata (timestamp, key, topic, partition and offset fields).

https://support.k2view.com/Academy/Release_Notes_And_Upgrade/V7.0/Fabric_Release_Notes_V7.0.1.pdf
