### ISSUE TITLE
k2batchprocess and k2audit RF

### ISSUE THREAD

**Issue by tarikh03** [k2view-academy/K2View-Academy#83]
k2batchprocess was presented in 6.0, when upgrading to 6.0 or installing, do we have to set RF and DC somewhere or should
we always alter those keyspaces manually after installation is done?

**Comment by lionbro1** [comment]
These keyspaces are generated automatically after upgrading to 6.0, however if you want to change the RF + DC, it should be done manually after the upgrade.
