### ISSUE TITLE
open file when using broadway publisher

### ISSUE THREAD

**Issue by tarikh03** [k2view-academy/K2View-Academy#837]
recently we've been advised to set PUB_POOL_MAX_IDLE_PER_KEY to 0 in order to avoid open files with publishers.

is it due to a defect that will be fixed in the future?

what are the side effects of setting it to 0?

**Comment by lionbro1** [comment]
In 6.5.1-6.5.8 versions this parameter was used also for disabling the Kafka Publishers pool, in 6.5.9 a new parameter was added to manage the publisher pool called PUB_POOL_ENABLED. 

So if you are using 6.5.9 and on, there is no need to set PUB_POOL_MAX_IDLE_PER_KEY to zero as it is controlled by the new parameter.

**Comment by smokyMount** [comment]
Which parameter controls kafka pooling in v7.2.2? There is a PUB_POOL_MAX_TOTAL in config.ini but no PUB_POOL_ENABLED

**Comment by lionbro1** [comment]
PUB_POOL_ENABLED is a hidden parameter under [default_pubsub] section and is set to true by default, we don't recommend changing it.
