### ISSUE TITLE
Connection pooling when MAX_WORKERS_PER_NODE > 1

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#840]
How does connection pooling work when an instance is in sync and MAX_WORKERS_PER_NODE > 1 (say 5) and more than one population from different tables is fetching from same Oracle database? 
Does Fabric open a new session for every population?

Does it behave any differently when instances are synced using Batch command?

**Comment by lionbro1** [comment]
All populations in single instance sync are sharing the same connection per interface.
It means Fabric holds only one open connection per interface per sync at any time.
No meter how many populations are running in parallel.

Of course if you have several workers it means several syncs in parallel, meaning a connection will be opened per interface per worker.
