### ISSUE TITLE
Batch with different number of workers on different nodes

### ISSUE THREAD

**Issue by dotants** [k2view-academy/K2View-Academy#841]
Is it possible to run a batch command on Fabric cluster, where different nodes will have different numbers of workers?

**Comment by lionbro1** [comment]
Yes, the definition of maximum number of workers is done on the node level, it is controlled by MAX_WORKERS_PER_NODE  in config.ini 

You can control the batch number of workers from the Batch Monitor screen however all batches together will not exceed the MAX_WORKERS_PER_NODE on the node level (https://support.k2view.com/Academy/articles/20_jobs_and_batch_services/18_batch_monitor.html).

You can also control the nodes to be involved in the batch process by using the affinity parameter.
