### ISSUE TITLE
Help needed understanding the k2fabric log messages while doing GET

### ISSUE THREAD

**Issue by ajay44u** [k2view-academy/K2View-Academy#852]
I am trying to troubleshoot the k2fabric.log(Level mode - INFO) to understand the action item between the each log message available by a single get from fabric
Would like to know resources(Cassandra/Fabric.. - Read/write) used inside this lifecycle of a single GET.

Below are the message body of the logs file when initiated a get, followed by questions

**c.k.f.s.FabricSession - START - ATTACH IIDF_LU.5455651083**
     **Q**. Any Cassandra reads to validate the user roles/permissions? (Should this be done at every get irrespective of sync modes/new session)

**c.k.f.s.FabricSession - Access to [IIDF_LU.5455651083] by user admin is authorized.**
	**Q** .  Like to know if there are any validations involved before determining the node request details?

**c.k.f.s.FabricSession - local get request**
	**Q**. Any Cassandra/Fabric selects involved before the below line is printed?
	**Q**. Should we expect here a wait period if there are no available resources(Means if MDB_CONTEXT_POOL_SIZE is exhausted)?
        **Q**. Should there be any isEncrypted check between these lines?

**c.k.f.s.FabricSession - START - sync IIDF_LU.5455651083**
	**Q**. Any Cassandra/Fabric selects involved before the below line is printed?
	**Q**. Should we expect here a wait period if there is a parallel sync on the same instance running?
        **Q**. Should a big sized LU is expected to take more time at this stage?

**c.k.f.s.s.l.SyncExecution - Start operation 'Sync IIDF_LU.5455651083'**
	=> All the Schema Tables will be updated based on sync mode - So Writes to fabric & select on sources should be taken into account, 
        **Q**. Please correct me if anything else is involved here?

**c.k.f.s.s.l.SyncExecution - End operation 'Sync IIDF_LU.5455651083' successfully.  [6984ms]**
	 => Enrichments should be running in between these lines.
	**Q**. Should this region involves writing to cassandra(Saving the Entity/ Updating the Cache tables/ Writing the fabric stats(_k2_objects_info..))

**c.k.f.s.s.l.SyncExecution - IIDF_LU:5455651083 was synced from source**
	**Q**. Like to know if there are any reads/writes involved between these lines.

**c.k.f.s.FabricSession - FINISHED - sync IIDF_LU.5455651083 (UPDATE)**
	**Q**. Like to know if there are any reads/writes involved between these lines.

**c.k.f.s.FabricSession - FINISHED - ATTACH IIDF_LU.5455651083 (UPDATE)**

Please let me know on the above requested details.
Any other important information regarding the lifecycle of a GET that helps the troubleshooting of a GET time will be much appreciated.

**Comment by eyalk2** [comment]
Hi
Lets discuss over a call / chat what is the business or operation objectives behind these questions. Is there any specific need from customer for this? if yes - what is it (i.e. regardless the log lines)
