### ISSUE TITLE
TDM load flows- partial commit (chunks)

### ISSUE THREAD

**Issue by AlexMaziya** [k2view-academy/K2View-Academy#854]
In TDM, is there an option of committing X number of records per table in a load flow and not per entity?
*  Assuming its OK to not have "all or nothing" data load.
** For performance of really large entities load.

**Comment by tahata1** [comment]
Since each table has its own Broadway flow to load its data, you can change the flow and limit each table to maximum number of records to be loaded.

**Comment by AlexMaziya** [comment]
Let me clarify, I have a LOAD flow for customer LU table, this table has 200K records for this entity. 
I'd like to commit every 10K records for this load flow.
* assuming I'm OK to load to target 190K records if the last 10K batch fails (or any other partial commit)

**Comment by tahata1** [comment]
Each table has it own load flow to target. For big tables, the flow can be enhanced to create groups of records from the selected records from Fabric (the 200K in the above example), let's say were each group is 10K records using ArrayGrouper Broadway Actor.
And then Apply the DBLoad on each group separately.
