### ISSUE TITLE
migration distribution between nodes

### ISSUE THREAD

**Issue by mariana-shinnara** [k2view-academy/K2View-Academy#856]
We are trying to reproduce a slow migration issue, the scenario we have is:
we have 2 fabric nodes and 2 LUs, and I want to run migration on both LUs at the same time, first migration is running only on the first fabric node with MAX_WORKERS_PER_NODE=8 defined in the migration command, second migration is regular and should run on both nodes.
MAX_WORKERS_PER_NODE is set to 8 on both config.ini files.
once the migrations are started we know that the total rate (from migrate_summary) for the second migration is slower than expected because the first node is working slower (since two migrations are running on it).
we increased the MAX_WORKERS_PER_NODE to 12/16 on the first node, we expected to total rate to be higher than before, but we see that it balanced between the two nodes and the total rate stayed the same.
is that an expected behaviour? can we get further insight? 

Please advise
thanks.

**Comment by lionbro1** [comment]
Hi,

Scenario is not clear, how come after increasing the number of workers on the first node you see that migrate balanced between the nodes? didn't you run the first migration with affinity defined only for the first node?
If that's the case, I guess you didn't see a performance improvement as CPU or memory was already totally consumed in such a case increasing the number of workers can even damage the performance. please clarify

**Comment by mariana-shinnara** [comment]
I expected to see improvement in the second migration (that is running on both nodes) which didn't happen and that's why I am confused.

before increasing the number of workers:
rate for first node: 10
rate for second node: 16

after increasing:
rate for first node: 13
rate for second node: 13

No, it's not CPU/memory issue. could this be related to something else that I'm missing?

thanks.

**Comment by lionbro1** [comment]
Maybe the bottleneck is the source DB.

Please check this direction.

**Comment by mariana-shinnara** [comment]
I checked and it is not.
from what I understand is that in normal scenarios the expected behaviour is that when I increase the workers number on one node the rate on the same node should go up without affecting the rate on the other node, correct? unless there's something in my environment that's affecting this.

**Comment by lionbro1** [comment]
Correct, this is the expected behavior i guess something in your env. If you want to keep and analyze it further it should be tracked as freshdesk ticket.
