### ISSUE TITLE
degrade process from 7.0 to 6.2 

### ISSUE THREAD

**Issue by tamarzohar** [k2view-academy/K2View-Academy#857]
Hi 
Do we have a degrade process documentation ?

**Comment by lionbro1** [comment]
No, it is not part of QA activities and not recommended.

**Comment by tamarzohar** [comment]
so if we want to do it ( for worse case scenario ) i need to look at upgrade scripts or save cassandra export ?

**Comment by lionbro1** [comment]
save Cassandra export before the upgrade.
