### ISSUE TITLE
is it possible to block CDC in session level for specific LU?

### ISSUE THREAD

**Issue by tarikh03** [k2view-academy/K2View-Academy#858]
in case we want to delete all instances for one LU, and resync them all.
we don't want deletes and inserts to be triggered to ES.

is it possible to turn off CDC for specific LU in session level ?

**Comment by lionbro1** [comment]
Hi,

Yes it can be controlled on the session level, you can add the following set command to the LU root table population:

set CDC_PUBLISH=<true/false>;
