### ISSUE TITLE
Delete LU data without dropping it

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#860]
Hi,
We have a requirement to delete all instances of an LU without dropping it to avoid code redeployment. Is it ok to truncate entity and entity_chunks table for the required LUT? Is there a better way?
Fabric version - 6.5.5, 6.5.9

**Comment by lionbro1** [comment]
It should work if you are using Cassandra as mDB storage layer and there is no iidFinder, otherwise you need to use DELETE INSTANCE command

**Comment by lionbro1** [comment]
Please note that in Fabric 8.5, following capability is added:

Enhanced the DROP LUTYPE Fabric command with a new data_only parameter. Set data_only=Y to drop only the data and retain the LUTYPE definition.
