### ISSUE TITLE
Mutual TLS support for APIs

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#861]
Hello, do we support mTLS for connecting to external APIs (to collect data, etc).

Fabric 7.1 / TDM 8.0

_____________
Best regards,
         Andrey

**Comment by eyalk2** [comment]
Hi
no, we do not.
Yet, if not talking about interfaces,  then you probably can do it in the implementation. 
Meaning - make calls where you shall send the requests with right headers, pointing to the certificate (file and key) as you got from the CA and imported to the fabric machine.
