### ISSUE TITLE
Decompress unencrypted LUI object

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#862]
Fabric 6.5.9 + AWS S3

How can an LUI object copied/retrieved from S3 by decompressed on the CLI?
For instance, to be inspected/checked by `sqlite3` tool.

> Note: LUIs are not encrypted.

I tried `lz4` tools but they fail to process header (error 44).

Does Fabric uses a proprietary decoder to perform block/frame resolution?
Please advise.
Thanks.

**Comment by lionbro1** [comment]
It doesn't matter if mdb is stored in S3 or Cassandra in both cases file should be available in /dev/shm uncompressed after get command.

**Comment by feamcor** [comment]
But that's not what I'm asking.
What if I'm not going to get the LUI from Fabric?
I just want to inspect it, directly, using sqlite3.

**Comment by lionbro1** [comment]
Can you share an example of such a blob so we will evaluate why you don't manage to query it?

Furthermore, please explain why you try to access directly the blob from S3? it is not our recommendation, It is better to use Fabric sync process so it handle all the side effects such as : decryption, uncompress, etc..
