### ISSUE TITLE
MinIO as alternative to S3

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#863]
Fabric 6.5.9

S3 is being introduced as LUI storage layer in a customer project.
I would like to be able to perform a local testing of S3 integration without using AWS.
For such, I installed MinIO on a single node/single volume configuration on docker.

Although API compatible, I don't see on config.ini how to configure the following attributes:
- hostname
- port
- protocol: http, https
- url style: virtual host, path

Is it possible or would require product changes?
Please advise.
Thanks.

**Comment by lionbro1** [comment]
Out of the box we don't support it, as we are using S3 JDK by counting on the lib to allocate the URL, we don't support override the URL in the code it requires product change.
