### ISSUE TITLE
How to convert timestamp in Fabric logs to print in epoch format?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#892]
There is a requirement from customer as follows:

> To convert the timestamp in the fabric logs to epoch 13 digit unix timestamp and print. i.e from "2023-07-18 18:13:33,332"  to "1689704106000"

What changes do we need to make in logback.xml to achieve this?

**Comment by eyalk2** [comment]
This requires further investigation by R&D.
A ticket was opened for it
https://k2view.freshdesk.com/a/tickets/35448
please track there
