### ISSUE TITLE
How to avoid a broadway flow from retyring when it fails after its triggered by an interface listener?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#893]
The expected behavior is that if a flow fails after getting triggered (as a BROADWAY_JOB) by the interface listener, it should be marked as failed in k2_jobs and should not perform any retries.

**Comment by natalylic** [comment]
In your implementation, you need to catch the exception and set "fail job no retry" as follows:
```
try {
    //// YOUR CODE HERE
}
catch (Exception e) {
    failJobNoRetry(e);
}
```

**Comment by natalylic** [comment]
To handle it in the Broadway flow, catch the exception using the **ErrorHandler** actor. Then, to prevent the retries, the ErrorHandler should invoke an Inner Flow that will invoke an **LuFunction** actor with the following code:
`failJobNoRetry(new Exception(message));`

The message can be taken from the exception itself, if needed. This is how the Inner Flow will look like:
![image](https://github.com/k2view-academy/K2View-Academy/assets/62207927/3d0a601c-23fc-4f11-9097-6e632c5300c6)

**Comment by smokyMount** [comment]
Opened a support ticket regarding the same as it did not stop the retries.

**Comment by natalylic** [comment]
Further to additional investigation, the correct code is:

```
import com.k2view.cdbms.jobs.JobExecutor;

JobExecutor.failJob(new Exception(), JobExecutor.FailAnd.noRetry);
```

**Comment by debargha95** [comment]
Hi @natalylic, we want to start a job with an Always Retry configuration. We’re currently using Fabric version 8.4.4_30. Has anything been added in the latest versions that would change the approach, or do we still need to follow the same steps outlined above?

Also, is there any plan to add retry configuration directly to the BroadwayJob actor, such as options for No Retry, Always Retry, or Retry X Times?
