### ISSUE TITLE
"Fetch Schema List" setup for custom interface type

### ISSUE THREAD

**Issue by AlexMaziya** [k2view-academy/K2View-Academy#899]
I have a custom interface type for _IBM Classic Federation_ source which has DB2 characteristics in my Fabric project.
I'm able to query source but when trying to _Fetch Schema List_ option in the interface: getting exception **Unsupported Catalog Call.**

Question 1: What query Fabric studio uses to fetch schema list from an interface (built in vs custom interface type)?
- Can it be modified?

Question 2: What syntax should be used in order to configure schema list extraction from a custom interface type?
- Are there any examples in the KB for studio metadata - SQL queries section?

**Comment by eyalk2** [comment]
By default, it uses the JDBC standard method to get this meta data like schema list.
You can override it using DB Interface type feature.
In your case - right click on the Database Types to create new DB2 from template. Then look for "Studio Metadata" section and override what needed.
when you can on each field - you can see at
 bottom a description about what expected to be brought.
see attached 
![db types](https://github.com/k2view-academy/K2View-Academy/assets/74238756/c8129097-f30b-4c95-9379-65354f611885)
