### ISSUE TITLE
FabricLocal

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#904]
Fabric 6.5.9

How to enable the Fabric Local interface on Studio?
Currently, only Fabric Remote is available.
Development is performed on a shared Windows server by multiple users in parallel.
A Fabric Remote interface is set due to different Session Providers on a GraphIt.
But due to the parallel users, it requires that they developers keep changing the port of the Fabric Remote interface because of multiple instances of the Debug Server running on the same machine (hence, ports 5124, 5125, 5126 and so on).
The ideal here is that this would be an interface to the local Fabric, no matter its credentials and settings.
Please advise.
Thanks.

**Comment by eyalk2** [comment]
Local Fabric is no longer available as interface, as you can call to Fabric directly via implementation.
Note that connection string in that case also contains the port so it would not help you, for your need, to use it as "local" interface, where each fabric knows its port. You had to create different interfaces.
