### ISSUE TITLE
Ref sync and batch process dependencies

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#905]
Hi,

We have setup a new environment and are trying to load LUs using batch command. The batch job was created but did not start loading the LUs. Found in the logs that the batch is waiting for couple of ref tables to sync before it could start the LU loads. Those 2 ref tables were failing to sync because of source permission issue for this new environment.
In the LU schema properties, none of the reference tables are selected under References.

Is this an expected behavior that the batch will not start until all reference tables are updated to READY status? Does it happen for the very first migration in a new environment or is expected to happen for consecutive loads as well?

Below is the message printed in logs for associated with the said batch process:

`INFO  2023-08-02 14:31:44,786 [LID8a5200000000057e] [batchProcessWorker_0365f405-1fec-4e20-8bae-f1a6c5317931_node_0f683301-6645-4afa-9513-d21ce19f11de] c.k.c.c.VerifyRefSync - Wait for tables COMMON.REF_VIS_DATA_TYP,COMMON.REF_VIS_SVC_PROD_ATTR to sync`

Fabric version - fabric-6.5.9_144-HF6

**Comment by lionbro1** [comment]
Sync of instance will wait to a reference table to be synced only if the Reference table is checked in the LU schema level, like in the example below (data_changes table)

<img width="1369" alt="Screenshot 2023-08-02 at 20 06 42" src="https://github.com/k2view-academy/K2View-Academy/assets/21338328/6ea06134-525c-4bc7-bf08-bbd5da466981">

If the dependency is not needed, so uncheck the table and redeploy.

**Comment by smokyMount** [comment]
Hi,
As mentioned earlier, none of the tables are checked in the LU schema level. 
This is the first time I have observed this behavior in any environment.

**Comment by lionbro1** [comment]
In such a case it should not happen. try to reproduce and open a ticket in freshdesk with all the details.
