### ISSUE TITLE
TDM Reference - How to control load data volume

### ISSUE THREAD

**Issue by AlexMaziya** [k2view-academy/K2View-Academy#906]
In case I have Cassandra target which gets write timeouts once a ref Load reference is performed.
What would be the best way to control the volume of the reference data load ?
Is there a way to utilize Cassandra COPY (import/export) commands in the TDM workflow involving Cassandra as a source?

For ver 7.6 & 8.x

**Comment by tahata1** [comment]
Which interface of Cassandra are you using JDBC (DB_CASSANDRA) or Loader (CASSANDRA_LD)?
Did you try using the other interface? In the DBLoad Actor, is the batch set to true? (In case of DB_CASSANDRA it does not work and can cause issues)
Try replacing the interface and change the batch mode and see if that can help.

Regarding COPY, The reference handling in TDM is a general tool, and therefore it cannot support the export/import of each DB type. But you can create your own flow that does the export/import and run it as a post execution flow of a task.
Please note, that we have a new requirement that will probably be in TDM 8.2 to support direct load of tables (without loading first to Fabric), which can be used also for copying reference table, but this is still under design.
