### ISSUE TITLE
6.1.3, rejectInstance custom message

### ISSUE THREAD

**Issue by tarikh03** [k2view-academy/K2View-Academy#91]
Is custom message for rejectInstance not supported anymore?

we are using rejectInstance("I am rejecting this instance!"); to reject instance.
but still we see default message of SyncResponse.INSTANCE_REJECTED.

fabric>get CUS.8568446336;
Instance CUS.8568446336 was rejected and was deleted from Fabric

**Comment by lionbro1** [comment]
Hi,

in order to support skip sync functionality we added on release 6.1 the skipSync() functionality.

You can read further under:

https://github.com/k2view-academy/K2View-Academy/blob/4b10f45420a2749b98fca482abfbc35bd4a1090a/articles/14_sync_LU_instance/09_skip_sync.md

**Comment by tarikh03** [comment]
the skipSync() doesnt provide any reason of the skip.

current customer implementation is using rejectInstance with reason message, but in newer version the same call the message sent to rejectInstance is ignore and only pr-defined message is being shown, which is confusing.

why do we have rejectInstance accepting message as input if not used, the question is if to fetch this message we have to do something extra.
