### ISSUE TITLE
SSH SFTP interfaces to accept private key instead of user and password

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#915]
Fabric 7.1

Customer project needs to interact with target server using SSH and the connection don't use username and password but a trust through the use of private/public keys (-i option of SSH).

How to achieve that in Fabric without resorting to system exec?

Please advise.
Thanks.

**Comment by eyalk2** [comment]
Fabric supports it

Locate the key and then uncomment and update at config.ini the following 2 parameters

#### A directory for ssh keys
#SSH_DIR=${FABRIC_HOME}/.ssh/

#### Private ssh key name
#SSH_PRIVATE_KEY=id_rsa
