### ISSUE TITLE
getInstanceID() is not working inside a Trigger function

### ISSUE THREAD

**Issue by natalylic** [k2view-academy/K2View-Academy#92]

**Comment by natalylic** [comment]
The getInstanceID() is supported only from SYNC execution, trigger can be outside of sync.   
Use  "select iid('luname')" in sync to get the iid.

For example: "SELECT IID('Customer')".

**Comment by ShaniRotemIl** [comment]
getInstanceID is working in the .net version. No plans to support it in cloud too?

**Comment by lionbro1** [comment]
in case of trigger function, "SELECT IID('Customer')" is the right solution for both .Net and cloud

**Comment by ShaniRotemIl** [comment]
Thanks
