### ISSUE TITLE
Session Global Set Before Running Batch

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#923]
Fabric 6.5.9

There is a global defined within a LU.
Its valid values are `true` or `false` (default).

In a console session...
1. Global's **session** value is set to `true`.
2. A batch is created.
3. Console session is terminated. 

The batch on step #2 comprises of thousands/millions of entities.

As part of the LU's synchronization rules, an enrichment function is executed, and on its code, the global value is checked. 

What will be the value of the global on worker's execution, considering that the batch creation session is no more?

Will it consider...
1. The global's value that was set prior to the batch creation (i.e. `true`); or
2. The global's value when the workers execute (i.e. `false`, as they are not being executed in the same session when the batch was created)?

In case of #2, what is the recommended approach to propagate session's value to the workers of a batch, without setting global's value cluster-wide (i.e. using `set_global global`)?

Please advise.
Thanks.

**Comment by taliei** [comment]
Hi.

The batch process gets the session-level keys as set before its initiation. Later changes (such as additional changes on the session level key or closing the console), that are initiated after the batch command execution, do not impact the running batch.

Regards,
Tali

**Comment by feamcor** [comment]
@taliei ... Even the workers that are distributed to other nodes (not the job affinity node) of the Fabric cluster will __inherit__ the context of the batch creation session?

**Comment by lionbro1** [comment]
yes it should
