### ISSUE TITLE
Using HTTP actor with multipart file attachment upload in bwFlow

### ISSUE THREAD

**Issue by cern7** [k2view-academy/K2View-Academy#924]
I need to make a http post call that will upload a file to some remote location. 
This is an example of the call using CURL
`curl -v -k -X --location --request POST '[https://api-call.com/dm/v1/uploadFile'](https://api-xtest-1.x-test03.aws.solstice.vodafone.com/digitalmass/v1/uploadFile%27) --header 'Authorization:Bearer xxxxxxxxxx' --header 'Content-Type:multipart/form-data' --form 'file=@"/opt/apps/k2view/pl/cstIds.csv"'`

Cannot use httpForm actor as it doesn't support multipart file attachment upload. 
![image](https://github.com/k2view-academy/K2View-Academy/assets/62252282/f246a70a-7447-4886-b0df-576a2b616b44)

Is there a way to use the Http actor to upload a file, and how exactly can I set the '--form' option in case of this actor?

**Comment by natalylic** [comment]
Unfortunately this is not supported by the Http actor
