### ISSUE TITLE
TDM: Does TDM LU_PARAMS support Date/DateTime/Time?

### ISSUE THREAD

**Issue by alexmessel** [k2view-academy/K2View-Academy#925]
Does TDM LU_PARAMS support Date/DateTime/Time?

**Comment by taliei** [comment]
Hi.

The TDM <LU NAME>_Params table keeps each parameter as an array of Strings. Date or datetime parameters are kept in the format of Fabric dates (set in the in DATETIME_FORMAT parameter of the config.ini file). The default format is 'yyyy-MM-dd HH:mm:ss.SSS'.

The parameter's search may be based on either a Date (removing the time from the Date format) or a Datetime.

Examples:

2022-12-28
2023-04-03 10:00:00
The date value is set without quotation marks. 

See the example below of the OPEN_CASE_DATE parameter in the Customer_params TDM DB table: 

{"2016-01-13 04:27:36.0","2017-02-10 20:44:54.0","2015-09-16 06:14:40.0"}

Tali
