### ISSUE TITLE
User IAM / SAML - set passphrase in jvm.options isn't encrypted

### ISSUE THREAD

**Issue by JohnH-K2View** [k2view-academy/K2View-Academy#926]
the config.ini for saml says to set the java keystore and passphrase via jvm.options flags; but if this is done those values are not encrypted on the server as other passwords are (for example in config.ini). Is there an alternate that won't expose the keystore password to all users with read access to the jvm.options file?

```
## Alias for the service provider's certificate
## The keystore, where this certificate's alias is, Must be provided by the following jvm arguments (in the jvm.options)
## -Djavax.net.ssl.keyStore=</path/to/keystore>
## -Djavax.net.ssl.keyStorePassword=<keystore-password>
#SP_CERT_ALIAS=fabric_cert

## Alias for the idp's certificate (A certificate to be provided by the idp's account)
## The idp's certificate must be imported to a truststore.
## The truststore, could be provided by the following jvm arguments (in the jvm.options)
## -Djavax.net.ssl.trustStore=/path/to/truststore
## -Djavax.net.ssl.trustStorePassword=<truststore-password>
## If no truststore provided, the default jdk's truststore will be used
## (default jdk's truststore path - $JAVA_HOME/jre/lib/security/cacerts)
#IDP_CERT_ALIAS=idp_cert
```

**Comment by eyalk2** [comment]
Fabric takes it from system variables.
JVM options file is one of the option to have it there.
But you can remove it from file and inject it dynamically as any other OS system env variables.

**Comment by JohnH-K2View** [comment]
It would still be exposed when running a 'ps -ef' in shell though, as the passed command arguments are visible. A useful enhancement would be to encrypt similar to other sensitive inputs in config.ini

John Hereford
Mobile: 214-763-3557

Autocorrect sometimes makes me type things I didn't Nintendo.
________________________________

**Comment by eyalk2** [comment]
Trustsotre and keystore are system OS stuff, so any access shall be done with actual password, not the encrypted (if this is what you mean in 'ps -ef').


Let me explain the difference between the jvm.options and config.ini and what can be encrypted:

The one who is encrypting config.ini is Fabric itself. When Fabric is up.

However, jvm.options is Java stuff that "inject" values into system variables. Then, when Fabric is going up it takes it and use it.

we can consider move these passwords also into config.ini, but we shall evaluate with R&D if it is fisible.


For now, the way of doing it is use system env variables, so it is not saved at files at all.

(Like any other case, if someone has access to the runtime system, then he can see the env variables, but then he is probably able to make many other things and have access to many other sensitive information).

________________________________
