### ISSUE TITLE
TDM- Loading and Truncating reference tables with FK dependency

### ISSUE THREAD

**Issue by AlexMaziya** [k2view-academy/K2View-Academy#928]
What would be the product approach for re-loading reference tables with foreign keys to other ref tables.

Table A --> (FK) Table B --> (FK) Table C.

Initial Load will be A --> B --> C 
If I mark truncate indicator to true in trnRefList, the second run will result in FK constraint error while truncating table A.
I need to set hierarchical truncate C --> B --> A prior to reloading.

**Comment by taliei** [comment]
Hi.

Currently, we do not support an execution order of reference tables in the TDM task. We plan to add it in Q4 of 2023. Meanwhile, you can do the following:

Define an LU with the reference tables that have an FK/PK relation. For example: 
![image](https://github.com/k2view-academy/K2View-Academy/assets/43947470/86bdf3a7-6091-499a-a330-b83629211364)

Note that you can also add to the LU tables that are not linked to a parent table (business tables) if needed.

Define a BE on each LU of reference tables and populate its entity list. For example- 'select customer_type_value from customer_type'.

Create a delete and load task on the Reference BE.

Tali
