### ISSUE TITLE
client_id parameter configuration for OAuth2 integration

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#929]
Hello - on our support portal page ( https://support.k2view.com/Academy/articles/26_fabric_security/05_fabric_webservices_security.html ) we say about OAuth2 that --

>>>
Fabric extends the standard OAuth authorization capabilities, beyond the provided scopes: The access token (JWT) can be sent with an extra optional payload parameter, representing the client ID. This ID should be mapped to APIKEY in Fabric and it should be granted permissions upon demand. **By default, the name of this optional parameter is "client_id"**.
>>>

Is there a way to change the default name of this parameter from 'client_id' to something else?

______________
Best regards,
         Andrey

**Comment by eyalk2** [comment]
Parmenter's name is ACCESS_TOKEN_APIKEY_PROPERTY_NAME
Lets understand together why scopes cannot be used (following conversation on chat)
