### ISSUE TITLE
Option to call fabric API on the same host in local / internal mode

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#930]
Hello, we have a use case when we need to call fabric API from BW flow to get entire LUI data in JSON format in distributed multi-DC fabric cluster. Is there a way to execute this API call to the same fabric host where we have BW flow running ( to avoid using HTTP interface with fabric 'public' URL via Load Balancer that might hit remote DC )? Something similar to internal 'fabric' interface that we have available in DB actors w/o defining it under Interfaces, etc.. ?

_____________
Best regards,
         Andrey

**Comment by lionbro1** [comment]
You can't use this capability as internal userCode function call.

Create http interface, put IP as localhost and define a proper APIKEY. 

Afterwards use HttpJson actor within the BW flow and call the product API as described here 

https://support.k2view.com/Academy/articles/15_web_services_and_graphit/02_built_in_lu_ws.html

**Comment by avvakandr** [comment]
Hi Lion - this is how we have set it initially and all was ok, but in production environment we have distributed cluster with HTTPS/SSL hardening (via LB hostname), we can not use localhost as certificates will not work. Was looking for some ways around this...

**Comment by avvakandr** [comment]
One more question - is there a way to call the Java API that is used by the Web Service directly ?
