### ISSUE TITLE
k2_auditing persistency and configuration

### ISSUE THREAD

**Issue by dotants** [k2view-academy/K2View-Academy#932]
Hi

What is the default persistence (TTL) of the audit information in Cassandra k2audit.k2_auditing, and how can it be configured?

**Comment by eyalk2** [comment]
Currently there is no TTL on the table.
It can be configured at Cassandra by executing "alter table " command.
However, because there is a lot of data aggregated there, having auditing data at Cassandra is probably not the best option. rather shall use Kafka or to external storage
