### ISSUE TITLE
TDM - refresh LU schema option

### ISSUE THREAD

**Issue by AlexMaziya** [k2view-academy/K2View-Academy#933]
In respect to: 
[https://support.k2view.com/Academy/articles/03_logical_units/18_LU_schema_refresh_LU_options.html](url)
Is there any option (or in the TDM road map) to auto refresh schema based on broadway flows using _Update Tables from Database_ button?

Is there an option to automate TDM LU schema refresh and apply all the DB changes to the different TDM flows?

<img width="819" alt="image" src="https://github.com/k2view-academy/K2View-Academy/assets/58711321/187213da-8e61-481c-b70c-71a9f9505ebe">

**Comment by taliei** [comment]
Hi.

We plan to add support for updating the LU tables and their populations (based on Broadway flows) to the web Studio in the next Fabric major release (Fabric 8).

Tali
