### ISSUE TITLE
fabric query tuning - performance improvement

### ISSUE THREAD

**Issue by AminSidd** [k2view-academy/K2View-Academy#935]
I have created a customer micro db in fabric. Now when I am running a sql query (it's a complex query) to fetch the data from k2view fabric microdb, it is taking too much time. I tried creating all the necessary indexes and simplified the query (as much as I could), still no luck. What more can I do?
Also, how can I debug in realtime what's happening during the sql execution? The fabric logs does not show any information about the SQL processing in the database.

Any suggestions?

**Comment by feamcor** [comment]
Add `explain query plan` in front of the `select` statement to get info about how the engine is handling the query.

**Comment by AminSidd** [comment]
This is the result that I got. But there is very less documentation available on query tuning, so I am not able to understand the issue. Do you see something alarming ?
![image](https://github.com/k2view-academy/K2View-Academy/assets/96882279/cec3e1ba-0e74-4917-af7b-23d613652923)

**Comment by lionbro1** [comment]
please refer to trace capabilities in the following article https://support.k2view.com/Academy/articles/29_tracing/01_tracing_overview.html

If further performance tuning session is needed, please track it as a freshdesk ticket asking for consulting services.
