### ISSUE TITLE
Calling SOAP API using Broadway HTTP actor

### ISSUE THREAD

**Issue by dotants** [k2view-academy/K2View-Academy#936]
Hi

Do we have an example of calling SOAP API using Broadway HTTP actor?

**Comment by eyalk2** [comment]
Was not it discussed here?:
https://github.com/k2view-academy/K2View-Academy/issues/483

**Comment by lionbro1** [comment]
isn't it duplicate with this one?
https://github.com/k2view-academy/K2View-Academy/issues/483

**Comment by dotants** [comment]
Yes, it is duplicate, I could not find it in the search
