### ISSUE TITLE
DbFetchFirstRow actor behaviour in K2view application

### ISSUE THREAD

**Issue by kottuba** [k2view-academy/K2View-Academy#937]
I want to have an understanding of the DbFetchFirstRow actor on how it works, Will it directly fetches the first row and stops hitting database? or will it fetches the complete query result and then take the first row?

Can you please help me with this

**Comment by natalylic** [comment]
Hi, the DbFetchFirstRow actor fetches the complete query results and then returns the first row.
It is equal to drawing the link type = First from the DbCommand result set.

**Comment by kottuba** [comment]
Thanks for the information. Am good with the response
