### ISSUE TITLE
Adjusting Tomcat attribute

### ISSUE THREAD

**Issue by dotants** [k2view-academy/K2View-Academy#938]
Hi

How can we change a Tomcat attribute?
There is no configuration file specifying them.

It is possible to set from Java code, but where can we place such code so it is valid for all Fabric APIs?
Example in Java code:
    Tomcat t = new Tomcat();
    t.getConnector().setAttribute("maxHttpHeaderSize",65536);
  (see [https://tomcat.apache.org/tomcat-9.0-doc/api/org/apache/coyote/http11/AbstractHttp11Protocol.html#setMaxHttpHeaderSize(int)] )

**Comment by eyalk2** [comment]
Because Tomcat is embedded inside Fabric, there is no way for you to change it (i.e. unless changed in product)

**Comment by dotants** [comment]
The Web Services Java files do not contain a constructor to the Logic class, they extend “WebServiceUserCode”:

public class Logic extends WebServiceUserCode {…}

Will it not work to add default constructor to the class, and put the attributes setup in the constructor, using the internal Fabric Tomcat – for that, I’ll need to know the “Tomcat”-type variable name (assuming it is accessible):

public Logic () {
    fabricTomcatInstance.getConnector().setAttribute("maxHttpHeaderSize",65536);
}

**Comment by eyalk2** [comment]
I do not think that we wish to expose tomcat server, which is one of the core elements of the product, to the implementation
