### ISSUE TITLE
Cassandra interface - set DC aware option

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#94]
In the Cassandra interface, can we set a DC aware option? 
In one of the current non-fabric implementations, the client uses a "DCAwareRoundRobinPolicy" option in order to avoid timeouts connecting to remote DC during API calls, something like below:

if ("DCAwareRoundRobinPolicy".equalsIgnoreCase(loadBalancePolicy)) {
cluster.setLoadBalancingPolicy(
DCAwareRoundRobinPolicy.builder().withLocalDc(<dataCenterName>).withUsedHostsPerRemoteDc(<usedHostsPerRemoteDc>).allowRemoteDCsForLocalConsistencyLevel().build());
}

**Comment by lionbro1** [comment]
We use the default in the configuration file, fabric doesn't support overriding it.

**Comment by lionbro1** [comment]
The product uses DC / Token Aware load balancing. It is an internal product settings and you cannot change it.

By default this is also used for Cassandra Interfaces you define in the studio. However, for Studio Cassandra interfaces you can change the default by adding loadBalancing=<LoadBlanceClassName> paramter to the JDBC URL.
