### ISSUE TITLE
Non-Cassandra System Database on v7.2

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#940]
Hi,
Is it possible to use Postgres or SQLite as the system database for the debug server?
If so, how would it deal with different projects?
Would it leverage built-in cluster_id like in Cassandra?
Would it, for instance, create different databases per project when on Postgres?
Would it, for instance, create different database files per project when on SQLite?
Please advise.
Thanks.

**Comment by eyalk2** [comment]
yes, it is possible.
and yes, different projects are handled similar to Cassandra using the cluster_id.
For Postgres - different schemas will be created.
For SQLite - different files will be created.
