### ISSUE TITLE
How to report duration type of metric over JMX

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#942]
Hello, we need to report 'duration' type of metric over JMX from our BW flow - I tried JMX Write actor and it looks like it can report only count type.

I can see in our support portal we have java API 'statsDuration()' - :

AutoCloseable sw = statsDuration("JMX_EXAMPLE", "XXX_DURATION");
sleep(1000);
sw.close();

when I tried that - I still see my 1000 reported as a count (same as JMX Write or 'statsCount()' do):

<img width="423" alt="image" src="https://github.com/k2view-academy/K2View-Academy/assets/92332494/fc31033a-003c-45c0-8216-2e182a5fcb5c">

while I'm looking for something like this:

<img width="484" alt="image" src="https://github.com/k2view-academy/K2View-Academy/assets/92332494/21da7b85-1835-410e-96c4-9de1e15193f6">

Can we report duration from BW JMX Actor and if not - how can we do it from lu function? 

Is 'statsDuration(entry,key) -- close()' different from 'statsCount(entry,key, value)' - if I report the same duration in last one via 'value' ? 
____________
Best regards,
         Andrey

**Comment by yuvalp-k2view** [comment]
Andrey, the Stats system just holds count/total/timestamp. 
The interpretation of what that value means and how to present it to the user is up to the monitoring system (eg. Grafana). Also, cluster level aggregation is done outside Fabric.

The stats page is intended for documentation purposes. There is no support to document custom stats as duration but that does not affect any workings of the monitoring system.
