### ISSUE TITLE
How to refer to system_db from BW flow?

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#946]
Hello, is there a way to refer to whatever DB interface we have under config.ini - system_db from my BW flow? In case I want to use it in my DB actor without duplicating/maintaining it under interfaces - kind of similarly to 'fabric' interface we have available there in drop-down...

______________
Best regards,
         Andrey

**Comment by natalylic** [comment]
No, you can't refer to system DB from an actor without first creating it as an interface.
'fabric' is available in the drop-down due to a specific development.
If this is required, you might open a CR for this new feature.
