### ISSUE TITLE
Is there a way to use compound 'key' for FabricSetRead actor?

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#947]
Hello - in my BW flow I'd like to read global that is constructed based on few parameters (like JobId and Name) - is there a way to pass these two as an input to FabricSetRead actor and use them as 'set ${JobId}_${Name}'? 

I can do it from StringFormat actor before, but would like to avoid using 'extra' actors where possible to make BW more tranparent.

______________
Thank you,
         Andrey

**Comment by natalylic** [comment]
Hello! The FabricSetRead actor **reads** a key from the fabric scope by running the SET command:
`SET KEY;  `
If the key is comprised of two values (by using a certain pre-defined pattern), you will need to use another actor (e.g. Split or Substring) after the FabricSetRead and not before it.

**Comment by natalylic** [comment]
Clarification: it is **not** possible to perform SET command with the syntax such as: 'set ${JobId}_${Name}'
This is because the actor interprets $ as prepared statement and the above syntax is invalid.
