### ISSUE TITLE
Input parameter for Fail actor

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#949]
Hello, is there a way to supply input parameter for Fail actor (error message I'd like to throw)? I'd like to construct my error message based on my previous actor result.

____________
Best regards,
          Andrey

**Comment by natalylic** [comment]
Yes, you need to add ${param_name} to the message text. Then the <param_name> will be added as a new input to the actor.
![image](https://github.com/k2view-academy/K2View-Academy/assets/62207927/321cd19e-25e2-49b2-8130-537865554cba)

**Comment by avvakandr** [comment]
Hi Nataly, thank you! Not sure how I missed that, it is even in actor description.. my bad (
