### ISSUE TITLE
BatchProcessUnit in K2View Fabric Status

### ISSUE THREAD

**Issue by tarikh03** [k2view-academy/K2View-Academy#95]
in K2View Fabric Status page, http://localhost:3213/static/status/status.html

few questions about BatchProcess and BatchProcessUnit .

1 .Does BatchProcess represent processes other than migrates?

2. what does the BatchProcessUnit stand for? 
    is the number of BatchProcessUnit related to the number of rows brought by populations?
I migrated 1 instance, and saw that it took 169 BatchProcessUnits to do it.
then I migrated different instance and it was handled by 70.

**Comment by lionbro1** [comment]
From version 6.2 and on fabric shows only batchprocesses matrices and it is provided by LU name.
1. batch process represent and batch process (migrate, broadway or cdc_repbulish).
2. it's the number of instances running currently, like migrate_in_process, however we removed this matric from 6.2 and on
