### ISSUE TITLE
MTable not found

### ISSUE THREAD

**Issue by mariana-shinnara** [k2view-academy/K2View-Academy#950]
Hi,
I have to broadway flows that does the following:
1. DbCommad SET CLUSTER_DISTRIBUTE_AFFINITY = 'ALL'
2. Mtable Load
3. DbCommand SET CLUSTER_DISTRIBUTE_AFFINITY = ''
4. Call internal flow

In the internal flow I do MTableLookup.
I'm working on a 3 node cluster, on the node where I execute the first bw flow I'm able to do MTableLookup, on the other two nodes I get exception MTable not found.
Is there an extra step that I need to do?

Thanks,
Mariana

**Comment by natalylic** [comment]
Hi, as discussed - it seems that you did everything OK (except that you don't need to do the second SET).
Please open the ticket to investigate as it looks like a bug.
