### ISSUE TITLE
TDM - copy reference tables with specific columns

### ISSUE THREAD

**Issue by AlexMaziya** [k2view-academy/K2View-Academy#951]
What is the TDM best practice for copying reference tables with specific columns.
trnRefList support only entire table copy.

**Comment by taliei** [comment]
Hi.

We plan to redesign the table-level solution to support filtering on the tables. This is planned for the next TDM release by the beginning of 2024. 

For now, as a workaround, you can edit the fnGetTableInJson Java function: add a condition to check the table name and set a select of specific columns for the required table.

Tali
