### ISSUE TITLE
Is there a way to 'break' from BW inner flow to continue ?

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#952]
Hello, I have a BW flow 'XXX' that I'm using as inner flow from my main BW flow 'YYY', and under certain conditions I want my InnerFlow 'XXX' to exit at stage 'A' w/o executing all subsequent stages 'B', 'C', 'D' - and my 'YYY' to continue...

I can do conditional stage 'A1' and check condition to continue (without any split or else on A1 stage), but is there something like Fail actor to exit current flow w/o throwing error, returning whatever return values I provided before that stage?

_____________
Best regards,
         Andrey

**Comment by natalylic** [comment]
Are there any actors that are supposed to be executed in stage A prior to exiting the inner flow? If not - you can put the conditional stage in the main flow YYY - on the stage that invokes an inner flow. So that if it's not true, the inner flow XXX will not even start.
