### ISSUE TITLE
DbSqlDialect output options

### ISSUE THREAD

**Issue by mariana-shinnara** [k2view-academy/K2View-Academy#954]
Hi, 
I want to use DbSqlDialect actor, but I see that the only supported outputs are 
cassandra, postgres, oracle, generic and it's missing (sqlite, mysql, mssql ...).
Is there a reason for that?

Thanks.

**Comment by natalylic** [comment]
Hi, the **DbSqlDialect** actor has been introduced to answer some internal needs. The dialects which are currently supported are as you mentioned above. The other output param **productName** returns the vendor name as you can see in the image.
If however the productName is not enough and you need to get the dialect, please open the CR with requirement explanation.
![image](https://github.com/k2view-academy/K2View-Academy/assets/62207927/4f851328-b35f-460e-b50e-4885f7717363)
