### ISSUE TITLE
TDM - Load performance statistics

### ISSUE THREAD

**Issue by AlexMaziya** [k2view-academy/K2View-Academy#956]
What is TDM best practice to isolate the load performance part of a task?
In addition, If I have Delete-->Extract-->Load  task, where can we see performance breakdown for each step per table?

**Comment by taliei** [comment]
Hi.

We plan to add reporting information to the TDM to get the sync (extract), load, and delete statistics in future TDM releases.

For now, you can add custom JMX stats to the TDMOrchestrator flow (in the Shared Objects) and monitor the JMX by DataDog or Grafana or whatever monitoring tool that is used on your account.

You can add the following JMX custom stats: TotalSyncTimePerTaskExecution, TotalDeleteTimePerTaskExecution, and TotalLoadTimePerTaskExecution. The key for each statistic will be the task execution id. Note that you can wrap the statsCount Fabric function with a project function and invoke the project function using the LUFunction Actor.

See the statistics screenshot below:

![image](https://github.com/k2view-academy/K2View-Academy/assets/43947470/345b8a0b-f083-47f7-b7ab-ad9a3419693f)


for more information about the JMX statistics see https://support.k2view.com/Academy/articles/34_JMX_statistics/03_JMX_custom.html 


Attached are examples of the TDMOrchestrator flow and the project function that calls the statsCount Fabric function.
[tdm-custom-stats-example.zip](https://github.com/k2view-academy/K2View-Academy/files/13376156/tdm-custom-stats-example.zip)

Regards,
Tali
