### ISSUE TITLE
Broadway Cache

### ISSUE THREAD

**Issue by mariana-shinnara** [k2view-academy/K2View-Academy#959]
Hi,
In the implementation of the delta parsers we store instance ids and GET timestamp in a cache using LoadingCache, the cache is created upon deployment and updated on after each GET done by the parser.
I'm working on converting this parser to broadway flow.. are there any suggestions on how to recreate the caching functionality in bw? or any replacement to achieve this.
thanks.

**Comment by yuvalp-k2view** [comment]
There is a Context.globals() that let's you cache data on the broadway execution level. If you want to handle a specific singleton, I suggest wrapping it with an Actor and allocating it there.
