### ISSUE TITLE
Installation Error - Fabric fails connection to Cassandra

### ISSUE THREAD

**Issue by benkipnis** [k2view-academy/K2View-Academy#96]
When attempting to start Fabric after a fresh install, i receive an error that it cannot connect to the locally installed Cassandra instance: 
k2view@xxx:~ . k2fabric start
++Giving up: Fabric is FAIL @Encryption: All host(s) tried for query failed (tried: /135.59.66.98:9042 (com.datastax.driver.core.exceptions.UnavailableException: Not enough replicas available for query at consistency LOCAL_QUORUM (1 required but only 0 alive)))

*Add'l Notes*
Fabric 6.1.6 with associated Cassandra and Kafka
Single node installation w/ separate users for each application
Linux VM (on-prem) with 8 cores / 64GB RAM / 1.5TB
Cassandra is running and can be accessed successfully by the cassandra user via cqlsh and via Studio from my laptop
Verified IP addresses in configuration files (cassandra.yaml and config.ini)

**Comment by lionbro1** [comment]
Hi Ben, I think it's better you will open a freshdesk ticket to our DevOps team to check what is wrong on your environment, as this release already works for few customers. @gabiochman please have a look

**Comment by lionbro1** [comment]
closing ticket, as it will be tracked in freshdesk. the problem can be resolved by matching Cassandra  DC to dc1.

Link to freshdesk https://k2view.freshdesk.com/a/tickets/18597
