### ISSUE TITLE
Execute StopJob actor w/o uid parameter

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#961]
Hello, is there a way to use StopJob actor w/o UID parameter? I need to stop my BW job from another BW flow only by supplying BW job name, but it looks like uid is always required for this StopJob actor. Do I need to use DBCommand instead?

_____________
Best regards,
          Andrey

**Comment by natalylic** [comment]
Hi Andrey,
**UID** is a mandatory parameter for running the **StopJob** actor. You can do the following: when running your BW job, use the **BroadwayJob** actor and send it the UID input param. In this way, you will have the UID for running the **StopJob** actor.
The second option is to use the **DbCommand** actor to run the fabric command.
