### ISSUE TITLE
"Token timout" parameter of OAuth 2.0 Password Credentials HTTP interface

### ISSUE THREAD

**Issue by dotants** [k2view-academy/K2View-Academy#963]
How is the "Token timout" parameter of an HTTP interface with "OAuth 2.0 Password Credentials" authentication type used?
Is the value in seconds or milliseconds?
What does the value 0 mean?

**Comment by feamcor** [comment]
Value is in seconds.
Fabric will use it to get a new token or renew existing one (if authentication server provides one).
If set as zero, it will consider the timeout returned by the authentication server.
By setting your own, it allows you to get/renew a token ahead of their usual expiration time.
