### ISSUE TITLE
K2View Studio integration with IntelliJ IDEA Ultimate

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#964]
Fabric 6.5.9 HF#19

Does Studio integrate with IDEA Ultimate, or it only integrates with the Community Edition?
I uninstalled the CE and installed the Ultimate one and it doesn't show on the contextual menu.
I opened and closed Studio a few times without success.
I saw that Studio expects process to be `idea64`.
I checked and Ultimate's executable is `idea64.exe`.

Please advise.
Thanks.

**Comment by eyalk2** [comment]
Try set an env var named "IntelliJ" - where value for this key is the full path to the intellij exe.

**Comment by feamcor** [comment]
I added system envar `INTELLIJ` and it worked. Thanks.
Could it be because this was installed using the Jetbrains Toolbox under the AppData directory?

**Comment by eyalk2** [comment]
Studio is trying to detect IntelliJ in several methods, from LOCALAPPDATA when installed from the JetBrain toolbox or from registry for the CE (we don't look for the ultimate edition). 
But there is another method which has a higher priority over the 2 methods above: using env var "IntelliJ, as propsoed and worked for you :)
