### ISSUE TITLE
Binding variables

### ISSUE THREAD

**Issue by devikameda** [k2view-academy/K2View-Academy#965]
I want to use below variable in where condition for query based population for particular table. Is there a way to do that?

fabric>set environment;
|value|
+-----+
|PP   |

**Comment by eyalk2** [comment]
want to it at your user code?
Example at function - fabric().fetch("set environment").firstRow().toString()
Example at BW: use DBCommand actor with SQL = set environment (select interface to be  fabric)

**Comment by devikameda** [comment]
I want to use the global variable in the population based on DB query, not in the function and broadway based populations

**Comment by eyalk2** [comment]
Also when using DB query you can call to a function that will get it.

Embedding fabric values into SQL is available for Globals, but here too, available inside function. (https://support.k2view.com/Academy/articles/08_globals/04_globals_code_examples.html)
But anyway environment value is not part of Globals

**Comment by smokyMount** [comment]
I believe she is asking if there is a way to pass globals not to a root function but a DbQuery population.

When fetching the value of schema or table name from a global variable we surround global with @ sign but how to pass it for binding variables?


________________________________

**Comment by eyalk2** [comment]
When using only DbQuery you cannot do it

**Comment by natalylic** [comment]
In the article https://support.k2view.com/Academy/articles/19_Broadway/actors/05_db_actors.html you can find the section about **Parameters and Non-Prepared Statements Support**. The following example is provided there:
```Select * From ${@table} where ${@column} = ${case_sts}```
```${@param}``` - is a syntax for non-prepared statement parameters. Hope it helps.
