### ISSUE TITLE
How to create an Async WS on Fabric

### ISSUE THREAD

**Issue by dotants** [k2view-academy/K2View-Academy#966]
How can we create an async WS on Fabric, i.e. a WS that will immediately return "OK", and will continue to perform it's action in the background?

**Comment by eyalk2** [comment]
Maybe you can trigger a job, as it runs independent.

**Comment by dotants** [comment]
Executing Brodway flow that will include only a "BrodwayJob" actor to trigger another flow works.
But the question is - how to do the async WS in Java?

**Comment by eyalk2** [comment]
Here is a simple example I did:
1. I created a function of type job (located at my LU named Customer)

	@type(UserJob)
	public static void printToLog() throws Exception {
		for (int i=0;i<100;i++)
			log.info("print "+i);
	}

2. via Jobs window I created a job with Execution Mode = manual, with that function
3. I created a simple WS - single line - that executes the job:
		fabric().execute("STARTJOB USER_JOB NAME='Customer.printToLog'");

4. I executed the WS

Job ran
