### ISSUE TITLE
Start interface listener without deployment

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#968]
Hi,

What parameters do we need to pass to startjob command to start an interface listener job? Assume, a flow is already added to interface listener in studio and was deployed in the past. For some reason, we had to stop the interface listener job but cannot redeploy the LU.

We tried using following commands, but it gives an error:
`startjob INTERFACE_LISTENER name='ACCLU.flowInterfaceAutomate' UID='flowInterfaceAutomate' AFFINITY='primary_node' ARGS='{"Interface Name":"InvoiceFile"}';`

> ERROR 2024-01-02 18:36:01,008 [LID607f000000000106] [JobPoolExecutorThread_INTERFACE_LISTENER_2280] c.k.c.j.JobExecutor - Error in job execution. Job: INTERFACE_LISTENER.ACCLU.flowInterfaceAutomate.flowInterfaceAutomate
> java.lang.NullPointerException: null
>         at com.k2view.cdbms.jobs.InterfaceListener.process(InterfaceListener.java:44)
>         at com.k2view.cdbms.jobs.Job.execute(Job.java:49)
>         at com.k2view.cdbms.jobs.JobExecutor.run(JobExecutor.java:95)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:750)
> INFO  2024-01-02 18:36:02,010 [LID607f000000000106] [JobPoolExecutorThread_INTERFACE_LISTENER_2280] c.k.c.j.JobExecutor - job INTERFACE_LISTENER.ACCLU.flowInterfaceAutomate.flowInterfaceAutomate status was updated to FAILED.

**Comment by natalylic** [comment]
Hi, the exception you're getting is on retrieving the **interface**. 
Are you sure the interface name is spelled correctly and it is deployed?
If everything is spelled correctly and deployed and you're still getting an exception, please open a freshdesk ticket in order for us to investigate the issue (including all the details such as Fabric version, etc.)

**Comment by smokyMount** [comment]
The issue was not with the interface name but the argument name. The correct value to pass as argument to startjob command was `interface` as shown below

`startjob INTERFACE_LISTENER name='ACCLU.flowInterfaceAutomate' UID='flowInterfaceAutomate' AFFINITY='primary_node' ARGS='{"interface":"InvoiceFile"}';`
