### ISSUE TITLE
IsFirstSync BW population

### ISSUE THREAD

**Issue by mariana-shinnara** [k2view-academy/K2View-Academy#969]
Hi,
Is there a way to identify instance first sync from broadway population?

Thanks.

**Comment by natalylic** [comment]
There is no actor that can return such information. However you can add this check to the population either by an inner flow or a LU function actor. For example, using the ```list instances lu_name=xxx``` command and checking if the instance is returned.

**Comment by natalylic** [comment]
There is a Fabric function `public static boolean isFirstSync()`
It can be invoked using an LuFunction actor from the population flow. 
You can see the description and a code example [here](https://support.k2view.com/Academy/articles/14_sync_LU_instance/06_sync_decision_functions_recommendations.html).

**Comment by mariana-shinnara** [comment]
Thanks Nataly, I know of this function just wanted to check if there's an actor of population argument that I can use.
I saw in the deploy flow there's is_first_deploy external parameter, I thought there's something similar for isFirstSync.

**Comment by natalylic** [comment]
No, there isn't.
