### ISSUE TITLE
Boadway - Consuming Kafka Topic from external Interface

### ISSUE THREAD

**Issue by ghost** [k2view-academy/K2View-Academy#97]
Is it possible to use broadway to consume/subscribe to kafka topics from a external source using interfaces?

When trying to implement it, with the Broadway Kafka example and changing the interface from Memory to the interface and running the debugger, Broadway can't get the schema of the message and always shows it as empty array.

**Comment by natalylic** [comment]
Broadway supports Apache Kafka and JMS Queue / Topic by any JMS provider.
Note that the message type to be processed by the Broadway Pub / Sub functionality must be aligned with the Data type defined on the Interface and is limited to: String, byte[], JSON, long. The message type of an in-memory broker is not limited to any specific types.
Please refer to the KB Item [Pub/Sub Actors](https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.2/articles/19_Broadway/actors/04_queue_actors.md) for the full explanation about the Pub / Sub asynchronous message handling.
The below flow example displays a JSON data type which is published to Kafka topic:
![image](https://user-images.githubusercontent.com/62207927/94136521-b896c380-fe6d-11ea-8387-bc6f47cf39ab.png)
The message is:
![image](https://user-images.githubusercontent.com/62207927/94136887-44a8eb00-fe6e-11ea-94e0-ce0ba402a942.png)
