### ISSUE TITLE
Broadway error handling

### ISSUE THREAD

**Issue by mariana-shinnara** [k2view-academy/K2View-Academy#970]
Hi,
I have a batch that executes a broadway flow (for example BATCH CUSTOMER.('1','2','3','4') fabric_command="broadway CUSTOMER.SampleFlow SampleIID=?" ) and returns a report.
The broadway flow is very big and nested, I call many inner flows, I use multiple mapper actors that call broadway flows, I execute GETs on other lus, etc...
My main issue here is that in case of an error in one of the inner flows, the main flow will continue.
I need to handle those errors, log details about them, and notify that the report is not valid.
What is the best way to handle errors in this situation?
If an actor fails inside the broadway flow of the Mapper, is there a way to catch it from the mapper itself? Or do I need to add error handling on each stage in the flow?

Thanks.

**Comment by natalylic** [comment]
When you're calling an InnerFlow from the main flow, you can add the ErrorHandler actor and mark **Suppress** to suppress the error and continue the flow. You can also mark **Log** - to report the error to the log. See below.
The error in Broadway can be caught on the Stage level, by adding an error handling to the relevant stage - either the built-in ErrorHandler actor, or any other actor or even a InnerFlow that will perform whatever is needed once the error occurs.
![image](https://github.com/k2view-academy/K2View-Academy/assets/62207927/0a94871b-29c4-461e-a9a1-65df801791d2)

**Comment by mariana-shinnara** [comment]
Is there a way to mimic try/catch on multiple stages? instead of error handling on each stage.
As I said my flow is very big and complex and I want to minimize the number of error handlers

**Comment by natalylic** [comment]
The way to "mimic" the try/catch logic is to put all the stages that require error handling **into an inner flow**.
Then, in your main flow, you should put only **1 error handling actor** on the stage of the inner flow and it can be configured to catch various types of errors and handle them differently.
