### ISSUE TITLE
Can I use DBLoad actor only to generate SQL w/o actually executing them?

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#971]
Hello, in one of TDM projects as a 'safe' approach customer do not want us to execute insert/update statements on target DB from our application and they are asking us to provide INSERT / UPDATE queries from our TDM load flows so they can inspect them and execute manually in current phase before granting us with write access to their DB...

I see we have SQL as an output from DBLoad actor, but this is returned only when actor is successfully executed - is there a way to make this actor only to return query w/o actually executing it?

<img width="215" alt="image" src="https://github.com/k2view-academy/K2View-Academy/assets/92332494/a5664672-a0bb-47cd-b083-ab6524da682f">

_____________
Best regards,
         Andrey

**Comment by natalylic** [comment]
Hi, the DBLoad actor can't return the query w/o executing it. 
As a workaround, you can run the flows on some internal DB adding the logger actor that will "catch" all the queries, and then provide the log to the customer.
