### ISSUE TITLE
Is there a way to suppress input/output params from being displayed in my parent BW flow

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#972]
Hello, I'm using inner BW flow as one of input parameters in my custom actor and this BW flow has few input and output params.

Once I add this flow into my actor - I see its input and output added to my actor as well:

<img width="406" alt="image" src="https://github.com/k2view-academy/K2View-Academy/assets/92332494/6f3eb238-145e-496b-8995-d885c82f290d">

is there a way to avoid this and keep only actor parameters displayed (other than changing editor for this param to 'string' from 'InnerFlow' as I still want to select BW flow from nice menu and not type it manually) ?

_____________
Best regards,
         Andrey

**Comment by natalylic** [comment]
Hello! Only the **external** input and output parameters of the inner flow are automatically added to the actor when the flow is added. This is the way to communicate with your inner flow. If you don't need the flow's output parameters in this custom actor, remove their external definition in the flow.

**Comment by avvakandr** [comment]
Unfortunately I need these as external as I'm using it later inside the flow that implements my custom actor - 

<img width="232" alt="image" src="https://github.com/k2view-academy/K2View-Academy/assets/92332494/7552dbf3-0df7-43c6-844e-a8dda02e002b">

So, I guess my only option for now is to use flow name as a string parameter and not as InnerFlow...

_____________
Best regards,
         Andrey

**Comment by natalylic** [comment]
Yes, it sounds like you need a flow name as a parameter to your actor, and not the inner flow itself.
