### ISSUE TITLE
If a node goes down during migration/batch process, what happens to IIDs that were in process status on that node.

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#974]
We know that if a node goes down during migration, the remaining IIDs/entities of that node get distributed to other nodes that are up. But what happens to the entities that were in process when the fabric node stopped? 

How are those entities updated in the k2batchprocess keyspace? Are they marked as Failed? or do they remain unchanged (i.e., with status change as in process and without an end time)?

Please let us know the exact steps so we can design failover/retry scenarios accordingly.

Assume there is no affinity defined. Fabric version is 6.5.9.

**Comment by lionbro1** [comment]
All the instances in process when a node goes down are staying in status "WAITING" till picked up by another node, nothing should be done by the users, it's automated process.

**Comment by smokyMount** [comment]
[like]  Hardik Parekh reacted to your message:
________________________________

**Comment by smokyMount** [comment]
Thanks. And what if the node that went down was the coordinator of this batch process? Will another available node become the coordinator for managing the batch?

**Comment by lionbro1** [comment]
Yes, you can control it, as it is one of the parameters of the batch command, if you don't pass coordinator parameters, all nodes are candidates.
