### ISSUE TITLE
Add property to Publish Actor

### ISSUE THREAD

**Issue by tarikh03** [k2view-academy/K2View-Academy#976]
Is there a way of adding a property to broadway producer?

We need to set --producer-property max.request.size=10485880.

**Comment by natalylic** [comment]
Please refer to the article [PubSub Configuration Interface](https://support.k2view.com/Academy/articles/24_non_DB_interfaces/02a_pubsub_config.html) which explains how to setup the pubsub. 
You can add a new property either to the [default_pubsub] section of config.ini or create a new section and add it there. Then a new PubSub interface should be created as well, that will point to this new section. Use this new PubSub interface from your Broadway actor. 
Note that when creating a property in the config.ini, the dots should be replaced by '_' => MAX_REQUEST_SIZE.

**Comment by tarikh03** [comment]
This is only available in version 7 onwards right?
is it possible to do it in other way in version 6.5.9 ?

**Comment by natalylic** [comment]
Unfortunately no option for that in 6.5.9... this is why we created PubSub configuration in 7.

**Comment by tarikh03** [comment]
ok thanks.

one more thing, I checked in version 7, in [PubSub Configuration Interface](https://support.k2view.com/Academy/articles/24_non_DB_interfaces/02a_pubsub_config.html)
it is mentioned only thing we need to change in interface definition is Config Section.
while I don't see Config section in the interface definition:

is it the right place I am looking at?

![image](https://github.com/k2view-academy/K2View-Academy/assets/47483757/0fd33462-6268-439a-bebc-29f6744456f5)

**Comment by natalylic** [comment]
No, your screenshot shows a Kafka interface, while this article refers to a new interface type: **PubSub Configuration**.
The KB article refers to the configuration changes that can be performed using the **config.ini** configuration file - as I wrote before. 
You can either make your changes under the [default_pubsub] section, or update the section name in the interface definition and create this new section in the config.ini, with your required settings. 
![image](https://github.com/k2view-academy/K2View-Academy/assets/62207927/90e3df96-61c2-4e4c-8cef-2c78d101e35a)

**Comment by tarikh03** [comment]
got it, thanks :)
