### ISSUE TITLE
Executing Oracle PL/SQL block from Fabric 7.2

### ISSUE THREAD

**Issue by dotants** [k2view-academy/K2View-Academy#981]
Hi

Is there a way to execute Oracle PL/SQL block from Fabric, either by Broadway or Java function?
the semicolons (;) are always failing the execution...

PL/SQL dummy code block example:
    BEGIN
    select sysdate from dual;
    end;

**Comment by lionbro1** [comment]
Hi,

Pointing to an already opened Q&A on this matter

https://github.com/k2view-academy/K2View-Academy/issues/977
