### ISSUE TITLE
Fabric Audit logging - "fabricMe" address

### ISSUE THREAD

**Issue by dotants** [k2view-academy/K2View-Academy#982]
We turned on the Fabric audit logging in Production environment (in config.ini: AUDIT=ON).
What is the source of the audit data entries that have as IP address the value "fabricMe"? These entries do not correspond with any user activities:

![image](https://github.com/k2view-academy/K2View-Academy/assets/74860302/d8198787-cd7f-4de0-bb28-d65c7e68d010)

**Comment by mhanna** [comment]
local fabric is fabricMe :)

**Comment by dotants** [comment]
So "fabricMe" is internal Fabbic activities? Which ones?

**Comment by lionbro1** [comment]
yes, it is used internally for example any job creation opens internal connection to Fabric, migrate, etc..
