### ISSUE TITLE
Get parent(s) lu tables names

### ISSUE THREAD

**Issue by AlexMaziya** [k2view-academy/K2View-Academy#983]
Assuming my LU schema is:
table_a --> table_b --> table_c

from the BW population of table_c I'd like to know the table name of my parent(s) (table_b  & table_a ).
is there a functionality that can get me all predecessors names or at least the direct parents?

**Comment by natalylic** [comment]
You can use: `UserCode.getLuTableParents()`
Note that this function is deprecated but currently there is no other alternative and it's safe to use it.

A different way is to use the JDBC FK metadata. See the below code sample that demonstrates it:
```
DatabaseMetaData metaData = conn.getMetaData();

 // Get the parent tables of a specific table (replace 'your_table' with the actual table name)            
String tableName = "your_table";
ResultSet resultSet = metaData.getImportedKeys(conn.getCatalog(), null, tableName);

System.out.println("Parent tables of " + tableName + ":");
while (resultSet.next()) {
                String parentTableName = resultSet.getString("PKTABLE_NAME");
                System.out.println(parentTableName);
 }
```
