### ISSUE TITLE
Too-long keyspace name on Debug

### ISSUE THREAD

**Issue by dotants** [k2view-academy/K2View-Academy#985]
Hi

We are getting errors on deploy to debud due to Keyspace name length:

![image](https://github.com/k2view-academy/K2View-Academy/assets/74860302/3bbbc6d9-749b-4a28-9667-66766bf7c00b)

Is there any solution or W/A for this?

**Comment by lionbro1** [comment]
The keyspace is a combination of k2view_{LU name}_{version}_{project name}

Cassandra limitation for keyspace name is 48 characters.

So you have two options:

1. Change the LU name or the project name to a shorter length.
2. Change the system DB to use sqlite or PostgreSQL instead of Cassandra.

**Comment by dotants** [comment]
There is a 3rd option - change the username, since it is in the TortoiseGIT configuration :-)

**Comment by lionbro1** [comment]
we concatenate the user name as well only when using terminal windows server.
