### ISSUE TITLE
Use InnerFlow from one LU to invoke a flow from another LU

### ISSUE THREAD

**Issue by dotants** [k2view-academy/K2View-Academy#988]
Is it possible to use InnerFlow actor on a flow in LU1, to invoke a flow from LU2? If yes, how?
[as a W/A - using DbCommand on Fabric and execute "broadway LU2.flowName"]

**Comment by natalylic** [comment]
Each LU has access only to the flows of the same LU and the flows of Shared Objects. 
So, you can put your flow to the Shared Objects - when it should be accessible across different LUs.
As a WA, you can run the `broadway `command as you mentioned above, assuming that LU1 (in your example) is deployed after LU2.
