### ISSUE TITLE
Ref sync warning msg meaning

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#991]
Hi, 

A reference table failed to sync with following warning msgs. What is the meaning of these warning msgs? When does fabric print them?
Rerunning ref sync for this failed table fixes it.
Fabric version - fabric-6.5.5_29-HF1

```
WARN  2024-02-21 15:55:24,296 [LID40b300000000000a] [PollingConsumerThread-common.PROFILE_DATA] c.k.f.c.c.m.AbstractMessageProcessor - Process message: - Message Snapshot id 'bb64b782-b11a-4159-b71d-a09443830ba5' for Table 'common.PROFILE_DATA', Required true  doesn't exist in source com.k2view.fabric.commonArea.consumer.messageProcess.CassandraInternalMessageSource@6f664372
WARN  2024-02-21 15:55:24,297 [LID40b300000000000a] [PollingConsumerThread-common.PROFILE_DATA] c.k.f.c.c.m.AbstractMessageProcessor - Received exception Message doesn't exist in source
WARN  2024-02-21 15:55:24,297 [LID40b300000000000a] [PollingConsumerThread-common.PROFILE_DATA] c.k.f.c.c.m.SnapshotMessageProcessor - Received exception, rolling back snapshot. Table common.PROFILE_DATA, snapshot bb64b782-b11a-4159-b71d-a09443830ba5 - failed
WARN  2024-02-21 15:55:24,299 [LID40b300000000000a] [PollingConsumerThread-common.PROFILE_DATA] c.k.f.c.CommonTablesDao - Temp snapshot table for common.PROFILE_DATA was present at the beginning of snapshot
```

**Comment by lionbro1** [comment]
Hi,

The meaning of this warning in the log is that 
the message was already deleted or not yet written to Cassandra (got timeout on select). 
It’s an expected behavior, especially if Cassandra is very loaded.

**Comment by smokyMount** [comment]
Thanks for the quick response. And is rerunning the ref_sync for failed tables the only way to overcome it?

**Comment by lionbro1** [comment]
yes, as the original command uses retries mechanism based on the Cassandra driver capabilities, if it fails after all the retries the only option to kick off the process again is to re-run the command
