### ISSUE TITLE
Setting up Fabric with a mix of Physical servers and VMs

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#994]
Hi, 
The customer reached out today asking if we can have "mix & match of both VM and Physical servers (For example, can we have 34 VMs + 1 or 2 physical servers for fabric)" for a new production environment?
Is this recommended? Are there any know issues that we should be aware of?

**Comment by lionbro1** [comment]
Hi,

1. yes we support a mixed cluster contains physical servers and VMs.
2. Our recommendation is to have a symatric cluster to ensure optimized load between nodes (for example in case of migrate).
