### ISSUE TITLE
List of features / differences between WebStudio and Desktop / .NET version

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#998]
Hello, several customers have been asking for a list of features that they may not see (or have some limited functionality) on Desktop / .NET Studio vs WebStudio version? 

Due to security concerns, they can use only on-prem type of environment (including for Dev / Studio) and therefore spinning up K8s cluster with all relevant infrastructure to enable WebStudio/Fabric mode may seem a bit complex and they prefer to proceed with simple Desktop version, unless there are some features that they need and these are available only with Web version.

We mentioned WebStudio benefits like Catalog and PII Discovery, LU creation based on catalog, etc... but it is not 100% clear from our portal what exactly is the difference. 

If they can have Desktop version with Catalog , PII Discovery, etc - do we have any installation / configuration "how-to" for this type of setup?

Thank you!

_____________
Best regards,
         Andrey

**Comment by eyalk2** [comment]
Hi

First, the mentioned disclaimers:
1. While security concerns are fully understood, we believe there are good answers that can address them, during a session with  relevant teams.
2. Spinning up a K8s cluster on-prem is not more complex than any Fabric installation VM/Docker. It is one script that does everything. 

Second, while Desktop Studio is fully maintained, Web Studio becomes more and more to be the standard Studio product, where new capabilities are mostly applied and available only there. 

Putting aside the whole and wider approach of k2cloud, which Web Studio is part of it, overall it is aimed to improve the productivity, the time-to-market and project life cycle maintenance. 
Here are some items. among others:
* Web Studio is a full stack all in one IDE, where you can develop, test & debug, track changes in GIT, view logs, open Linux and Fabric terminal, all in same place. No need to move between different screens and apps. Having it on browser, lets you easily swith to other tabs where you cna open other Fabric web framework application, like APIs.
* DB Explorer - a contextual tool, where can be used for easily building queries, like inside Query builder and inside Instance groups; auto-made DB query syntax inside functions; auto-made actors inside BW flows, auto-made query and output nodes inside Graphit.
* Code Editing - Intelisense and code completion; Fabric oriented code snippets helpers
* Query builder code completion assistant
* Panels - can be moved around and relocated within the screen
* Problem panels which on click lead you the problem location - in source code editing and at schema.
* Consume extensions from K2Exchange
* native web application development with preview.
* Integrated with Catalog
* Population Order View - A table view of schema tables and their populations, for better visibility of the schema. 
* Mtables visual editor
* Improved table and schema Reconciliation capability.
* change color theme (dark, light and more)
* Many features, for better developer experience - functionality and visually aspects.
* Nothing shall be installed at the end-user - better users working and for security.

**Comment by avvakandr** [comment]
Hello - what about Catalog-related features? Is it the same experience for Desktop vs Web?

My understanding was that Desktop version has some limitations around this, but was looking to see/confirm what are these differences (installation complexity, auto LU creation, etc)...
