### ISSUE TITLE
Changing DATETIME_FORMAT in Fabric

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#999]
Hello, is there any special step required to change DATETIME_FORMAT for Fabric?

W/o changing it - keeping commented in config.ini as #DATETIME_FORMAT=yyyy-MM-dd HH:mm:ss.SSS I'm getting my Datetime values stored in Fabric tables as:

<img width="371" alt="image" src="https://github.com/k2view-academy/K2View-Academy/assets/92332494/c57ec3f0-1f9a-45f4-b54b-af9502db5fd8">

After changing it as following:
<img width="491" alt="image" src="https://github.com/k2view-academy/K2View-Academy/assets/92332494/d72fe610-3aff-4124-9632-2777ed4e7df9">

Restarting Fabric, delete my instance and resync - I still see the same format..

<img width="374" alt="image" src="https://github.com/k2view-academy/K2View-Academy/assets/92332494/255a681e-aeb5-41de-89cf-5de7650874b1">

what do I miss?

____________
Thank you,
      Andrey

**Comment by eyalk2** [comment]
Hi

Can you share how it looks like in the source DB? is this with ms?
What is the source DB? (oracle? other?)

**Comment by avvakandr** [comment]
In this case I tested with local Postgres DB (our demo CRM_DB ) - and it has no ms in DB:

<img width="334" alt="image" src="https://github.com/k2view-academy/K2View-Academy/assets/92332494/6f9fb2b2-6195-4e78-a047-9be4426d322d">

**Comment by eyalk2** [comment]
So can you provide the concrete example where it did not work?

**Comment by avvakandr** [comment]
Hello - yes, please see one of these.

This is my config:

<img width="500" alt="image" src="https://github.com/k2view-academy/K2View-Academy/assets/92332494/eb4e6cd5-c868-4ac8-805a-466c1a515495">


This is my get and data in fabric (with .0 in the end):

<img width="263" alt="image" src="https://github.com/k2view-academy/K2View-Academy/assets/92332494/1b8355d6-02c1-4039-b2db-4a4257db5230">

This is the same data in source DB:

<img width="608" alt="image" src="https://github.com/k2view-academy/K2View-Academy/assets/92332494/aab4cb7d-ecf1-4e6b-a11b-53580a69df01">


and when it is published to ElasticSearch via CDC for this table - it is failed on ES side as datetime format is unexpected (it is coming with .0, while ES expecting it only w/o ms or with .sss for millis)

_____________
Best regards,
         Andrey

**Comment by eyalk2** [comment]
Hi
Are you using Date as the format inside Fabric? 
If so, the config.ini is irrelevant. This is used to previous versions, where Fabric did not support Date and holds dates as text. For this, you could control on the format using the config definition (instead user had to convert it in implementation).
When using Date format, then you shall use the date-to-text SQL function, each time according to the required format,

**Comment by avvakandr** [comment]
Yes, in this case I have it as 'Datetime' in fabric table
